### ISSUE TITLE
undefined sort.Slice

### ISSUE THREAD

**Issue by woonhak** [dgraph-io/badger#100]
Hi,

I'm trying to use badger, but I've got erros with undefined sort.Slice().

When I tried to run
go get -t -v github.com/dgraph-io/badger

then,
src/github.com/dgraph-io/badger/level_handler.go:64: undefined: sort.Slice
src/github.com/dgraph-io/badger/level_handler.go:69: undefined: sort.Slice
src/github.com/dgraph-io/badger/levels.go:200: undefined: sort.Slice
src/github.com/dgraph-io/badger/levels.go:363: undefined: sort.Slice
src/github.com/dgraph-io/badger/value.go:271: undefined: sort.Slice
src/github.com/dgraph-io/badger/value.go:493: undefined: sort.Slice

I'm running golang 1.7.6 on Fedora 25

**Comment by pawanrawal** [comment]
Hey @woonhak 

`sort.Slice()` was introduced starting with Go `v1.8` and we use it in badger. You would have to upgrade to Go version > `1.8`.

**Comment by woonhak** [comment]
Thanks for letting me know that.
