### ISSUE TITLE
Bbloom is unsafe

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#1005]
* It moves locks (https://github.com/AndreasBriese/bbloom/pull/8)
* It mis-uses unsafe (https://github.com/AndreasBriese/bbloom/issues/9).
* It ignores unmarshal errors.

The IPFS project has a fork (https://github.com/ipfs/bbloom) that fixes these issues but we've made some significant API changes that make these fixes a bit difficult to upstream. These changes should either be upstreamed manually or you should consider switching to the fork.

Benchcmp:

```
BenchmarkM_New-4                        14633         16021         +9.49%
BenchmarkM_Clear-4                      2283          2004          -12.22%
BenchmarkM_Add-4                        2324843       1849145       -20.46%
BenchmarkM_Has-4                        2162063       1183050       -45.28%
BenchmarkM_AddIfNotHasFALSE-4           2464076       2224163       -9.74%
BenchmarkM_AddIfNotHasClearTRUE-4       2471798       2240655       -9.35%
BenchmarkM_AddTS-4                      5748868       3423050       -40.46%
BenchmarkM_HasTS-4                      5912475       1869951       -68.37%
BenchmarkM_AddIfNotHasTSFALSE-4         5841705       3982971       -31.82%
BenchmarkM_AddIfNotHasTSClearTRUE-4     6067134       4027179       -33.62%
```

(i.e., our fork is faster everywhere that counts but doesn't use unsafe)

**Comment by AndreasBriese** [comment]
... 
using math/bits means using unsafe anyway. I prefer doing things transparent instead of obfuscating it.
I will look into the speed comparison.

**Comment by Stebalien** [comment]
It uses the unsafe _package_ internally but it uses it correctly. I only suggested switching libraries assuming that the changes from our bbloom fork aren't upstreamed. You appeared to be busy so I didn't want to block fixing these issues on upstreaming the necessary changes.

**Comment by Stebalien** [comment]
@AndreasBriese has fixed upstream so updating to the latest master (of AndreasBriese/bbloom) should fix the issue.

**Comment by jarifibrahim** [comment]
Badger uses `dgraph-io/ristretto/z/bbloom` - a fork of `AndreasBriese/bbloom`. https://github.com/dgraph-io/ristretto/tree/master/z should be updated accordingly.
