### ISSUE TITLE
Why a pointer issue?

### ISSUE THREAD

**Issue by fpessolano** [dgraph-io/badger#1011]
### What version of Go are you using (`go version`)? 
1.12

### What version of Badger are you using? 
1.5.3 to 1.5.5

### Does this issue reproduce with the latest master? 
I cannot upgrade to 1.6 since it breaks the API and this is a released product

### What did you do?

For some reason, all of the sudden writing/reading a pair result into the error:
Invalid value pointer offset: % greater than current offset: 0

    err := db.Update(func(txn *badger.Txn) error {
     var err error
     if ttl && (!data.oride) {
      err = txn.SetWithTTL(data.id, data.val, currentTTL)
     } else {
      err = txn.Set(data.id, data.val)
     }
     return err
    })
    if err != nil {
     log.Printf("Error writing at address %v: %v\n", data.id, err)
    }
    // Test for write - delete
    b := SerieEntries{}
    val, err := read(data.id, b.MarshalSize(), b.MarshalSizeModifiers(), db)
    if err != nil {
     fmt.Println(string(data.id), err)
    } else {
     e := new(SerieEntries)
     _ = e.Unmarshal(val)
     fmt.Println("Checking store in DBS:", string(data.id), *e)
    }

Where:

    func read(id []byte, l int, offset []int, db badger.DB) (v []byte, err error) {
	read := func(id []byte, lb int, db badger.DB) (r []byte, err error) {
		if lb > 0 {
			r = make([]byte, lb)
			err = db.View(func(txn *badger.Txn) error {
				item, err := txn.Get(id)
				if err != nil {
					return err
				}
				val, err := item.ValueCopy(nil)
				if err != nil {
					return err
				}
				copy(r, val)
				return nil
			})
		} else {
			err = errors.New("storage.DBS: error storing data with length <= 0")
		}
		return
	}

	if l > 0 {
		return read(id, l, db)
	} else {
		if l == 0 && len(offset) == 2 {
			var r []byte
			r, err = read(id, 2, db)
			if err == nil {
				vs := int(binary.LittleEndian.Uint16(r))*offset[0] + 2 + offset[1]
				if r, err = read(id, vs, db); err == nil {
					v = make([]byte, len(r))
					copy(v, r)
				}
			}
		}
	}
	return
    }

I have tried to delete the database and so on (to account for database corruption) to no avail.

I seem to have isolated to issue to the line:
     val, err := item.ValueCopy(nil)

### What did you expect to see?
The stored value data.val (whatever that might be)

### What did you see instead?
Invalid value pointer offset: % greater than current offset: 0
(% changed depending on the used label data.id)

Any help is welcome, thanks!

**Comment by fpessolano** [comment]
Please delete, this is not an issue related to badger or so it seems

**Comment by jarifibrahim** [comment]
Thanks @fpessolano. I'm closing this issue.
