### ISSUE TITLE
merge operator with managed db

### ISSUE THREAD

**Issue by yangzh** [dgraph-io/badger#1016]
### What version of Go are you using (`go version`)?

It doesn't matter for this, it's a feature request.

### What version of Badger are you using?

2.0 pre.

### Does this issue reproduce with the latest master?

N/A.

### What did you do?

It seems merge operator currently is only available for non-managed db.
For feature parity, it would also be available (and there is no fundamental reason why it cannot) for managed db.

I don't have a concrete use case yet, but maybe someone can come up with one?

### What did you see instead?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8668). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
