### ISSUE TITLE
github.com/dgraph-io/ristretto/pull/37 breaks badger

### ISSUE THREAD

**Issue by Marreck** [dgraph-io/badger#1019]
https://github.com/dgraph-io/ristretto/pull/37 Removes AESHash(data []byte) uint64 for MemHash(data []byte) uint64 which Badger relies on.

**Comment by jarifibrahim** [comment]
This should be fixed by https://github.com/dgraph-io/badger/pull/1018.

**Comment by ashish-goswami** [comment]
Hey @Marreck, we have just fixed Badger to avoid breaking. It should work fine.

Feel free to reopen this if required.
