### ISSUE TITLE
badger info: Add flag to open DB in read-write / truncate mode

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/badger#1025]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### What version of Badger are you using?
v1.6.0

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
N/A

### What did you do?

I tried to get information about a Badger DB directory using the `badger info` tool. In this case, the DB wasn't closed properly, so I see an error when using the info tool.

### What did you expect to see?

I expected to be able to use the info tool on this Badger directory. If there was an option to open it in read-write mode, then this would work.

### What did you see instead?
```
failed to open database: Unable to replay logfile. Path=./000319.vlog. Error=Database was not properly closed, cannot open read-only
```

**Comment by kshitij10496** [comment]
Hey @danielmai !
I would like to work on this if it's fine by you.

**Comment by kshitij10496** [comment]
The reason this is failing currently is because we are opening the DB in read-only mode via `WithReadOnly`. As it's documented behaviour that opening the DB after a crash with some vlog data to be replayed will fail with `ErrReplayNeeded` error, this should be expected. 

https://github.com/dgraph-io/badger/blob/a44139040bb686239ecfda106fd7bc300f43e9c8/badger/cmd/info.go#L90-L97

In order to resolve it, which would you prefer opening the DB:
1. using the default options (`ReadOnly=false`, `Truncate=false`)
2. with `Truncate`.
3. a new `ReadWrite` flag.

Let me know what you think. I'd be happy to get it to work and send in a PR. 😃

**Comment by ashish-goswami** [comment]
Hey @kshitij10496, I think flag name can be **ReadOnly**, with its default value as **true**. This can avoid dropping data if the user is not aware of this option and runs info tool on Badger dir.
If **ReadOnly** have value false, Badger can automatically truncate corrupt data.
Feel free to send PR for this.

**Comment by jarifibrahim** [comment]
Adding only a read-write flag might not be enough. We'll need to set the truncate flag also.

**Comment by kshitij10496** [comment]
Sorry, I was occupied with some stuff so couldn't reach back earlier. 😅 

> Adding only a read-write flag might not be enough. We'll need to set the truncate flag also.

If I understand correctly from the [documentation](https://godoc.org/github.com/dgraph-io/badger#Options.WithTruncate), the DB can only be opened in "truncate" mode, if its not in ReadOnly mode i.e. specifying read-only will override an explicit truncation. 
Can we not use this fact to create a sensible default with just a single new `truncate` boolean flag? 
The proposed final API would look something like:

```
$ badger info # read-only by default
failed to open database: Unable to replay logfile. Path=./000319.vlog. Error=Database was not properly closed, cannot open read-only

$ badger info --truncate # truncate explicitly (truncate= true, read-only= false)
# success
```

Is there a use-case where we would want the `info` command to open the DB in read-write mode apart from truncation? If so, then I agree that we would need 2 flags.
