### ISSUE TITLE
Should we be Key Value Storage API compatible?

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#1040]
This is a request coming from @markmssd in https://github.com/dgraph-io/badger/issues/832#issuecomment-528868327.

Taking into account that Samsung has announced a new SSD compatible with [Key Value Storage API Specification](https://www.snia.org/tech_activities/standards/curr_standards/kvsapi) ([announcement](https://www.anandtech.com/show/14839/samsung-announces-standardscompliant-keyvalue-ssd-prototype)), we should consider whether badger can work on top of these SSDs and whether it's a good idea to recommend this setup.

Maybe it'd be a good idea to run some benchmarks on this.

**Comment by markmssd** [comment]
Thank you! Glad to see it taken into consideration 😄

**Comment by markmssd** [comment]
Dropping their official document where they compare RocksDB performance on their KV SSD https://www.samsung.com/semiconductor/global.semi.static/Samsung_Key_Value_SSD_enables_High_Performance_Scaling-0.pdf
