### ISSUE TITLE
TeamCity should fail on compilation errors

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1044]
The following build succeeded even where there were compilation errors. https://teamcity.dgraph.io/viewLog.html?buildId=24566&buildTypeId=Badger_UnitTests&tab=buildLog#_state=110

**Comment by jarifibrahim** [comment]
@danielmai Please look into this.

**Comment by danielmai** [comment]
Fixed by adjusting the TeamCity config for Badger. Compilation errors now fail the build: https://teamcity.dgraph.io/viewLog.html?buildId=24807&tab=buildLog&_focus=327#_state=327
