### ISSUE TITLE
Bank test fails but teamcity shows status as success

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1048]
See build https://teamcity.dgraph.io/viewLog.html?buildId=24863&buildTypeId=Badger_BankTest&tab=buildLog&branch_Badger=%3Cdefault%3E#_state=1015

The bank test crashed but team city reported success.

**Comment by jarifibrahim** [comment]
@danielmai Please look into asap.

**Comment by danielmai** [comment]
Yikes. This is now fixed by setting `set -o pipefail` as bash options for test runner.
