### ISSUE TITLE
Badget multiple goroutines Panic

### ISSUE THREAD

**Issue by AkbaraliShaikh** [dgraph-io/badger#1057]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.7
</pre>

### What version of Badger are you using?
latest

### Does this issue reproduce with the latest master?
maybe

### What are the hardware specifications of the machine (RAM, OS, Disk)?
16GB RAM, Ubuntu 19.04 and SSD

### What did you do?

```
func TestBadger(t *testing.T) {
	db, err := badger.Open(badger.DefaultOptions("/tmp/badger"))
	if err != nil {
		log.Fatal(err)
		t.Fatalf("TestBadger:%v", err)
	}
	defer db.Close()
	var wg sync.WaitGroup
	txn := db.NewTransaction(true)
	for i := 0; i < 100000; i++ {
		key, _ := crypto.RandomToken(20)
		go func(k string) {
			wg.Add(1)
			defer wg.Done()
			if err := txn.Set([]byte(k), []byte(k)); err == badger.ErrTxnTooBig {
				_ = txn.Commit()
				txn = db.NewTransaction(true)
				_ = txn.Set([]byte(k), []byte(k))
			}
		}(key)
	}
	wg.Wait()
	_ = txn.Commit()
}
```

### What did you expect to see?
test passed

### What did you see instead?
badger 2019/09/28 14:11:22 INFO: Replaying file id: 4 at offset: 48683028
badger 2019/09/28 14:11:22 INFO: Replay took: 11.248µs
fatal error: concurrent map writes

goroutine 88 [running]:
runtime.throw(0x8f33f9, 0x15)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00a219e40 sp=0xc00a219e10 pc=0x42f152
runtime.mapassign_faststr(0x863840, 0xc00937e3f0, 0xc009554c80, 0x14, 0xc009554c80)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc00a219ea8 sp=0xc00a219e40 pc=0x4148aa
github.com/dgraph-io/badger.(*Txn).modify(0xc0000fc000, 0xc00011c2d0, 0x14, 0xc009554c60)
        /home/akbar/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/txn.go:337 +0x1aa fp=0xc00a219f08 sp=0xc00a219ea8 pc=0x7e5fda
github.com/dgraph-io/badger.(*Txn).SetEntry(...)
        /home/akbar/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/txn.go:356
github.com/dgraph-io/badger.(*Txn).Set(...)
        /home/akbar/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/txn.go:347
vmware.com/biene/test.TestBadger.func1(0xc0093623f0, 0xc0093760c8, 0xc000102a80, 0xc00a1eb3c0, 0x14)
        /home/akbar/go-work/src/vmware/biene/test/test_test.go:26 +0x196 fp=0xc00a219fb8 sp=0xc00a219f08 pc=0x7ff986

**Comment by jarifibrahim** [comment]
@AkbaraliShaikh The code sample uses the same transaction across multiple goroutines, is there a reason for doing that?
Using the same transaction across multiple goroutines will panic because transactions aren't thread-safe.

**Comment by jarifibrahim** [comment]
@AkbaraliShaikh Your code is using the same transaction accross multiple go routines. The following changes seem to work.
```diff
@@ -1990,19 +1990,19 @@ func TestBadger(t *testing.T) {
 	}
 	defer db.Close()
 	var wg sync.WaitGroup
-	txn := db.NewTransaction(true)
 	for i := 0; i < 100000; i++ {
 		key, _ := crypto.RandomToken(20)
 		go func(k string) {
 			wg.Add(1)
 			defer wg.Done()
+			txn := db.NewTransaction(true)
 			if err := txn.Set([]byte(k), []byte(k)); err == badger.ErrTxnTooBig {
 				_ = txn.Commit()
 				txn = db.NewTransaction(true)
 				_ = txn.Set([]byte(k), []byte(k))
 			}
+			_ = txn.Commit()
 		}(key)
 	}
 	wg.Wait()
-	_ = txn.Commit()
 }
```

**Comment by AkbaraliShaikh** [comment]
@jarifibrahim then how can I do a bunch of insert in a single transaction?

**Comment by AkbaraliShaikh** [comment]
@jarifibrahim  same thing I have tested with PostgresSQL, I'm able to do it.

The way you are suggesting can cerate huge transactions and slow, Let me know what is the best way to insert/update bunch of statements in single transaction? 

The library should not panic, instead should throw error I belive.

**Comment by jarifibrahim** [comment]
@AkbaraliShaikh `WriteBatch` should work https://github.com/dgraph-io/badger#my-writes-are-really-slow-why

https://github.com/dgraph-io/badger/blob/e7d0a7b722ef7351aad3dd5b5ba70f147497e309/batch.go#L40

**Comment by AkbaraliShaikh** [comment]
@jarifibrahim let me try this.
