### ISSUE TITLE
Separate Value Log from WAL

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#1068]
The idea is to only use Value Log when the value length exceeds the ValueThreshold. For all other values, we use the WAL, which can be discarded much more readily, without invoking a Value Log GC.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8725). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
