### ISSUE TITLE
handling of sequences

### ISSUE THREAD

**Issue by nonpcnpc** [dgraph-io/badger#1071]
I need to key all incoming messages sequantially, essentially having a uint64 primary key. I wonder if it is ok to simply keep the last sequence in a variable like vars/_seq = 123 and just have data as seq/{sequence} = value while using transactions, or if the db.GetSequence() handles this on its own(ie. single consecutive list of ids, **persisted in badger on its own**) that can continue on next run, just like auto increment primary key in sql databases?

I need to stress that I cannot have missing/skipped numbers. The sequence HAS to be consecutive, exactly like a primary key.

**Comment by jarifibrahim** [comment]
@nonpcnpc https://github.com/dgraph-io/badger#monotonically-increasing-integers can be used to generate. 
The `db.Sequence` leases `bandwidth` numbers from badger but
