### ISSUE TITLE
How to support Windows XP/2003

### ISSUE THREAD

**Issue by cobolbaby** [dgraph-io/badger#1072]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.12 linux/amd64
</pre>

### What version of Badger are you using?

v1.6.0

### What are the hardware specifications of the machine (RAM, OS, Disk)?

Windows XP/2003

### What did you do?

```
	db, err := badger.Open(badger.DefaultOptions(path).WithLogger(this.Logger).WithTruncate(true).WithSyncWrites(false))
	if err != nil {
		this.Logger.Fatalf("Fail to execute badger.Open: %s", err)
	}
	// defer db.Close()

```

### What did you see instead?

```
Fail to execute badger.Open: Map log file. Path=C:\\Program Files\\DCAgent\\data\\000000.vlog. Error=MapViewOfFile: The parameter is incorrect.
```

**Comment by cobolbaby** [comment]
The same problem: https://discuss.dgraph.io/t/issue-running-badger-on-windows-mapviewoffile/2492

**Comment by jarifibrahim** [comment]
@cobolbaby Is there a reason for using Windows XP/2003?

**Comment by cobolbaby** [comment]
In many factories, some client operating environments are XP/2003.

**Comment by cobolbaby** [comment]
@jarifibrahim

**Comment by jarifibrahim** [comment]
@cobolbaby I'm not sure why it's failing for you. The failure might be related to windows XP/2003.
Can you try to run badger on a different directory and see if that works?
Can you also try running latest version of badger? I fixed a bunch of issues with badger on windows in  https://github.com/dgraph-io/badger/commit/cbdef65095c7c34544963f31eb1f7867c49d6725

It will be tough for me to reproduce the issue and find a fix since the windows XP/2003 are no longer supported. Please do try on newer versions of windows and let me know how it goes.

**Comment by cobolbaby** [comment]
- Can you try to run badger on a different directory and see if that works?

It doesn't work after I switch to different directories.

- Can you also try running latest version of badger? I fixed a bunch of issues with badger on windows in `cbdef65`

When I used the latest version, there was a compilation problem. Maybe I need to set the `WithValueLogLoadingMode` to `options.FileIO` to circumvent similar problems. Are there other alternative configurations that can be adjusted?

**go.mod**:

```
module github.com/cobolbaby/log-agent

go 1.12

require (
	...
	github.com/dgraph-io/badger v0.0.0-20191010101102-bcf8b972e5a2
        ...
)
```
**Result**:
```
GO111MODULE=on go mod vendor
CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags "-w -X main.GIT_COMMIT=`git rev-parse --short HEAD` -X 'main.BUILD_TIME=`date +%FT%T%z`' -X 'main.GO_VERSION=`go version`'" -o /opt/workspace/git/dc-agent-release/v2.0/dcagent_2.0.5_windows_x86.exe main.go
vendor/github.com/dgraph-io/badger/table/builder.go:25:2: build constraints exclude all Go files in /opt/workspace/git/go-demo/src/dc-agent-go/vendor/github.com/DataDog/zstd
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by cobolbaby** [comment]
@jarifibrahim

**Comment by jarifibrahim** [comment]
@cobolbaby The `github.com/DataDog/zstd` requires `cgo`. Your makefile sets `CGO_ENABLED=0` which means `DataDog/zstd` won't compile. 
```
CGO_ENABLED=0 GOOS=windows GOARCH=386 go build ${LDFLAGS} -o $(NAME)_2.0.1_windows_x86.exe main.go
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build ${LDFLAGS} -o $(NAME)_2.0.1_windows_amd64.exe main.go
```
from https://github.com/cobolbaby/log-agent/blob/71f7f9fb2219c802fffd4f21619a3aecd885f3c3/Makefile#L15-L16 

>When I used the latest version, there was a compilation problem. Maybe I need to set the WithValueLogLoadingMode to options.FileIO to circumvent similar problems. Are there other alternative configurations that can be adjusted?

File I/O mode should not affect compilation. You can set the table loading to `LoadToRam` and you can set value log file loading mode to `FileIO`. Please note that reading data from a file opened in `fileIO` mode is slow. So if your values are of large size, value lookups will be slower.

How big are your values?

**Comment by cobolbaby** [comment]
The largest size is less than 1G

**Comment by cobolbaby** [comment]
@jarifibrahim 
From: https://github.com/dgraph-io/badger#comparisons
> Pure Go (no Cgo)
Is `zstd` a strong dependency? I haven't found any exception when I don't package the library. Under what circumstances will it be used?

For the current biz, the largest size is less than 1G.

**Comment by cobolbaby** [comment]
And when I'm trying to cross compile from linux to windows 64/32, the following error has occurred
```
runtime/cgo
gcc: error: unrecognized command line option ‘-mthreads’
```
Is there any solution?

**Comment by cstlaurent** [comment]
Golang itself do not support XP/2003 for 1.11+, so I'm not sure there is anything we can do here. See https://github.com/golang/go/wiki/MinimumRequirements

**Comment by cobolbaby** [comment]
@cstlaurent After testing, we found that Go 1.11 also supports XP/2003. The go.mod above is not accurate.

**Comment by cobolbaby** [comment]
@cstlaurent Even if I downgrade to version 1.10, the `MapViewOfFile` error would be reported.
