### ISSUE TITLE
Synchronizing master->slave

### ISSUE THREAD

**Issue by nonpcnpc** [dgraph-io/badger#1073]
I have an append-only database and I want to split it into single master for writes and multiple slaves for reads. I have looked at the streams but I fail to see how to communicate to the slave the newest records so it knows it is healthy and can server or if it needs to catch up before signaling it is healthy. I can do this with manual logic but I was wondering if there is a way to do this with the built-in streams instead, which were made for this exact purpose?

**Comment by jarifibrahim** [comment]
@nonpcnpc You could try using the `Subscribe` API for this https://github.com/dgraph-io/badger/blob/f50343ff404d8198df6dc83755ec2eab863d5ff2/db.go#L1510-L1516 

Here's an example of how to use it https://github.com/dgraph-io/badger/blob/f50343ff404d8198df6dc83755ec2eab863d5ff2/db_test.go#L1939-L2002 

You can add replication logic in the callback passed to the subscribe API which would allow you to replicate the data.

**Comment by nonpcnpc** [comment]
the subscribe() is a local method, external instance has no access to it so i fail to see how is that relevant to my question.
as for replication, that's what the streams are for, as I mentioned, so I fail to see what you're getting at with this 🤷🏻‍♂️

**Comment by jarifibrahim** [comment]
>the subscribe() is a local method, external instance has no access to it so i fail to see how is that relevant to my question.

The subscribe function accepts a callback that can be used to do something with the updates. You could post the updates to an endpoint or a file and push the updates on a new badger instance. Isn't that what you're looking for?

>as for replication, that's what the streams are for, as I mentioned, so I fail to see what you're getting at with this 🤷🏻‍♂️

Streams would help you stream data (not updates). The stream framework doesn't know anything about the updates happening in the system. For that, we have ths subscribe API. If I understand correctly, you just want the updates, not the entire DB dump.

**Comment by nonpcnpc** [comment]
OK, I get what you are trying to say. But I think you have missed the main point of my question:

> I have looked at the streams but I fail to see how to communicate to the slave the newest records so it knows it is healthy and can server or if it needs to catch up before signaling it is healthy. 

In other words, with the built-in methods(whether streams or updates) I have no way of telling the slave that it is up-to-date with the master and can server reliable not out-of-date data to the clients.

Hence, I was looking into writing a manual syncer that would keep track of the last primary key(or last "operation" id, with WAL/transaction log/binary log in place), which would be send with the sync operation into the slave. I was just looking for something built-in but it does not look like that is the case.

**Comment by jarifibrahim** [comment]
Hey @nonpcnpc apologies for the delayed reply. I don't think we have anything in badger that would help you achieve this. We have streams that can help you replicate data and we have the subscribe API which can send updates. But I don't think either of these would help you achieve what you're looking for.
