### ISSUE TITLE
Add missing documentation about the Subscribe API

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1075]
The subscribe API 
https://github.com/dgraph-io/badger/blob/f50343ff404d8198df6dc83755ec2eab863d5ff2/db.go#L1510-L1516

was added in badger via https://github.com/dgraph-io/badger/commit/26128a761d2639840a238a54d812c1a386ae4fa0 but there is no documentation about it. We should also have an example of how to use the Subscribe API.

https://github.com/dgraph-io/badger/blob/f50343ff404d8198df6dc83755ec2eab863d5ff2/db_test.go#L1939-L1948 can be used for inspiration.

**Comment by jarifibrahim** [comment]
cc @balajijinnah

**Comment by kaustubhmallik** [comment]
@jarifibrahim is this still available to grab?

**Comment by kaustubhmallik** [comment]
@jarifibrahim By documentation, you mean adding explanations and usage (code example) in the README directly, correct? As far as I have understood, this feature enables you to add a post-update behaviour (callback function) for certain set of keys, configured using the key's prefix.

Also, as you said, the example can be directly quoted from the test you have written.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8726). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
