### ISSUE TITLE
Data lost on fatal crash (electricity loss)

### ISSUE THREAD

**Issue by fpessolano** [dgraph-io/badger#1076]
### What version of Go are you using (`go version`)? 
1.13

### What version of Badger are you using? 
1.5.3

### Does this issue reproduce with the latest master?
I cannot move to a API breaking version since the database is deployed

### What are the hardware specifications of the machine (RAM, OS, Disk)? 
Arch Linux server, Intel x86 arhcitecture 

### What did you do? 
Badger data was lost due to loss of electricity. Even with options syncwrite and truncate set to true, bagdre did not recover from the vlog file.

### What did you expect to see? 
Maybe loss of some data, not weeks of data!

### What did you see instead? 
Loss of all data

I believe that the fact badger stores in the vlog is a liability, is it possible to force it to move data in the tree faster?

**Comment by fpessolano** [comment]
These are my currention options, what should change in order to prevent data loss due to such a crash.

0: Dir string = dbs/current
1: ValueDir string = dbs/current
2: SyncWrites bool = true
3: TableLoadingMode options.FileLoadingMode = 1
4: ValueLogLoadingMode options.FileLoadingMode = 2
5: NumVersionsToKeep int = 1
6: MaxTableSize int64 = 67108864
7: LevelSizeMultiplier int = 10
8: MaxLevels int = 7
9: ValueThreshold int = 32
10: NumMemtables int = 5
11: NumLevelZeroTables int = 5
12: NumLevelZeroTablesStall int = 10
13: LevelOneSize int64 = 268435456
14: ValueLogFileSize int64 = 1073741823
15: ValueLogMaxEntries uint32 = 1000000
16: NumCompactors int = 2
17: CompactL0OnClose bool = true

Thanks

**Comment by manishrjain** [comment]
Can you elaborate more with some logs from badger. Or perhaps, if you have the directory, you could privately share it with us.
