### ISSUE TITLE
Conflicting transactions

### ISSUE THREAD

**Issue by nonpcnpc** [dgraph-io/badger#1077]
I wrote a small script to test transactions in Badger where I spin up 1000 goroutines, each running 1000 transactions with 100 values, and I am getting transaction conflict for every single one of them.

Which makes me think that Badger does not really support non-blocking transactions?

Also, does that mean that in order to process many transactions I would have to have a centralized batching processor that would queue and *serialize* transactions and periodically commit them to avoid these conflicts?

**Comment by manishrjain** [comment]
There is a batch write option you can use.

**Comment by nonpcnpc** [comment]
The issue with it is that it does not allow me to read AI primary key:
`Note that WriteBatch API does not allow any reads. For read-modify-write workloads, you should be using the Transaction API.`
