### ISSUE TITLE
The log picking logic in RunValueLogGC is funky

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#1079]
### What version of Badger are you using?

> 851e462df52e830df8415f92676c0c9586a21df6

### Does this issue reproduce with the latest master?

Yes.

### Description

This function is supposed to pick the best log to garbage collect. However:

1. It _claims_ to pick a random log when it can't find a good candidate in the discard stats. However, this is incorrect. It _always_ picks a random candidate, even if it finds a candidate in the discard stats. This seems weird and suboptimal.
2. It's unclear _why_ one would ever pick a random candidate. Badger should have enough information to make `RunValueLogGC` a no-op when there's nothing to delete.

**Comment by manishrjain** [comment]
It picks one from the discard stats and one randomly. It would then first try to garbage collect on the discard starts pick. And only if that does not result in any collection, it would move to the random selection.

**Comment by Stebalien** [comment]
Ah, thanks! That makes sense.

If you don't mind my asking, why does it pick a random log? Is it possible for the discard stats to be wrong?
