### ISSUE TITLE
Provide a PrefixPartition concept

### ISSUE THREAD

**Issue by stephane-martin** [dgraph-io/badger#108]
Hi,

as a single instance of *badger.KV can consume quite some memory, it was suggested to have a single instance, and to separate different "partitions" using a key prefix. That's quite easy to code, but as many people are going to code the same, badger could provide a partition abstraction.

A partition should rely on a parent KV, and have a "prefix". The same operations than on a KV should be available, but they would be applied on the parent KV using its prefix.

partition.Set(key, val) -> parent.Set(partition.Prefix + key, val).

**Comment by manishrjain** [comment]
This can be done easily in the client, and would unnecessarily expand the APIs that Badger needs to maintain.
