### ISSUE TITLE
master can't compile without CGO_ENABLED=1 (zstd)

### ISSUE THREAD

**Issue by akhenakh** [dgraph-io/badger#1081]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64

</pre>

### What version of Badger are you using?
master v1.6.1-0.20191012010444-dbe1cb90c815

### Does this issue reproduce with the latest master?
yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
macbook pro

### What did you do?
updated badger from 1.6.0 to master

### What did you expect to see?
compilation working without CGO_ENABLED=1

### What did you see instead?
```
 go build github.com/DataDog/zstd: build constraints exclude all Go files in /Users/xxx/dev/go/pkg/mod/github.com/!data!dog/zstd@v1.4.1  
```

Enabling cgo solved the issue (related to zstd), is it by choice or a bug, badger v2 will require cgo ?

**Comment by jarifibrahim** [comment]
@akhenakh Its by choice. ZSTD requires CGO. I'll update the README to reflect this https://github.com/dgraph-io/badger/#comparisons .

**Comment by akhenakh** [comment]
FIY Sarama just replaced datadog/ztsd by https://github.com/klauspost/compress

Not being full native is a huge change, a stopper for some, especially for a library ...

**Comment by amurchick** [comment]
> @akhenakh Its by choice. ZSTD requires CGO. I'll update the README to reflect this https://github.com/dgraph-io/badger/#comparisons .

I am understand correctly - the badger will now never can be build without CGO?

Or is there a plan to return the build without a CGO?

**Comment by jarifibrahim** [comment]
@akhenakh @amurchick  https://github.com/klauspost/compress is not in stable state https://github.com/klauspost/compress/tree/master/zstd#status . We might switch to  https://github.com/klauspost/compress once it is more stable.

>@jarifibrahim - Is I am understand correctly - the badger will now never can be build without CGO?

No. CGO will be optional once https://github.com/dgraph-io/badger/pull/1094 is merged. Badger can be build with or without CGO.
