### ISSUE TITLE
Compressing k/v pairs under 1KB.

### ISSUE THREAD

**Issue by Think7** [dgraph-io/badger#1083]
Greetings,

I'm trying to improve the compression ratio of data store in BadgerDB log. According to the below blog post, only data pairs which exceed 1KB are actually compressed and that this threshold can be adjusted by the user.

https://blog.dgraph.io/post/badger/

`To deal with this, Badger does two things. It allows compressing values in value log. Instead of compressing multiple key-values together, we only compress each key-value individually. This provides the best possible random read performance. The client can set it so compression is only done if the key-value size is over an adjustable threshold, set by default to 1KB.
`

I've scoured the docs and source and cannot find any mention of this option / setting or how to adjust it.

Thanks for your time. I apologize in advance if i've simply misunderstood or overlooked something.

**Comment by jarifibrahim** [comment]
Hey @Think7, I think the key-value compression was removed in https://github.com/dgraph-io/badger/commit/ec0f11d0de3502e422abdad7665cb49dc762c291 . We don't support single key-value compression anymore.

**Comment by Think7** [comment]
Understood. Is there some way to reduce the size of the log files / database as a whole?

**Comment by jarifibrahim** [comment]
We recently added compression to badger. That should reduce the SST file sizes. You can also run `garbage collection` periodically. That will clean up some old value log files.
