### ISSUE TITLE
Unresolved reference `Open` and `DefaultOptions`

### ISSUE THREAD

**Issue by darionyaphet** [dgraph-io/badger#1106]
### What version of Go are you using (`go version`)?

<pre>
$ go version

`go version go1.13.3 darwin/amd64`

</pre>

### What version of Badger are you using?

Check source code from github

When I try the get start 

`db, err := badger.Open(badger.DefaultOptions("/tmp/badger"))`

can't resolved reference `Open` and `DefaultOptions`

and report 

```
../../../dgraph-io/badger/y/zstd_cgo.go:22:2: cannot find package "github.com/DataDog/zstd" in any of:
	/usr/local/Cellar/go/1.13.3/libexec/src/github.com/DataDog/zstd (from $GOROOT)
	/Users/darion/go/src/github.com/DataDog/zstd (from $GOPATH)
```

**Comment by jarifibrahim** [comment]
@darionyaphet does running `go get -v ` in badger directory help? It should pull all the dependencies.

**Comment by darionyaphet** [comment]
It doesn't seem to work ...

**Comment by jarifibrahim** [comment]
@darionyaphet Can you show me the output of `go get -v`? By default badger requires `gcc` to build the `zstd` library. If you don't have gcc, `go get -v` would fail. You can do `CGO_ENABLED=0 go get -v` to pull badger without ZSTD.

**Comment by jarifibrahim** [comment]
@darionyaphet Ping!

**Comment by darionyaphet** [comment]
Sorry for late reply.

```
~/go/src/github.com/dgraph-io/badger(master) » go get -v                                                                                                                                                                     darion@localhost
golang.org/x/net/trace
github.com/DataDog/zstd
github.com/dgraph-io/badger/v2/y
github.com/dgraph-io/badger/v2/skl
github.com/dgraph-io/badger/v2/table
github.com/dgraph-io/badger/v2
```

```
~/go/src/github.com/dgraph-io/badger(master) » CGO_ENABLED=0 go get -v                                                                                                                                                       darion@localhost
github.com/dgraph-io/badger/v2/trie
github.com/dgraph-io/badger/v2/options
github.com/cespare/xxhash
github.com/dgryski/go-farm
github.com/golang/snappy
golang.org/x/sys/unix
github.com/pkg/errors
golang.org/x/net/internal/timeseries
github.com/dgraph-io/ristretto/z
github.com/golang/protobuf/proto
github.com/dustin/go-humanize
net
github.com/dgraph-io/ristretto
vendor/golang.org/x/net/http/httpproxy
net/textproto
crypto/x509
github.com/dgraph-io/badger/v2/pb
vendor/golang.org/x/net/http/httpguts
crypto/tls
net/http/httptrace
net/http
golang.org/x/net/trace
github.com/dgraph-io/badger/v2/y
github.com/dgraph-io/badger/v2/skl
github.com/dgraph-io/badger/v2/table
github.com/dgraph-io/badger/v2
```

**Comment by jarifibrahim** [comment]
Hey @darionyaphet this seems like some kind of misconfiguration on your side. I tried to reproduce this but didn't have any luck.

Here's what I tried.
1. `docker run -it golang:1.13 bash`
2. `go get github.com/dgraph-io/badger/...`
3. Create `main.go` with
```go
db, err := badger.Open(badger.DefaultOptions("./"))
```
and it worked fine.

@darionyaphet do you have a repository that I can look at?

**Comment by darionyaphet** [comment]
I move it into a new repo seems could find `Open` and `DefaultOptions`

```
../../../dgraph-io/badger/y/zstd_cgo.go:22:2: cannot find package "github.com/DataDog/zstd" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/DataDog/zstd (from $GOROOT)
	/Users/darion/go/src/github.com/DataDog/zstd (from $GOPATH)
```

**Comment by jarifibrahim** [comment]
Do you have a `dataDog/zstd` directory inside `$GOPATH/pkg/mod/github.com/` path?

**Comment by darionyaphet** [comment]
No Should I download it ?

**Comment by jarifibrahim** [comment]
Yeah. Download it manually and see if it fixes your issue. Ideally, `go get github.com/dgraph-io/badger` should've downloaded `DataDog/ZSTD`.

**Comment by darionyaphet** [comment]
Nice ! It work well :)  But I meet another question.

```
# github.com/dgraph-io/badger
../../../dgraph-io/badger/db.go:386:31: undefined: ristretto.Metrics
../../../dgraph-io/badger/db.go:1481:15: db.blockCache.Clear undefined (type *ristretto.Cache has no field or method Clear)
```

**Comment by jarifibrahim** [comment]
Can you confirm if go mod is actually being used? The error shows you have an older version of ristretto. If go mod was being used, you should've got a newer version of ristretto.

You can do a `go get -v github.com/dgraph-io/ristretto` to fix this but I suggest you delete everything and start fresh. Ideally, all these dependencies should've been installed automatically.

**Comment by darionyaphet** [comment]
thanks a lot for your help. I have remove them and reinstall. It's useful and work well now.

**Comment by jarifibrahim** [comment]
@darionyaphet Badger does not have a c++ client. I found this [article](https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf) which says you can compile go code and use it in a C program. See if it helps.
