### ISSUE TITLE
VerifyValueChecksum functionality is broken

### ISSUE THREAD

**Issue by markadev** [dgraph-io/badger#1127]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### What version of Badger are you using?
v2.0.0

### Does this issue reproduce with the latest master?
master is the same as v2.0.0

### What are the hardware specifications of the machine (RAM, OS, Disk)?

Ubuntu 18.04 VM

### What did you do?

I set `VerifyValueChecksum` to `true` in the Options.  Then did a write and a read to read back the value.

```
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/dgraph-io/badger/v2"
)

func main() {
	opts := badger.DefaultOptions("/tmp/jankydb")
	opts.VerifyValueChecksum = true
	db, err := badger.Open(opts)
	if err != nil {
		fmt.Println("Open failed", err)
		os.Exit(1)
	}
	defer db.Close()

	key := []byte{0x00, 0x01, 0x02}
	value := make([]byte, 128)
	err = db.Update(func(txn *badger.Txn) error {
		return txn.Set(key, value)
	})
	if err != nil {
		fmt.Println("Update failed", err)
		os.Exit(1)
	}

	err = db.View(func(txn *badger.Txn) error {
		item, err := txn.Get(key)
		if err != nil {
			return err
		}
		return item.Value(func(readValue []byte) error {
			if !bytes.Equal(readValue, value) {
				return fmt.Errorf("Value not matched")
			}
			return nil
		})
	})
	if err != nil {
		fmt.Println("View failed", err)
		os.Exit(1)
	}
}
```

### What did you expect to see?

Reads in the presence of no corruption should behave the same as they did before.

### What did you see instead?

All reads return "checksum mismatch" error.

```
badger 2019/11/19 14:00:14 INFO: All 0 tables opened in 0s
View failed value corrupted for vp: {Fid:0 Len:149 Offset:20}: checksum mismatch
```

**Comment by jarifibrahim** [comment]
Thanks for reporting @markadev. I'll look into this.
