### ISSUE TITLE
close issue.

### ISSUE THREAD

**Issue by TangsWang** [dgraph-io/badger#1130]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.4
</pre>

### What version of Badger are you using?
latest

### Does this issue reproduce with the latest master?
yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
8G,win10,ssd

### What did you do?
when not exec db.Close() before exit process, it will occur "Value log truncate required to run DB. This might result in data loss" errors.
but if my program crash, it won't exec db.Close(), then db can't reopen again?

**Comment by jarifibrahim** [comment]
Hey @TangsWang , when DB crashes all your data might not be saved. When such a `crashed DB` has to be re-opened, you need to set the `truncate` options to `true`. The truncate option only removes the corrupted data. If your data was written to the vlog before the crash. It will replay the file and insert the data back into the DB.
