### ISSUE TITLE
port replication from Dgraph down to badger

### ISSUE THREAD

**Issue by yangzh** [dgraph-io/badger#1133]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### What version of Badger are you using?
2.0.0rc

### Does this issue reproduce with the latest master?
didn't test and doesn't apply here.

First of all, thanks for creating and maintaining such a great piece of software (with elegant design and solid implementation): it has been a joy and fun to play with it.

I think this is a general feature discussion / request (instead of a bug report). 

I'm trying to build a distributed data store, and I know badger is originally designed to be a key-value library that will be linked in-process, and you can see there is a mis-connection. Even though I can probably borrow the online replication logic from Dgraph, however, I'm a bit hesitate to do so as it requires intimate knowledge of how badger works inside and out, and a true dedication to details. 

The lack of server-to-server replication is a show stopper for me (and possible to other people) and I feel I really need some help here. So my questions: 
1) Does it make sense to port existing replication logic (from Dgraph) down to badger storage layer? The value proposition is that it will greatly help badger towards a fully-fledged key-value store solution, and can easily add at least a few hundred stars for badger, as it's such as useful feature addition.

2) At the same time, I understand distributed system is very complicated and it heavily depends on the replication primitives (as provided by underlying infrastructure). If that's too much of work (and distraction to the real porting work), I would say provide an abstraction layer on that, and provide enough documentation on how to plug in. I happen to have quite a few experience on that and am happy to iterate on a good compromise and solution. For my specific use case, I would like to try deployment under k8s. 

3) If full port is not possible (due to whatever reasons), can you (badger team) at least provide some working example of how online replication can be added to a badger keystore (and maybe some notes on anything we need to pay attention to). I have no doubt it's possible, but without some concrete code example (and documentation), it would be a daunting task.

In terms of form, I'm thinking about something similar to gRPC feature examples (https://github.com/grpc/grpc-go/tree/master/examples/features)

I'm happy to chat / iterate on this request. thanks again.

**Comment by shekarm** [comment]
Thank you for the questions. Someone from our team will respond soon.

**Comment by danielmai** [comment]
This is a duplicate of #451. Our answer today is the same as before: Raft is beyond the design goal of Badger.

Etcd has been useful for many as a distributed KV store. It's possible to have Badger as a backend for etcd as evident from this PR https://github.com/etcd-io/etcd/pull/10311. That'd be a great way to have a distributed version of Badger.
