### ISSUE TITLE
How to create a key only when it does not exist?

### ISSUE THREAD

**Issue by hnakamur** [dgraph-io/badger#114]
I know there are `Exists` and `Set`, but after calling `Exists` and before calling `Set` another goroutine may call `Set` then my call of `Set` overrides the value set by another goroutine without notice.
So I think we need something like `SetIfAbsent`.

**Comment by manishrjain** [comment]
https://godoc.org/github.com/dgraph-io/badger#KV.Touch is the closest to what you want. We can replace `Touch` with `SetIfAbsent`, if you also need to set a value.
