### ISSUE TITLE
[question] Can I iterate in Insertion Order?

### ISSUE THREAD

**Issue by leogr** [dgraph-io/badger#1141]
Is that possible and if so which is the best way?

In my use case I need to fetch the last inserted key, so it's actually reverse insertion order.

Thanks in advance.

**Comment by jarifibrahim** [comment]
Hey @leogr, I don't think there's a way to directly get items in the order of insertion. However, you could add some prefix which allows you to iterate in the order of insertion.

Let's say you want to insert `B`, `A`, `C`. then you could add integer prefix to your keys like `1B`, `2A`, `3C`. Now if you iterate over the entire DB in reverse order, you should get keys in the insertion order. 

There would still be a problem of cleaning up the prefix but that can be fixed.

**Comment by leogr** [comment]
Hi @jarifibrahim ,

Thanks for your answer. 

Just another idea: assuming all values are stored into the vlog (I know they could be skipped, but `ValueThreshold` can be set to 0), would it be possibile to iterate over the vlog directly?
Values are stored in insertion order, aren't?

**Comment by jarifibrahim** [comment]
@leogr Not really. Each transaction is written to the vlog file. Inside the transaction, the entries could be out of order. This might be easy to fix by writing only one entry in a single transaction.

We have  `vlog.iterate` but it's not exposed and it won't be easy to expose it since it uses some internal objects like the log file.

https://github.com/dgraph-io/badger/blob/1ee50f7900277ea1c153cee923108fd22caa8828/value.go#L400

**Comment by leogr** [comment]
@jarifibrahim I was aware that inside the transaction, the entries could be out of order, but it's not an issue (at least for my use case).

It would be awesome to have a public API for that, but I perfectly understand that's not so easy to expose.

Thank you.

**Comment by jarifibrahim** [comment]
@leogr I'd like to better understand why do you need to iterate entries in the order of which they were inserted. What are you trying to accomplish with this?

**Comment by leogr** [comment]
We're evaluating to build a tamper-evident history system on top of badger. Basically, KV pairs are always appended and never deleted, then a Merkle Tree is used to prove that data has been not changed. 

Implementing that would require to fetch KV pairs by insertion index, also to iterate in insertion order over a range of KV pairs or the full db (e.g. to check the consistency after a crash).

Atm (still R&D) we used badger in managed mode, writing only one entry per transaction and incrementing the commit timestamp by 1 each time (basically the timestamp would match the insertion order index). Ofc, not yet sure this is approach is correct.

In order to do not lose the lexicographic order of keys, I would avoid to encode the index as key prefix.
