### ISSUE TITLE
Why badger don't need a Bucket ?

### ISSUE THREAD

**Issue by fengyanliang** [dgraph-io/badger#1148]
I am used boltdb for a long time , I found Bucket is a useful function of it. Now I changed to use Badger.
Why badger don't need a Bucket?

**Comment by ForCraft2013** [comment]
> I am used boltdb for a long time , I found Bucket is a useful function of it. Now I changed to use Badger.
> Why badger don't need a Bucket?

 You can use key prefixes instead of Buckets. It's not as bad as it seems

**Comment by fengyanliang** [comment]
> > I am used boltdb for a long time , I found Bucket is a useful function of it. Now I changed to use Badger.
> > Why badger don't need a Bucket?
> 
> You can use key prefixes instead of Buckets. It's not as bad as it seems

Thanks for your replay, ForCraft2013.
But I don't think Prefix scan in badger can be as fast as foreach in a bucket. How can we use it on this condition?

**Comment by simon28082** [comment]
boltdb every bucket can use 2G space, but badger if only use single db only support 2G space,  I'm thinking of adding the badger bucket wrapper, which would be a collection of multiple db instances

**Comment by simon28082** [comment]
I have implemented a bucket function, I can contribute if needed
