### ISSUE TITLE
Doesn't report error that indicates data loss

### ISSUE THREAD

**Issue by notduncansmith** [dgraph-io/badger#1159]
### What version of Go are you using (`go version`)? 
`go1.13 darwin/amd64`

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### What version of Badger are you using?
github.com/dgraph-io/badger v1.6.0 h1:DshxFxZWXUcO0xX476VJC07Xsr6ZCBVRHKZ93Oh7Evo=

### Does this issue reproduce with the latest master?
Haven't checked

### What are the hardware specifications of the machine (RAM, OS, Disk)?
- 2018 MacBook Pro
- macOS Catalina 10.15.1
- 16 GB RAM 2400 MHz DDR4
- ~30GB of free disk space

### What did you do?

I was writing tests for a library I'm working on, and wanted to get Badger to report an error during the writing process. I decided to try removing the database directory while the DB was still open.

### What did you expect to see?

I expected to get an error when trying to write to a file that has been removed.

### What did you see instead?

No error is returned. BadgerDB accepts the write, and then hangs indefinitely on `db.Close()`. I see that others have reported the hang-on-close issue, but that's not my current worry. If the database directory is removed, and the current behavior is to go into an infinite loop (not sure how this is materially different from crashing?), then BadgerDB can know that there is no way it will be able to  save the written data and should not accept the write.

Full test case below:

```go
func TestBadgerReportsErrorOnWriteMissingFile(t *testing.T) {
	os.MkdirAll("./fixtures", 755)
	db, err := badger.Open(badger.DefaultOptions("./fixtures/will_be_removed"))
	if err != nil {
		t.Errorf("Should be able to open DB")
	}
	out, err := exec.Command("ls", "-al", "./fixtures").Output()
	fmt.Println(string(out), err)

	out, err = exec.Command("rm", "-rf", "./fixtures/will_be_removed").Output()
	fmt.Println(string(out), err)
	err = db.Update(func(txn *badger.Txn) error {
		return txn.Set([]byte("foo"), []byte("bar"))
	})

	if err == nil {
		t.Errorf("Should get error from writing to missing file")
	}

	err = db.Close()
	if err != nil {
		t.Errorf("Should be able to close DB %v", err)
	}
	db, err = badger.Open(badger.DefaultOptions("./fixtures/will_be_removed"))
	if err != nil {
		t.Errorf("Should be able to open DB")
	}

	out, err = exec.Command("ls", "-al", "./fixtures").Output()
	fmt.Println(string(out), err)

	var val string
	err = db.View(func(txn *badger.Txn) error {
		item, err := txn.Get([]byte("foo"))
		if err != nil {
			return err
		}
		return item.Value(func(v []byte) error {
			val = string(v)
			return nil
		})
	})

	if val != "bar" {
		t.Errorf("expected to find 'bar', found %v", val)
	}
}
```

Aside: if there's a better way to force BadgerDB to return an error from a write, I'd love to know. I don't expect DB files to get `rm -rf`'d in production, but couldn't figure out another way to get an error from a write.

**Comment by jarifibrahim** [comment]
Hey @notduncansmith , thanks for reporting this. The problem here is that all writes are kept in memory and then eventually flushed to a disk. These flushes run periodically and we don't report the error if it fails because the flush will be retried after some time.

However, in your case, the flush will never succeed since the directory does not exist. Badger wouldn't complain if you do a 	`rm -rf fixtures/will_be_removed/*` that is, you keep the directory but just delete the files inside the directory.

>Aside: if there's a better way to force BadgerDB to return an error from a write, I'd love to know. I don't expect DB files to get rm -rf'd in production, but couldn't figure out another way to get an error from a write.

Don't delete the directory, just remove the `directory contents`.

Also, if the same directory is reopened, you might have data loss because the `manifest file` which stores the information about every table is deleted. This means badger would mark old files as invalid and delete them.

**Comment by notduncansmith** [comment]
> The problem here is that all writes are kept in memory and then eventually flushed to a disk

I would agree that this is the problem. Is there any way to request that BadgerDB not return until the write is committed? If the files or directory have been removed, I want to get back an error from BadgerDB.

**Comment by jarifibrahim** [comment]
>I would agree that this is the problem. Is there any way to request that BadgerDB not return until the write is committed? If the files or directory have been removed, I want to get back an error from BadgerDB.

@notduncansmith `transaction.commit` call is blocking. We waiting until all writes are successful.
But if the directory is removed, there is no way badger can recover from the error. We have `value log` which serves as `write ahead log`. If your DB crashes before the memtable was flushed, we replay the value log to get the entries back. But if you lose the entire directory, badger cannot recover from it.
