### ISSUE TITLE
Is KV thread (goroutine) safe?

### ISSUE THREAD

**Issue by hnakamur** [dgraph-io/badger#116]
Can I use one instance of KV from multiple goroutines without lock?
I found the comment `For now, single threaded.` at
https://github.com/dgraph-io/badger/blob/5ae0851516a27bd02958c266f380a7fdb9096093/kv.go#L1007

Does that mean KV is not thread safe?

**Comment by manishrjain** [comment]
KV is thread-safe. In fact, we highly recommend doing writes in batches with multiple goroutines.

The code you're pointing to is just switching a mutable inmemory table to an immutable one. That small thing requires locks (which are encapsulating it). You can ignore that internal working as a user.

**Comment by hnakamur** [comment]
Thanks for your comment!
I found it is mentioned in FAQ.
https://github.com/dgraph-io/badger#frequently-asked-questions
