### ISSUE TITLE
BadgerDB open() call takes long time (> 2 min) to complete

### ISSUE THREAD

**Issue by SumanthPuram** [dgraph-io/badger#1161]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### What version of Badger are you using?
github.com/dgraph-io/badger v1.6.0

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
RAM - 16GB
OS - Ubuntu 16.04
Disk - SSD

### What did you do?

We are using BadgerDB for deduplication. We store message ID as the key and the value as nil.
We open the badgerdb during the initialization. 

<pre>
gateway.badgerDB, err = badger.Open(badger.DefaultOptions(path))
</pre>

Code that writes to badger DB
<pre>
		err := badgerDB.Update(func(txn *badger.Txn) error {
			for _, messageID := range messageIDs {
				e := badger.NewEntry([]byte(messageID), nil).WithTTL(dedupWindow * time.Second)
				if err := txn.SetEntry(e); err == badger.ErrTxnTooBig {
					_ = txn.Commit()
					txn = badgerDB.NewTransaction(true)
					_ = txn.SetEntry(e)
				}
			}
			return nil
		})
</pre>

<pre>
$ du -ch -d 1 ./badgerdb
18G	./badgerdb
18G	total

$ ls -l ./badgerdb/ | grep sst | wc -l
270
</pre>

Over 1 day, we have 270 SST files and 18 GB data.

### What did you expect to see?

The badger.Open call completing in a few seconds. 

### What did you see instead?

The badger.Open takes around 2.5 minutes to open 270 files.

**Comment by jarifibrahim** [comment]
Hey @SumanthPuram, can you show me the logs also? I suspect that your DB crashed and the entire `level 0` along with the `memtables` had to be replayed.

**Comment by lokey** [comment]
Hi @jarifibrahim, I work with @SumanthPuram. These are the badger DB logs when it took 2.5 minutes.

```
Dec 10 07:09:24 badger 2019/12/10 07:09:24 INFO: 6 tables out of 269 opened in 3.314s
Dec 10 07:09:27 badger 2019/12/10 07:09:27 INFO: 18 tables out of 269 opened in 6.447s
Dec 10 07:09:30 badger 2019/12/10 07:09:30 INFO: 23 tables out of 269 opened in 9.233s
Dec 10 07:09:33 badger 2019/12/10 07:09:33 INFO: 30 tables out of 269 opened in 12.212s
Dec 10 07:09:36 badger 2019/12/10 07:09:36 INFO: 43 tables out of 269 opened in 15.215s
Dec 10 07:09:39 badger 2019/12/10 07:09:39 INFO: 50 tables out of 269 opened in 18.314s
Dec 10 07:09:42 badger 2019/12/10 07:09:42 INFO: 58 tables out of 269 opened in 21.079s
Dec 10 07:09:45 badger 2019/12/10 07:09:45 INFO: 71 tables out of 269 opened in 24.087s
Dec 10 07:09:48 badger 2019/12/10 07:09:48 INFO: 75 tables out of 269 opened in 27.244s
Dec 10 07:09:51 badger 2019/12/10 07:09:51 INFO: 87 tables out of 269 opened in 30.039s
Dec 10 07:09:54 badger 2019/12/10 07:09:54 INFO: 97 tables out of 269 opened in 33.562s
Dec 10 07:09:58 badger 2019/12/10 07:09:58 INFO: 103 tables out of 269 opened in 36.945s
Dec 10 07:10:00 badger 2019/12/10 07:10:00 INFO: 110 tables out of 269 opened in 39.698s
Dec 10 07:10:04 badger 2019/12/10 07:10:04 INFO: 116 tables out of 269 opened in 43.598s
Dec 10 07:10:06 badger 2019/12/10 07:10:06 INFO: 119 tables out of 269 opened in 45.306s
Dec 10 07:10:09 badger 2019/12/10 07:10:09 INFO: 124 tables out of 269 opened in 48.562s
Dec 10 07:10:12 badger 2019/12/10 07:10:12 INFO: 130 tables out of 269 opened in 51.022s
Dec 10 07:10:16 badger 2019/12/10 07:10:16 INFO: 137 tables out of 269 opened in 54.872s
Dec 10 07:10:18 badger 2019/12/10 07:10:18 INFO: 141 tables out of 269 opened in 57.223s
Dec 10 07:10:21 badger 2019/12/10 07:10:21 INFO: 146 tables out of 269 opened in 1m0.149s
Dec 10 07:10:24 badger 2019/12/10 07:10:24 INFO: 152 tables out of 269 opened in 1m3.274s
Dec 10 07:10:27 badger 2019/12/10 07:10:27 INFO: 156 tables out of 269 opened in 1m6.101s
Dec 10 07:10:31 badger 2019/12/10 07:10:31 INFO: 163 tables out of 269 opened in 1m10.106s
Dec 10 07:10:34 badger 2019/12/10 07:10:34 INFO: 167 tables out of 269 opened in 1m13.069s
Dec 10 07:10:36 badger 2019/12/10 07:10:36 INFO: 170 tables out of 269 opened in 1m15.174s
Dec 10 07:10:40 badger 2019/12/10 07:10:40 INFO: 177 tables out of 269 opened in 1m19.211s
Dec 10 07:10:43 badger 2019/12/10 07:10:43 INFO: 182 tables out of 269 opened in 1m21.781s
Dec 10 07:10:45 badger 2019/12/10 07:10:45 INFO: 186 tables out of 269 opened in 1m24.338s
Dec 10 07:10:48 badger 2019/12/10 07:10:48 INFO: 191 tables out of 269 opened in 1m27.351s
Dec 10 07:10:52 badger 2019/12/10 07:10:52 INFO: 195 tables out of 269 opened in 1m30.879s
Dec 10 07:10:54 badger 2019/12/10 07:10:54 INFO: 199 tables out of 269 opened in 1m33.669s
Dec 10 07:10:57 badger 2019/12/10 07:10:57 INFO: 205 tables out of 269 opened in 1m36.495s
Dec 10 07:11:00 badger 2019/12/10 07:11:00 INFO: 209 tables out of 269 opened in 1m39.091s
Dec 10 07:11:04 badger 2019/12/10 07:11:04 INFO: 215 tables out of 269 opened in 1m42.998s
Dec 10 07:11:06 badger 2019/12/10 07:11:06 INFO: 219 tables out of 269 opened in 1m45.319s
Dec 10 07:11:09 badger 2019/12/10 07:11:09 INFO: 226 tables out of 269 opened in 1m48.237s
Dec 10 07:11:13 badger 2019/12/10 07:11:13 INFO: 231 tables out of 269 opened in 1m52.004s
Dec 10 07:11:15 badger 2019/12/10 07:11:15 INFO: 236 tables out of 269 opened in 1m54.09s
Dec 10 07:11:19 badger 2019/12/10 07:11:19 INFO: 241 tables out of 269 opened in 1m57.935s
Dec 10 07:11:21 badger 2019/12/10 07:11:21 INFO: 245 tables out of 269 opened in 2m0.33s
Dec 10 07:11:24 badger 2019/12/10 07:11:24 INFO: 250 tables out of 269 opened in 2m3.096s
Dec 10 07:11:27 badger 2019/12/10 07:11:27 INFO: 255 tables out of 269 opened in 2m6.547s
Dec 10 07:11:30 badger 2019/12/10 07:11:30 INFO: 261 tables out of 269 opened in 2m9.307s
Dec 10 07:11:33 badger 2019/12/10 07:11:33 INFO: 265 tables out of 269 opened in 2m12.697s
Dec 10 07:11:35 badger 2019/12/10 07:11:35 INFO: All 269 tables opened in 2m14.596s
Dec 10 07:11:35 badger 2019/12/10 07:11:35 INFO: Replaying file id: 330 at offset: 37670486
Dec 10 07:11:36 badger 2019/12/10 07:11:36 INFO: Replay took: 1.081368103s
```

**Comment by jarifibrahim** [comment]
Hey @lokey , the problem here is that you have many tables and badger v1.6 would load all of them into memory and then try to initialize them. 

https://github.com/dgraph-io/badger/blob/2fa005c9d4bf695277ab5214c1fbce3735b9562a/table/table.go#L146-L149

We've made significant changes to how tables are opened in badger v2. Can you please try to migrate your data directory from badger v1.6 to badger v2.0 and try it again?

Here's how you can migrate the data directory - https://github.com/dgraph-io/badger#i-see-manifest-has-unsupported-version-x-we-support-y-error

**Comment by SumanthPuram** [comment]
Hi @jarifibrahim 
I ran a test with latest v2.0.0-rc2.

Please check out the test repo here
https://github.com/SumanthPuram/badger-test

I generated some load for a few hours. It generated 22GB data and DB took 36 secs to open. This is much better than the earlier version. But we are planning to use badgerDB for deduplication, and this needs to be started before starting our HTTP server. So, we can manage up to a few seconds of latency and 36 secs is still a huge time for us.

Can you suggest tuning any parameters that could help the loading time? 

```
$ go run main.go
badger 2019/12/20 08:20:45 INFO: 27 tables out of 329 opened in 3.108s
badger 2019/12/20 08:20:48 INFO: 54 tables out of 329 opened in 6.027s
badger 2019/12/20 08:20:51 INFO: 82 tables out of 329 opened in 9.007s
badger 2019/12/20 08:20:54 INFO: 111 tables out of 329 opened in 12.159s
badger 2019/12/20 08:20:57 INFO: 141 tables out of 329 opened in 15.194s
badger 2019/12/20 08:21:00 INFO: 168 tables out of 329 opened in 18.073s
badger 2019/12/20 08:21:03 INFO: 198 tables out of 329 opened in 21.051s
badger 2019/12/20 08:21:06 INFO: 228 tables out of 329 opened in 24.16s
badger 2019/12/20 08:21:09 INFO: 259 tables out of 329 opened in 27.229s
badger 2019/12/20 08:21:12 INFO: 288 tables out of 329 opened in 30.183s
badger 2019/12/20 08:21:15 INFO: 319 tables out of 329 opened in 33.189s
badger 2019/12/20 08:21:16 INFO: All 329 tables opened in 34.243s
badger 2019/12/20 08:21:16 INFO: Replaying file id: 561 at offset: 5291081
badger 2019/12/20 08:21:17 INFO: Got compaction priority: {level:1 score:1.0706684216856956 dropPrefix:[]}
badger 2019/12/20 08:21:17 INFO: Running for level: 1
badger 2019/12/20 08:21:18 INFO: Got compaction priority: {level:2 score:1.03202206119895 dropPrefix:[]}
badger 2019/12/20 08:21:18 INFO: Running for level: 2
badger 2019/12/20 08:21:18 INFO: Replay took: 2.329462897s
badger 2019/12/20 08:21:18 INFO: Replaying file id: 562 at offset: 0
badger 2019/12/20 08:21:18 DEBUG: LOG Compact. Added 1713931 keys. Skipped 0 keys. Iteration took: 833.026345ms
badger 2019/12/20 08:21:18 INFO: Replay took: 280.382597ms
DB Opened in: 36 secs
badger 2019/12/20 08:21:19 DEBUG: LOG Compact. Added 1717881 keys. Skipped 0 keys. Iteration took: 877.651606ms
```

**Comment by jarifibrahim** [comment]
@SumanthPuram You can try increasing the table size. The less number of tables you have, the less work badger has to do while opening them. The default size is 64 MB, try setting it to a higher value (opt.MaxTableSize).

There are other side effects of this change.
 - Badger will consume more memory because all L0 tables are stored in memory (you can change this by setting the KeepL0InMemory options to `false`)
 - Compactions will take longer. Compaction merges multiple tables into one. The bigger the tables, the costlier the compactions.


Maybe there's something we can do to optimize the start-up time. Can you show me your CPU and memory profiles?

Here's how you can profile your program https://golang.org/pkg/net/http/pprof/ 
 - Import net/pprof
 - Start a golang web server
 - Do a curl on `localhost:port/debug/pprof/profile` and `localhost:port/debug/pprof/heap`  (Please do this while badger is trying to open the table files. Ideally you should try to run this while badger has opened more than half the table files.) 

Please send me both the files and I'll see what can be done.

**Comment by gane5hvarma** [comment]
Hi @jarifibrahim, i have used two versions [v2.0.0-rc1](https://github.com/dgraph-io/badger/tree/v2.0.1-rc1) and [v2.0.0-rc2](https://github.com/dgraph-io/badger/tree/release/v2.0) and generated around 6gb of data. below are the stats for both versions.

- rc1
took around 300 sec for badger.Open(badger.DefaultOptions(path)) and no of tables are around 29

![cpu_v2 0 0-rc1](https://user-images.githubusercontent.com/23616236/71616321-ba33a380-2bdb-11ea-99a7-16e62db4bc24.gif)
![heap_v2 0 0-rc1](https://user-images.githubusercontent.com/23616236/71616345-cfa8cd80-2bdb-11ea-810d-9f326c23b3bf.gif)

- rc2
took around 10 sec and no of tables are around 75
![cpu_v2 0 0-rc2](https://user-images.githubusercontent.com/23616236/71616377-f5ce6d80-2bdb-11ea-9751-927500df4424.gif)
![heap_v2 0 0-rc2](https://user-images.githubusercontent.com/23616236/71616381-fb2bb800-2bdb-11ea-940b-18b089f4d86f.gif)

**Comment by jarifibrahim** [comment]
Hey @gane5hvarma , I'm sorry I forgot to mention. please run your test/benchmarks against `badger v2` (`rc1` and `rc2` are very different from each other).

From the profiles, it seems like compression seems to be taking a lot of time (compression algorithms are slow). So please set the compression option to `None` and that should improve your startup speed.

Can you share your data generation script? Are you using the badger write benchmark tool to generate the data? It'll be easier for me to profile the code if I have it locally.

**Comment by gane5hvarma** [comment]
Hi @jarifibrahim you can find the data generation script [here](https://github.com/SumanthPuram/badger-test/blob/master/main.go)

**Comment by gane5hvarma** [comment]
Hi @jarifibrahim. any update on this issue and workaround's do you want me to try?

**Comment by jarifibrahim** [comment]
@gane5hvarma Did you try with `WithCompression(options.None)`? This should have significant speed improvement.

**Comment by jarifibrahim** [comment]
I have a badger directory with around 300 GB of data (740 SST) and I see that the `JSON Unmarshal` of the bloom filter takes up most of the time.
![Screenshot from 2020-01-21 18-55-20](https://user-images.githubusercontent.com/12949454/72819247-f2864900-3c92-11ea-8236-fc4d9eeb5ca7.png)

I think we can do either of two things here
1. Optimize the bloom filter read from the file (store bloom filters in a different manner?)
2. Make bloom filters optional (user can disable bloom filter if not needed)

**Comment by gane5hvarma** [comment]
@jarifibrahim how can I disable bloom filter

**Comment by jarifibrahim** [comment]
@gane5hvarma Badger doesn't support disabling bloom filters right now. We might add this in the future. We'll be more than happy to accept a PR :)

**Comment by gane5hvarma** [comment]
@jarifibrahim how much did it took for badger.Open() for 300 GB of data and 740 sst ?

**Comment by jarifibrahim** [comment]
@gane5hvarma I don't remember correctly but it took more than 7 minutes. Also, I was running it on a hard disk so it would take some time to open the files.

You can do `opt.MaxCacheSize = 0` to disable cache. Once the cache is disabled, we won't load the bloom filters on DB open. They will be read from the SST on demand.

I would suggest you disable compression and encryption if you've disabled the cache otherwise for every read, badger will have to read data from the file and decompress/decrypt it.


@gane5hvarma would it be useful for you if there was an option to disable the bloom filters completely? Disabling bloom filters mean the read speed would be reduced but I think you don't care much about the read speed. Is this correct?

**Comment by jarifibrahim** [comment]
Hey @gane5hvarma, I've raised a PR to improve the startup speed https://github.com/dgraph-io/badger/pull/1233 . Can you try this PR and let me know how it goes?

**Comment by jarifibrahim** [comment]
The original report says it took more than 2 minutes to open 270 tables and on this PR https://github.com/dgraph-io/badger/pull/1233 I was able to open 497 tables in around 10 seconds.

I think the major performance difference is because I tested on the latest master branch while @SumanthPuram did their tests on v1.6 release.

**Comment by SumanthPuram** [comment]
We did our tests on v2.0.0-rc1 and v2.0.0-rc2 as well. Anyway, we will give it a shot sometime soon and get back to you @jarifibrahim

**Comment by jarifibrahim** [comment]
@SumanthPuram Please run your tests against v2.0.2 or master. The v2.0.0-rc1 and v2.0.0-rc2 don't have newer fixes. We don't have any breaking changes on the v2 release so the same data directory which works for v2.0.0-rc* should work for v2.0.2 or master.

**Comment by jarifibrahim** [comment]
Hey @SumanthPuram, with PR https://github.com/dgraph-io/badger/pull/1260 , we've added a new flag `LoadBloomsOnOpen`. When this flag is set to false, the bloom filters won't be loaded at DB startup. This should improve the DB startup time.

Thank you for filing the issue and helping debug it :)
