### ISSUE TITLE
DropAll()  error

### ISSUE THREAD

**Issue by rickyHuang1986** [dgraph-io/badger#1164]
badger 2019/12/19 15:30:19 INFO: DropAll called. Blocking writes...
panic: close of closed channel

goroutine 127483 [running]:
github.com/dgraph-io/badger/y.(*Closer).Signal(...)

**Comment by jarifibrahim** [comment]
@rickyHuang1986 Can you share the complete stack trace? What were you trying to do with badger when it crashed? Any information would be useful.

**Comment by rickyHuang1986** [comment]
Concurrent request DropAll produce an accident ,Because Implementation of delete File size unchanged So I used this method

**Comment by rickyHuang1986** [comment]
Concurrent request the method of DropAll,and using the method of Delete to delete the file of key which will cause the size of key don’t change by accident.So I add ‘db.Update(func(txn *badger.Txn) error {’ in the method of DropAll

**Comment by jarifibrahim** [comment]
@rickyHuang1986 why do you need to call `dropAll` concurrently? Calling it once vs calling it concurrently would have the same outcome.

**Comment by jarifibrahim** [comment]
@rickyHuang1986 I'm closing this issue as it is invalid. Calling `dropAll` concurrently has no benefit and you shouldn't be doing it.

Feel free to reopen if you think there's something we should fix in Badger.
