### ISSUE TITLE
Using Badger for storing immutable, append-only logs, FIFO compaction strategy?

### ISSUE THREAD

**Issue by morningsend** [dgraph-io/badger#1165]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### What version of Badger are you using?
v2.0

Hi, we are comparing Badger and RocksDB and are building a distributed database. I am wondering what is the options in badger to optimise the key-value store for append-only log storage. The log entries would be appended in order and never change. We would like to periodically drop older logs to free disk space.

RocksDB supports FIFO compaction strategy which will delete old data by removing SSTables. I am wondering if Badger can support something similar?

**Comment by ashish-goswami** [comment]
Hey @morningsend, currently Badger doesn't have much options to tweak compaction(other than number of threads running compaction concurrently). Badger follows level tiered compaction strategy(with `minimum overlapping file picking first` strategy).

**Comment by morningsend** [comment]
@ashish-goswami  Thanks for your advice.

**Comment by jarifibrahim** [comment]
@morningsend In FIFO style compaction the oldest table is deleted first. Badger supports only leveled compaction for now. By default, we keep only a single version of a key. Older versions are dropped by compactions automatically. This means old stale data will be cleaned up eventually.
