### ISSUE TITLE
badger.Open copies the options.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/badger#1178]
I was trying to fix some of the warnings in dgraph about copied arguments. Some of them involved the `badger.Options` object but I didn't fix them because `badger.Open` is invoked later and the options are passed as a copy. Why is this the case? From the code there doesn't seem to be a good reason and `badger.Options` is a fairly big struct. I assume that changing the signature of `badger.Open` is a breaking change so it would need to be approved. Not a huge deal, though.

@jarifibrahim, thoughts?

**Comment by jarifibrahim** [comment]
I agree @martinmr . I think when the `db.Open(..)` function was added `badger.Option` was a small struct. We've added too many new options in recent times and so we might want to use pointers now.

This could definitely be fixed in badger 3.x release.

**Comment by jarifibrahim** [comment]
@martinmr, @ashish-goswami pointed out that there might be issues if we accept a pointer to the option struct in `Open`. Once the options are passed to badger, we use only pointers to it everywhere in the system. If the user `accidentally` changes any of the passed options, we might run into issues.

I think it's safe to make one copy of the option struct and use pointers to it inside badger.
