### ISSUE TITLE
Provide options for disabling Cache

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/badger#1183]

**Comment by damz** [comment]
Adding an option to disable the bloom filter would be interesting too. We have a use case where we do not do any single-key lookups, and my understanding is that it means we have no use for neither the cache nor the bloom-filter.

**Comment by jarifibrahim** [comment]
>We have a use case where we do not do any single-key lookups, and my understanding is that it means we have no use for neither the cache nor the bloom-filter.

@damz Bloom filters are used for single key look ups https://github.com/dgraph-io/badger/blob/0f2e6297a34efdb07001eba8531ed85e8b42189e/level_handler.go#L263-L268

Cache is also used for single key look ups (we fetch the block that has the key) https://github.com/dgraph-io/badger/blob/0f2e6297a34efdb07001eba8531ed85e8b42189e/table/iterator.go#L223

**Comment by damz** [comment]
@jarifibrahim Do you want a PR for disabling the bloom filter?
