### ISSUE TITLE
Very High Disk Reads

### ISSUE THREAD

**Issue by qrpike** [dgraph-io/badger#1188]
### What version of Go are you using (`go version`)?
1.12.3

### What version of Badger are you using?
2.0.0

### What are the hardware specifications of the machine (RAM, OS, Disk)?
CoreOS Stable, 10gb ram for this service ( 128gb ram total ), RAID0 2tb samsung SSDs

### The issue
The disk writes are normal and consistent when writing data to the DB. However the disk reads spike dramatically ( I believe this is due to running the compactions & GC ). All of our data has a 48hr TTL.

My question: Is there anything we can do to cut down on the disk reads. It is negatively impacting other services which are running on this machine. We are currently running GC every 5min. Would changing the max levels or anything else relieve this pressure? Even if it takes up more space on disk. 

Thanks,

**Comment by jarifibrahim** [comment]
Hey @qrpike 
How big are your values? For value sizes less than 32 bytes we keep them in the LSM tree. The LSM Tree is stored in the memory (memory-mapped mode) which means if you read the value from LSM tree, you should get very low disk reads (or none).

Here's a list of options you should tweak
- Set `KeepL0InMemory` - if you keep `level 0` in memory, you would see higher memory usage but there would be fewer disk reads.
- Ensure your `tableLoadingMode` is set to either `memory-map` or `fileIO`
- Set a higher `ValueThreshold` - ValueThreshold is used to determine if the `value` should be kept in `LSM Tree` or `value log` file. LSM trees are usually memory-mapped or stored completely in ram.


Can you share your `badger.Options`, please?

> Is there anything we can do to cut down on the disk reads. It is negatively impacting other services which are running on this machine. We are currently running GC every 5min. Would changing the max levels or anything else relieve this pressure? Even if it takes up more space on disk

You should reduce the GC interval. Every GC call will read the key from the LSM tree and if the key should be GC'ed, the value will be read from LSM Tree/Vlog file and written back to the LSM Tree (with newer pointers).
