### ISSUE TITLE
Error closing the badger KV

### ISSUE THREAD

**Issue by stephane-martin** [dgraph-io/badger#119]
Hello,

after updating badger with recent changes, I now have an error when calling Close():

`KV.Close: close /badger/dir: bad file descriptor`

opts.ValueDir is the same directory than opts.Dir.

The error happens on MacOS and OpenBSD (haven't tried FreeBSD), but not on Linux.

Tell me if you need more debug info or some tests.

Thank you!

**Comment by srh** [comment]
Hey @stephane-martin, this is an interesting bug, I'll fix it and try it out on my Mac soon today.

**Comment by srh** [comment]
This doesn't reproduce on my Mac.  Could you show me the program that produces this error?

**Comment by stephane-martin** [comment]
I can't reproduce in an atomic setup either. The code is there (https://github.com/stephane-martin/skewer/blob/master/store/store.go) but it is not trivial.

I ran a dtrace to identify where it happens:

```
unlink("/var/lib/skewer/LOCK\0", 0x70000E054C5C, 0x0)		 = 0 0
close(0x3)		 = -1 Err#9
open("/var/lib/skewer\0", 0x1000000, 0x0)		 = 3 0
fsync(0x3, 0x1000000, 0x0)		 = 0 0
close(0x3)		 = 0 0
open("/var/lib/skewer\0", 0x1000000, 0x0)		 = 3 0
fsync(0x3, 0x1000000, 0x0)		 = 0 0
close(0x3)		 = 0 0
```
That should correspond to: https://github.com/dgraph-io/badger/blob/master/y/directorylock_unix.go

```
err := os.Remove(guard.path)
if closeErr := guard.f.Close(); err == nil {
        err = closeErr
}
```

**Comment by stephane-martin** [comment]
After adding an explicit call to unlock the flock, the issue looks solved.

The linux man page for flock states:
"the lock is released either by an explicit LOCK_UN operation on any of these duplicate file descriptors, or when all such file descriptors have been closed."

If I read correctly, the MacOS flock man page does not have such a statement about "when all FD have been closed".



```
// Release deletes the pid file and releases our lock on the directory.
func (guard *DirectoryLockGuard) Release() error {
	// It's important that we remove the pid file first.
	err := os.Remove(guard.path)
	----> unix.Flock(int(guard.f.Fd()), unix.LOCK_UN) <----
	if closeErr := guard.f.Close(); err == nil {
		err = closeErr
	}
	guard.f.Close()
	guard.path = ""
	guard.f = nil

	return err
}
```

**Comment by srh** [comment]
Could you show the part of the syscall trace before that, between opening and closing the descriptor?  Say, grepping every line between that matches 0x3?

What version of macOS are you using?

I've never seen anything like this, and I've used `flock(fd, LOCK_UN | LOCK_EX) ... close(fd)` successfully (with error code checking for close) on a directory for a long time, on macOS.

```
// Release deletes the pid file and releases our lock on the directory.
func (guard *DirectoryLockGuard) Release() error {
	// It's important that we remove the pid file first.
	err := os.Remove(guard.path)
	----> unix.Flock(int(guard.f.Fd()), unix.LOCK_UN) <----
	if closeErr := guard.f.Close(); err == nil {
		err = closeErr
	}
	guard.f.Close()  <----------------------
	guard.path = ""
	guard.f = nil

	return err
}
```

What's this extra Close() call here?  That's not in Badger's master branch.

**Comment by stephane-martin** [comment]
The extra Close() was copy-paste junk.

But you're right, and the LOCK_UN did not solve it :( My mistake.

MacOS 10.12.6

Will post trace in a few min.

**Comment by stephane-martin** [comment]
I struggled to get the correct trace...
- When i add a time.Sleep(time.Second) at program start, the Close() error does not appear at program end
- Sometimes when tracing with dtrace the error disappears.
- Anything that slowers the program makes the error disappear.

So there is some racing condition smell there...

Anyway the trace, filtered on "(0x3|3\s0)" : https://pastebin.com/uBBEFHRk

**Comment by stephane-martin** [comment]
Looks suspicious:

```
close(0x3)		 = 0 0
stat64("/var/lib/skewer/clog\0", 0xC42007A038, 0x3)		 = 0 0
```

The two lines appear next to each other in the unfiltered trace, so they probably happen in the same part of code.

Is it possible that somewhere in levels.go the root badger directory with the same name would be closed ?

**Comment by srh** [comment]
```
open("/var/lib/skewer\0", 0x1000000, 0x0)        = 3 0
flock(0x3, 0x6, 0x0)         = 0 0
getpid(0x3, 0x6, 0x0)        = 69890 0
close(0x3)       = 0 0
```
Going by this it looks like the problem isn't flock.  It opens, flocks, and closes, relatively early in the process. It looks like that's when the KV has been closed, and you're using the KV after it has been closed.  (You would see the removal of LOCK early in the trace too.)

Because there's the assignment fd = -1 in the File::Close() method, I think something then happens to create two File::Close() calls on the same File, from different threads.

**Comment by stephane-martin** [comment]
After adding a bunch of fmt.Printf everywhere in badger when a file close happens ("print debugging, a more civilized tool for more civilized times"), I can see strange things.

In compact_log.go:
```
func compactLogIterate(filename string, f func(c *compaction)) error {
	fd, err := os.Open(filename) // Read only.
	if err != nil {
		return err
	}
	defer func() {
		fmt.Printf("compactLogIterate close fd: %d\n", int(fd.Fd()))    // <---------
		fd.Close()
	}()
```

In directorylock_unix.go:
```
func AcquireDirectoryLock(dirPath string, pidFileName string) (*DirectoryLockGuard, error) {
	// Convert to absolute path so that Release still works even if we do an unbalanced
	// chdir in the meantime.
	absPidFilePath, err := filepath.Abs(filepath.Join(dirPath, pidFileName))
	if err != nil {
		return nil, errors.Wrap(err, "cannot get absolute path for pid lock file")
	}
	f, err := os.Open(dirPath)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot open directory %q", dirPath)
	}
	fd := int(f.Fd())
	fmt.Printf("fd: %d\n", fd) // <------
	err = unix.Flock(fd, unix.LOCK_EX|unix.LOCK_NB)


[...]
// Release deletes the pid file and releases our lock on the directory.
func (guard *DirectoryLockGuard) Release() error {
	fmt.Println("Release!") // <-----

```

Then on some executions, i can see:
```
fd: 3
compactLogIterate close fd: 3




[...
and finally near end of exec
...]

valueLog close: 10
Table Close: 8
Table Close: 3
Table Close: 4
Table Close: 10
Table Close: 7
compactLog close fd: 9
Release!
WARN[07-25|02:03:35] Error closing the badger                 class=MessageStore error="KV.Close: close /var/lib/skewer: bad file descriptor"
``

**Comment by stephane-martin** [comment]
(I also added some check guards in my code to ensure that the KV is not used after KV.Close() is called)

**Comment by stephane-martin** [comment]
http://www.linuxprogrammingblog.com/multi-thread-specific-bugs, "Double close() and other uses of invalid file descriptors"

I think there is one lingering somewhere, don't know if it is in badger code, or mine. Ill try to find out net evening...

**Comment by stephane-martin** [comment]
very stupid error on my side. you can close. thanks for your time.
