### ISSUE TITLE
Replace eventlog with normal logs

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1193]
Badger uses [`eventLog`](https://godoc.org/golang.org/x/net/trace#EventLog) to keep track of long-running background operations.
 https://github.com/dgraph-io/badger/blob/2a90c665f1e57fdc48256f222ed5d826c554043c/levels.go#L38-L42

https://github.com/dgraph-io/badger/blob/2a90c665f1e57fdc48256f222ed5d826c554043c/value.go#L828-L832

These `eventLogs` are expensive as seen in https://github.com/dgraph-io/badger/issues/938#issuecomment-513964707

All the trace/eventlog calls should be replaced with `logger.Debugf(...)` statements.

**Comment by gabru-md** [comment]
Hi @jarifibrahim 
I've started writing Go quite recently. Can I work on it?

**Comment by jarifibrahim** [comment]
Hey @gabru-md, feel free to work on it. We use https://godoc.org/golang.org/x/net/trace#EventLog which we don't really need. The task here to is to replace all the `eventlog.Printf` with `logger.Debugf(..)` statements.
