### ISSUE TITLE
Remove coveralls.io integration

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1196]
`Coverall.io` integration fails frequently which leads to a failed build. We should remove it.

See example build https://travis-ci.org/dgraph-io/badger/jobs/636936733?utm_medium=notification&utm_source=github_status

https://github.com/dgraph-io/badger/blob/5870b7b1975e031549f8a3d4309335f6b03f0fa4/.travis.yml#L24-L29

**Comment by janisz** [comment]
How about replacing it with https://codecov.io/
Integration is much simpler 
```
after_success:
- bash <(curl -s https://codecov.io/bash)
```

**Comment by vardhanapoorv** [comment]
@janisz the code coverage isn't a reliable metric, hence it would be better to remove it.
Feel free to send a PR.

**Comment by janisz** [comment]
@vardhanapoorv test are not working :(

**Comment by jarifibrahim** [comment]
Hey @janisz . I am aware of the test failure. There seems to be some configuration issue with the build. We'll fix it soon :)

Thank you for your PR.
