### ISSUE TITLE
TestPageBufferReader2 test is flaky

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1197]
Travis build randomly fails with 
```
=== RUN   TestPagebufferReader2
--- FAIL: TestPagebufferReader2 (0.00s)
    y_test.go:185: 
        	Error Trace:	y_test.go:185
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestPagebufferReader2
        	Messages:   	unable to read error
=== RUN   TestPagebufferReader3
--- PASS: TestPagebufferReader3 (0.00s)
=== RUN   TestPagebufferReader4
--- PASS: TestPagebufferReader4 (0.00s)
FAIL
coverage: 19.9% of statements
FAIL	github.com/dgraph-io/badger/y	0.022s

```
see https://travis-ci.org/dgraph-io/badger/jobs/636936684#L9192

I've seen the test fail multiple times on various PRs.

**Comment by andhe** [comment]
I just ran into this and looking at https://sources.debian.org/src/badger/2.0.1-2/y/y_test.go/#L179 I think there's an off-by-one. The problem can be reproduced by setting `randOffset` to the biggest number that randInt31n may return statically like:

```
        //randOffset := int(rand.Int31n(int32(b.length)))
        randOffset := int(int32(b.length-1))
```

This makes the problem reliably reproducible as the offset is now pointing at EOF.

Thus hopefully changing the line to this should solve the problem:
`randOffset := int(rand.Int31n(int32(b.length-1)))`

**Comment by jarifibrahim** [comment]
That could actually fix the issue. Can you send a PR @andhe? We'll be more than happy to accept it :)
Thank you for looking into this.
