### ISSUE TITLE
Block size may exceed max block size specified in options

### ISSUE THREAD

**Issue by jiapengliu613** [dgraph-io/badger#1212]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13

</pre>

### What version of Badger are you using?
master

### Does this issue reproduce with the latest master?
yes

### What did you do?

I started reading badger's source code recently and noticed that in the part of building sst blocks, there is a potential bug where block size might exceed the max specified in the option, in `shouldFinishBlock` method
```go
entriesOffsetsSize := uint32((len(b.entryOffsets)+1)*4 +
		4 + // size of list
		8 + // Sum64 in checksum proto
		4) // checksum length
``` 
here 8 bytes is accounted for checksum and compared against the limit, however what's actually stored is the proto bytes which will be larger than 8 bytes. This leads to a situation where having 8 bytes to store checksum won't exceed the limit but the actual stored proto bytes will. 

i'm pretty new to badger, not sure if there will be any further implications if block data exceeds limit.

**Comment by jarifibrahim** [comment]
Hey @jiapengliu613, the actual size of the checksum stored in the block is 6 bytes. You can easily find the size by adding a print statement.
```diff
diff --git a/table/builder.go b/table/builder.go
index 2651949..53bf582 100644
--- a/table/builder.go
+++ b/table/builder.go
@@ -19,6 +19,7 @@ package table
 import (
 	"bytes"
 	"crypto/aes"
+	"fmt"
 	"math"
 	"unsafe"
 
@@ -304,6 +305,7 @@ func (b *Builder) writeChecksum(data []byte) {
 	// Write checksum to the file.
 	chksum, err := proto.Marshal(&checksum)
 	y.Check(err)
+	fmt.Println("len checkusm", len(chksum))
 	n, err := b.buf.Write(chksum)
 	y.Check(err)
 ```

>i'm pretty new to badger, not sure if there will be any further implications if block data exceeds limit.

There's no side effect if the table size exceeds the limit. Usually, the table size is less than the limit. If the user has set a `4 KB` limit, the block would not have `4 KB` of actual data.
