### ISSUE TITLE
panic on compaction

### ISSUE THREAD

**Issue by mjentsch** [dgraph-io/badger#1222]
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### What version of Badger are you using?
1.6.0

### Does this issue reproduce with the latest master?
can't test due to incompatible file formats

### What did you do?
flatten + runGC

### What did you expect to see?
no crash

### What did you see instead?
Feb 20 09:40:03 s0eu store: badger 2020/02/20 09:40:03 DEBUG: LOG Compact. Added 1716167 keys. Skipped 2 keys. Iteration took: 1.757337981s
Feb 20 09:40:05 s0eu store: badger 2020/02/20 09:40:05 DEBUG: LOG Compact. Added 1703932 keys. Skipped 0 keys. Iteration took: 1.747716922s
Feb 20 09:40:06 s0eu store: badger 2020/02/20 09:40:06 DEBUG: LOG Compact. Added 1716972 keys. Skipped 0 keys. Iteration took: 1.520665838s
Feb 20 09:40:07 s0eu store: panic: send on closed channel
Feb 20 09:40:07 s0eu store: goroutine 6042 [running]:
Feb 20 09:40:07 s0eu store: github.com/dgraph-io/badger.(*DB).ensureRoomForWrite(0xc00004f500, 0x0, 0x0)
Feb 20 09:40:07 s0eu store: /home/ssdg.4/src/github.com/dgraph-io/badger/db.go:804 +0x123
Feb 20 09:40:07 s0eu store: github.com/dgraph-io/badger.(*DB).writeRequests(0xc00004f500, 0xc0bd4b8dc0, 0x1, 0xa, 0xc000222080, 0xc00048a800)
Feb 20 09:40:07 s0eu store: /home/ssdg.4/src/github.com/dgraph-io/badger/db.go:635 +0x216
Feb 20 09:40:07 s0eu store: github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc0bd4b8dc0, 0x1, 0xa)
Feb 20 09:40:07 s0eu store: /home/ssdg.4/src/github.com/dgraph-io/badger/db.go:692 +0x5a
Feb 20 09:40:07 s0eu store: created by github.com/dgraph-io/badger.(*DB).doWrites
Feb 20 09:40:07 s0eu store: /home/ssdg.4/src/github.com/dgraph-io/badger/db.go:741 +0x329

**Comment by jarifibrahim** [comment]
Hey @mjentsch, the fix for this issue is already in the `release/v1.6` branch https://github.com/dgraph-io/badger/compare/v1.6.0...release/v1.6 . You can try updating your go mod to use the `release/v1.6` branch. Run `go get -v -u github.com/dgraph/badger@587c8113304dde4ce6052a77ee5cb341c1266bea`.
