### ISSUE TITLE
Unable to use Badger on Raspberry

### ISSUE THREAD

**Issue by dstreppa** [dgraph-io/badger#1229]
Hi all,
I am trying to use Badger on a Raspberry but with no results.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/arm
</pre>

### What version of Badger are you using?

<pre>
github.com/dgraph-io/badger v1.6.0
</pre>

### What are the hardware specifications of the machine (RAM, OS, Disk)?

<pre>
ARCH: ARM
RAM: 1 GB
DISK: 32 GB
OS: Raspbian GNU/Linux 9
</pre>

### What did you do?

I've tested this simple code fund on the github doc:

<pre>
package main

import (
	"log"
	badger "github.com/dgraph-io/badger"
)

func main() {
	// Open the Badger database located in the /tmp/badger directory.
	// It will be created if it doesn't exist.
	db, err := badger.Open(badger.DefaultOptions("/tmp/badger"))
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	// Your code here…
}
</pre>

### What did you expect to see?

Something similar to the following output, tested on my PC:

<pre>
$ GOPATH/bin/test_badger 
badger 2020/02/25 16:57:23 INFO: All 1 tables opened in 0s
badger 2020/02/25 16:57:23 INFO: Replaying file id: 0 at offset: 16723
badger 2020/02/25 16:57:23 INFO: Replay took: 25.745µs
badger 2020/02/25 16:57:23 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
</pre>

### What did you see instead?

The following error on the Raspberry:

<pre>
$ GOPATH/bin/test_badger 
badger 2020/02/25 17:06:31 INFO: All 0 tables opened in 0s
badger 2020/02/25 17:06:31 INFO: Replaying file id: 0 at offset: 0
badger 2020/02/25 17:06:31 INFO: Replay took: 96.302µs
2020/02/25 17:06:31 Map log file. Path=/tmp/badger/000000.vlog. Error=cannot allocate memory
</pre>

**Comment by jarifibrahim** [comment]
Hey @dstreppa, you can one of the following two things
1. Reduce the value log file size. By default, it is set to 1 GB and we memory map it to 2 GB. My guess is your raspberry pi doesn't have enough memory and that's why badger crashed trying to mmap 2 GB of memory.
2. Set the value log loading mode to `FILEIO`. If your raspberry has limited memory, you shouldn't keep the value log in memory.

You might need to tweak other options if your raspberry pi has very limited memory.

**Comment by dstreppa** [comment]
Yeah thank you very much @jarifibrahim. It is working now. Its has been enough to set the loading node to `FILEIO`.
