### ISSUE TITLE
WithInMemory(true) panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by dpgarrick** [dgraph-io/badger#1234]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 darwin/amd64
</pre>

### What version of Badger are you using?
2.0.2

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

SSD drive

### What did you do?
Trying to store a ~2MB protobuf message in a badgerdb instance. Running badgerdb in disk mode and storing to ./db runs perfectly but changing the db instance to disk-less using WithInMemory(true) fails.

Decreasing the data size also runs fine in memory.

I've made a sparse repo just with source code reproducing the problem here:
https://github.com/dpgarrick/badgerdb-inmem

Should be able to reproduce via
```
go get github.com/dpgarrick/badgerdb-inmem
go run main.go manifest.pb.go > testOutput
```
and just commenting/uncommenting the database instance lines to go from disk to disk-less.

Unsure if I am just overlooking something obvious (pretty new to golang and badgerdb) but if I take only the first 40,000 lines of the data file instead of all ~88000 lines it runs fine WithInMemory(true) and it always runs fine when using badgerdb in disk mode so it seems more like a bug to me.

### What did you expect to see?
Disk-less mode to run identical to the disk mode.

### What did you see instead?
<pre>
panic: runtime error: index out of range [0] with length 0

goroutine 23 [running]:
github.com/dgraph-io/badger.(*DB).writeToLSM(0xc00078a800, 0xc0015bc720, 0x0, 0x0)
	/Users/dpg/go/src/github.com/dgraph-io/badger/db.go:667 +0x341
github.com/dgraph-io/badger.(*DB).writeRequests(0xc00078a800, 0xc00013a050, 0x1, 0xa, 0x0, 0x0)
	/Users/dpg/go/src/github.com/dgraph-io/badger/db.go:720 +0x364
github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc00013a050, 0x1, 0xa)
	/Users/dpg/go/src/github.com/dgraph-io/badger/db.go:762 +0x5a
created by github.com/dgraph-io/badger.(*DB).doWrites
	/Users/dpg/go/src/github.com/dgraph-io/badger/db.go:815 +0x329
exit status 2
</pre>

**Comment by jarifibrahim** [comment]
Thanks for raising this @dpgarrick. This definitely looks like a bug to me. I'll look into it.

**Comment by jarifibrahim** [comment]
@dpgarrick I've raised https://github.com/dgraph-io/badger/pull/1235 to fix this. The issue was that I had set a hard limit of 1 MB on the maximum size of value in in-memory mode. Your code was inserting value of size 2 MB and that's why badger crashed. I've changed the code so that the maximum size of value in in-memory mode will be math.MaxInt32 (around 2 GB).

**Comment by dpgarrick** [comment]
@jarifibrahim Great thanks, I wondered if it was something simple like that.

2GB should be more than enough but also nice to know I can just increase the options.ValueThreshold to address.

**Comment by jarifibrahim** [comment]
@dpgarrick If you're running badger in in-memory mode, the value of `ValueTheshold` will not be used. We over-write it while opening DB.

https://github.com/dgraph-io/badger/blob/617ed7c7db9d618b6511adfff5d22dcde2233049/db.go#L309-L312

**Comment by dpgarrick** [comment]
@jarifibrahim Ahh right, thanks for the clarification.
