### ISSUE TITLE
Feature Request: Back By Kafka (Changelog Topic)

### ISSUE THREAD

**Issue by wood-jp** [dgraph-io/badger#1236]
We (my company) extensively use RocksDB (in memory) and have it backed by a Kafka changelog topic to persist across service restarts (ie on startup we read in the changelog topic to get into the correct state before continuing to process data).

![Example](https://user-images.githubusercontent.com/3757184/75715841-1b3f2c80-5c9c-11ea-87c3-986fed39d0ef.jpg)

Badger seems like an excellent option to help us get off of the Scala/Rocks stack we have and onto a pure Go stack instead, which is more aligned with the rest of our engineering org. However, persisting Badger onto a disk doesn't really work for us: We leverage Kafka to partition the workload. That partitioning carries over into the KV store. We cannot control which partitions a particular instance will be given however, yet we do need to maintain that partitioning so as to not lose data.

This is a big ask, and I'd be happy to help out if you can point the way.

**Comment by jarifibrahim** [comment]
Hey @wood-jp, what does this `change log` store?

**Comment by wood-jp** [comment]
> Hey @wood-jp, what does this `change log` store?

@jarifibrahim It's a direct copy of what is stored in RocksDB. Ie (Key, Value) pairs that are a mirror of the store.

**Comment by wood-jp** [comment]
Hi @jarifibrahim, I've been thinking more about this and I believe that I was mistaken in thinking that this support should be part of Badger - I was just thinking about how Rocks and Kafka have such a tight relationship and figured it would make sense to mirror that. However, if I want to back the state of Badger with a Kafka topic, then I should just write a wrapper that does that by always writing to Kafka just before Badger.

**Comment by jarifibrahim** [comment]
Hey @wood-jp, it looks like there's nothing we need to do in badger for this issue.

Feel free to reopen. Thank you!
