### ISSUE TITLE
Updating only the metadata byte on an existing entry

### ISSUE THREAD

**Issue by harikb** [dgraph-io/badger#1240]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### What version of Badger are you using?
v2.0.1
<pre>
% grep badger go.*
go.mod:	github.com/dgraph-io/badger/v2 v2.0.1
go.sum:github.com/dgraph-io/badger v1.6.0 h1:DshxFxZWXUcO0xX476VJC07Xsr6ZCBVRHKZ93Oh7Evo=
go.sum:github.com/dgraph-io/badger/v2 v2.0.0 h1:Cr05o2TUd2IcLbEY0aGd8mbjm1YyQpy+dswo3BcDXrE=
go.sum:github.com/dgraph-io/badger/v2 v2.0.0/go.mod h1:YoRSIp1LmAJ7zH7tZwRvjNMUYLxB4wl3ebYkaIruZ04=
go.sum:github.com/dgraph-io/badger/v2 v2.0.1 h1:+D6dhIqC6jIeCclnxMHqk4HPuXgrRN5UfBsLR4dNQ3A=
go.sum:github.com/dgraph-io/badger/v2 v2.0.1/go.mod h1:YoRSIp1LmAJ7zH7tZwRvjNMUYLxB4wl3ebYkaIruZ04=
</pre>

The current API requires update of `.Value` when updating the meta-byte.  That is `.SetEntry` only exists in the version were one has to pass in the value again.

<pre>
err := db.Update(func(txn *badger.Txn) error {
  e := badger.NewEntry([]byte("answer"), []byte("42")).WithMeta(byte(1))
  err := txn.SetEntry(e)
  return err
})
</pre>

Is there an alternate way to update just the one-byte metadata byte?

**Comment by jarifibrahim** [comment]
@harikb We don't have any other way to update meta bits right now. The only way to do this is to fetch the (key, value) and reinsert it in badger with the new meta.

**Comment by paulnpdev** [comment]
Sigh
