### ISSUE TITLE
Is it possible to get rid of ErrTxnTooBig ?

### ISSUE THREAD

**Issue by zhiqiangxu** [dgraph-io/badger#1242]
```golang
// LClear removes the list of the key.
func (t *TxStructure) LClear(key []byte, ) (err error) {
	metaKey := t.encodeListMetaKey(key)
	meta, err := t.loadListMeta(metaKey)
	if err != nil || meta.IsEmpty() {
		return
	}

	for index := meta.LIndex; index < meta.RIndex; index++ {
		dataKey := t.encodeListDataKey(key, index)
		if err = t.txn.Delete(dataKey); err != nil {
			return
		}
	}

	err = t.txn.Delete(metaKey)
	return
}
```

The above is the expected shape of code when implementing something generic like clearing a list structure.

But when implementing it on top of badger, the size of the list is not known, so in theory every call to `t.txn.Delete` may return `ErrTxnTooBig`,

 in which case the only thing one can do is to commit the old transaction and create a new one, 

this will make the resultant code very ugly and hard to modularize, 

because one will never be sure whether a new transaction is created  to replace the old one after a call to functions like `LClear` above returns.

In fact the check for `ErrTxnTooBig` will be scattered all around , because in theory every call to `txn.Set` or `txn.Delete` may return `ErrTxnTooBig`, one should always distinguish `ErrTxnTooBig` from other errors, in order to  do `txn.Commit` and `db.NewTransaction(true)` in that case.

**Comment by jarifibrahim** [comment]
@zhiqiangxu How about using `WriteBatch`? It internally uses multiple transactions to commit the result. https://github.com/dgraph-io/badger/blob/8dbc982d4975a76318b42525adc670b80b491f63/batch.go#L40

You can also try to increase the size of your tables. The transaction too big is returned when the skiplist (in-memory table) doesn't have enough space. Try increasing the size of `opt.MaxTableSize`.

**Comment by zhiqiangxu** [comment]
@jarifibrahim No matter how big `MaxTableSize ` is, the **correct** code still needs to handle `ErrTxnTooBig `.

**Comment by jarifibrahim** [comment]
@zhiqiangxu In that case use `WriteBatch`.

**Comment by zhiqiangxu** [comment]
@jarifibrahim But if I replace all such generic implementation with `WriteBatch`, it has no transaction guarantee, which will cause data inconsistency. That's why I suggested the possibility of getting rid of `ErrTxnTooBig` completely.

**Comment by jarifibrahim** [comment]
@zhiqiangxu `WriteBatch.Flush()` will commit all the underlying transactions. Wouldn't that be enough for your usecase?

**Comment by zhiqiangxu** [comment]
@jarifibrahim Data consistency is a very important factor for serious usage, which is only guaranteed by a `transaction`. I think `WriteBatch` can only be used where data consistency is not very important.

**Comment by jarifibrahim** [comment]
@zhiqiangxu  `WriteBatch.Flush()` calls `writeBatch.commit()` which commits the underlying transactions. `WriteBatch.Flush()` also waits for all the underlying transactions to complete by calling `throttle.Finish()`. So `write batch` should provide all the same transactional guarantees provided by `transactions`

https://github.com/dgraph-io/badger/blob/8dbc982d4975a76318b42525adc670b80b491f63/batch.go#L137-L164

**Comment by zhiqiangxu** [comment]
@jarifibrahim Data consistency means ACID, which is only guaranteed by transaction.

**Comment by jarifibrahim** [comment]
@zhiqiangxu ah, I see what you mean. The `ErrTxnTooBig` allows us to limit what could be the worst-case increase in the size of in-memory tables. Right now this limit is at 15%

https://github.com/dgraph-io/badger/blob/8dbc982d4975a76318b42525adc670b80b491f63/db.go#L195-L196

Removing the error would mean a user could easily cause an `Out Of Memory` error if they use a single transaction and keep inserting keys for a long while without committing the transaction.

Right now this limit also ensures all updates made in a single transaction have the same `commit timestamp` and they are stored in the same table. Without this limit, we might have to put some values in a different table if the current one doesn't have enough space. I am not sure if this would cause any issues with badger.

@zhiqiangxu How about wrapping up the badger transaction into your own type and then all the `txn.Delete`/`txn.Set` APIs would take care of creating a new transaction when the current one returns `ErrTxnTooBig`. Would this work for you?

**Comment by zhiqiangxu** [comment]
@jarifibrahim It's nice that the limit ensures all updates made in a single transaction have the same commit timestamp and they are stored in the same table, but trouble is that because of the existence of `ErrTxnTooBig`  the caller never knows whether the whole batch is executed in the same transaction. I can understand the point of `ErrTxnTooBig` though, it seems there's no win-win solution...
