### ISSUE TITLE
Unclosed iterator at time of Txn.Discard

### ISSUE THREAD

**Issue by makediff** [dgraph-io/badger#1250]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### What version of Badger are you using?
github.com/dgraph-io/badger v1.6.0

### What did you do?

this is my code
```golang
for {
    err := loopDeleteKey(db, jobPrefix)
    if err != nil {
        fmt.Printf("[v] delete-key job error1:%v\n", err)
    }
    time.Sleep(deleteGapTime)
}


// another is:

func loopDeleteKey(db *badger.DB, jobPrefix []byte) error {
    defer func() {
        if err := recover(); err != nil {
            fmt.Printf("[v] delete-key job error(11202): %v\n", err)
        }
    }()
    //c := 0
    //var needJobIds [][]byte
    runCount++
    err := db.View(func(txn *badger.Txn) error {
        //it := common.NewIterator(txn)
        it := txn.NewIterator(badger.IteratorOptions{
            PrefetchValues: false,
            PrefetchSize:   0,
            Reverse:        false,
            AllVersions:    false,
            Prefix:         nil,
            InternalAccess: false,
        })
        defer it.Close()
        return nil
    })
    if err != nil {
        fmt.Printf("[v] delete-key job(3), error %v\n", err)
        return err
    }
    return nil
}
```

when I press Ctrl+C stop program, get error

> [v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard.
[v] delete-key job error(11202): Unclosed iterator at time of Txn.Discard

### What did you see instead?

Thank you !

**Comment by konart** [comment]
I have a similar problem I guess.

I'm trying to write a simple Count() function that will return a number of entries in db:

```go
func (r *Item) Count() (int, error) {
	var count int

	err := r.db.View(func(txn *badger.Txn) error {
		iter := txn.NewIterator(badger.IteratorOptions{})
               defer iter.Close()

		for {
			iter.Next()
			if !iter.Valid() {
				return nil
			}

			count++
		}
	})
	if err != nil {
		return 0, err
	}

	return count, nil
}
```

and the I use it in a simple test:

```go
type Item struct {
	db *badger.DB
}

func TestItemSetFrom(t *testing.T) {
	item, err := NewItem()
	if err != nil {
		t.Fatal(err)
	}

	add := func(hash []byte) bool {
		if len(hash) == 0 {
			return true // we don't need zero hashes for now
		}

		n, _ := item.Count() // panic!

		if err := item.SetFromHash(hash); err != nil {
			t.Log(err)
			return false
		}

		m, _ := item.Count()

		t.Log(n, m)

		return m == n+1
	}

	if err := quick.Check(add, nil); err != nil {
		t.Errorf("add failed")
	}
}

```

**Comment by konart** [comment]
Okay, sorry about that, turns out I had to read docs and note that you have to call `Rewind()` first: https://pkg.go.dev/github.com/dgraph-io/badger#readme-iterating-over-keys
