### ISSUE TITLE
BadgerDB Installation Error in Linux Instance (EC2 t2.micro)

### ISSUE THREAD

**Issue by Gauthamastro** [dgraph-io/badger#1251]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.10.4 linux/amd64

</pre>

### What version of Badger are you using?
v2.0.2

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
I am building my code in an AWS EC2 t2.micro Instance

### What did you do?
BadgerDB outputs the following error during Installation using go get
`# command-line-arguments
github.com/dgraph-io/ristretto/z.FastRand: call to external function
github.com/dgraph-io/badger/skl.(*Skiplist).randomHeight: relocation target github.com/dgraph-io/ristretto/z.FastRand not defined
github.com/dgraph-io/badger/skl.(*Skiplist).randomHeight: undefined: "github.com/dgraph-io/ristretto/z.FastRand"
`

### What did you expect to see?

Nothing But clean Installation

### What did you see instead?
`# command-line-arguments
github.com/dgraph-io/ristretto/z.FastRand: call to external function
github.com/dgraph-io/badger/skl.(*Skiplist).randomHeight: relocation target github.com/dgraph-io/ristretto/z.FastRand not defined
github.com/dgraph-io/badger/skl.(*Skiplist).randomHeight: undefined: "github.com/dgraph-io/ristretto/z.FastRand"
`

**Comment by jarifibrahim** [comment]
Hey @Gauthamastro, `fastrand` might not be available in g1.10. Can you switch to go1.13 or go 1.12?

**Comment by jarifibrahim** [comment]
As mentioned over here https://github.com/dgraph-io/badger#installing,
