### ISSUE TITLE
Badger 2.0.2 go module not found

### ISSUE THREAD

**Issue by dougdonohoe** [dgraph-io/badger#1253]
### What version of Go are you using (`go version`)?

`go version go1.12.7 darwin/amd64`

### What version of Badger are you using?

On `	github.com/dgraph-io/badger v1.6.0` trying to upgrade to Badger 2, specifically the latest release: `v2.0.2`

### What did you do?

I'm trying to update my project to use Badger 2.0, but I'm having trouble finding the right version to get go modules to work.

With the help of IntelliJ, I found this works:

```
$ go get github.com/dgraph-io/badger/v2.0.0-rc2+incompatible
```

By the way, I'm not sure why this works, as there isn't an actual tag called `v2.0.0-rc2+incompatible`

However, I want to use the latest release, v2.0.2 and I get an error when trying to fetch it.

```
$ go get github.com/dgraph-io/badger@v2.0.2
go: finding github.com/dgraph-io/badger v2.0.2
go: github.com/dgraph-io/badger@v0.0.0-20200302175743-b81faa561c6d: go.mod has post-v0 module path "github.com/dgraph-io/badger/v2" at revision b81faa561c6d
```

The README.md doesn't provide any guidance about properly using go modules.  How do I get the latest release?

**Comment by dougdonohoe** [comment]
Update.  I ran this:

```
$ go get github.com/dgraph-io/badger/v2
go: finding github.com/dgraph-io/badger/v2 v2.0.2
go: finding github.com/DataDog/zstd v1.4.1
go: finding github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
go: downloading github.com/dgraph-io/badger v2.0.0-rc2+incompatible
go: extracting github.com/dgraph-io/badger v2.0.0-rc2+incompatible
go: downloading github.com/dgraph-io/badger/v2 v2.0.2
go: extracting github.com/dgraph-io/badger/v2 v2.0.2
go: downloading github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
go: downloading github.com/DataDog/zstd v1.4.1
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
go: extracting github.com/cespare/xxhash v1.1.0
go: extracting github.com/DataDog/zstd v1.4.1
```

It says `go: extracting github.com/dgraph-io/badger/v2 v2.0.2` and now my `go.mod` looks like this:

```
	github.com/dgraph-io/badger v2.0.0-rc2+incompatible
	github.com/dgraph-io/badger/v2 v2.0.2 // indirect
```

And also

```
$ go list -m all | grep dgraph
github.com/dgraph-io/badger v2.0.0-rc2+incompatible
github.com/dgraph-io/badger/v2 v2.0.2
github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
```

So things may be okay, but this is still confusing.  It isn't clear how to cleanly upgrade to the next version (e.g., `v2.0.3` when it comes out).

**Comment by danielmai** [comment]
> Update. I ran this:
> 
> ```
> $ go get github.com/dgraph-io/badger/v2
> ```

This is the right way to import BadgerDB v2. That is, you'll specify the semantic import path (ending in /v2) and you can also specify the version tag by adding `@v2.0.2` to the end. `go get github.com/dgraph-io/badger` gets the latest Badger v1 and `go get github.com/dgraph-io/badger/v2` gets the latest Badger v2.

There's a lot of information about how to use Go Modules in their [wiki](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). e.g., to upgrade to the latest patch release you can use `go get -u=patch`.

Good point about the README. We'll update it to explain how to get Badger v2.

I'll close this issue for now. Feel free to reopen if you continue having the same issue.

**Comment by dougdonohoe** [comment]
Thanks for update.  I needed to do this:

```
go get github.com/dgraph-io/badger/v2@v2.0.2
```

One other thing that isn't clear.  Do I also need to change my imports to 

```
	import "github.com/dgraph-io/badger/v2"
```

from 

```
	import "github.com/dgraph-io/badger"
```

?

**Comment by danielmai** [comment]
Yeah, the dependencies in your `go.mod` file will say `github.com/dgraph-io/badger/v2`, and you'll need to use `import "github.com/dgraph-io/badger/v2"` for your import paths as well.
