### ISSUE TITLE
Nil pointer in iterator.Item()

### ISSUE THREAD

**Issue by jpkrohling** [dgraph-io/badger#1262]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### What version of Badger are you using?
v2.0.2

### Does this issue reproduce with the latest master?
Not sure.

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Fedora 31, SSD, 16GiB RAM

### What did you do?
In Jaeger, we [have a code](https://github.com/jaegertracing/jaeger/blob/61490383e249f97f75cb5a9053e84e1a0fd2db04/plugin/storage/badger/spanstore/reader.go#L612-L618) like the following which works in Badger v1.5:

```go
	if it.Item() != nil {
		...
	}
```

When there are no items in the iterator, Badger v2 will trigger a nil pointer:

(excerpt)
```
--- FAIL: TestFindNothing (0.05s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd0378c]

goroutine 11553 [running]:
testing.tRunner.func1(0xc0004c8800)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/testing/testing.go:874 +0x69f
panic(0xfe63a0, 0x1760100)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/badger/v2.(*Item).Key(...)
	/home/jpkroehling/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/iterator.go:70
github.com/dgraph-io/badger/v2.(*Iterator).Item(...)
	/home/jpkroehling/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/iterator.go:504
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.scanFunction(0xc0000f28c0, 0xc00002a280, 0xa, 0x40, 0xc0001de038, 0x8, 0x8, 0x8)
	/home/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:562 +0x9c
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).scanIndexKeys.func1(0xc000260080, 0x0, 0x0)
	/home/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:540 +0x43f
github.com/dgraph-io/badger/v2.(*DB).View(0xc0005a6c00, 0xc00223f8a0, 0x0, 0x0)
	/home/jpkroehling/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/txn.go:683 +0x100
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).scanIndexKeys(0xc0003fa070, 0xc00002a280, 0xa, 0x40, 0xc00223fbb8, 0xc00223f940, 0x468361, 0x1685016, 0x2d65636976726573, 0x31)
	/home/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:527 +0xfd
```

Changing our code to check `it.Valid()` got me around the problem, but I wonder if this change is expected.

For reference, here's how our code looks like now:
```go
	if !it.Valid() {
		return false
	}

	if it.Item() != nil {
		...
	}
```

### What did you expect to see?
Not a nil pointer panic.

### What did you see instead?
Nil pointer panic.

**Comment by jarifibrahim** [comment]
@jpkrohling Here's what `iterator.Valid()` function does
https://github.com/dgraph-io/badger/blob/91c31ebe8c22bf0098d152128402acaf98b1def0/iterator.go#L509-L517

`iterator.Item()` is supposed to be used only when `iterator` is `Valid` (in other words, the `item` is not`nil`)

**Comment by jpkrohling** [comment]
Thanks for the quick clarification!
