### ISSUE TITLE
Consider using xorfilter to replace bloomfilter

### ISSUE THREAD

**Issue by choleraehyq** [dgraph-io/badger#1263]
From its paper, xorfilters are faster and more concise alternative to bloomfilters.
https://github.com/FastFilter/xorfilter

**Comment by jarifibrahim** [comment]
This looks like a nice improvement over the bloom filters used in badger. I'll run some benchmarks to confirm the performance.

**Comment by jarifibrahim** [comment]
Using xor filters is a breaking change and the performance benefit is not worth breaking the on-disk format. See https://github.com/dgraph-io/badger/pull/1264 .
