### ISSUE TITLE
Consider export txn.addReadKey ?

### ISSUE THREAD

**Issue by zhiqiangxu** [dgraph-io/badger#1265]
It can be used to pretend that a txn `read` some key.

If user prefer to cache value of a specific key(which changes infrequently), it would be very useful to export `addReadKey`, so that when the key changed in badger, the txn will fail.

**Comment by jarifibrahim** [comment]
Hey @zhiqiangxu, why is it necessary to export the `addReadKey` function? If you `read` a key, it will automatically be added to the `txn.reads` slice. Wouldn't that be enough?

Also, I don't understand how `txn.AddReadKey` would help with caching the value.
If you want to cache the value, you can use the `key+version` as the cache key. The `key+version` will always be unique.
