### ISSUE TITLE
Project Status update?

### ISSUE THREAD

**Issue by coder543** [dgraph-io/badger#1269]
### What did you do?

Viewed the README

### What did you expect to see?

A "Project Status" section that doesn't seem at odds with the latest blog posts

### What did you see instead?

> Project Status [Jun 26, 2019]
> 
> Badger is stable and is being used to serve data sets worth hundreds of terabytes. Badger supports concurrent ACID transactions with serializable snapshot isolation (SSI) guarantees. A Jepsen-style bank test runs nightly for 8h, with --race flag and ensures the maintenance of transactional guarantees. Badger has also been tested to work with filesystem level anomalies, to ensure persistence and consistency.
> 
> Badger v1.0 was released in Nov 2017, and the latest version that is data-compatible with v1.0 is v1.6.0.
> 
> Badger v2.0, a new release coming up very soon will use a new storage format which won't be compatible with all of the v1.x. 

I see that Badger 2.0 has been released. Is it recommended to use Badger 2.0, or should we still be using the 1.x series?

If it would be possible to update this Project Status section sometime, that would be great. I was a little confused by it, but because I happened to find the blog posts, I _think_ I know I'm supposed to be using Badger 2.0... others may not happen to see the blog posts.

EDIT: I think it would also be helpful to update the README example to import Badger v2 (`"github.com/dgraph-io/badger/v2"`) if v2 is recommended

**Comment by jarifibrahim** [comment]
Hey @coder543, it is recommended to use badger v2.
I'll update the readme. Thanks for pointing it out :)
