### ISSUE TITLE
Test Badger with libfiu

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#127]
https://blitiri.com.ar/p/libfiu/doc/posix.html

This library can simulate reads and writes failing -- would be good to know how well does Badger handle these cases of faulty FS.

**Comment by manishrjain** [comment]
Actually, run Badger with ALICE, a tool which can test KV stores.

**Comment by peterstace** [comment]
ALICE doesn't support mmap, but can run in a mode where it ignores all mmap operations (so won't find any vulnerabilities related to them).

**Comment by manishrjain** [comment]
We don't mmap, unless specifically asked to do so. The default options use LoadToRAM.

**Comment by manishrjain** [comment]
@peterstace ran this already with ALICE. Results here: https://blog.dgraph.io/post/alice/

**Comment by manishrjain** [comment]
I doubt this is needed anymore.
