### ISSUE TITLE
How is the merge operator intended to work?

### ISSUE THREAD

**Issue by dbolkensteyn** [dgraph-io/badger#1270]
* Go version: `go1.12.1 windows/amd64`
* Badger version 1.6.0
* Not tested against master version

I am new to Badger and trying to get a better understanding of what the merge operator does and how it works. Note that I am using v1.6.0.

Here is the evaluation code I am using:
```Go
db, _ := badger.Open(badger.DefaultOptions("badger").WithNumVersionsToKeep(1).WithTruncate(true))
defer db.Close()

db.Update(func(txn *badger.Txn) error {
    txn.Set([]byte("foo"), []byte{'!'}) // Discarded because overwritten in the same transaction
    txn.Set([]byte("foo"), []byte{'A'})
    txn.Set([]byte("foobar"), []byte{'C'})
    return nil
})
db.Update(func(txn *badger.Txn) error {
    txn.Set([]byte("foo"), []byte{'B'})
    return nil
})
m := db.GetMergeOperator(
    []byte("foo"),
    func(existingVal, newVal []byte) []byte {
        return append(newVal, existingVal...) // LIFO order
    },
    100*time.Millisecond,
)
db.Update(func(txn *badger.Txn) error {
    txn.Set([]byte("fooqux"), []byte{'D'})
    return nil
})
db.Update(func(txn *badger.Txn) error {
    txn.Set([]byte("foobar"), []byte{'E'})
    return nil
})
m.Add([]byte{'F'})
time.Sleep(1 * time.Second) // Wait for the compacter to run
m.Stop()

db.View(func(txn *badger.Txn) error {
    item, _ := txn.Get([]byte("foo"))
    result, _ := item.ValueCopy(nil)
    fmt.Println(string(result)) // Will print "FBAECD"
    return nil
})
```

To my initial surprise, this program prints `FBAECD`.

After some digging, here is what I believe is happening.
1) The merge operator works on a key prefix, not a specific key (seems to relate to #373)
1) It starts by pair-wise merging the most recent version with the second most recent one, all the way down to the oldest version. [`newVal`](https://github.com/dgraph-io/badger/blob/v1.6.0/merge.go#L41) will contain the previously merged result.
1) The written keys are ordered as following: **foo** < **foobar** < **fooqux**
1) Their values are in order: **foo:** `A, B, F`, **foobar:** `C, E`, **fooqux:** `D`
1) The LIFO order applied to the sorted keys give back: `FBA` for key **foo**, `EC` for key **foobar** and `D` for key **fooqux**, yielding `FBAECD`

Questions:
1. Is it really expected for the merge operator to work on a key prefix and not a single key? I initially expected the output to be `FBA`
1. Is it expected for the merge operator to "ignore" the `WithNumVersionsToKeep(1)` option with which the database was opened? If it was strictly enforced, I believe the output should have been `FED`
1. Is there a way to force the compaction, removing the need for the `time.Sleep()` call in this example? `m.Get()` seems to compute the merged result, but not to write it back to key **foo**. My motivation is similar to #373: many dynamically generated keys to be merged.

Thank you!

**Comment by jarifibrahim** [comment]
Hey @dbolkensteyn
>Is it really expected for the merge operator to work on a key prefix and not a single key? I initially expected the output to be FBA

There seems to be a bug in the `v1.6.0` release. If you run your program against master (or v2.x) it dumps `FBA`. Please be aware that the updates `B` and `A` were inserted via a normal transaction and they could be dropped if compaction happens before the merge compaction runs. Merge compactions are different from LSM Tree compactions.

>Is it expected for the merge operator to "ignore" the WithNumVersionsToKeep(1) option with which the database was opened? If it was strictly enforced, I believe the output should have been FED

The entries inserted via merge operator are excluded from compaction. A special bit denotes that these are special entries and should not be discarded by compaction. These entries will be discarded once merge operator has processed them.

>Is there a way to force the compaction, removing the need for the time.Sleep() call in this example? m.Get() seems to compute the merged result, but not to write it back to key foo

Calling `mergeOperator.Get(...)` would always return the latest value. You don't need to wait for the merge compactions to complete.
```go
...
	db.Update(func(txn *Txn) error {
		txn.Set([]byte("fooqux"), []byte{'D'})
		return nil
	})
	db.Update(func(txn *Txn) error {
		txn.Set([]byte("foobar"), []byte{'E'})
		return nil
	})
	m.Add([]byte{'F'})
	val, err := m.Get()
	if err != nil {
		panic(err)
	}
	m.Stop()

	fmt.Println(string(val))

```
https://github.com/dgraph-io/badger/blob/91c31ebe8c22bf0098d152128402acaf98b1def0/merge.go#L159-L169

**Comment by dbolkensteyn** [comment]
Thank you @jarifibrahim , this is extremely helpful! I'll upgrade to v2 to make my future findings more actionnable and useful.
