### ISSUE TITLE
Custom comparator for comparing keys?

### ISSUE THREAD

**Issue by molon** [dgraph-io/badger#1276]
https://github.com/dgraph-io/badger/blob/91c31ebe8c22bf0098d152128402acaf98b1def0/y/y.go#L131-L136

Sometimes we have certain requirements on the order of storage.
Is it possible to provide a callback that can be customized like this
https://github.com/syndtr/goleveldb/blob/166222840a9a83a65c1e314fda00121fb6719c99/leveldb/opt/options.go#L246-L251

Or provide a score for entry?

**Comment by jarifibrahim** [comment]
Duplicate of https://github.com/dgraph-io/badger/issues/776
