### ISSUE TITLE
Feature Request: Allow custom transactional Ristretto caches

### ISSUE THREAD

**Issue by MarcErdmann** [dgraph-io/badger#1277]
It would be great, if one can add custom Ristretto caches to a database and access them within transactions. This will allow applications to cache computed values in memory.
If the same use case can be solved with Badger's existing features, a guide would be helpful. Thanks!

**Comment by jarifibrahim** [comment]
Hey @MarcErdmann, please help me understand your feature request. Why can't the application cache the values on top of badger? Or why is it necessary to have access to the cache within a transaction?

**Comment by MarcErdmann** [comment]
I am not sure how Badger handles aborted transactions internally. It would be great to allow indexing data in ristretto during a primary DB transaction and if the primary DB transaction fails also undo the ristretto cache alteration.
Caching data on top of Badger is difficult to keep in sync with badger itself, if abortions of transactions occur, because e.g. ristretto and other in-memory caches do not support transactions.

**Comment by jarifibrahim** [comment]
>I am not sure how Badger handles aborted transactions internally. It would be great to allow indexing data in ristretto during a primary DB transaction and if the primary DB transaction fails also undo the ristretto cache alteration.

Wouldn't it be easier to add the data to the cache when it is accessed for the first time? Adding the data and then removing it might not be the best way to do this.

>Caching data on top of Badger is difficult to keep in sync with badger itself, if abortions of transactions occur, because e.g. ristretto and other in-memory caches do not support transactions.

How about adding data to the cache only when it is accessed? That way you won't have the `aborted transaction` issue.

**Comment by MarcErdmann** [comment]
For multiple concurrent transactions this would violate consistency (snapshot isolation). Imagine transaction A and B: transaction B is started while A is still running. Data is inserted during A and also accessed (1) - therefore it is cached. Queries in B will then find this data in the cache although transaction is not yet committed.
(1) Looking up values from the database in the same transaction that inserted them is e.g. needed for big data applications, which can not keep all data in memory and rather process it as a stream.
