### ISSUE TITLE
WSL: get an incomprehensible value

### ISSUE THREAD

**Issue by xiusin** [dgraph-io/badger#1279]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 linux/amd64
</pre>

### What version of Badger are you using?
```
github.com/dgraph-io/badger/v2 v2.0.2
```

### Does this issue reproduce with the latest master?

none
### What are the hardware specifications of the machine (RAM, OS, Disk)?

Linux DESKTOP-J2HNMBI 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

wsl env

### What did you do?

When I find a value operation, I will get an incomprehensible value at some time.  
sorry my english.  

### What did you expect to see?
right value

### What did you see instead?
![image](https://user-images.githubusercontent.com/36065131/77742457-73760e00-7051-11ea-890a-09d76e9cd2d9.png)

**Comment by xiusin** [comment]
windows 10 is ok, but wsl is not ok.

**Comment by xiusin** [comment]
![image](https://user-images.githubusercontent.com/36065131/77743390-f8adf280-7052-11ea-8b3c-a3e347eff756.png)

**Comment by jarifibrahim** [comment]
Hey @xiusin, I'm sorry, I don't understand which value is wrong. Can you help me understand what values did you insert and what was the response you got back?

I have not tried running Badger with WSL. If you can give me a script or test which shows this behavior, I'll try to run it locally and figure out what's going on.
