### ISSUE TITLE
Badger fails to open due to manifest table mismatch

### ISSUE THREAD

**Issue by julieStackRox** [dgraph-io/badger#1291]
### What version of Go are you using (`go version`)?
<pre>
1.13
</pre>

### What version of Badger are you using?
<pre>
1.6
</pre>

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Not sure

### What did you do?
When we try to open a Badger DB we get the error "file does not exist for table 1938" or the error "file does not exist for table 1941."  When we examine the disk the two files do not exist.

### What did you expect to see?
No errors. What the Badger believes in the manifest should match tables on disk.

### What did you see instead?
Got an error. Not sure how to recover.

**Comment by jarifibrahim** [comment]
@julieStackRox Are you sure you're using badger v1.6 and not v1.6.1? We recently added some fixes to v1.6.1 and my guess is one of those fixes introduced a bug.

**Comment by julieStackRox** [comment]
@jarifibrahim Thank you for your response. Yes, we were on 1.6.1. Tried to rollback now.

**Comment by jarifibrahim** [comment]
@julieStackRox My guess is PR https://github.com/dgraph-io/badger/commit/3e25d771067d933c88674f26e5a11ef75c492e90 introduced this.

Do you have a way to reproduce this issue? I'd like to reproduce this so that I can dig deeper.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8731). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
