### ISSUE TITLE
Cannot go get v2 as per readme

### ISSUE THREAD

**Issue by drathier** [dgraph-io/badger#1298]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### What operating system are you using?
macOS 10.14.6

### What version of Badger are you using?
v2?

### Does this issue reproduce with the latest master?
Yes

### Steps to Reproduce the issue
`go get github.com/dgraph-io/badger/v2`

### What Badger options were set? 
none

### What did you do?
follow the readme install instructions

### What did you expect to see?
the package installed

### What did you see instead?
```
package github.com/dgraph-io/badger/v2: cannot find package "github.com/dgraph-io/badger/v2" in any of:
	/usr/local/Cellar/go/1.14.2_1/libexec/src/github.com/dgraph-io/badger/v2 (from $GOROOT)
	/Users/d/d/go/src/github.com/dgraph-io/badger/v2 (from $GOPATH)
```

**Comment by jarifibrahim** [comment]
Looks like this has something to do with go mods. If I run `go get github.com/dgraph-io/badger/v2` inside a directory which has a `go.mod` file the command works but it fails if I run it in a directory which does not have `go.mod` file.

**Comment by LookoutHill** [comment]
@drathier Run this instead: go get github.com/dgraph-io/badger

**Comment by jarifibrahim** [comment]
> @drathier Run this instead: go get github.com/dgraph-io/badger

This would do the trick. The command in readme works fine for a project which has a `go.mod` file. We can change it if necessary. 

Thanks for the help @LookoutHill :+1:
