### ISSUE TITLE
"github.com/dgraph-io/badger/v2/options" doesn't exist

### ISSUE THREAD

**Issue by enenum** [dgraph-io/badger#1307]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64
</pre>

### What operating system are you using?
MacOsX10.15.4

### What version of Badger are you using?
2.0.3

### Does this issue reproduce with the latest master?
yes

### Steps to Reproduce the issue

glide install - with a the repo well include in glide.yaml

### What Badger options were set? 

did not get as far as building

### What did you do?
	db, err := badger.Open(badger.DefaultOptions(location))

### What did you expect to see?
build success

### What did you see instead?
github.com/dgraph-io/badger/v2/options: cannot find package" "."

The options.go file in the badger folder refers to the problematic package, but such a directory/package does not exist. Rather there is `github.com/dgraph-io/badger/options`

**Comment by enenum** [comment]
further: on running (on a clean machine) `go get github.com/dgraph-io/badger/v2/...` as given in the main README.md pulls the master fine and then gives the warning:
`go warning: "github.com/dgraph-io/badger/v2/..." matched no packages`

**Comment by jarifibrahim** [comment]
@enenum I think the failure is because of glide and go modules. Badger v2 uses go modules. Is there a reason for using `glide`?

From  https://github.com/Masterminds/glide#go-modules
```
The Go community is now using Go Modules to handle dependencies.
Please consider using that instead of Glide. Glide is now mostly unmaintained.
```

**Comment by enenum** [comment]
Yep. I had to turn on GO111MDULE=on in the project... Thanks
