### ISSUE TITLE
updateOffset should always update the vptr.

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#131]
We update KV's vptr field conditionally.  The underlying reason is that `ptrs[len(ptrs)-1]` is sometimes uninitialized because valueLog::write leaves it that way when SyncWrites is configured to be false and the value is smaller than ValueThreshold.

We should always update the vptr field, for example, by looking into ptrs[len(ptrs)-2] or earlier for a valid vptr.  Or just keep track of {Fid, EndOffset} instead of pointing at a particular value chunk with {Fid, Offset, Len}.  (When opening the KV store we only use the values of Fid and `Offset+Len`.)

Note:  The consequences of this are that sometimes vptr isn't as far along as it could be, and we replay more of the value log than is necessary.  Hypothetically, if we're unlucky, vptr never gets updated.

**Comment by manishrjain** [comment]
Yeah, that's my bad. We're meant to iterate over all the ptrs, and then pick the top one from there.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger/pull/133

**Comment by manishrjain** [comment]
Submitted.
