### ISSUE TITLE
When set  data in Iterator, when  opts.PrefetchValues = false ,  the data will be mass.

### ISSUE THREAD

**Issue by fengyanliang** [dgraph-io/badger#1320]
Here is my test code, I add 0-100 keys and set it value to 0 -100. after run txn.set in iterator serval time, I have get the wrong values.

package main

import (
	"fmt"
	"log"

	"github.com/dgraph-io/badger"
)

var db *badger.DB

func main() {

	var err error
	db, err = badger.Open(badger.DefaultOptions("./data/reading.db"))
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Reverse = true
		opts.PrefetchValues = false
		it := txn.NewIterator(opts)
		defer it.Close()
		prefix := "mydbtest"
		// for i := 0; i < 100; i++ {
		// 	txn.Set([]byte(prefix+strconv.Itoa(i)), []byte(strconv.Itoa(i)))
		// }

		for it.Seek([]byte(prefix + "999")); it.ValidForPrefix([]byte(prefix)); it.Next() {
			item := it.Item()
			key := item.Key()
			err := item.Value(func(v []byte) error {
				// value, _ := fastjson.ParseBytes(v)
				return txn.Set(key, v)
			})
			if err != nil {
				return err
			}
		}

		for it.Seek([]byte(prefix + "999")); it.ValidForPrefix([]byte(prefix)); it.Next() {
			item := it.Item()
			key := item.Key()
			err := item.Value(func(v []byte) error {
				// value, _ := fastjson.ParseBytes(v)
				fmt.Println(string(key), string(v))
				return nil
			})
			if err != nil {
				return err
			}
		}
		return nil
	})

}

output:
......
mydbtest10 12
mydbtest1 2
mydbtest00 10
mydbtest0 0

some data is wrong, and I got mydbtest00 with data 10.

**Comment by fengyanliang** [comment]
And also, when I try to change the data back, txn.Set can not work in interator, it's return nil error, but the data have not been changed ,hereis my code 

for it.Seek([]byte(prefix + "999")); it.ValidForPrefix([]byte(prefix)); it.Next() {
			item := it.Item()
			key := item.Key()
			err := item.Value(func(v []byte) error {
				errr := txn.Set(key, key[8:])
				fmt.Println(errr)
				if errr != nil {
					return errr
				}
				return nil

			})
			if err != nil {
				return err
			}

		}

**Comment by jarifibrahim** [comment]
Hey @fengyanliang, I don't understand what you're trying to do in the provided script. I see you inserted 100 entries but you're iterating on them in reverse order with `prefix-999`. This would always be empty because you haven't inserted any key with `prefix-999`. 

Also, you should create an iterator when you want to use it. An iterator won't be able to see the data inserted the data that was inserted after it was created. For example
```go
// Create an iterator
it := txn.NewIterator()
...
// Insert some data
txn.Set(foo, bar)

// Try to read the data using the iterator.
// The following loop will not see the `foo` entry because it was inserted after the iterator was created
for it.Rewind(); it.Valid(); it.Next() {
}
```
The correct way to use the iterator would be to create an iterator when you need it, that is, after inserting the data
```go
// Insert some data
txn.Set(foo, bar)

// Create an iterator when needed.
it := txn.NewIterator()

// Try to read the data using the iterator.
// The following loop will see the `foo` entry because it was inserted before the iterator was created
for it.Rewind(); it.Valid(); it.Next() {
}
```

**Comment by fengyanliang** [comment]
I can discribe it for short,
When I set 5 keys in the badgerdb, just like:
(keys:values)
key1:1
key2:2
key3:3
key4:4
key5:5

I find the value is wrong, so I plan to change it, and I  used iterator.
When I try to set key1 to 0 key2 to 1 key3 to 2 key4 to 3 key5 to 4
If I set opts.PrefetchValues = true, the value did not changed, but txn.Set(key1, 0) return nil
If I set opts.PrefetchValues = false, the values changed everytime, but the value is not what I did set in txn(key1,0)
after run serval times, key1 key2 key3 key4 key5 's value is mass.

this is the problem, you can try it. 

If we can't do something, I think it's better to return a error, but not nil.

Hope it's clear, you can try it yourself, it's easy to find out. thanks

**Comment by fengyanliang** [comment]
> Hey @fengyanliang, I don't understand what you're trying to do in the provided script. I see you inserted 100 entries but you're iterating on them in reverse order with `prefix-999`. This would always be empty because you haven't inserted any key with `prefix-999`.
> 
> Also, you should create an iterator when you want to use it. An iterator won't be able to see the data inserted the data that was inserted after it was created. For example
> 
> ```go
> // Create an iterator
> it := txn.NewIterator()
> ...
> // Insert some data
> txn.Set(foo, bar)
> 
> // Try to read the data using the iterator.
> // The following loop will not see the `foo` entry because it was inserted after the iterator was created
> for it.Rewind(); it.Valid(); it.Next() {
> }
> ```
> 
> The correct way to use the iterator would be to create an iterator when you need it, that is, after inserting the data
> 
> ```go
> // Insert some data
> txn.Set(foo, bar)
> 
> // Create an iterator when needed.
> it := txn.NewIterator()
> 
> // Try to read the data using the iterator.
> // The following loop will see the `foo` entry because it was inserted before the iterator was created
> for it.Rewind(); it.Valid(); it.Next() {
> }
> ```

Hi 

> Hey @fengyanliang, I don't understand what you're trying to do in the provided script. I see you inserted 100 entries but you're iterating on them in reverse order with `prefix-999`. This would always be empty because you haven't inserted any key with `prefix-999`.
> 
> Also, you should create an iterator when you want to use it. An iterator won't be able to see the data inserted the data that was inserted after it was created. For example
> 
> ```go
> // Create an iterator
> it := txn.NewIterator()
> ...
> // Insert some data
> txn.Set(foo, bar)
> 
> // Try to read the data using the iterator.
> // The following loop will not see the `foo` entry because it was inserted after the iterator was created
> for it.Rewind(); it.Valid(); it.Next() {
> }
> ```
> 
> The correct way to use the iterator would be to create an iterator when you need it, that is, after inserting the data
> 
> ```go
> // Insert some data
> txn.Set(foo, bar)
> 
> // Create an iterator when needed.
> it := txn.NewIterator()
> 
> // Try to read the data using the iterator.
> // The following loop will see the `foo` entry because it was inserted before the iterator was created
> for it.Rewind(); it.Valid(); it.Next() {
> }
> ```

Hi jarifibrahim,

Is it clear now? Since it's really a big issue, please pay attention on it. 

I can discribe it for short,
When I set 5 keys in the badgerdb, just like:
(keys:values)
key1:1
key2:2
key3:3
key4:4
key5:5

I find the value is wrong, so I plan to change it, and I used iterator.
When I try to set key1 to 0 key2 to 1 key3 to 2 key4 to 3 key5 to 4
If I set opts.PrefetchValues = true, the value did not changed, but txn.Set(key1, 0) return nil
If I set opts.PrefetchValues = false, the values changed everytime, but the value is not what I did set in txn(key1,0)
after run serval times, key1 key2 key3 key4 key5 's value is mass.

this is the problem, you can try it.

If we can't do something, I think it's better to return a error, but not nil.

Hope it's clear, you can try it yourself, it's easy to find out. thanks
