### ISSUE TITLE
ristretto version issue when building against badger v2.0.3

### ISSUE THREAD

**Issue by RubyTuesdayDONO** [dgraph-io/badger#1334]
### What version of Go are you using (`go version`)?

```
[reuben@laptop badger-version-test]$ go version
go version go1.13.6 linux/amd64
```

### What operating system are you using?

```
[reuben@laptop badger-version-test]$ uname -a
Linux laptop 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Feb 12 14:08:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### What version of Badger are you using?

v2.0.3

### Does this issue reproduce with the latest master?

unsure / maybe not relevant? is a buildtime issue w/ latest v2 tag, not a runtime issue.

### Steps to Reproduce the issue

```
[reuben@laptop badger-version-test]$ go mod init foo
go: creating new go.mod: module foo

[reuben@laptop badger-version-test]$ ed go.mod
20
,n
1       module foo
2
3       go 1.13
a

require (
  github.com/dgraph-io/badger/v2 v2.0.3   
)
.
wq
73
```
```
[reuben@laptop badger-version-test]$ go build
go: github.com/dgraph-io/badger/v2@v2.0.3 requires
        github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3: invalid version: git fetch --unshallow -f https://github.com/dgraph-io/ristretto in /home/reuben/go/pkg/mod/cache/vcs/7accc6f9ec6f7dea6833d9e0bc8690ec2e1420f4a17407f65e4ff528f79bf17d: exit status 128:
        fatal: git fetch-pack: expected shallow list
```

### What Badger options were set? 

N/A -- failed to build

### What did you do?

attempted to build a project with a dependency on badger v2.0.3

### What did you expect to see?

badger is fetched+installed and project builds

### What did you see instead?

installation of badger fails due to apparent versioning issue w/ ristretto

### Anything else we should know?

i am not (yet) a virtuoso Gopher, so it's possible i'm doing something stupid. but as far as i can tell, there is some kind of versioning issue in badger@v2.0.3's dependency on ristretto (tag named in `go.mod` doesn't exist in github repo?)

**Comment by jarifibrahim** [comment]
Hey @RubyTuesdayDONO, the ristretto version listed in badger's go mod exists https://github.com/dgraph-io/ristretto/commit/8f368f2f2ab3a54cbe62fb9772cd75ce55e07802 . 

How did you install badger?

**Comment by jarifibrahim** [comment]
@RubyTuesdayDONO ping!
