### ISSUE TITLE
Cannot open database from x86 binary with Mmap error

### ISSUE THREAD

**Issue by foenixx** [dgraph-io/badger#1348]
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.5 windows/386
</pre>

### What operating system are you using?

Windows 10 x64

### What version of Badger are you using?

v2.0.3

### Does this issue reproduce with the latest master?

Yes, it does.

### Steps to Reproduce the issue

Just call badger.Open with default options from compiled for x86 code.

### What Badger options were set? 

`badger.DefaultOptions("./test")`

### What did you see instead?

Received unexpected error:
```
Mmap value log file. Path=C:\Users\oleg\AppData\Local\Temp\deski_test_534434171\db\000000.vlog. Error=MapViewOfFile: Not enough memory resources are available to process this command.
Error while creating log file in valueLog.open
 github.com/dgraph-io/badger/v2/y.Wrapf
C:/Users/oleg/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/error.go:82
github.com/dgraph-io/badger/v2.(*valueLog).open
C:/Users/oleg/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1101
github.com/dgraph-io/badger/v2.Open
C:/Users/oleg/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:380

```

**Comment by jarifibrahim** [comment]
It seems like your machine doesn't have enough memory
```
 Not enough memory resources are available to process this command
```

You can reduce the `memtable size` and `vlog size`. You can also try changing the file loading mode from `MemoryMap` to `FileIO`. FileIO mode will store everything on the disk. Your reads will be slower but that should work.

Also, set the `KeepL0InMemory=false`. Keeping L0 in memory would also take up disk space.

**Comment by foenixx** [comment]
> 
> It seems like your machine doesn't have enough memory
> 

I have 16Gb of physical memory, 5Gb of it is free and available. Also, a 64-bit version works just fine. Did you try to reproduce the problem? I reproduced it on 2 different PCs. No matter how much memory is available, if a process is 32-bit then the error occurs. 

>  You can also try changing the file loading mode from `MemoryMap` to `FileIO`. FileIO mode will store everything on the disk. Your reads will be slower but that should work.

Yes, it works. I use it as a workaround.

**Comment by jarifibrahim** [comment]
@foenixx Interesting. That looks like a bug to me.

>I have 16Gb of physical memory, 5Gb of it is free and available. Also, a 64-bit version works just fine. 

Can you make the following changes to badger code and show me what the output is? 
```diff
diff --git a/value.go b/value.go
index b68ef10..325a906 100644
--- a/value.go
+++ b/value.go
@@ -998,6 +998,7 @@ func (vlog *valueLog) createVlogFile(fid uint32) (*logFile, error) {
 	if err = syncDir(vlog.dirPath); err != nil {
 		return nil, errFile(err, vlog.dirPath, "Sync value log dir")
 	}
+	vlog.db.opt.Logger.Infof("Creating vlog with size: %d", 2*vlog.opt.ValueLogFileSize)
 	if err = lf.mmap(2 * vlog.opt.ValueLogFileSize); err != nil {
 		return nil, errFile(err, lf.path, "Mmap value log file")
 	}
```

I don't have a x86 machine so it will be difficult for me to reproduce the issue.

**Comment by foenixx** [comment]
> Can you make the following changes to badger code and show me what the output is?

```
badger 2020/06/01 21:50:06 INFO: All 0 tables opened in 0s
badger 2020/06/01 21:50:06 INFO: Creating vlog with size: 2147483646
2020/06/01 21:50:06 During db.vlog.open: Error while creating log file in valueLog.open: Mmap value log file. Path=./p\000000.vlog. Error=MapViewOfFile: Not enough memory resources are available to process this command.
```
Probably 2GB is too much for 32-bit process? Since it requires 2GB of continuous memory space, but as far as I know 32-bit processes have 2GB of addressable virtual memory space at all.
I tried some smaller values of log file size and it started working when size~=950Мб or smaller.

**Comment by jarifibrahim** [comment]
A quick google search tells me that there's a 2 GB per-process limit on 32-bit machines.
https://en.wikipedia.org/wiki/2_GB_limit
https://superuser.com/questions/1163749/why-do-32-bit-processes-have-a-2-gb-ram-limit

@foenixx Please reduce the vlog file size. I think that's the only way to run badger on 32 bit machines.

**Comment by foenixx** [comment]
@jarifibrahim Thank you!

**Comment by jarifibrahim** [comment]
@foenixx Just out of curiosity, where are you running badger?

**Comment by foenixx** [comment]
> Just out of curiosity, where are you running badger?

It's a simple application that manages kinda file cache on user's PC and we're using Badger as our local DB. Some of our users still work on 32-bit Windows PCs )).

BTW, Badger does quite well so far!

**Comment by jarifibrahim** [comment]
>BTW, Badger does quite well so far!

Glad to know. :)
We have an informal survey open about badger users. It is a Github issue called `Who is using badger`. If you can fill up the survey, it will be very helpful. Thanks!
