### ISSUE TITLE
Fixed GC for badger v1

### ISSUE THREAD

**Issue by RubenKelevra** [dgraph-io/badger#1362]
There are two important fixes, which we're looking forward to include in IPFS to solve out of memory issues as well as databases that won't decrease in size after deleting data from them.

* https://github.com/dgraph-io/badger/commit/fd8989493b52f39957e89ff3a7679bc45ea92674
* https://github.com/dgraph-io/badger/commit/14386ac9b764cb6655cb0da7c848e244369a2a27

Is there a Badger v1 version planned to bring those fixes to a release?

**Comment by jarifibrahim** [comment]
@RubenKelevra Yes, a new v1.6.x version is planned to be released soon. We ran into some crashes which are blocking the release currently. For instance this one https://github.com/dgraph-io/badger/issues/1363 . We'll do a release when the crash is resolved.

**Comment by RubenKelevra** [comment]
Great to hear. Thanks for the update!

**Comment by RubenKelevra** [comment]
@jarifibrahim I hate to bounce this, but can you take another look at it? Is there a blocker which avoids a release with the GC fix? :)

**Comment by jarifibrahim** [comment]
HI @RubenKelevra , we have a few blockers but I don't think it affects v1.6x . We found some bugs while testing badger which blocked badger release. See the issues tagged with `release blocker` on github.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8675). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
