### ISSUE TITLE
Use LockFile for directory locking on windows

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1364]
Badger acquires an exclusive lock on the directory to prevent multiple processes from using it. The existing code in `dir_windows.go` file relies on an in-memory handle to prevent multiple files from accessing it.
https://github.com/dgraph-io/badger/blob/14386ac9b764cb6655cb0da7c848e244369a2a27/dir_windows.go#L82-L98 

While opening we set the `sharing mode` to `zero` which means only one process can access it
From[ Create File Documentation](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#parameters)
```
If this parameter is zero and CreateFile succeeds, the file or device cannot be shared and cannot be opened again until the handle to the file or device is closed. For more information, see the Remarks section.
```

We can use [LockFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfile) for instead.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8739). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
