### ISSUE TITLE
DropPrefix breaks levels, resulting in hard crashes and data loss

### ISSUE THREAD

**Issue by damz** [dgraph-io/badger#1380]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### What operating system are you using?

Linux

### What version of Badger are you using?

master

### Steps to reproduce the issue

This is actually pretty tricky to reproduce in a synthetic way.

You need a database with a sufficient amount of data so that on one level you have a layout similar to this:

* Table containing the `badgerMoveKey` prefix (either actual move keys, or something else), and is not full
* [...] Some number of other tables
* Table with the prefix you want to drop

In this case, the `dropPrefix` will generate a same-layer compaction request where `bot` has two non-consecutive tables:

https://github.com/dgraph-io/badger/blob/d37ce36911ae349fbedba342f693184aa434cc30/levels.go#L301-L330

If it happens that `compactTables()` generates tables without the same exact boundaries (for example because there were expired keys / deleted keys) then the result will be a layer with overlapping tables.

The assumption that `bot` has consecutive tables was broken in https://github.com/dgraph-io/badger/pull/1331

This results in data loss, and/or various assertions depending on what compactions are going to happen after that. In our case, we trigger the new assertion added in https://github.com/dgraph-io/badger/pull/1365 and various other assertions.

### How to fix?

`dropPrefix` should generate a separate compaction request for the move key prefix, instead of trying to generate a single compaction request for everything.

**Comment by jarifibrahim** [comment]
![dropprefix](https://user-images.githubusercontent.com/12949454/85701104-ab492c00-b6fa-11ea-8079-43a915554df0.jpg)

The diagram above explains how the current implementation of drop prefix in https://github.com/dgraph-io/badger/pull/1331 can create invalid levels.

**Comment by damz** [comment]
That's exactly that :+1:
