### ISSUE TITLE
SetIfAbsent prone to race conditions

### ISSUE THREAD

**Issue by 1lann** [dgraph-io/badger#141]
A SetIfAbsent literally checks if the key exists or not in the store before adding it to the write queue. This makes it prone to race conditions where there is already a write in the queue that alters the key being checked. i.e. SetIfAbsent in a race condition can set a key-value even though it isn't actually absent.

Is this intended behaviour? Or will it be replaced in the future with something safer?

**Comment by srh** [comment]
It checks for existence first, but then does the write with the meta flag BitSetIfAbsent.  That causes another check for existence to happen later.

**Comment by 1lann** [comment]
Ah so sorry, one of my tests were failing because of what appeared to be a condition like this. Turns out I forgot to store the error value from SetIfAbsent, whoops, sorry!
