### ISSUE TITLE
README.md install instruction isnt working (anymore?)

### ISSUE THREAD

**Issue by Vincent864** [dgraph-io/badger#1415]
README.md > Getting Started > Installing
Instructs to use:
go get github.com/dgraph-io/badger/v2

Which gives:
package github.com/dgraph-io/badger/v2: cannot find package "github.com/dgraph-io/badger/v2"

And should probably just be:
go get github.com/dgraph-io/badger

It's my first minute visiting the project, so I'm not completely sure

(GO1.13.8 on Ubuntu 20.04 LTS kernel on MS - WSL2)

**Comment by jmburges** [comment]
same.

**Comment by jarifibrahim** [comment]
@Vincent864 It should be `go get -v github.com/dgraph-io/badger` . Please feel free to send a PR.

I had changed ti from `go get github.com/dgraph-io/badger` to `go get github.com/dgraph-io/badger/v2` because if you run the command inside a project with go.mod, it downloads badger v1.6

```
 docker run -it golang:1.14 bash
root@045bc70ef964:/go# ls
bin  src
root@045bc70ef964:/go# cd
root@045bc70ef964:~# ls
root@045bc70ef964:~# mkdir foo
root@045bc70ef964:~# cd foo/
root@045bc70ef964:~/foo# go mod init foo
go: creating new go.mod: module foo
root@045bc70ef964:~/foo# go get -v github.com/dgraph-io/badger
go: downloading github.com/dgraph-io/badger v1.6.1
go: github.com/dgraph-io/badger upgrade => v1.6.1
go: downloading github.com/dgraph-io/ristretto v0.0.2
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading github.com/golang/protobuf v1.3.1
go: downloading github.com/cespare/xxhash v1.1.0
github.com/dgraph-io/badger/options
github.com/dgraph-io/badger/trie
github.com/cespare/xxhash
golang.org/x/sys/unix
github.com/pkg/errors
golang.org/x/net/internal/timeseries
github.com/golang/protobuf/proto
github.com/AndreasBriese/bbloom
github.com/dustin/go-humanize
github.com/dgraph-io/ristretto/z
golang.org/x/net/trace
github.com/dgraph-io/badger/y
github.com/dgraph-io/badger/skl
github.com/dgraph-io/badger/table
github.com/dgraph-io/badger/pb
github.com/dgraph-io/badger
root@045bc70ef964:~/foo# cat go.mod 
module foo

go 1.14

require github.com/dgraph-io/badger v1.6.1 // indirect
```

But it should be okay to change the go get command in the readme.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8683). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
