### ISSUE TITLE
Docs do not mention the purpose of userMeta argument in Set()

### ISSUE THREAD

**Issue by pkieltyka** [dgraph-io/badger#142]
What is userMeta for?

**Comment by srh** [comment]
It's so you can add one inline byte to the index, so it can be accessed more efficiently without looking in the value log.

**Comment by pkieltyka** [comment]
Cool, makes sense. Like an enum for example that maps to data faster for seeking

**Comment by manishrjain** [comment]
We use it in Dgraph to give us more information about the value stored there. We sometimes store one kind of value, and sometimes the other kind. And we use bits in this byte to determine that; so we know how to parse the value.

**Comment by manishrjain** [comment]
Added to godoc. https://github.com/dgraph-io/badger/commit/730b6aa08e8af95aab780ec6ffbbc9fe0d69bd88
