### ISSUE TITLE
000000.vlog grows by 4M each time it is updated

### ISSUE THREAD

**Issue by shenmingxing** [dgraph-io/badger#1452]
//test 
func Test_DBUpdate(t *testing.T) {
	// db path
	options := badger.DefaultOptions("/root/dbtest")
	mDb, err := badger.Open(options)
	if err == nil {
		defer mDb.Close()
	}

	//4M data
	bytes, err := ioutil.ReadFile("/root/test.dat")
	for {
		err = mDb.Update(func(txn *badger.Txn) error {
			err := txn.Set([]byte("test"), bytes)
			return err
		})
		time.Sleep(time.Second * 3)
	}

}

000000.vlog grows by 4M each time it is updated, why does this happen and how to solve it. Expect not to grow, please friends to help me answer

**Comment by jarifibrahim** [comment]
Hey @shenmingxing , can you please file an issue on https://discuss.dgraph.io/c/issues/badger/37 ? i would be happy to help.
