### ISSUE TITLE
Tool for debugging badger directories

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#146]
Add a command line tool to Badger whose usage is:

`badger_info --dir x [--value_dir y]`

Have it output the following information:
- Tables and their levels, as recorded in the manifest
- Any out-of-place files, or missing files
- What the value log files are
- The sizes of all these files, noting any zero-length files

Edit: Changed command `from badger_check` to `badger_info`.

**Comment by manishrjain** [comment]
This is done, I suppose.
