### ISSUE TITLE
Unexpected lock unlock code.

### ISSUE THREAD

**Issue by jpittis** [dgraph-io/badger#15]
Sorry to be a bother but I was scanning through the code base and noticed these mutex lock / unlocks without a defer on the unlock. Not sure if it was a bug or if there's a reason behind it.

[Code from badger/y/y.go](https://github.com/dgraph-io/badger/blob/master/y/y.go#L106-L116)

````go

func (c *Closer) SignalAll() {
	c.RLock()
	c.RUnlock() // <---- I would have expected a defer here.

	for _, l := range c.levels {
		l.Signal()
	}
}

func (c *Closer) WaitForAll() {
	c.RLock()
	c.RUnlock() // <---- I would have expected a defer here.
````

**Comment by manishrjain** [comment]
Thanks for catching this. This is my bad.
