### ISSUE TITLE
Check if we can TRIM command

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#150]
See if it makes sense to use TRIM command when deleting files to avoid SSD running GC over invalid data.

Or, is TRIM a setting that someone can turn on (if SSD is compatible) which gets triggered automatically when file is deleted?

**Comment by srh** [comment]
That's something the user can configure in the file system with a `discard` option or by occasionally running `fstrim`.  https://wiki.archlinux.org/index.php/Solid_State_Drives

There's not a problem with SSD running GC if the database is growing or maintaining the same size -- if old files are replaced by new files of similar size, and if the file system puts new files in the same place where old files used to be.

**Comment by manishrjain** [comment]
And I think there's nothing here that we can do programmatically to aid SSD GC. Is that right?

If so, then this becomes a documentation issue (just informing users of the right flags to use when they use Badger on SSD).

**Comment by srh** [comment]
That's right.  Our data writing patterns are about as SSD-friendly as they can be, appending to large files like we do.  I think people these days are generally aware of TRIM, but it would only really help if the file system generally doesn't reuse blocks from deleted files.  It looks like it depends on workload and ext4 might have a problem there ( http://www.ogris.de/blkalloc/ ) but it might have been fixed by now.

**Comment by manishrjain** [comment]
@srh : Can you add some suggestions for the users about mounting their SSDs with the right options to utilize TRIM?

**Comment by srh** [comment]
Sure, if that's a good idea.  I'll run a workload that rewrites a static set of keys on ext4 in a VM, record the growth of the VM's dynamically allocated storage size, and see if there's a need.  The answer might be that you never need TRIM.

**Comment by srh** [comment]
Pushed a provisional comment to d27dcd5cf9ae38bca962fd324e6261cd60180052.

**Comment by manishrjain** [comment]
You promised more details in the README -- so fill them in soon.

**Comment by srh** [comment]
I've removed that promise.  It's not worth spending more time to investigate.  One reason is, we've got two different kinds of files -- .sst's and value log files.  Another is, there's a wider variety of situations than just running one badger DB on a VM.  So there's no way I could rule out the need for TRIM, unless there's some authoritative information about recent changes to ext4.
