### ISSUE TITLE
Fix value log GC threshold condition

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/badger#151]
The calculation to decide when to do a GC is incorrect.

Documentation says:

```
// Run value log garbage collection if we can reclaim at least this much space. This is a ratio.
ValueGCThreshold float64
```

The currently implemented logic is different (almost inverted).

**Comment by manishrjain** [comment]
We can just fix the docs right?

**Comment by peterstace** [comment]
Yeah, we could have done that. I think "run GC if we can reclaim at least this much space" is easier to understand than "run GC if less than this much space will not be collected (i.e. not be reclaimed)".

Already merged.
