### ISSUE TITLE
Update MANIFEST safely

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/badger#155]
ALICE detected that Badger can't restart when it crashes while updating the MANIFEST.

```
0       stdout("'start:big\n'")
1       creat("LOCK", parent=1355754, mode='0666', inode=1359282)
2       append("LOCK", offset=0, count=6, inode=1359282)
3       creat("MANIFEST", parent=1355754, mode='0666', inode=1359283)
4       trunc("MANIFEST", initial_size=0, inode=1359283, final_size=0)
5       fsync(".", size=100, inode=1355754)
6       creat("000000.vlog", parent=1355754, mode='0666', inode=1359288)
7       fsync(".", size=120, inode=1355754)
8       append("000000.vlog", offset=0, count=1048670, inode=1359288)
9       append("000000.vlog", offset=1048670, count=1048670, inode=1359288)
10      append("000000.vlog", offset=2097340, count=1048670, inode=1359288)
11      append("000000.vlog", offset=3146010, count=1048670, inode=1359288)
12      append("000000.vlog", offset=4194680, count=1048670, inode=1359288)
13      creat("000001.vlog", parent=1355754, mode='0666', inode=1359291)
14      fsync(".", size=140, inode=1355754)
15      append("000001.vlog", offset=0, count=1048670, inode=1359291)
16      creat("000001.sst", parent=1355754, mode='0666', inode=1359294)
17      fsync(".", size=160, inode=1355754)
18      append("000001.sst", offset=0, count=470, inode=1359294)
19      file_sync_range("000001.sst", count=470, offset=0, inode=1359294)
20      append("MANIFEST", offset=0, count=8, inode=1359283)
21      fsync("MANIFEST", size=8, inode=1359283)
22      unlink("LOCK", parent=1355754, inode=1359282, size=6, hardlinks=1)
23      fsync(".", size=160, inode=1355754)
24      fsync(".", size=160, inode=1355754)
25      stdout("'stop:big\n'")
-------------------------------------
Finding vulnerabilities...
...
(Dynamic vulnerability) Atomicity: Operation 20(garbage written, zero written)
...
```

**Comment by manishrjain** [comment]
Weren't we first writing to another file, then renaming it to MANIFEST? Based on the paper, all the rename calls are atomic.

**Comment by peterstace** [comment]
I don't think we're doing that. From the code, it looks like we just append (the strace above agrees).

The usual atomic update idiom should work.

1. Write to temp file
2. Sync temp file
3. Rename temp file to MANIFEST
4. Sync directory.

If MANIFEST gets really big though, wouldn't be too efficient...

**Comment by srh** [comment]
We rewrite the file only when MANIFEST gets a sufficiently high garbage ratio.

What ALICE is complaining about here, as far as I can tell, is that if append operations to MANIFEST include garbage, we have a problem.

That's a problem on file systems like ext4-writeback and can be addressed by giving the MANIFEST checksums too.

**Comment by srh** [comment]
Also, right now we use the same alternative name each time.  I don't see the problem with this.

**Comment by peterstace** [comment]
> What ALICE is complaining about here, as far as I can tell, is that if append operations to MANIFEST include garbage, we have a problem.

That's correct. In particular, badger was choking when decoding PB messages in the MANIFEST. E.g. `proto: ManifestChange: illegal tag 0 (wire type 0)`

Checksums would definitely detect the problem gracefully, although wouldn't the data still be unrecoverable at that point?

**Comment by srh** [comment]
That's right -- it hasn't been written to disk, so you can't read it.  On other file systems you just won't read the entry, or you'll get a short entry, which we handle.

**Comment by manishrjain** [comment]
> Also, right now we use the same alternative name each time. I don't see the problem with this.

I think it would be cleaner to create a tempfile somewhere else, and then rename it to the MANIFEST file; so we only have one MANIFEST file in the directory (and are not left with a conflicting duplicate in case of a crash).

**Comment by srh** [comment]
> I think it would be cleaner to create a tempfile somewhere else

We have to make the tempfile in the same file system for the rename to be atomic (or work at all, maybe).  In case of a crash you just delete the extra file.

> Even if we have checksums on MANIFEST, there's no way for us to recover. 

There shouldn't be any problem there.  When we get a bad checksum, we've finished reading MANIFEST, and we truncate the file to that point.  The directory will have all the .sst's the manifest refers to at that point.

**Comment by srh** [comment]
In master as of ef39d1f3ee3292e17237ba31faf722b035096a06.
