### ISSUE TITLE
Provide stable Badger API

### ISSUE THREAD

**Issue by rohanthewiz** [dgraph-io/badger#161]
Is the API completely unstable? If not, then how about some tags to version lock to (semver.org). 
Example `git tag -a v0.1.1 -m "A usable release"`

Thanks. I know it's a lot of work!

**Comment by manishrjain** [comment]
Sure, we should be able to do that. I think we can cut a v1.0 release of Badger soon, because we've been fortifying it for a while -- particularly with testing crash resilience against ALICE (blog post upcoming), we should be good.

Expect this in a few weeks.

**Comment by rohanthewiz** [comment]
Fantastic thanks!!

**Comment by manishrjain** [comment]
Created a milestone for v1.0 -- aimed at end of this month -- though might be mid of next month.

**Comment by whyrusleeping** [comment]
Hey guys, any update here?

**Comment by manishrjain** [comment]
Hey @whyrusleeping, we've changed the APIs in a major way to introduce transactions to Badger. So, what we're going to do is to tag v0.8 as the current version of Dgraph, and when transactions land, they'd become master (and tagged as v0.9), leading up to v1.0.

This way, anyone on current APIs can continue to use them and switch whenever they're ready to.

**Comment by deepakjois** [comment]
We did a review of the API yesterday, and removed some methods which did not really belong in the public API, and were not being used externally.

What we have now is what will go into v1.0, which should be out soon pending a couple of minor bug fixes. But the API itself should not undergo any further changes. Closing this now.
