### ISSUE TITLE
Iterate / seek by UserMeta

### ISSUE THREAD

**Issue by pkieltyka** [dgraph-io/badger#164]
Hello, are there any plans (/ does it make sense) to iterate, seek and/or get by the UserMeta field? I was thinking to use the UserMeta byte to partition types of kv-pairs and seek by them.

**Comment by manishrjain** [comment]
You can partition the keys by adding prefixes to them. UserMeta is not designed for that, and is not the right choice for that -- the purpose of `UserMeta` is purely to aid you in understanding the value by giving a bit more context about it.
