### ISSUE TITLE
Allow filling values selectively during key-only iteration

### ISSUE THREAD

**Issue by dominikh** [dgraph-io/badger#166]
Currently, Badger spawns a new goroutine and asynchronously reads values during iteration. In my application, I am reading a large number of k/v pairs, where the values are small (<100 byte), and every value is read almost immediately after advancing the iterator. Turning the read into a synchronous read (by calling it.kv.fillItem in Iterator.Fill directly), I could reduce wall time from 33s to 30s, and CPU usage from 460% to 120%. The reduction in runtime is due to the various overheads of using goroutines: memory allocations, locking and scheduling. The 33s and 30s figures are for the entire runtime of the application, which processes the values read. I can provide cleaner numbers if required.

In addition to my scenario, I can think of another one where the current behavior would be problematic: huge values with sparse reads during iteration. In that scenario, values would be large, and only a small subset of iterated items would have their value read. In the current implementation, this would lead to reading a lot of data unnecessarily, and to Next blocking until the (uninteresting) value has been read fully.

To address both scenarios at once, I propose a change to the semantics of the FetchValues option. Instead of requiring FetchValues == true for any reading of values to occur, it should only cause asynchronous reading. If FetchValues == false, a call to KVItem.Value should cause a synchronous read of the data.

**Edit:** I realize that prefetching interacts with this, both affecting the measured times and possibly requiring special consideration when making this change.

**Comment by manishrjain** [comment]
Agree.

I think we can easily make the `fillItem` internal API public, so you can selectively call it on some keys to avoid doing a `Get` again. This should be a simple change; we just need to ensure that it works and doesn't break anything.

**Comment by dominikh** [comment]
Is there a reason you're considering making `fillItem` public, as opposed to making `KVItem.Value` call `fillItem` internally?

**Comment by dominikh** [comment]
Also, the new title of the issue only summarizes part of my original proposal. Even in iteration that isn't key-only, I have seen large performance improvements by filling synchronously.

**Comment by manishrjain** [comment]
Hmm.. How big was the dataset? If the value log was small enough to stay within memory (assuming you also mmap-ed it), then the results might be skewed. That's when you'll start seeing goroutine overhead be significant to the overhead of doing random read on SSD (because it's really a read from RAM). We've optimized Badger for datasets which can't fit completely in RAM.

**Comment by dominikh** [comment]
In that context, the dataset was tiny; the value log was about 50 MB large, and stored in a tmpfs on top of that… You are likely correct that this wouldn't benefit large datasets. 

I understand the workloads you have optimized for. However, would you be willing to add my proposed `synchronous fetching` mode as an optional flag if it didn't negatively impact performance for other workloads? I am planning to use Badger with value logs that will rarely exceed a few gigabytes in size, and where reads will often be local enough to benefit from in-memory caching. Especially in combination with mmaping the value log this gives me immense improvements in performance.

If you'd rather not dilute Badger's goals, that is fine. In that case, I'll maintain a patched internal fork.

**Comment by manishrjain** [comment]
> add my proposed synchronous fetching mode as an optional flag if it didn't negatively impact performance for other workloads?

I think if you set prefetch to false and use the `FillItem()` which we're planning to add here; you'll achieve the synchronized reads already. This still allows us to do async reads for larger data sets as well.

Regarding memory maping value log, I think we should be able to allow users to do that with an option. https://github.com/dgraph-io/badger/issues/167 captures that. I doubt you need to maintain a separate fork, we should be able to give you these things already.

**Comment by dominikh** [comment]
> Because fillItem can be called asynchronously. So, Value() is set to wait for that operation to finish. If we only call fillItem when Value() is called, then there would be no async prefetching

Well, we're discussing key-only iteration, where fillItem isn't being called asynchronously. In that case, having Value call fillItem synchronously is identical to having the user call FillItem followed by Value. In key-value iteration, fillItem would still be called asynchronously, and Value would wait for it to finish. 

I suspect you're concerned about the overhead an additional check in Value could cause?

**Comment by manishrjain** [comment]
I think you're missing the bigger context of async prefetching here. Even if you call `go kv.fillItem()` internally for every call to `Value()`, that's not the same effect as what we're looking for. There's an option called `PrefetchSize` which allows us to call the `fillItem` asynchronously before the user reaches this key and calls that `Value()`. This gives it a head start to fetch the value before the user needs it.

Think of it as a linked list where user is at head and we're calling `fillItem` at tail, with the length of the list as `PrefetchSize`.

**Comment by dominikh** [comment]
@manishrjain I think there's a simple miscommunication, not a lack of understanding. I'm well aware of how async fetching behaves. And I am not suggesting calling `go kv.fillItem()` in `Value`. 

I am suggesting that for key-only iteration, with no prefetching of any sort, `Value` does a synchronous fetch, instead of adding a new API (the exported `FillItem`). That is, **for key-only iteration**, `Value` would implicitly be `FillItem + Value`. For key-value iteration, nothing would change.

**Comment by deepakjois** [comment]
What you are asking for is technically feasible, I guess. We just need to check if the `item.val` is `nil` and call `FillItem` in the Value() method before returning the value.

I guess it comes down to whether it is preferable to do an _explicit_ fetch (by letting the caller use `FillItem`) or an _implicit_ fetch (by checking if the value has been fetched when `Value()` is called, and calling `FillItem` before returning a value).

I will let @manishrjain comment on whether this is a good idea.

**Comment by deepakjois** [comment]
@dominikh, another thing to note is that we do not have access to the iterator state or options in the `Value()` method. So the way you originally suggested, i.e. checking the `FetchValues` option does not seem feasible.

**Comment by manishrjain** [comment]
@deepakjois The value can be nil, but then be filled concurrently via a goroutine (which got spawned when iteration filled in the key); so we can't deduce anything from the value.

@dominikh The issue that we have with doing a fetch after the user calls `Value()` is that it breaks async prefetching for us for key-value iteration. Exposing `FillItem` allows the user to make a value fetch call, while still allowing us to do value prefetching. I explained that above as well in my last comment, but somehow didn't get it across.

`kv.Item` doesn't have the context to know that `Value()` is being called from a key-only iteration or a key-value iteration; I don't see the need to complicate code to make it understand. `FillItem` gives the user what they need, i.e. a way to fetch value for some keys during a key-only iteration.

**Comment by manishrjain** [comment]
Btw, might make sense to rename `FillItem` to `FillValue` to make things clear, @deepakjois.

**Comment by deepakjois** [comment]
> Btw, might make sense to rename `FillItem` to `FillValue` to make things clear, @deepakjois.

Done
