### ISSUE TITLE
Evaluate using mmap for value logs

### ISSUE THREAD

**Issue by dominikh** [dgraph-io/badger#167]
While benchmarking a pure read-based workload (600,000 k/v pairs, stored in a tmpfs, values of size <100 byte, reading all values during iteration), I noticed a significant amount of time spent in Read syscalls. Quickly hacking in mmaping of the value log resulted in a wall time reduction of 33%, from 30s to 20s (30s includes the entire runtime of the application, which is processing the read data. I can provide cleaner numbers if required.). It is worth noting that this performance gain was only achievable after disabling asynchronous reads, as per #166.

Since Badger already supports mmap for the LSM tree it should be relatively straightforward to add mmap support for the value logs.

I haven't done any testing with regard to mmaped write performance.

**Comment by manishrjain** [comment]
My concern here is that the data set was only around 60-100MB and therefore mmap can easily load the whole thing up in RAM. With larger datasets, this isn't the case, and mmap on value log doesn't perform as well -- I've tried this in the past.

@deepakjois : Can you try this with 128B values and 250M keys?

**Comment by deepakjois** [comment]
We now use mmap for value logs.

**Comment by manishrjain** [comment]
@dominikh : Can you re-run your tests and check if you see the win you were expecting to see. You can turn off prefetch, and just call `item.Value(fn)`, to do them synchronously.
