### ISSUE TITLE
badger_info should sort output groups consistently

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#172]
Right now `badger_info`'s display of .sst's changes the file order every time, probably because they're put in a hash table.  Instead it should order by file number or perhaps key range.

**Comment by manishrjain** [comment]
Sort by key ranges and displaying the key ranges would be great. Also, would be good to output the total size of sst and value log files separately.

**Comment by srh** [comment]
Largely fixed by #185.  One thing that wasn't done was displaying the key ranges or sorting by them.  I'd recommend putting key ranges in the manifest before doing that.
