### ISSUE TITLE
design part is not in-depth

### ISSUE THREAD

**Issue by atidat** [dgraph-io/badger#1787]
**GitHub Issues are deprecated. Use [Discuss Issues](https://discuss.dgraph.io/c/issues/badger/37) for reporting issues about this repository.**
some core concept like **Arena** and **node** struct can't found any valuable describe in your official blog.

So, Hope upload some in-depth design document or add thorough comment in source code. 

Thx!

**Comment by jarifibrahim** [comment]
@atidat I can help if you have any specific question. We use skiplist for in-memory stuff. The skiplist uses a arena (block of memory) to keep nodes. The arena is used to reduce memory consumption. Golang GC doesn't like small chunks of memory. Arena is just a way to group nodes of the skiplist together.
