### ISSUE TITLE
How to reduce the file size, in windows，windows big file

### ISSUE THREAD

**Issue by hktalent** [dgraph-io/badger#1791]
windows big file
<img width="878" alt="image" src="https://user-images.githubusercontent.com/18223385/175198344-9f9314c2-6dc8-499e-b878-22ebe729add3.png">

but Mac OS
 $ ls -lah  .DbCache
total 24
drwx------   5 51pwn  staff   160B  6 21 22:24 .
drwxr-xr-x  27 51pwn  staff   864B  6 23 10:07 ..
-rw-------   1 51pwn  staff   1.3K  6 22 21:38 000000.vlog
-rw-r--r--   1 51pwn  staff     5B  6 23 10:05 LOCK
-rw-------   1 51pwn  staff    16B  6 23 10:05 MANIFEST

How to reduce the file size, in windows

**Comment by akon-dey** [comment]
@hktalent

**Comment by hktalent** [comment]
@jarifibrahim 
Yes, it looks like 2G on windows, I don't care, but some people using scan4all seem to care, so I have to automatically delete them by code after the program ends
thanks

**Comment by jarifibrahim** [comment]
@hktalent We truncate the file to actual file size when badger DB closes. You don't need to delete the file when your application closes.

**Comment by hktalent** [comment]
@jarifibrahim ok
Then I will update the latest version and check again
Thank you very much
