### ISSUE TITLE
high read bytes/s

### ISSUE THREAD

**Issue by zdyj3170101136** [dgraph-io/badger#1805]
i use rocksdb on my machine with 100 GB SSD disk.
and suddenly the read bytes / s is very high.

why it will happen and how to avoid it?

is there anything could help me debug reason like trace or metric?
![截屏2022-10-09 上午11 24 37](https://user-images.githubusercontent.com/52686065/194736326-d89758f9-1223-47b5-a86c-f1f9f6703c6f.png)

![截屏2022-10-09 上午11 25 10](https://user-images.githubusercontent.com/52686065/194736344-25037b5f-7f79-4a0c-ae7d-6cab0a303586.png)

**Comment by zdyj3170101136** [comment]
log may be useful:

seems there are a lot of compact.

```
level=info name=parca ts=2022-10-09T03:45:49.027089262Z caller=badger.go:53 msg="[1] [E] LOG Compact 5->6 (1, 14 -> 14 tables with 5 splits). [28382 . 28595 28596 27420 27413 27418 27419 27414 27416 27421 27422 27425 27423 27430 28531 .] -> [28610 28611 28616 28628 28629 28619 28627 28630 28615 28624 28626 28618 28621 28622 .], took 7.313s\n"
```

```
level=info name=parca ts=2022-10-09T03:45:37.182613441Z caller=badger.go:53 msg="[1] [E] LOG Compact 5->6 (1, 10 -> 11 tables with 4 splits). [28373 . 27441 27442 27405 27408 27409 27399 27406 27407 27403 27404 .] -> [28534 28546 28557 28525 28539 28545 28528 28542 28547 28529 28530 .], took 23.393s\n"
```

**Comment by mangalaman93** [comment]
I think this issue would be more relevant on the rocksdb repo.
