### ISSUE TITLE
[BUG]: Concurrent manifest corruption bugfix not pulled into latest build

### ISSUE THREAD

**Issue by dangermike** [dgraph-io/badger#1819]
### What version of Badger are you using?

v3.2103.3

### What version of Go are you using?

Go 1.19 (not that it matters)

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Doesn't matter

### What steps will reproduce the bug?

Look at #1756, see it in the `master` branch, but not on the `v3.2103.3` branch

### Expected behavior and actual result.

Expected merged bugfix to be in the latest release. Actually not.

### Additional information

I think this was just missed when the tag was created. It's a big deal for those affected by it.

**Comment by dangermike** [comment]
Thanks, @joshua-goldstein! I really appreciate the fast response.

**Comment by joshua-goldstein** [comment]
@dangermike Thanks again for bringing this to our attention, issue is patched in Badger v3.2103.4.
