### ISSUE TITLE
[BUG]: Iteration stops after 104854 items

### ISSUE THREAD

**Issue by lacikawiz** [dgraph-io/badger#1822]
### What version of Badger are you using?

v3.2103.3

### What version of Go are you using?

go1.19.1 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Intel© Core™ i7-6820HQ CPU
Linux Mint 20.3
Linux Kernel 5.2.7
RAM: 16GB

### What steps will reproduce the bug?

Run the following code. The "keys remained in the DB" should be 0 but it displays:  5146 . That means the iteration stopped after (110000-5146 =) 104854 items. Increasing the number of items created in the first step will increase the number that has been left.

```go
package main

import (
	"encoding/binary"
	"log"

	badger "github.com/dgraph-io/badger/v3"
)

func main() {
	db, err := badger.Open(badger.DefaultOptions("testdb"))
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	//11 times create 10000 entries and then remove them
	for i := 0; i < 11; i++ {
		log.Println("Round ", i+1)
		db.Update(func(txn *badger.Txn) error {

			seq, _ := db.GetSequence([]byte("abc"), 1000)
			b := make([]byte, 8)
			for j := 0; j < 10000; j++ {
				s, _ := seq.Next()
				binary.LittleEndian.PutUint64(b, s)
				key := make([]byte, 8)
				copy(key, b)
				txn.Set(key, []byte("Hasta la vista, baby!"))
			}

			return nil
		})

	}
	db.Update(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 10
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Rewind(); it.Valid(); it.Next() {
			txn.Delete(it.Item().KeyCopy(nil))
		}
		return nil
	})

	db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 10
		it := txn.NewIterator(opts)
		defer it.Close()
		ctr := 0
		for it.Rewind(); it.Valid(); it.Next() {
			ctr++
			//log.Println(string(it.Item().Key()))
		}
		log.Println(ctr, " keys remained in the DB.")
		return nil
	})

}
```

### Expected behavior and actual result.

The iteration loop over the items should remove all items, leave none.

**Comment by mdogan** [comment]
You should handle transaction errors. Most probably one of the update transactions is returning an error like `ErrTxnTooBig`:

https://github.com/dgraph-io/badger/blob/4dcd38419a1055d1c569dcf800d0050d8236bf9a/errors.go#L38-L39

**Comment by mangalaman93** [comment]
Feel free to reopen the issue if you are still seeing a problem after handling the errors
