### ISSUE TITLE
[QUESTION]: db.HandoverSkiplist function not available

### ISSUE THREAD

**Issue by evanoberholster** [dgraph-io/badger#1824]
### Question.

I am using the latest version of github.com/dgraph-io/badger/v3. It doesn't have (db *DB)HandoverSkiplist function. I have seen this function under the "main" tag on GitHub. Am I missing something or why is this function not in v3?

Thanks

**Comment by joshua-goldstein** [comment]
Looks like it is in the main branch (see [here](https://github.com/dgraph-io/badger/blob/356fef7509a9ea25e2c610e4b0fdae8af9eb1ea7/db.go#L1022)) but not in the latest tagged release of Badger (which is v3.2103.4).  So I am guessing your project is using the tagged version.  Several commits have gone into main but have not gone into the tagged versions.

**Comment by mangalaman93** [comment]
We have deprecated this function from `main` for now.
