### ISSUE TITLE
[Documentation]: Please add links to documentation

### ISSUE THREAD

**Issue by scr-oath** [dgraph-io/badger#1836]
### What version of Badger is the target?

Any/all

### Documentation.

https://dgraph.io/docs/badger is a 404

**Comment by yulai46** [comment]
Where docs?)

**Comment by vishalchandra** [comment]
lol

**Comment by scr-oath** [comment]
![image](https://user-images.githubusercontent.com/41922797/206925200-861832dc-1307-42c6-a9fd-7471cc762f28.png)

**Comment by akon-dey** [comment]
@vishalchandra we had an outage which affected our docs site. The issue was fixed and you should now be able to access the documentation. Please let us know if you face any problems. Thank you for your patience.
