### ISSUE TITLE
[Documentation]: Quick fix - update the URL on the GitHub about link

### ISSUE THREAD

**Issue by cuducos** [dgraph-io/badger#1839]
### What version of Badger is the target?

Any version.

### Documentation.

At the _About_ section in the GitHub repo page, the URL is pointing to an old URL that gives us `404`. I belive it should be pointing to https://dgraph.io/docs/badger/, right?

![Pasted_Image_2022-12-14__23_02](https://user-images.githubusercontent.com/4732915/207769788-0d1c7f01-2f30-4f8d-ac1c-11eb930b952e.png)

### Additional information.

Unfortunately, there's no PR for that, only contributors can update that — otherwise I would open a PR to try to help and thank you for this fantastic app : )

**Comment by skrdgraph** [comment]
@cuducos thanks for reporting this. We have fixed this up now. Please feel free to re-open this issue - if you see any related problems. 

We will close this shortly from our end.
