### ISSUE TITLE
[BUG]: *DB.Sync should sync memtable in addition to value log

### ISSUE THREAD

**Issue by mcfog** [dgraph-io/badger#1847]
### What version of Badger are you using?

github.com/dgraph-io/badger/v3 v3.2103.5

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

-

### What steps will reproduce the bug?

call *DB.Sync()

### Expected behavior and actual result.

Both memtable('s wal file) and value log should be persisted by Sync call.

**Comment by mangalaman93** [comment]
This seems reasonable to me. If you could raise a PR with a test that proves the issue, that'd be awesome. Otherwise, we will try to get to it as soon as we can. Thanks
