### ISSUE TITLE
when iterate file at GC，not lock logfile file?

### ISSUE THREAD

**Issue by laohanlinux** [dgraph-io/badger#1897]
### Question.

Hi，When run GC and the GC's file is `FileA`, but `FileA` not lock at GC iterte。If now，some *GetRequest* hit key also At `FileA` that changed  `FileA`'s file cursor and Interrupt `FileA' iterte file cusort. Is that okay?

**Comment by laohanlinux** [comment]
![WeChatWorkScreenshot_8c3fe698-89e1-454c-b54e-68792fe862c4](https://user-images.githubusercontent.com/4718156/222328217-361804de-bed3-48bf-8e34-1e11ef091625.png)
![image](https://user-images.githubusercontent.com/4718156/222328202-eb949b72-de9b-4e95-8771-4fc1a430f191.png)


**not see any lock**

**Comment by mangalaman93** [comment]
Hi there, thanks for filing the issue. Something seems off here to me too. Would it be possible for you to write a test that shows this problem?

**Comment by laohanlinux** [comment]
Unfortunately, I haven't built the corresponding test scene yet, which is a bit troublesome. However, I'm adapting a Rust Badger implementation and I'm testing this scenario。
https://github.com/laohanlinux/badger-rs

**Comment by laohanlinux** [comment]
@mangalaman93 Hi, The first version have release，implements all the features of badger-go 0.80.
https://github.com/laohanlinux/badger-rs
