### ISSUE TITLE
Tuning documentation?

### ISSUE THREAD

**Issue by siara-cc** [dgraph-io/badger#1907]
### Question.

Hi,

I am trying to store huge amount of key/value pairs using badger.  But my writes are quite slow.  I would like to tune the options to see if I can make it faster.

I don't seem to find the API documentation or tuning guide, although I can see reference to it [here](https://github.com/dgraph-io/badger/issues/109#issue-243691255).

The documentation linked on this repo leads to the one page getting started guide.

Kindly let me know where I can find the docs.

Also, [this repo](https://github.com/outcaste-io/badger) talks about a leaner (possibly faster?) version v4.  Where can I find docs for using it?

I am building a word/phrase frequency database [here](https://github.com/siara-cc/Text_frequency_research/blob/main/golang/gen_words_and_phrases.go) and I am trying to choose a suitable indexing system that can build this database.  Any recommended option settings for such a scenario?

**Comment by mangalaman93** [comment]
Usually, writes are pretty fast. I see you are using DefaultOptions. The only additional thing I can think of is to disable compression in the badger options. That should speed things up. Are you using SSDs or Hard Disks?

I believe increasing `NumMemtables` could also help speed up writes but that could slow down reads if that is one of the concerns. Hope that thelps

**Comment by mangalaman93** [comment]
Closing the issue, feel free to reopen if you have any more questions.
