### ISSUE TITLE
[QUESTION]: Publish before committing to WAL

### ISSUE THREAD

**Issue by hugy718** [dgraph-io/badger#1916]
### Question.

I found this potential issue, while studying the badger codebase.
In the current code, the publisher start to sends requests to subscribers before they are written to the write ahead log embedded inside memtable. Shouldn't subscribers only receive the updates after these changes are persisted? (For example, in the bank application that uses this pub/sub feature.)

https://github.com/dgraph-io/badger/blob/4ecafa250e832c071cd90a421c8c172f463f0ce4/db.go#L819-L849

The `sendupdate` can be shifted after the `writeToLSM` after L848, such that updates are persisted first. I tested that it will not break tests.

**Comment by mangalaman93** [comment]
I think this makes sense to me. We used to use vlog as WAL before and we do write to vlog before sending out the updates. Now, we don't use VLOG as WAL and it makes sense to send updates after. Feel free to raise a PR or we will get to it when we can. Thanks for filling the issue.

**Comment by hugy718** [comment]
I see. Thanks for giving the context. I will create a PR and reference this issue.
