### ISSUE TITLE
[QUESTION]: Time between new transaction and commit

### ISSUE THREAD

**Issue by Castigamat** [dgraph-io/badger#1926]
### Question.

Good evening,
I'm facing a particular situation in which is possible that between the opening of a new transaction and the commit instruction could pass much time.
Is there a sort of timeout that could discard automatically the transaction or is it safe untill the commit instruction?
Thanks and Regards.

**Comment by mangalaman93** [comment]
I think transactions could last as long as you want, it is perfectly safe.

**Comment by mangalaman93** [comment]
closing the issue, feel free to reopen it if needed.
