### ISSUE TITLE
[QUESTION]: Why does `isFull()` only checks the WAL's write offset without the new data included?

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/badger#1929]
### Question.

This only checks whether the position of the current write offset in the WAL has gone over the `MemTableSize`, it doesn't include the new data that needs to be written.

```
func (mt *memTable) isFull() bool {
	...
	return int64(mt.wal.writeAt) >= mt.opt.MemTableSize
}
```

**Comment by mangalaman93** [comment]
related to #1927
