### ISSUE TITLE
[QUESTION]: Badger getting crashed while performing backup call.

### ISSUE THREAD

**Issue by adpande** [dgraph-io/badger#1931]
### Question.

Hello,

We have implimented GC Call exactly as given in the docs. Still daily the application crashes after printing the following lines. Is there any way to catch it or we are doing something wrong?
```
badger 2023/04/26 20:44:14 INFO: Sent range 3 for iteration: [372e313638323337353530363237
38fffffffffffeeff5, 382e31363831353532323533363438ffffffffffff7c2d) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 4 for iteration: [33302e3136383234333137353735
3231fffffffffffee48b, 342e31363832333933333537313531fffffffffffeedae) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 5 for iteration: [342e313638323339333335373135
31fffffffffffeedae, 352e31363831353732373436353138ffffffffffff79b8) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 6 for iteration: [352e313638313537323734363531
38ffffffffffff79b8, 352e31363832343237323536393132fffffffffffee5bb) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 7 for iteration: [352e313638323432373235363931
32fffffffffffee5bb, 362e31363832333739353536313731fffffffffffeef7e) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 8 for iteration: [7636fffffffffffedbf2, 7638ff
fffffffffee31f) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 9 for iteration: [31302e3136383234313136353635
3238fffffffffffee976, 31302e31363832343932323039323934fffffffffffeda60) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 10 for iteration: [322e31363832343033383536393
435fffffffffffeeb0d, 33302e31363832343331373537353231fffffffffffee48b) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 11 for iteration: [382e31363831353532323533363
438ffffffffffff7c2d, 382e31363832343731363538363034fffffffffffeddf9) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 12 for iteration: [382e31363832343731363538363
034fffffffffffeddf9, 392e31363832333634353535393732fffffffffffef155) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 13 for iteration: [392e31363832333634353535393
732fffffffffffef155, 763130fffffffffffedf75) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 14 for iteration: [763130fffffffffffedf75, 763
330fffffffffffee71c) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 15 for iteration: [763330fffffffffffee71c, 763
6fffffffffffedbf2) of size: 4.7 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 16 for iteration: [, 31302e3136383234313136353
6353238fffffffffffee976) of size: 4.2 MiB
badger 2023/04/26 20:44:14 INFO: Sent range 17 for iteration: [7638fffffffffffee31f, ) of 
size: 2.3 MiB
```

**Comment by mangalaman93** [comment]
Hi @adpande, thank you for filling the issue. Could you provide us with more information? Does it not print any stack trace when it crashes? Do you know ho much % memory does system have available at this point?

**Comment by adpande** [comment]
Hi @mangalaman93, It does not print any stack trace when it crashes. We are using a 1GB RAM-1vCPU AWS lightsail instance. We monitored the memory but the avg memory consumption is ~100mb. We did not know the memory consumption exactly at the time of crashing.

**Comment by adpande** [comment]
Here is our GC function code.
```go
func GCTimer() {
    ticker := time.NewTicker(60 * time.Minute)
    for {
        select {
        case <-ticker.C:
            RunGC()
        }
    }
}

func RunGC() {
    log.Println("Running GC")
again:
    err := db.RunValueLogGC(0.5)
    if err == nil {
        goto again
    } else {
        log.Println(err)
        log.Println("GC finished")
    }
}
```

**Comment by mangalaman93** [comment]
Why are you trying to run ValueLogGC periodically? What is the value of the configuration "ValueThreshold" for you? By default, it is set to 1MB. If that is the case. do you have value that could be larger than 1 MB?

**Comment by adpande** [comment]
Nothing special. I am using the default config only.
```go
func InitBadger(path string) {
    log.Println("Initiating badger db")
    var err error
    options := badger.DefaultOptions(path)
    options.NumCompactors = 2
    db, err = badger.Open(options)
    if err != nil {
        log.Fatal(err)
    }
    log.Println("Badger init success")
}
```

**Comment by mangalaman93** [comment]
unless you have values higher than 1 MB, value log won't be used. We plan to improve on this as soon as we can. I hope this helps.

**Comment by mangalaman93** [comment]
oh, but, I am still interested in figuring out why badger would crash. Is it possible for you to share a snippet of the code that can help me reproduce this issue?

**Comment by adpande** [comment]
There is no snippet as such. We are constantly adding values to it. But whenever it fails it has the above logs (first ) in the file.

> ### Question.
> Hello,
> 
> We have implimented GC Call exactly as given in the docs. Still daily the application crashes after printing the following lines. Is there any way to catch it or we are doing something wrong?
> 
> ```
> badger 2023/04/26 20:44:14 INFO: Sent range 3 for iteration: [372e313638323337353530363237
> 38fffffffffffeeff5, 382e31363831353532323533363438ffffffffffff7c2d) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 4 for iteration: [33302e3136383234333137353735
> 3231fffffffffffee48b, 342e31363832333933333537313531fffffffffffeedae) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 5 for iteration: [342e313638323339333335373135
> 31fffffffffffeedae, 352e31363831353732373436353138ffffffffffff79b8) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 6 for iteration: [352e313638313537323734363531
> 38ffffffffffff79b8, 352e31363832343237323536393132fffffffffffee5bb) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 7 for iteration: [352e313638323432373235363931
> 32fffffffffffee5bb, 362e31363832333739353536313731fffffffffffeef7e) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 8 for iteration: [7636fffffffffffedbf2, 7638ff
> fffffffffee31f) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 9 for iteration: [31302e3136383234313136353635
> 3238fffffffffffee976, 31302e31363832343932323039323934fffffffffffeda60) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 10 for iteration: [322e31363832343033383536393
> 435fffffffffffeeb0d, 33302e31363832343331373537353231fffffffffffee48b) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 11 for iteration: [382e31363831353532323533363
> 438ffffffffffff7c2d, 382e31363832343731363538363034fffffffffffeddf9) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 12 for iteration: [382e31363832343731363538363
> 034fffffffffffeddf9, 392e31363832333634353535393732fffffffffffef155) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 13 for iteration: [392e31363832333634353535393
> 732fffffffffffef155, 763130fffffffffffedf75) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 14 for iteration: [763130fffffffffffedf75, 763
> 330fffffffffffee71c) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 15 for iteration: [763330fffffffffffee71c, 763
> 6fffffffffffedbf2) of size: 4.7 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 16 for iteration: [, 31302e3136383234313136353
> 6353238fffffffffffee976) of size: 4.2 MiB
> badger 2023/04/26 20:44:14 INFO: Sent range 17 for iteration: [7638fffffffffffee31f, ) of 
> size: 2.3 MiB
> ```

**Comment by adpande** [comment]
Hi @mangalaman93 ,

App again crashed. This is happening when we take backup periodically. Here are the logs for your reference. The app was consuming 94MB of RAM when it went down. (Total RAM is 1GB)

```
badger 2023/04/28 09:14:18 INFO: DB.Backup Streaming about 3.1 MiB of uncompressed data (1
.8 MiB on disk)
badger 2023/04/28 09:14:18 INFO: Number of ranges found: 18
badger 2023/04/28 09:14:18 INFO: Sent range 0 for iteration: [362e313638323534383736323837
39fffffffffffecf24, 372e31363832353333333133363538fffffffffffed403) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 1 for iteration: [31302e3136383235373532313639
3435fffffffffffecd15, 322e31363832353430393632363633fffffffffffed2d0) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 2 for iteration: [372e313638323533333331333635
38fffffffffffed403, 372e31363832353839363532353934fffffffffffeca96) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 3 for iteration: [372e313638323538393635323539
34fffffffffffeca96, 382e31363832343731363538363034fffffffffffeddf9) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 4 for iteration: [322e313638323630353435373131
39fffffffffffec7ac, 342e31363831383632383137373635ffffffffffff474c) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 5 for iteration: [342e313638313836323831373736
35ffffffffffff474c, 352e31363832343036353536333539fffffffffffeea7b) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 6 for iteration: [352e313638323430363535363335
39fffffffffffeea7b, 352e31363832353938353537373539fffffffffffec8ee) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 7 for iteration: [352e313638323539383535373735
39fffffffffffec8ee, 362e31363832353438373632383739fffffffffffecf24) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 8 for iteration: [7636fffffffffffedbf2, 7638ff
fffffffffec978) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 9 for iteration: [7635fffffffffffecd4a, 7636ff
fffffffffedbf2) of size: 5.1 MiB
badger 2023/04/28 09:14:18 INFO: Sent range 10 for iteration: [322e31363832353430393632363
633fffffffffffed2d0, 322e31363832363035343537313139fffffffffffec7ac) of size: 5.1 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 11 for iteration: [382e31363832343731363538363
034fffffffffffeddf9, 392e31363832343133303036373239fffffffffffee919) of size: 5.1 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 12 for iteration: [392e31363832343133303036373
239fffffffffffee919, 392e31363832353832373532313235fffffffffffecbb7) of size: 5.1 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 13 for iteration: [392e31363832353832373532313
235fffffffffffecbb7, 7632fffffffffffee2eb) of size: 5.1 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 14 for iteration: [7632fffffffffffee2eb, 7635f
ffffffffffecd4a) of size: 5.1 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 15 for iteration: [31302e313638323530343531313
23530fffffffffffed8ab, 31302e31363832353735323136393435fffffffffffecd15) of size: 5.0 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 16 for iteration: [, 31302e3136383235303435313
1323530fffffffffffed8ab) of size: 4.7 MiB
badger 2023/04/28 09:14:19 INFO: Sent range 17 for iteration: [7638fffffffffffec978, ) of 
size: 2.5 MiB
```

**Comment by adpande** [comment]
Hi @mangalaman93 ,

Did you try the above snippet. I think, this is the one which is crashing the app.

Regards,
Abhishek

**Comment by mangalaman93** [comment]
Hi @adpande, I am able to reproduce this issue on my end. Thanks for the code. Let me figure out why it is allocating so much memory during backup. I will keep you posted.

**Comment by adpande** [comment]
Awesome! Let me know if you need any help

**Comment by adpande** [comment]
@mangalaman93 Any updates on this issue?

**Comment by adpande** [comment]
@harshil-goel thanks a lot for looking into this issue. I saw the issue about introduction of a flag or option to set memory. But instead of giving a user an option to set it, is it possible to do it automatically based on some formula, algorithm or db size? This would be easier to use.

**Comment by harshil-goel** [comment]
Hey @adpande, we checked the script that you gave again. It looks like we are not actually able to reproduce the issue. We were just looking at alloc space, which is going upto 2GB. However, when we checked the code further, it looks like we de-allocate the space quite soon also. To confirm this, we ran the script in a container with 500MB of memory, and it didn't crash. 

Are you sure that your badger is crashing with low memory? Next time your badger crashes, can you check the result of `sudo dmesg` once. It should show you something like 
```
[440414.328057] Memory cgroup out of memory: Killed process 952626 (badger.test) total-vm:5522976kB, anon-rss:405776kB, file-rss:10284kB, shmem-rss:0kB, UID:0 pgtables:1276kB oom_score_adj:0
```

Meanwhile, if it's happening because of memory, can you running badger with NumGoroutines = 1. This should use less memory and might be able to fit your ram. If would be great if you could get some profiles as well. It would help us debug the issue. Something like this: https://www.neteye-blog.com/2019/06/go-pprof-how-to-understand-where-there-is-memory-retention/

**Comment by adpande** [comment]
@harshil-goel, Here is tyhe output i get from `sudo dmesg`

```
[2164052.943313] Out of memory: Kill process 19147 (timestone) score 858 or sacrifice chil
d
[2164052.951115] Killed process 19147 (timestone) total-vm:4441460kB, anon-rss:850572kB, f
ile-rss:0kB, shmem-rss:0kB
[2164052.990745] oom_reaper: reaped process 19147 (timestone), now anon-rss:0kB, file-rss:
0kB, shmem-rss:0kB

```

where timestone is the process name.

**Comment by harshil-goel** [comment]
@adpande I tested the script on my machine with 1GB limit. I think there might be a difference because you are running only on 1 CPU. That combined with occasional compaction might be increasing your memory usage. Can you try to take a memory profile before your code crashes?

**Comment by adpande** [comment]
@harshil-goel will setting environment variable NumGoroutine=1 impact performance? Or it is just using duing backup?

**Comment by harshil-goel** [comment]
This flag is used inside the stream framework that badger gives. In general it is only used when you want to read the entire db, which generally only happens during backup. So you should ideally only see performance impact during backup.
