### ISSUE TITLE
Coverage report needed to add to awesome-go

### ISSUE THREAD

**Issue by francoishill** [dgraph-io/badger#195]
The awesome-go lib requires coverage reports, please see the avelino/awesome-go [PR #1561](https://github.com/avelino/awesome-go/pull/1561#pullrequestreview-59140788) for this. I could check all tickboxes but not coverage...

**Comment by pawanrawal** [comment]
I added integration with coveralls. A badge is also available in the README.

**Comment by francoishill** [comment]
@pawanrawal, awesome! I updated the [PR](https://github.com/avelino/awesome-go/pull/1561) on awesome-go
