### ISSUE TITLE
[QUESTION]: Browser wasm support

### ISSUE THREAD

**Issue by omar391** [dgraph-io/badger#1956]
### Question.

Hi,

Is there any plan to support Browser IndexedDB via wasm? This would be very very interesting since several large projects like IPFS use badger DB.

Best.

**Comment by mangalaman93** [comment]
Hi Omar, We don't have any such plans right now but feel free to give it a try and let us know what doesn't work.

**Comment by tangxusc** [comment]
# env
go version go1.21.4 darwin/arm64
# code
```go
package main

import (
	"github.com/dgraph-io/badger/v4"
	"github.com/extism/go-pdk"
	"log"
)

var db *badger.DB

func main() {
	var err error
	db, err = badger.Open(badger.DefaultOptions("/tmp/badger"))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(db)
}

```

# Compile command
```shell

GOOS=wasip1 GOARCH=wasm go build -o main.wasm main.go
```

# error out
package command-line-arguments
        imports github.com/dgraph-io/badger/v4
        imports golang.org/x/sys/unix: build constraints exclude all Go files in /Users/tangxu/sdk/gopath/pkg/mod/golang.org/x/sys@v0.5.0/unix
