### ISSUE TITLE
Investigate using Fadvise to improve random read performance

### ISSUE THREAD

**Issue by maximecaron** [dgraph-io/badger#197]
On linux machine it's possible to use Fadvise(fd_, 0, 0, 1); to let the OS know to not perform read ahead during random read.

**Comment by peterstace** [comment]
Most reads from the value log will be random, so could improve disk throughput there.

**Comment by manishrjain** [comment]
This sounds like something we should try asap. @deepakjois

**Comment by deepakjois** [comment]
@maximecaron You can take a look at the changes I made in another branch. I believe those are the changes that you had in mind when filing the issue.

I ran some benchmarks, and did not notice a significant difference for reads. It was slightly faster for iterations, but not by a significant enough amount.

It is still an interesting change, and we can evaluate it later based on how our changes to incorporate mmap into value log (issue #182) go.

**Comment by deepakjois** [comment]
We are now using mmap for reading value log, and we also issue an `madvise` which disables readahead.

Closing this.
