### ISSUE TITLE
[Documentation]: Update for Stream and v4 in general

### ISSUE THREAD

**Issue by naivary** [dgraph-io/badger#1972]
### What version of Badger is the target?

v4

### Documentation.

Some APIs changed for v4 and none of them are documented. For exmaple streaming API changed and its really hard to figure out how to work with the new API.

**Comment by baryluk** [comment]
Would be nice to update at least https://dgraph.io/docs/badger/get-started/ to use `v4` imports.

**Comment by baryluk** [comment]
Also in few places in docs, it says that cgo is required for zstd, which is no longer true.
