### ISSUE TITLE
[QUESTION]: Connection pooler for badger

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dgraph-io/badger#1975]
### Question.

I am trying to evaluate if badger is the best tool for my use case. I need the speed that this db offers but I also need to access it from multiple processes, the first thing that came in my mind using some sort of connection pooler, is this something that can be achieved with badger?

**Comment by mangalaman93** [comment]
Because badger is used as an embedded library, you can create multiple txns that run in parallel in one process. Currently, we do not allow accessing badger from multiple processes.
