### ISSUE TITLE
[QUESTION]: Is it possible to access/open DB by one write process and multiple read processes?

### ISSUE THREAD

**Issue by PD-Pramila** [dgraph-io/badger#1978]

**Comment by PD-Pramila** [comment]
I am getting error " can not lock the dir" while opening it using readonly option, when it's already opened with default options.

I also tried to open just readonly mode, but it also fails.

**Comment by mangalaman93** [comment]
Hi @PD-Pramila, this is not allowed right now.

**Comment by PD-Pramila** [comment]
Just to finally confirm. We can open DB once and that is for write only, correct??
We even can not open it just for read only, right?

**Comment by mangalaman93** [comment]
You can open the DB for read only if you like.

**Comment by PD-Pramila** [comment]
How to open for read only mode? When I set readonly option in options and try to open DB it gives errors.

For DB, which has some data stored in it:
error while opening memtables error: while opening fid: 39 error: while updating skiplist error: end offset: 20 < size: 134217728 error: Log truncate required to run DB. This might result in data loss\ngithub.com/dgraph-io/badger/v3.init

For new dir, when there is no data and try to open for read only:
 no manifest found, required for read-only db"

**Comment by mangalaman93** [comment]
I think, because the db was not closed properly. If you open it once in write mode and close it properly, you should be able to open it in read only mode after that.
