### ISSUE TITLE
[FEATURE]: Data comparison between multiple badger instance

### ISSUE THREAD

**Issue by tangxusc** [dgraph-io/badger#1981]
### Have you tried Badger before this proposal? and did not find anything similar?

None

## background
When using Badger to build a distributed storage system, data in multiple unowned replication shards cannot be quickly compared
## expect
Badger supports data comparison by key prefix for multiple instances

**Comment by mangalaman93** [comment]
You can always iterate over two badger instances and figure out the differences between the two. Will that not work for you?

**Comment by tangxusc** [comment]
Is there a better way to use iterative methods to transmit key and value data across multiple distributed nodes that consume significant performance?

**Comment by tangxusc** [comment]
I will try using Merkel tree to calculate abstracts and quickly compare them at different nodes. Thank you
