### ISSUE TITLE
Importing github.com/dgraph-io/badger/table just to get table.Nothing seems overkill

### ISSUE THREAD

**Issue by GwynethLlewelyn** [dgraph-io/badger#199]
Hi,

While trying to fit a Go FastCGI process into the available RAM that my shared provider allows to be run, I switched the tables to stay on disk as opposed as being loaded to RAM (of course, this obviously means everything gets _much_ slower; it's a trade-off).

To do that, I needed the `table.Nothing` value to set in the options... which meant importing & compiling the whole `table` module just to get _one_ tiny little thing. Shouldn't there be a simple way to avoid that?

(of course I can, for now, use the values and not the consts, and thus avoid importing `table`, but that's A Bad Idea For The Future)

**Comment by deepakjois** [comment]
You do have a point. This will be refactored, as part of another change (see #182).

I am assigning this issue to myself, and will close this issue when the change has been committed to master.

**Comment by deepakjois** [comment]
The change is in master now. You no longer need to import the whole `table` package. You just need the `options` package, which is lightweight.

Also the option names have changed a bit, as listed here: https://github.com/dgraph-io/badger/blob/4606da93f7bf5fe8319157005a989772900164a2/options/options.go

**Comment by GwynethLlewelyn** [comment]
Excellent! I've tried it out and it seems to work exactly as expected. I also noted that there were some more changes here and there on the way certain functions were called, so I needed some time to change all the code to support the new calls... and thus my lack of response.

For my purposes, this issue is totally fixed and everything makes much more sense the way it has been implemented.
