### ISSUE TITLE
[BUG]:  /lib64/libc.so.6: version `GLIBC_2.34' not found 

### ISSUE THREAD

**Issue by adpande** [dgraph-io/badger#1993]
### What version of Badger are you using?

4.2.0

### What version of Go are you using?

1.21

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

1GB, 1 vCPU, Amazon Linux 2

### What steps will reproduce the bug?

Update dependency to 

github.com/dgraph-io/badger/v4 v4.2.0

Try to run binary on amazon linux 2.

### Expected behavior and actual result.

It should run, but it fails with error:

/lib64/libc.so.6: version `GLIBC_2.34' not found

**Comment by mangalaman93** [comment]
Could you try running `make jemalloc` in the badger directory and check whether that helps? badger requires jemalloc, I am not sure whether `go mod tidy` will end up installing `jemalloc`
