### ISSUE TITLE
[QUESTION]: Disk space not reclaiming, what do I need to adjust?

### ISSUE THREAD

**Issue by mattdurham** [dgraph-io/badger#1995]
### Question.

I am using BadgerDB for a durable queue and in most cases Key,Values exist for 60s and then are deleted. Over the past hour no space has been reclaimed. I call `RunValueLogGC(0.01)` every 5 minutes but it never reclaims any space.

My options are 

```
opts.SyncWrites = true
opts.MetricsEnabled = true
opts.NumVersionsToKeep = 0
opts.MaxLevels = 1
opts.NumLevelZeroTables = 0
opts.NumLevelZeroTablesStall = 2
```

![Screenshot from 2023-08-21 16-25-28](https://github.com/dgraph-io/badger/assets/3036838/27bd75b5-bd88-4b99-bfc9-4cee6dd5fff5)

Thank you

**Comment by mangalaman93** [comment]
Is it possible for you to share the badger data directory? I can run value log gc on it locally and figure out why it is not cleaning up these files?

**Comment by wxbool** [comment]
I'm having the same problem. gc doesn't automatically clean up disk space.
