### ISSUE TITLE
Does this support range query?

### ISSUE THREAD

**Issue by kokizzu** [dgraph-io/badger#20]
for example i need to do something like this SQL:

```
SELECT value
FROM table
WHERE key >= 'key1'
   AND key <= 'key2'
```
does badger have a function or command to do this?

**Comment by manishrjain** [comment]
Yeah. We support range iteration. You can create an iterator, then do:
https://godoc.org/github.com/dgraph-io/badger/badger#Iterator.Seek

```
itr := kv.NewIterator(opt)
for itr.Seek(key1); itr.Valid(); itr.Next() {
  item := itr.Item()
  key := item.Key()
  if bytes.Compare(key, key2) > 0 { break }
  // rest of the logic.
}
```
