### ISSUE TITLE
cannot use generic type ristretto.Cache[K, V any] without instantiation ../../github.com/dgraph-io/badger/v4/table/table.go:80:14: cannot use generic type ristretto.Cache[K, V any] without instantiation

### ISSUE THREAD

**Issue by simokogice** [dgraph-io/badger#2005]
### What version of Badger are you using?

the latest

### What version of Go are you using?

1.21

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

32Go, 3,2; Apple M1 

### What steps will reproduce the bug?

when i try to build my project i got the error below:

# github.com/dgraph-io/badger/v4/table
../../github.com/dgraph-io/badger/v4/table/table.go:79:14: cannot use generic type ristretto.Cache[K, V any] without instantiation
../../github.com/dgraph-io/badger/v4/table/table.go:80:14: cannot use generic type ristretto.Cache[K, V any] without instantiation

**Comment by mangalaman93** [comment]
I am not sure why one would get this error. Ristretto supports generics on the newer version but badger still uses the older version of ristretto.

**Comment by mangalaman93** [comment]
Could you upgrade to Badger v4.3.1 https://github.com/dgraph-io/badger/releases/tag/v4.3.1 and let us know whether you are seeing this issue still. Thanks
