### ISSUE TITLE
[QUESTION]: Why badger use WAL? 

### ISSUE THREAD

**Issue by acekingke** [dgraph-io/badger#2015]
### Question.

I see the badge codes, in memtable.go file, there is wal for memtable, but I have read `wisckey ` paper, Instead of wal, the vlog can ensure the consistency, Why bager still use wal ?

**Comment by mangalaman93** [comment]
At some point, we realized that VLOG GC was getting complex due to the fact it was also used as a WAL. In Dgraph, we don't even use VLOG any more. I think this needs rework.

**Comment by acekingke** [comment]
Thanks
