### ISSUE TITLE
[QUESTION]: How can I limit the disk size used by Badger or the number of keys that Badger can store through parameter configuration in the program?

### ISSUE THREAD

**Issue by Delete-S** [dgraph-io/badger#2016]
### Question.

How can I limit the disk size used by Badger or the number of keys that Badger can store through parameter configuration in the program?

**Comment by Delete-S** [comment]
this is the use case:
we use  badger on a iot device. In order to prevent the program from running out of hard disk when a bug leads to unlimited SET data into the badger.

**Comment by Delete-S** [comment]
this is the use case:
we use  badger on a iot device. In order to prevent the program from running out of hard disk when a bug leads to unlimited SET data into the badger.

**Comment by Delete-S** [comment]
@mangalaman93  Thanks for answering my questions.
this is the use case:
we use badger on a iot device. In order to prevent the program from running out of hard disk when a bug leads to unlimited SET data into the badger.

**Comment by mangalaman93** [comment]
I think the best way to achieve this is to partition the disk you have and use badger on just one partition.

**Comment by Delete-S** [comment]
@mangalaman93   thanks ~
