### ISSUE TITLE
[QUESTION]: Search keys by regular expressions

### ISSUE THREAD

**Issue by julianthome** [dgraph-io/badger#2026]
### Question.

Hello,

I am working on a problem where regular expression based key search would be useful. 

At the moment I suppose a custom iterator based solution for adding in regular expression search support would work well enough if the search pattern includes a constant prefix. Otherwise, we basically have to search through the whole key set.

Are there any plans to support this type of feature are do you happen to be aware of a custom-iterator implementation that already does something similar?

**Comment by harshil-goel** [comment]
We don't have that feature planned, as we store the keys in sorted fashion.
