### ISSUE TITLE
Value log GC removes vlog files out from underneath iterators

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#203]
To reproduce, do the following:

1. Load a bunch of data
2. Make an iterator.  Maybe you need to rewind it now.
3. Make the value log trigger a GC.
4. Continue to use the iterator.

The iterator will hold references to old tables which contain value pointers to the now-deleted value log file.

This reproduction can be seen in TestValueGC3 in branch sam/valuegc or commit 19f231f066ac1d7ede0e19ac7f7c639fa0833e30.

There are various ways to fix this problem.

**Comment by deepakjois** [comment]
Yes, this came up when doing code review for #182 with @manishrjain. It is nice that we have a test for it.

With the changes in #182 (now in master), this should trigger an ErrRetry, signaling to the caller that they should call Get again. So at least there is a graceful way to recover from this.

**Comment by srh** [comment]
Well, we certainly can't have iteration spontaneously stop working just because we're actively writing to the database.

A solution to this, also encompassing table lifetimes under compaction, is to do the following:

1. Track value log files in the manifest.
2. Have an incrementing counter "manifestCounter" that increments every time we make a change to the file configuration (value log files, table compaction).  In other words, it increments every time we add a changeset to the manifest.
3a. When we start an iteration or perhaps other Badger operations, note the manifestCounter value it uses.
3b. When we delete a table or value log file, note in-memory the new manifestCounter value on which, and after which, the file is deleted.
3c. When we create a table file, note the manifestCounter on which it was created.
4. Don't actually delete the file until all iterations or other operations associated with a lower manifestCounter value have finished.  The reason is, they might possibly need that file.
5. To start iterating we won't have to go to every single freakin' table and call IncrRef (and later DecrRef) for it.  Or even construct a TableIterator up-front, as nice an abstraction as that may be.  We can just make a shallow copy of `levelHandler::tables` -- its pointers.

**Comment by manishrjain** [comment]
> Don't actually delete the file until all iterations or other operations associated with a lower manifestCounter value have finished. The reason is, they might possibly need that file.

How do you know there are pending ops related to this counter? Does every Get needs to now register itself to this?

**Comment by srh** [comment]
Point Get()s can retry automatically instead of registering.  Iteration, though, if you reconstruct the iterator from scratch then the key you're on (which the user has already read `Key()` for) might not exist anymore.

(Note that every Get() already touches a bunch of the same locks and atomic variables.)

If need be we could make registration/deregistration not involve having everything fight over the same cache line.

**Comment by manishrjain** [comment]
If this change simplifies our code base by not having each table incr and decr references -- and overall deletes more code than it introduces -- sounds good.
