### ISSUE TITLE
update ristretto

### ISSUE THREAD

**Issue by dezren39** [dgraph-io/badger#2046]
### Question.

hi!

related to #2027 

can you please update the ristretto dependency to the latest code in the main branch?

the change from this PR might resolve #2027 for many people:

- https://github.com/dgraph-io/ristretto/pull/366

i have also made an issue in ristretto suggesting a tag, if this happens then you could update to latest tag

- https://github.com/dgraph-io/ristretto/issues/374

**Comment by dezren39** [comment]
related
https://github.com/dgraph-io/badger/issues/1922#issuecomment-1703865146

**Comment by paralin** [comment]
I did it here: https://github.com/dgraph-io/badger/pull/2047

**Comment by paralin** [comment]
Not stale

**Comment by ryanfoxtyler** [comment]
PR #2047 has been merged
