### ISSUE TITLE
[Documentation]:  Document of BadgerDB missing

### ISSUE THREAD

**Issue by Fischer0522** [dgraph-io/badger#2075]
### What version of Badger is the target?

latest

### Documentation.

The documentation for BadgerDB appears to be missing. The URL provided, https://dgraph.io/docs/badger/, leads to a "Page Not Found" error when accessed.

**Comment by ryanfoxtyler** [comment]
Thanks for flagging. Trying to sort through what's happening in the rewrites, but feel free to reference https://badger-docs.netlify.app/ directly for now.

**Comment by ryanfoxtyler** [comment]
This should be all set now. Thanks again for raising.
