### ISSUE TITLE
Bug: not storing value pointer correctly in LSM tree after crash

### ISSUE THREAD

**Issue by szymonm** [dgraph-io/badger#21]
After crash we're replaying entries from value log. We are handling only the case when value should be stored in the LSM and omit the case when value is stored as value pointer in the tree.

See: https://github.com/dgraph-io/badger/blob/master/badger/kv.go#L181

**Comment by manishrjain** [comment]
This code should work:
https://gist.github.com/art4711/9d781b8cf1f9f36df73a9c5c0403f703

**Comment by manishrjain** [comment]
This code works now.
