### ISSUE TITLE
[BUG]: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

### ISSUE THREAD

**Issue by Hellseher** [dgraph-io/badger#2103]
### What version of Badger are you using?

1.6.2, 2.0.3

### What version of Go are you using?

1.21.5

### Have you tried reproducing the issue with the latest release?

No

### What is the hardware spec (RAM, CPU, OS)?

MEM: 64GiB
CPU:  AMD Ryzen 7 3800X 8-Core Processor
OS: GNU/Guix (Linux kernel)

### What steps will reproduce the bug?

go test -v ./...

### Expected behavior and actual result.

Tests passed

### Additional information

Fixed with substiituting `string()` ->  `fmt.Sprint()` in `histogram_test.go` test file

**Comment by shivaji-kharse** [comment]
This issue cannot be reproduced locally or in CI (see this workflow run: https://github.com/dgraph-io/badger/actions/runs/11521693967/job/32527838000).
