### ISSUE TITLE
[QUESTION]: Resilience under an environment with hard reboots?

### ISSUE THREAD

**Issue by bouk** [dgraph-io/badger#2110]
### Question.

Hi there, I was wondering how resilient badger is expected to be in an environment that often experiences hard reboots? We want to use it for robot hardware that is often powered off abruptly. I couldn't find much mention of this use case in the README.

Is there anything we need to do besides enabling syncwrites to ensure we don't corrupt the database in this case?

**Comment by mangalaman93** [comment]
If you set `SyncWrites=true`, it will slow things down a lot but it will resilient against any unexpected crashes.

**Comment by mangalaman93** [comment]
Closing, feel free to reopen if needed. Thanks
