### ISSUE TITLE
[QUESTION]: gogo/protobuf is deprecated; can the project migrate off of it?

### ISSUE THREAD

**Issue by BatmanAoD** [dgraph-io/badger#2111]
### Question.

According to the [repo itself](https://github.com/gogo/protobuf), which links to an [announcement on f.k.a. Twitter](https://x.com/awalterschulze/status/1584553056100057088),`gogo/protobuf` is deprecated. 

Can the `badger` project migrate onto either the official Google protobuf library or another solution?

**Comment by solracsf** [comment]
Fixed on v4.5.0 by https://github.com/dgraph-io/badger/pull/2131
