### ISSUE TITLE
[BUG]: install latest doesn't work

### ISSUE THREAD

**Issue by marcelloh** [dgraph-io/badger#2113]
### What version of Badger are you using?

go install github.com/dgraph-io/badger/v4/badger@latest

### What version of Go are you using?

go version go1.23.1 darwin/arm64

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

MacOs 

### What steps will reproduce the bug?

run the command:
go version go1.23.1 darwin/arm64

### Expected behavior and actual result.

go install github.com/dgraph-io/badger/v4/badger@latest
go: github.com/dgraph-io/badger/v4@v4.3.0: verifying module: checksum mismatch
        downloaded: h1:JZ8tapVYg+6sFQqg+BOokAxX+t09UeVPsPoXIq7jlNg=
        sum.golang.org: h1:lcsCE1/1qrRhqP+zYx6xDZb8n7U+QlwNicpc676Ub40=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by harshil-goel** [comment]
We are not able to reproduce this. Please try clearing caches and or reinstalling golang.
