### ISSUE TITLE
Couple of test failures  due to mmap changes

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#212]
This seems to be happening because the AppVeyor instance does not have enough virtual address space to map the value log. I am guessing this should not prevent Badger from working on a Windows machine with enough RAM, but I don’t have one around to test.

![screenshot from 2017-09-11 11-08-52](https://user-images.githubusercontent.com/5342/30259942-e9c3b504-96e1-11e7-9cbd-ff3c93e132c5.png)

**Comment by fjl** [comment]
Maybe it could fall back to file IO in this case?

**Comment by deepakjois** [comment]
This seems like a problem specific to the AppVeyor instance, and may not happen for users trying out Badger on Windows. But I don’t have a Windows machine with me at the moment, to confirm.

Moreover, falling back to File I/O would also mean maintaining two different code paths. Windows is not a primary target for us at the moment. We try to make sure that the code builds so that people can try out Badger on that platform. Maintaining a separate code path with File I/O fallback just for Windows doesn’t sound like a great option.

**Comment by manishrjain** [comment]
We could set the max value size to be the same as the size of log file (a parameter in options). Then we can set the write mmap to be twice the size of the log file. That way, we know that we won't exceed that limit. And it would also work on Appveyor.

**Comment by manishrjain** [comment]
IPFS is failing because of this. Let's fix this asap.

**Comment by deepakjois** [comment]
I don’t have a Windows machine, so I am using AppVeyor as a remote build bot to investigate. I created a [small project][windows-mmap]. Here is the [build history](https://ci.appveyor.com/project/deepakjois/windows-mmap/history).

* When I mmap the file with it’s exact size, it works fine.
* When I mmap it with `math.MaxUint32` or `500*1024*1023` (500MB), it fails.

There is probably an issue in the way we mmap on Windows. This code was probably never actually exercised on Windows (in the `tables` package we load to RAM by default).

I will investigate further.

[windows-mmap]: https://github.com/deepakjois/windows-mmap

**Comment by deepakjois** [comment]
So after a lot of trial and error, I made [some changes][mmapfix] which work well in my test project replicating this problem.

[mmapfix]:https://github.com/dgraph-io/badger/commit/ddd91503c9bfe62f7fdbb30143cf86b85fc2f5e3

But the changes are still causing [test failures](https://ci.appveyor.com/project/manishrjain/badger/build/395) (screenshot below):

* `TestWrite` is failing with : ` truncate:The requested operation cannot be performed on a file with a user-mapped section open.`.  This refers to the truncate operation during value log replay. It seems that we cannot use truncate on windows while a file is mmap-ed. A fix for this would require changes in the way we do value log replay. I can’t really say if it is a trivial change or not, without further investigation.

* `TestConcurrentWrite` is failing because it just takes too long to run. This indicates that there is some sort of race condition, but it only happens when we use mmap. We need to understand how Windows mmap-ing works more deeply to dig into this.

Sigh… @manishrjain  I hate to say it, but it seems like #235 might be the easiest way to get around this, after all.

![screenshot from 2017-09-19 14-42-21](https://user-images.githubusercontent.com/5342/30584897-cf031eb8-9d48-11e7-85fd-a8770ac67902.png)
.

**Comment by manishrjain** [comment]
Based on our last chat, a good solution here would be to not mmap until replay has been completed. Also, to preallocate the write file to 2xvalue log size, and then truncate it when done.
