### ISSUE TITLE
[QUESTION]: <Is it possible to implement pagination?>

### ISSUE THREAD

**Issue by filinvadim** [dgraph-io/badger#2133]
### Question.

I just want to implement simple blog using Badger and the question is: having key like `{namespace}:{name}:{timestamp}:{id}` is it possible to use offset or cursor to retrieve data by sequential batches?

**Comment by harshil-goel** [comment]
We also have stream framework, where you can give a prefix, and you can then implement map-reduce over your data. Could that be useful for your use case?

**Comment by filinvadim** [comment]
Not sure that i understand. I'm trying to reuse last key as cursor because keys contain timestamp and they are lexicographically sorted. But i'm getting random data for second page.
Could you add examples to docs if possible? This use case is quite common.

**Comment by filinvadim** [comment]
That's how i implemented it. If it's LGTM could you add this snippet to docs?
```
err = db.badger.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(opts)
		defer it.Close()

		p := prefix // prefix may look like 'namespace:id'
		if startCursor != nil { // startCursor may look like 'namespace:id:timestamp
			p = startCursor
		}
		iterNum := 0
		for it.Seek(p); it.ValidForPrefix(p); it.Next() {
			p = prefix // starting point for iteration found, revert prefix to  'namespace:id' to be able to continue iteration

			item := it.Item()
			key := string(item.Key())

			if iterNum > int(limit) { // limit reached
				lastKey = key // next item after limit provides cursor
				return nil
			}
			iterNum++

			val, err := item.ValueCopy(nil)
			if err != nil {
				return err
			}
			// do something with value
		}
		if iterNum < int(limit) {
			lastKey = ""
		}
		return nil
	})
if err != nil {
	return "", err
}
return lastKey, nil
```

**Comment by filinvadim** [comment]
@harshil-goel done!
