### ISSUE TITLE
Improve error of key-value limits

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/badger#227]
Ran into this limit while loading the stackoverflow data set.

Should also return two distinct errors so that it's clear whether it was the key or value that was too big.

Also, would be good to show the prefix of the actual key/value to aid with debugging if this occurs again.

**Comment by manishrjain** [comment]
The value limit should be based on the value log file size. Also see: https://github.com/dgraph-io/badger/issues/212

**Comment by peterstace** [comment]
PR: #237

**Comment by deepakjois** [comment]
@peterstace, can this be closed now?

**Comment by peterstace** [comment]
Yes, closed.
