### ISSUE TITLE
Level zero->one non-copying compaction.

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#236]
If we compact level 1->2 or higher levels and the key range of the compacted file doesn't overlap any key ranges in the next level, we avoid touching any .sst files -- we just update the manifest file.

It would be nice to be able to do that for level 0->1 compaction so that when the keys are inserted in increasing or decreasing order, we can use half as much disk I/O.  This would be quite useful for restoring from a backup, where (in the implementation awaiting PR) keys arrive in increasing order.

The basics have been implemented in branch sam/compactzero.  But for this to be practical we'll also need to make the !badger!head keys be written out-of-band somehow.

**Comment by srh** [comment]
We can remove !badger!head and write the info into the manifest.  I'll also get rid of the !badger prefix entirely.

**Comment by manishrjain** [comment]
That won't help. The head has to go along with the tables when they are
written out to disk. If we write a head for the latest table to manifest
(which gets synced to disk), the process can crash and that table can be
lost. But the head would incorrectly point to the value log past the table.
So, the data would become irrecoverable.

Thanks!

Cheers,
Manish

Founder/CEO, Dgraph Labs
+61-487138931
https://calendly.com/mrjn

**Comment by srh** [comment]
We write the manifest after the table comes to exist, and the table persists through a crash precisely when the manifest entry persists, so the head value can persist if and only if the table does.
