### ISSUE TITLE
Not convenience about the change:  KVItem.Value()  -> KVItem.Value(consumer func([]byte) error)

### ISSUE THREAD

**Issue by yqylovy** [dgraph-io/badger#242]
Hello ,
I notice that the API `KVItem.Value()` had been changed to `KVItem.Value(consumer func([]byte) error)`.
However, in many use case, it's useful to return value directly,also it is confused and danger to use `Value` as a method name when the value actually unchangable.
I think It's better to Keep the `Value()` method and ADD a new method such as `WithMmapValue(consumer func([]byte) error)`

**Comment by manishrjain** [comment]
The earlier Value() interface caused a bunch of confusion, because users didn't realize that they can't just use that value directly. It has to be copied over. The new function based interface makes that very clear.

**Comment by yqylovy** [comment]
Yes,I used the `Value()` directly too, DO NOT know it need copy! But I still think a method return a no-side-effect value is important.

**Comment by longdeqidao** [comment]
The badger got cool design but bad backwards compatibility. My project can't compile for multiple times because of update of **expoted API**.

**Comment by manishrjain** [comment]
We'll make the API stable once we're past v1.0. Right now, we're still making breaking changes to Badger's public APIs. Sorry for that -- but you can use vendor Badger into your project, so you're protected from such changes.
