### ISSUE TITLE
Question: multiple columns families or logical tables?

### ISSUE THREAD

**Issue by dvsekhvalnov** [dgraph-io/badger#255]
Hi,

sorry for naive question, but coming from cassandra experience. How would one implement multiple logical tables or column families (or namespaces if you will) on top of Badger?

1. Having single `badger.KV` instance but prefix keys with namespace info? (e.g. 0x00 for table1, 0x01 for table2, e.t.c.)

2. Having `badger.KV` per logical table? And hence multiple data dirs.

3. Something else?

Thank you in advance.

**Comment by tonyalaribe** [comment]
I'm interested in an answer to this issue as well

**Comment by peterstace** [comment]
For multiple logical tables, a fixed size key prefix would work well. If you have <= 256 logical tables, you could just use a single byte prefix (as suggested by @dvsekhvalnov).

**Comment by dvsekhvalnov** [comment]
Thanks Peter !
