### ISSUE TITLE
Test harness for iteration performance

### ISSUE THREAD

**Issue by lumost** [dgraph-io/badger#26]
Congrats on the release!

I've run a few benchmarks of iteration performance but ran into a few divergent results from those on the blog post.  Is it possible to publish additional details on the test rig/ test code used to compare with RocksDB?

**Comment by manishrjain** [comment]
The code is all in https://github.com/dgraph-io/badger-bench, as mentioned in the blog post. Do you need something more?

**Comment by lumost** [comment]
hmm missed that.. apologies!
