### ISSUE TITLE
Proposal: Add text/human/debug-mode

### ISSUE THREAD

**Issue by longdeqidao** [dgraph-io/badger#263]
The design of badger is cool, and I knew the reason why the disk file is binary is speed. But It's not convenient for developers/Operations to quickly check real data by using tools like `cat` in the terminal. So do you think whether it is great to add a text(like JSON) format storage or provide a utility to convert binary storage to text?

**Comment by peterstace** [comment]
We wouldn't want to add a text storage mode, speed is too important.

Something like `cat` for badger could be useful though. Maybe it could iterate over all keys and do a [hex dump](https://golang.org/pkg/encoding/hex/#Dump)hex dump of the key/value pairs. If whatever is being stored in the key/values is text, it would show up as readable text in the hex dump.

**Comment by longdeqidao** [comment]
@peterstace Your answer makes sense to me, thanks!
