### ISSUE TITLE
Add notes about garbage collection to README

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#269]
We have the `DB.RunValueLogGC()` method, and we will be introducing two more methods (`DB.PurgeOlderVersions()` and `DB.PurgeKeyVersionsBelow()`) for deleting older versions of keys.

We should document them in a separate section in the README.

**Comment by manishrjain** [comment]
Replace the name from Delete to Purge, so it doesn't conflate with the actual txn.Delete APIs.
