### ISSUE TITLE
Opening a DB example has a syntax error or two

### ISSUE THREAD

**Issue by rbastic** [dgraph-io/badger#274]
Hello,

In this example in the README:

```code
package main

import (
	"log"

	"github.com/dgraph-io/badger"
)

func main() {
  // Open the Badger store located in the /tmp/badger directory.
  // It will be created if it doesn't exist.
  opts := badger.DefaultOptions
  opts.Dir := "/tmp/badger"
  opts.ValueDir := "/tmp/badger"
  db, err := badger.Open(opts)
  if err != nil {
	  log.Fatal(err)
  }
  defer db.Close()
	…
}
```

I believe it should be opts.Dir = , not opts.Dir := -- the same for opts.ValueDir on the subsequent line.

Thanks for making Badger!

**Comment by deepakjois** [comment]
Thank you for the report. It’s fixed now

**Comment by rbastic** [comment]
It looks like the point of ellipsis at the bottom of the same example was rendered strangely, also, btw
