### ISSUE TITLE
[feature request] could badger provide column family apis?

### ISSUE THREAD

**Issue by wuxingyi** [dgraph-io/badger#276]
We plan to build a distribute storage system on top of key/value database and consider using badger as low-level storage engine. In our system, we shard user key/values into many badger instances to accelerate data recovery when some nodes died. We may also nee
In our design, a single daemon may open up to 1000 of badger instances, which sounds really crazy, it's a little hard to manage such big amount of instances.

Currently, a single badger instance is not enough for us, because we may drop a whole part of key/values(which is not sorted), which would drop performance for the whole LSM tree and also cause large amount of vlog gc. So I was wondering can badger provide column family api like rocksdb do? It's really helpful for us so we can shard key/values to column families in a single badger instance, the upside is, we can avoid vlog gc because all vlogs of a column family can simply deleted safely.

**Comment by manishrjain** [comment]
I'm trying to understand the need for having multiple Badger instances, or multiple column families. From your description:

> Currently, a single badger instance is not enough for us, because we may drop a whole part of key/values(which is not sorted), which would drop performance for the whole LSM tree and also cause large amount of vlog gc. 

Why would deleting a bunch of keys reduce the performance of the entire LSM tree? Even if that's the case, we could just optimize for that problem than to compound the issue by having 1000s of Badger instances on the same server.

**Comment by wuxingyi** [comment]
Thanks for the quick reply:)
The performance issue is mainly about data deletion, we are trying to build a storage system for object  storage, a single daemon may at most hold more than 12TB data, when deleting an collection of data(we organize data with collections), the key/value pairs may be 100GBs or more. When it comes to such big scale, I think seperated vlogs can avoid performance dropping because we can delete all of them, actually vlog gc does not come for free, it brings much extra disk io, so is the LSM tree, it need compaction because 1/1000 of keys are deleted, when value for single key is quit small(say ~10kB), key amount can be very large.

I was wondering managing 1000s of instances may be harder to optimize, because we have to manage file descriptors、memory、cache across all these instances.

I find rocksdb use a single WAL simply for replay, so multi column family can share a single WAL, while badger(or wiskey) actully use vlog as both WAL and value, so I think it's hard to implement multi column families because if we shard vlog to different column families, then it's totally like multi instances: seperated lsm, seperated vlog, seperated memtable.

**Comment by manishrjain** [comment]
There could be a way where the value logs can be separated by some identifier (equivalent of column family). So, each write would fall into a value log based upon this identifier (default maybe zero). But, they'd still share the same LSM tree, thus giving you transactional access across the entire DB. This gives you the advantage of not having to do value log GC, though the key tombstones could still consume some space in LSM.

But, this would add complexity and I'm not sure how useful this feature is to others. Creating multiple instances of Badger is always an option which would give you most of what you want anyway.

**Comment by deepakjois** [comment]
Doesn’t look like there is anything to do here. Closing.
