### ISSUE TITLE
Update magic number of Badger just before v1.0 release

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#282]
This would probably mean anybody who is using Badger prior to v1.0 will have to re-import their data (include Dgraph users).

**Comment by manishrjain** [comment]
Just confirm with IPFS folks that it would help.

**Comment by deepakjois** [comment]
cc: https://github.com/ipfs/go-ipfs/pull/4327

**Comment by deepakjois** [comment]
Maybe we should do this anyway, just to start off with a clean slate. Just need to make sure that we have covered all the implications of changing the magic number for existing data.

**Comment by manishrjain** [comment]
I'd like to avoid adding more things in the run towards v1.0. Unless IPFS folks see a clear benefit, we can release v1.0 and then work towards a solution to upgrade Badger data on disk.

**Comment by deepakjois** [comment]
Moving #135 to v1.0 milestone.
