### ISSUE TITLE
Write a unified CLI tool for Badger

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#292]
We currently have `badger_info`, and soon we will have `badger_backup`. We need to get v1.0 out of the door, so it is fine for now. But it would be much better to unify the commandline tools and have a single binary that performs all the functions.

It seems like [cobra] might be a good choice (`kubectl` is based on it, for one).

[cobra]: https://github.com/spf13/cobra

**Comment by deepakjois** [comment]
I am thinking it is probably a good idea if we do some initial work for this change before we go v1.0. Otherwise we will have to make yet another backwards incompatible change, deprecate some tools in favor of the new ones and inconvenience our users.

Maybe we don’t port `badger_info` to a unified just yet, but I am wondering if we should just go ahead and use a cobra based subcommand-driven tool, instead of `badger_backup` as I was originally thinking.

The subcommands that we need before we go to v1.0 are:

* `badger backup`
* `badger restore`
* `badger purge`

We can add more complexity later, but there is one thing we should nail down immediately, which is the global flags. So my assumption is that every subcommand we add to Badger, will require at a minimum these flags (alternate flag name suggestions welcome):

* `--sst-dir`, `-t` 
* `--vlog-dir`, `-l`
* …other flags for logging etc can be added later

Thoughts?

**Comment by manishrjain** [comment]
Hmm.. my initial reaction was to say no, and to push for v1.0 as soon as we can. But, this doesn't seem like such a big change, and we should be able to get it out the door in a day or so. If so, then let's do it and just keep focused on 1.0.

**Comment by manishrjain** [comment]
Actually backup can't be a tool, it has to be called from a running instance. Same for purge.

**Comment by manishrjain** [comment]
We'd also need an offline tool for badger GC. But after v1.0.

**Comment by deepakjois** [comment]
Ok. So for v1.0 we will build `badger backup` and `badger restore`.

**Comment by deepakjois** [comment]
#297 is now under review, which introduces the Badger CLI tool.

I am closing this for now. I will create individual issues for any additional commandline tool that we think we need. At the same time, every new tool also means an additional maintenance burden. So we need to be judicious. One idea is to create the issues and let them be open for a while and let ppl vote on whether it is something they find useful. We could do the same for any tool contributions from the community.
