### ISSUE TITLE
badger defrag tool

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#299]
Create a tool for purging older versions of a key from the DB.

**Comment by manishrjain** [comment]
I think `badger purge` should also literally remove keys from LSM tables which are deleted. The online `Purge` function would mark keys as deleted. But, this offline version of purge can be a good way to decrease the size of LSM tree by rewriting the LSM tree to get rid of all deleted keys.

As a counter point, there could be two different tools to achieve this -- one to mark keys as deleted and other to remove them from LSM. But, that just adds confusion. A way to decrease the size of LSM tree is more useful, IMO.

**Comment by deepakjois** [comment]
@manishrjain How about a `badger purge` subcommand that also takes in a `--compact` (`-c`) option. The default behavior of `badger purge` would be to just perform deletes. When the `--compact` option is passed, it will perform tree compaction as well.

**Comment by manishrjain** [comment]
As per discussion on slack, we need a defrag command, which can run the value log GC, and then also run LSM compactions removing the deleted/expired keys, to decrease the size of LSM tree and either push all tables to a single level, and/or rewrite them in place to remove any such keys.

**Comment by umbrellary** [comment]
PurgeOlderVersions() and RunValueLogGC() does not seem to work...
I am using it on an embedded device, so I'm very concerned about the size of the vlog file...
![image](https://user-images.githubusercontent.com/6939585/34282281-27c2893a-e6ff-11e7-87a8-21d033d2c384.png)

**Comment by manishrjain** [comment]
Tasks for the defag tool:

- Run compactions through the entire LSM tree to get rid of all invalid keys.
- Then run value log GC through all the log files to get rid of these keys and reclaim space.

All this would be done offline with the aim to reclaim maximum space.

**Comment by arctica** [comment]
I'll reference my comment from https://github.com/dgraph-io/badger/issues/226#issuecomment-391934265 here because I saw several other tickets mentioning this ticket here.

In my comment, I argue for a way to compact a DB online via API instead of an offline commandline tool as suggested here.

**Comment by SwarnimRaj** [comment]
@manishrjain Is the Badger defrag tool part of the current code- it seems its absence is causing an issue in Jaeger OpenTracing using Badger as storage https://github.com/jaegertracing/jaeger/pull/760#issuecomment-440272104

**Comment by manishrjain** [comment]
As mentioned in my comment on the original topic, the defrag tool is really meant for offline usage, not online usage. I think the growth of the data on disk, sounds like a different issue. I'm happy to help, let me know how.

**Comment by manishrjain** [comment]
There's now a new `flatten` tool and a `Flatten` API which consolidates all the data into a single LSM tree level. Running value log GC after that should be able to reclaim more space.
