### ISSUE TITLE
DB directory can not be created if it doesn't exist

### ISSUE THREAD

**Issue by sgon00** [dgraph-io/badger#312]
I was just trying the first simplest example code in README.md, the code comment has `Open the Badger database located in the /tmp/badger directory. It will be created if it doesn't exist.` and surprisingly, when I run `go run main.go`. the output is:

```
Invalid Dir, directory does not exist
exit status 1
```

Thanks.

**Comment by manishrjain** [comment]
Is `/tmp` present? It would create `badger` directory, but not recursively create all the parent directories.

**Comment by deepakjois** [comment]
Actually, we do not create the directory right now. But we should probably do that. So instead of changing the README to reflect the current behavior, we should just fix the code.

**Comment by sgon00** [comment]
yeah, `/tmp/` does exist for sure. I am running archlinux. I also tried `./badgerdb`. :)
