### ISSUE TITLE
optimize for hdd too

### ISSUE THREAD

**Issue by vtolstov** [dgraph-io/badger#319]
I'm read that badger is optimized for ssd, this is fine. But what about hdd?
I want to store data on hdd, and have hot writeback cache on ssd. So:
1) lsm is append data and create tombstone markers so i think for hdd it minimize seeks to? Or it have significant slowdown on hdd?
2) does it possible to add on evict event when ttl is expired?

**Comment by manishrjain** [comment]
You could serve LSM out of RAM, that way the LSM tree access would be super fast; and it would only need to reach out to disk once it has found the key. This should work well on HDD as well.

We do support TTL, you can see godocs for that.

**Comment by vtolstov** [comment]
TTL is fine, but when it expired it delete element. But i need on expire callback function. Does it possible?

**Comment by manishrjain** [comment]
No. We don't keep track of all keys actively. When we read a key, if it has expired, we just don't return it, skip it or error out depending upon context of the call.

**Comment by vtolstov** [comment]
ok, thanks
