### ISSUE TITLE
Roadmap worthwhile ?

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/badger#32]
I am wondering if this is going to be integrated into dgraph ?
Partly because I find dgraph awesome but also to see usage examples to get an idea of good approaches. I want to try out using go generate on top of this for some ideas.

I want to try this out and help improve it, so I was wondering if it's worth making a basic roadmap ? For example the WAL looks really interesting for doing data sync / reconciliation between many instances.

**Comment by manishrjain** [comment]
Yeah, it is going to be integrated with Dgraph.
https://github.com/dgraph-io/dgraph/pull/932

There's no particular roadmap for Badger. It already has all the APIs that it needs to have; we would just be improving performance and fixing bugs.

Not sure what you mean by data sync between instances.

**Comment by joeblew99** [comment]
thanks.
Regards data sync. Basically when you have many databases running in
different locations and you want to do data synchronisation between all of
them, the WAL helps allot because it contains the mutations, but also the
history of mutations. This is commonly used in a CQRS 7 kappa sytyle
architecture setup where the READS are all going to Materialised Views and
the WRITES are all going to the mutation WAL. When an event hits the
mutation log, you publish it on your message bus (or whatevr your using)
and the Materialised VIews (written in golang) can update themselves if
they are interested in the mutation. This gets you a type of DB that is
AOT. THere is no need for complex queries because they are at the end of
the days done AOT (ahead of time).
