### ISSUE TITLE
partially rewrite key value

### ISSUE THREAD

**Issue by vtolstov** [dgraph-io/badger#320]
Does it possible to partially rewrite key value?
For example value is about 4M-32M in size and i need to overwrite only data from offset 1024 to 4096 , does it possible to do that without read full key value, update it in memory and write?
If no, does it possible to access key value directly? To allow seek it and update partially?

**Comment by manishrjain** [comment]
Not something we currently do. It's something Badger could do, but this would add extra complexity, and I'm not sure how many users want a feature like this.

If we get a bunch of support for this, and complexity vs usage tradeoff makes sense, we could consider it.

**Comment by vtolstov** [comment]
Does it possible to determine file name in this case? So i'm directly read/write to it if i need?

**Comment by manishrjain** [comment]
Item struct in iterator.go contains the `vptr` which has the file id, and the offset etc. So, you could potentially write it there. But, do note that each key-value entry has a hash, which would be rendered invalid if you overwrite the value. We don't check the hash every time we do a read, but we check it when you replay logs.

You might want to fork Badger and implement this if you really need it.

**Comment by vtolstov** [comment]
ok.

**Comment by deepakjois** [comment]
Looks like this discussion is resolved for now. Closing this.
