### ISSUE TITLE
Get returns deleted key without errors

### ISSUE THREAD

**Issue by nikandfor** [dgraph-io/badger#321]
Is it a bug?
https://gist.github.com/nikandfor/137eb7990a048c8785d2b03c22a1f61a

**Comment by janardhan1993** [comment]
Thanks for reporting. I have merged the fix to master.

**Comment by manishrjain** [comment]
@janardhan1993 Can you also update the CHANGELOG.md. Sorry, I forgot to mention it earlier.

**Comment by janardhan1993** [comment]
Done.
