### ISSUE TITLE
Getting nil pointer when using txn.Get on db.View

### ISSUE THREAD

**Issue by MTRNord** [dgraph-io/badger#324]
Hi I get a nil pointer in https://github.com/dgraph-io/badger/blob/ed7c7f05a6e46b193469f5c604a2d2a3979fcc87/transaction.go#L460 I have a db opened with db.Open() and `SyncWrites = false`.

Looking at the doc my code should be correct as the nil pointer isn't because of my code isn't it?

**Comment by manishrjain** [comment]
Is your `db` object valid? I'd check that. I'd also check if `db.opt` was valid.

**Comment by MTRNord** [comment]
@manishrjain seems be the problem I used `sync.Once.Do()` for my DB opening and did not realise I open 2 databases with 1 `sync.Onc` variable :) (I will close this if I tested if fixing that fixes this problem)
