### ISSUE TITLE
assert triggered during GC collection after purging old versions

### ISSUE THREAD

**Issue by GlenDC** [dgraph-io/badger#327]
For http://github.com/zero-os/0-stor/ we make use of badger as the underlying storage, for which we thank you.

Currently we use badger version: bd9447c51360d3a3ca6c206be5bc2e42eba4c737 (vendored using golang/dep, on master branch).

For the project however we do not require any older versions and so prior to calling `RunValueLogGC` (which is done using a ticker of 10 minutes) we run `PurgeOlderVersions`. Our 0-stor server (which uses badger) has crashed during on of those calls however, while an engineer of ours was running the server for a test of his.

The full stack we received during that panic (triggered because of an assert in the badger transaction code):

```
INFO[2017-11-23T14:24:21+07:00] Space reserved : 0B                          
INFO[2017-11-23T14:24:21+07:00] Space available : 3.881GiB                   
INFO[2017-11-23T14:24:21+07:00] Server interface: grpc                       
INFO[2017-11-23T14:24:21+07:00] Server listening on [::]:12346               
2017/11/23 17:25:11 Assert failed
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/y.AssertTrue
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/y/error.go:55
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*oracle).decrRef
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:74
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*Txn).Discard
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:350
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*Txn).Commit
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:411
github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger.(*DB).Update
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/github.com/dgraph-io/badger/transaction.go:476
github.com/zero-os/0-stor/server/db/badger.BadgerDB.Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/db/badger/badger.go:61
github.com/zero-os/0-stor/server/db/badger.(*BadgerDB).Delete
        <autogenerated>:2
github.com/zero-os/0-stor/server/db.(*Object).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/db/object.go:270
github.com/zero-os/0-stor/server/manager.(*ObjectManager).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/manager/object.go:62
github.com/zero-os/0-stor/server.(*ObjectAPI).Delete
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/server/object_api.go:144
github.com/zero-os/0-stor/grpc_store._ObjectManager_Delete_Handler
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/grpc_store/store.pb.go:803
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).processUnaryRPC
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:781
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).handleStream
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:981
github.com/zero-os/0-stor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
        /home/ibk/pathgo/src/github.com/zero-os/0-stor/vendor/google.golang.org/grpc/server.go:551
runtime.goexit
        /home/ibk/go/src/runtime/asm_amd64.s:2197
```

Not sure if it's true, but from that stack I seem to think that for some reason the combination of:

+ Being in an update transaction which deletes a Key,
+ while at the same time cleaning the GC (after purging old keys),
+ seems to trigger this assert (because `len(o.commitMark) != 0`);

If we're abusing the badger API somehow, please do let me know.

The only thing we wish to achieve:

+ Collect the garbage at a regular interval in the background;
+ PurgeOldVersions as well, while collecting the garbage;

For this panic we also created an issue in our repo, which can be found at: https://github.com/zero-os/0-stor/issues/347

**Comment by GlenDC** [comment]
You can see how we use badger in https://github.com/zero-os/0-stor/blob/65060292f43a0c20a356f8c8b1e8004a14ba859f/server/db/badger/badger.go. Maybe that might give you a better clue in what might be (going)  wrong.

**Comment by GlenDC** [comment]
This is what our engineer was doing in his manual test when this panic/assert happened, in sequence and given order:

1. store value of 10 bytes;
2. store a file of 7 MiB in blocks of 4KiB:
  + Due to erasure encoding you do get more files than just 7MiB/4KiB;
  + Due to compression and encryption, you do not get values of exactly 4KiB;
3. Delete all those values once again;

It's during step 3 that the crash/panic/assert (of which I've given the call stack earlier) happened, once.

All steps happen in sequence, and currently also all tasks are done in sequence for each step. So the workload is extremely low I would think, compared to what you might be used to.

**Comment by janardhan1993** [comment]
Fixed in master

**Comment by GlenDC** [comment]
Thank you very much!
