### ISSUE TITLE
Fails to build on 32bit windows

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#331]
```
> GOOS=windows GOARCH=386 go build

# github.com/dgraph-io/badger/y
y/mmap_windows.go:70:12: constant 4294967295 overflows int
y/mmap_windows.go:70:12: array bound is too large
```

**Comment by deepakjois** [comment]
This diff makes it compile. However, I am not sure of anything beyond that. Do you have a 32-bit windows machine to try out the change and see if it doesn’t cause any other issues.

```diff
diff --git a/y/mmap_windows.go b/y/mmap_windows.go
index b81463e..dbc99b5 100644
--- a/y/mmap_windows.go
+++ b/y/mmap_windows.go
@@ -67,7 +67,7 @@ func Mmap(fd *os.File, write bool, size int64) ([]byte, error) {
                return nil, os.NewSyscallError("CloseHandle", err)
        }
 
-       data := (*[math.MaxUint32]byte)(unsafe.Pointer(addr))[:size]
+       data := (*[math.MaxInt32]byte)(unsafe.Pointer(addr))[:size]
        return data, nil
 }
```

**Comment by Stebalien** [comment]
Unfortunately, I don't. However, I believe a "more correct" fix is:

```go
diff --git a/y/mmap_windows.go b/y/mmap_windows.go
index b81463e..268bb74 100644
--- a/y/mmap_windows.go
+++ b/y/mmap_windows.go
@@ -20,7 +20,6 @@ package y
 
 import (
 	"fmt"
-	"math"
 	"os"
 	"syscall"
 	"unsafe"
@@ -67,7 +66,16 @@ func Mmap(fd *os.File, write bool, size int64) ([]byte, error) {
 		return nil, os.NewSyscallError("CloseHandle", err)
 	}
 
-	data := (*[math.MaxUint32]byte)(unsafe.Pointer(addr))[:size]
+	// Slice memory layout
+	var sl = struct {
+		addr uintptr
+		len  int
+		cap  int
+	}{addr, int(size), int(size)}
+
+	// Use unsafe to turn sl into a []byte.
+	data := *(*[]byte)(unsafe.Pointer(&sl))
+
 	return data, nil
 }
```

(stolen from the unix Mmap code).

**Comment by calvinchengx** [comment]
Will this be merged in soon or do I patch this on my own fork first?

**Comment by deepakjois** [comment]
@Stebalien You are probably right in that your fix is "more correct". However, I am not sure how it will affect behavior. I will make the changes you suggest in a branch and let the CI tests run. I don’t have any kind of Windows machine to test this right now, so I can only rely on AppVeyor.

@calvinchengx Are you actively using Badger on Windows 32-bit. Can you check if the fix by @Stebalien  works?

**Comment by Stebalien** [comment]
@deepakjois I've opened a PR to make testing easier.

**Comment by calvinchengx** [comment]
@deepakjois nope. I don't use windows. Am using this library in the context of another open source project and it's make file breaks when building for win32 arch.

**Comment by deepakjois** [comment]
@calvinchengx I just commited the fix to master. Hope that helps.
