### ISSUE TITLE
SetWithTTLAndMeta

### ISSUE THREAD

**Issue by genexp** [dgraph-io/badger#332]
Is there a public method exposed at the moment to set a value with both a TTL and Meta?  I don't see one, but it seems like something that would be common?

It seems like it would be possible...

https://github.com/dgraph-io/badger/blob/f3ac31901819eb7c111b7efcc6406f3a9bed6b11/transaction.go#L314

Thanks y'all!

**Comment by manishrjain** [comment]
We have a SetEntry method which we can expose if you need this functionality.

**Comment by deepakjois** [comment]
Fixed in 5bc2e1628ba2db7957ef4310d33393f964e5f3cc

I will cut a release in a bit.

**Comment by genexp** [comment]
Oh cool!  Thanks @manishrjain
