### ISSUE TITLE
SetEntry / Get

### ISSUE THREAD

**Issue by genexp** [dgraph-io/badger#335]
Hey @manishrjain What's the conceptual different at this point between Item and Entry.  

Now that we have a shiny new SetEntry, if you (for example) want to change a TTL or meta on an existing Item, you'll now GET an Item, convert the Item to an Entry, and then SetEntry.  Make sense?

**Comment by manishrjain** [comment]
That's the right flow. Item and Entry are two very different structs, despite them publicly giving access to the same info. Item gets stuff out of Badger and contains a lot of private information, while Entry is just a basic way to push stuff into Badger.

**Comment by genexp** [comment]
Thanks!
