### ISSUE TITLE
Option to not mmap value log files?

### ISSUE THREAD

**Issue by rjasonadams** [dgraph-io/badger#336]
Would it be possible to get an option added to not mmap the vlog files? Our values are quite large (~500KB) and each badger database will be around 12TB. I'm not sure if mmap will be an issue, but I have a feeling it will?

**Comment by manishrjain** [comment]
@deepakjois : This ties into our earlier discussions. I think many people have asked for this feature, where either the server is too small, or the data is too large. So, let's get the option to not mmap value log back, as you wanted to before.

**Comment by rjasonadams** [comment]
I'm not sure if it would kill performance, but another option may be to only mmap the file that is currently being written too and the others as they're read.

**Comment by manishrjain** [comment]
Reads directly off disk would still be pretty fast if done off SSD and with GOMAXPROCS set appropriately (recommended to 128). But, this could decrease the memory consumption of the mmap. It's best to test it out with existing settings, and then tweak if necessary.

It's going to be slow to map a file, read it and unmap it. Badger doesn't _need_ these files to be mmaped, we've just seen slightly better performance for larger values with it; so we had turned it on by default.

**Comment by deepakjois** [comment]
#341 is now merged. Please try setting the `ValueLogLoadingMode` option to `options.FileIO` and let us know how it goes. Closing this now.
