### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by mikegleasonjr** [dgraph-io/badger#34]
Hi is it normal Badger consumes 392mb in resident memory when my database holds 5mb of stuff?

Also, CPU looks quite high.

Thanks!

**Comment by manishrjain** [comment]
Depends. Badger does allocate certain chunks of memory upfront, irrespective of whether it's immediately used or not. It might be that. I haven't checked. Did you run a memory profiler to see what's consuming this memory -- it might help.

CPU: If nothing is going on, Badger won't consume much CPU. If you share your program, or a profile report, I could have a look.
