### ISSUE TITLE
Access to history of an item

### ISSUE THREAD

**Issue by romeovs** [dgraph-io/badger#343]
Not sure if this makes sense or if it is possible at all, but it can be convenient to have access to historical versions of an item so clients do not need to implement versioning theirselves. This would probably mean two things:

- Add a way to specify that versions need not be compacted or removed.
- Add API to access items at a specific version.

**Comment by peterstace** [comment]
Have you seen the [`ManagedDB`](https://godoc.org/github.com/dgraph-io/badger#ManagedDB) part of the Badger API? It allows you to access the previous states of items if you know the timestamp (user supplied) when they were created.

This API is a bit trickier to use than the main Badger API, but should do what you want.

**Comment by janardhan1993** [comment]
@romeovs : You can use iterator to fetch all versions of a key. You need to pass Allversions=true in iterator options.

If you would like to access items at specific version or want to remove items before a specific version you need to use 'ManagedDb' as peter suggested.

**Comment by peterstace** [comment]
I think this just about covers it. If this doesn't match well onto your use case, we can reopen this issue and continue the discussion.

**Comment by romeovs** [comment]
The `AllVersions=true` trick might work. Is there a way to force the database never to garbage collect old versions?

**Comment by gpahal** [comment]
This is the default behavior. It won't gc all the versions.

**Comment by deepakjois** [comment]
@romeovs Just to add to what others have said, older versions are not GC collected automatically. They will need to be purged first, by calling `DB.PurgeOlderVersions()` or `DB.PurgeVersionsBelow()`.
