### ISSUE TITLE
the item view not timestamp?

### ISSUE THREAD

**Issue by RyouZhang** [dgraph-io/badger#344]
when I use item.Version() get the item version, I find it likes 56, 57,58... not timestamp?
and when i call PurgeOlderVersions and RunValueLogGC(0.5), i get Value log GC attempt didn't result in any cleanup

**Comment by janardhan1993** [comment]
The timestamp used by transactions internally is just a incrementing counter and has no relation to the system time.
Badger couldn't find a file which has 50% or more entries which could be discarded.  Probably you don't have enough data which needs to be garbage collected or your data which needs to be garbage collected is uniformly spread across value log files in which case you can use a lesser threshold. It's difficult to say without knowing your workload.

**Comment by RyouZhang** [comment]
my test like this:
	for j := 0; j < 100; j++ {
		db.Update(func(txn *badger.Txn) error {
			for i:=0; i<100000; i++ {
				txn.Set([]byte(fmt.Sprintf("A_%d", i)),[]byte("....16kb...."))
			}
			return nil
		})
	}
i think last the item version is 100, i have 99 old version
some time RunValueLogGC(0.5) work, but the old vlog file not be delete
