### ISSUE TITLE
Not enough Documentation #MemoryUsage

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/badger#356]
I am running my app on DigitalOcean server with 1GB RAM Server and I got the error:-  `Unable to mmap RDWR logfile`, further googling asks me to follow the URL: https://github.com/dgraph-io/badger#memory-usage

I see some of the options that are to be set to work under LOW GB RAM server, but there is not enough information on what sort of values are set.

**Update**: I am looking into file : https://github.com/dgraph-io/badger/blob/38e50f1855596d8c69a9b9eb37ee791f42a0353e/options.go

**Comment by deepakjois** [comment]
@rebootcode Badger tries to mmap a 2Gb segment of memory for each value log when it starts up. Running it on a 1GB server may be causing an issue.

We just pushed a change yesterday which allows you to change the loading mode of value log files from mmap, to using standard file I/O. That might help in your case. If you use the latest Badger from master, try setting the `ValueLogLoadingMode` to `options.FileIO` and let us know if you are still facing issues.

Regarding the documentation, we will try and improve by adding more detail. We should also be mentioning the `ValueLogLoadingMode` option too.

**Comment by rebootcode** [comment]
I did `go get .....badger` half an hour before, so, I assume, it is the latest version. Below is the code, I am using :- 

```
opts := badger.DefaultOptions
	opts.Dir = "./data"
	opts.ValueDir = "./data"
	db, err := badger.Open(opts)
	if err != nil {
		panic(err)
	}
```
I did changes as per your statement:- 

imported `"github.com/dgraph-io/badger/options"`

and added

`opts.ValueLogLoadingMode = options.FileIO`

It seems to work, Will update after few testing, just in case anything looks weird.

Thanks for the support
