### ISSUE TITLE
Question: get key count in range?

### ISSUE THREAD

**Issue by dvsekhvalnov** [dgraph-io/badger#361]
Hi,

another question, is it feasible to get number of keys between 2 key values?

E.g. let's say we have startTimestamp and endTimestamp as a key, is there is way to get count of keys in-between without iteration through all of them?

Thank you.

**Comment by peterstace** [comment]
At the moment you will just have to iterate over the keys and count as you go.

You can see the iterator options such that the values aren't pre-fetched, which will speed things up a bit.

**Comment by manishrjain** [comment]
Key-only iteration is blazingly fast -- so I doubt you need anything more in terms of counting keys. Let us know if the speed isn't sufficient for some reason.

**Comment by dvsekhvalnov** [comment]
Yeah, that's what we basically doing right now. In average key-only iteration gives us about ~1.6mln keys per sec on current hardware. Which is fine.

I'm more curious about capabilities. Fror scenarios with deep paging and when not using offsets (e.g. next page key), skipping first 1mln rows sounds like waste. While getting overall results count is always nice.

Thanks for answer.

**Comment by manishrjain** [comment]
To precompute counts is tricky. Because based on the read timestamp and iterator settings, some key versions might be skipped or might be overridden by something newer in upper levels of the LSM tree, etc. You can't get accurate counts, without iterating.

**Comment by dvsekhvalnov** [comment]
Ah, interesting point about versions, i see.

That's what we do for pagination usually, returning `offset` (last known key) to client. But sometimes client can lost session and have only `page` number. To give an example - copyable urls, where you send link to somebody. Usually it will not contains `offset` string.
