### ISSUE TITLE
multiple instance for multiple directory ?

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/badger#366]
Is it possible to create multiple instances for storing a variety of data in multiple directories. I want to store "blog" data in blog folder, "user" data in user folder and so forth.

It's like creating multiple buckets for different types of data. I know, there is prefix option to separate between data, but it complicates thing when we need to do lots of mass changes.

Having multiple buckets for the different column will simplify thing, just like a new table creating in RDBMS.

**Comment by deepakjois** [comment]
The only way to do what you are asking for, is to have two _independent_ Badger databases in two different directories.

It is possible to write some code on top of badger which will manage these independent databases for you, for e.g.

```Go
type BlogDB struct {
    blog *DB
   users *DB
}

func (blogdb *BlogDB) AddPost(…) {
   //…
}
```

 but you can never have any sort of ACID guarantees on concurrent reads/writes that spans multiple DBs. Transactions on these databases execute independent of each other.
