### ISSUE TITLE
Value log GC to rewrite file in-place

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#367]
We currently append valid entries to latest log, and then discard the older log file. This causes us to rewrite these keys back into the LSM tree, but with older versions -- which causes us to have to look through the entire LSM tree for every key lookup (which affects read latency).

Instead, we can add an index at the end of the value log file, which has entry id -> file offset. And as we discard entries, we can rewrite the file (logically) in-place to change this id -> file offset mapping. This way, the entries wouldn't need to be rewritten in the LSM tree; avoiding older versions to show up at the top of the LSM tree.

The file size thus would keep dropping, and eventually become zero.

**Comment by manishrjain** [comment]
Similarly, PurgeVersionsBelow should not modify the LSM tree. Instead, it should just set a key -> version entry, which can be used during value log GC.

In other words, there should be no case, where an older version should be written to the LSM tree. The versions should always increase monotonically.

**Comment by janardhan1993** [comment]
I have started working on the purge part first. Purge will write a new key which would be used during GC.

**Comment by manishrjain** [comment]
Okay. I'll work on the VC log in-place rewrite.

**Comment by rjasonadams** [comment]
>The file size thus would keep dropping, and eventually become zero.

Over time wouldn't this create many small files (bad for the filesystem)? An option to rewrite the vlog file after it falls below a certain size could make sense.

**Comment by manishrjain** [comment]
We dropped this idea. Instead, we now punch holes in value log files.
