### ISSUE TITLE
Better error handling for background goroutines

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#368]
Right now, when we have a background goroutines performing tasks like compactions, merge operations etc. and they encounter an error, we log an error and keep going. It would be good to come up with a better pattern to handle these errors.

One idea that came up is to have a sort of pattern where we send an error on a channel, to a goroutine on the other end which can make a better decision around handling errors.

**Comment by briansorahan** [comment]
I typically use golang.org/x/sync/errgroup to run an arbitrary number of goroutines.  IMO packages should favor blocking calls over channels: e.g. the Wait method on errgroup

**Comment by campoy** [comment]
Hey @deepakjois could you tell me more about what kind of error checking you need to do and how you imagine doing it?

We have the opportunity of changing some APIs while we release v2, so I'd like to consider any improvements.

**Comment by deepakjois** [comment]
This issue is outdated now. The code has changed too significantly for this issue to be tracked meaningfully.
