### ISSUE TITLE
Backup API improvements

### ISSUE THREAD

**Issue by mperham** [dgraph-io/badger#370]
Today, the Backup() API is rather low-level.  It would be nice if Badger exposed a higher-level BackupEngine API like RocksDB which handles multiple incremental backups and combines them into a single RestoreFromLatestBackup() call.

Ideally I can use the API to easily create an hourly incremental backup with a daily full backup.

https://godoc.org/github.com/tecbot/gorocksdb#pkg-index

**Comment by bjzhang** [comment]
Hi,
Is there anyone working on this?

After read the [gorocksdb api]( https://godoc.org/github.com/tecbot/gorocksdb#BackupEngine) and [rocksdb documents](https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F#under-the-hood). I found that it is what we need. I want to pick this task. And I will do the following in detail:
1.  Add the api in `type BackupEnginefunc` in gorocksdb, including:
    *   `OpenBackupEngine(opts *Options, path string) (*BackupEngine, error)`
    *   `func (b *BackupEngine) Close()，func (b *BackupEngine) CreateNewBackup(db *DB) error`
    *   `func (b *BackupEngine) GetInfo() *BackupEngineInfo`
    *   `func (b *BackupEngine) RestoreDBFromLatestBackup(dbDir, ro *RestoreOptions) error`
2.  I will investigate and discuss the implementation later. And generally speaking, I will reference the design of rocksdb.
    1.  Disabling file delete during backup. So, it will not block the compaction. Badger will delete the file after backup. The user could sync the deleted and newly added sst files in further incremental backup.
    2.  There might be some differences because of the vlog in badgerIO. I am not sure which is the better way to do it. Considering gc is triggered by user. For an initial implementation, I suggest only backup when gc exit. And a live backup will block further gc. User should check this before issuing gc. When user issue a incremental backup, copy the latest vlog and mark the deling of the old one.

Thanks

**Comment by manishrjain** [comment]
I don't see the need to open the DB in a specific way with `OpenBackupEngine` to backup the DB. You can just use a view-only transaction, which can iterate over the entire DB to back it up. In fact, we have functions to that effect.

To restore a backup, the right thing to do would be to build a tool, which can create a fresh Badger instance, picking up the data from multiple backup files.

Most of the APIs are already there, we just need to package them up in a nicer way.

**Comment by campoy** [comment]
Hey @martinmr and @manishrjain,

Is this something that StreamWriter allows us to do easily?
If not, should this issue be kept open?

**Comment by campoy** [comment]
Hey @martinmr,

Please answer my question above.

**Comment by martinmr** [comment]
The stream writer is used to create the backups but not to restore them. For that the Load function in backup.go is used.

Like @manishrjain said, all the tools to be able to do this are already there.

* Incremental backups can already be done.
* Loading a single backup can already be done.

Seems like we could exted the existing restore command to allow multiple files to be restored. This would provide something like what is being asked.

**Comment by campoy** [comment]
Thanks, @martinmr!

According to this, @mperham you should be able to backup all of your data by using [Stream Writer](https://godoc.org/github.com/dgraph-io/badger#DB.NewStreamWriter) first and then load all values into a new instance very quickly with [Load](https://godoc.org/github.com/dgraph-io/badger#DB.Load).

Feel free to reopen this issue if this answer is not satisfactory or you have any other concerns.

**Comment by manishrjain** [comment]
Sorry, didn't see me getting tagged. But, yeah, we do already have backup and restore tools. This issue would have to be more specific about what is needed beyond them.
