### ISSUE TITLE
Can badger open database in readonly mode without locking?

### ISSUE THREAD

**Issue by vrealzhou** [dgraph-io/badger#372]
Is it possible to add option to open database in readonly mode which no need to lock the database? It could share the database between different read only processes?

**Comment by deepakjois** [comment]
I don’t believe this is possible without a major design change, that will affect multiple layers in the code. So I am not sure if this is something we will look into actively.

**Comment by ivanjaros** [comment]
I just did a blocking test and seems badger does not block readers and writers so you could utilize multiple readers and to avoid writes, add api layer on top of badger.

**Comment by manishrjain** [comment]
This can be done -- would essentially need to avoid doing the lock on DB, and modify the scope of APIs a bit. I don't know how much demand is there for this feature. If we get 5-10 thumbs-up on the top post, we can build this.

**Comment by manishrjain** [comment]
The PR which adds this functionality is merged.
