### ISSUE TITLE
Merge scalability

### ISSUE THREAD

**Issue by mperham** [dgraph-io/badger#373]
Right now the merge operator creates a goroutine and ticker for every key that uses merge.  If I have thousands of statistics keys, some of which are dynamically generated, this doesn't work.

Ideally I could say "create a merge operator for all keys with prefix `xyz`".  The associated goroutine would scan the keyspace every N seconds for all new versions of those prefixes to merge.

Also ideally: if I Get() the value for a key that uses merge, any pending values would be merged so the value returned would be up-to-date.  I would be happy to call a different API to fetch these keys, e.g. `MergeGet(key)`.

WDYT?

**Comment by deepakjois** [comment]
I do concede that the merge feature, as it is designed currently is not ideal for your use case. It may not be too difficult to modify the merge feature to operate on a prefix, instead of a specific key. I could look into it.

@manishrjain Do you have any thoughts around this?

**Comment by manishrjain** [comment]
The basic idea here of using a prefix based goroutine makes sense. I'll see if I have some cycles to work on it, and if it can be done effectively.

**Comment by campoy** [comment]
Hey @manishrjain,

Should this be downgraded to a lower priority? There's no update since Feb 2018
