### ISSUE TITLE
File id limit

### ISSUE THREAD

**Issue by pydima** [dgraph-io/badger#376]
Hello. I've found in the code the following line: https://github.com/dgraph-io/badger/blob/a05762747bf83bc4633e80d48ed4c468cccf8099/value.go#L728
you check here that file id doesn't overflow uint16. But I don't see any id rotation mechanism or something. So it looks to me that if I have long living db, that created 65536 files, badger will stop working at this point. Is it correct? Thank you.

**Comment by janardhan1993** [comment]
@pydima The size of each value log file is 1gb, so uint16 would give us about 65TB of data. We choose uint16 thinking it should be sufficient for most of the workloads.

**Comment by manishrjain** [comment]
Actually, @janardhan1993 I remember we switched it to uint32. The surrounding code is using uint32. And it's possible that the assert got left behind? Maybe read through it again just to verify.

**Comment by janardhan1993** [comment]
It's uint32, i will change the assert.

**Comment by janardhan1993** [comment]
@pydima : The limit was changed to uint32 but the assert remained, i have updated it to check for maxuint32 now.

**Comment by pydima** [comment]
Ok, thanks for the information. But as far as I understand 65TB of data is the write limit not data limit. I mean let's imagine that I'd use it for message queue system, I'd have a lot of data writes, that would be latter GC'ed but when I write 65TB of data my application will stop working, because it reached the max number of files, however at this point I might have only let's say 5 value log files and 5gb of data, and my old data were GC'ed. So it's basically mean that this limit will stop working at some point, the question is when and it completely depends on amount of data written, not amount of data stored. Do I miss something? Is it intentional behaviour? Should application that use badger care about that? Thanks.

**Comment by janardhan1993** [comment]
we changed the limit to uint32 which allows upto 42949672955GB , the assert was not updated after changing the id from uint16 to uint32.

**Comment by pydima** [comment]
OK, got it, it's intentional. Thanks for answering.
P.s. To be precise the limit now is 999999GB, since you use 6 digits in filenames.

**Comment by manishrjain** [comment]
6 digits are for padding. There's no limitation on the number used as the filename.

**Comment by deepakjois** [comment]
It appears the query is resolved. Closing, but pls re-open if there is any more related questions.
