### ISSUE TITLE
How to use badger without Persistent ? only in ":memory:"

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/badger#377]
I want to use `badgerdb` for chat application with `multiple room` options. I want to store all chat in badgerdb, I want to ask the badgerdb team, is `badgerdb` right choice for chat message app? 

Also, as stated in example `README` file, it stores code in same file, but I want to store them in memory without persistence.

```
opts := badger.DefaultOptions
  opts.Dir = "/tmp/badger"
  opts.ValueDir = "/tmp/badger"
  db, err := badger.Open(opts)
```

Is there any option, where we can set option to store data in ":memory:" and not in `file`.

**Comment by janardhan1993** [comment]
@rebootcode Badger is designed to support high throughput writes and reads with persistence in mind. If you want to store the data in memory without persistence you might want to look for other alternatives. 
Else you can also try badger with sync writes set to false in option, it would give you better performance and also persist the data in async way.

**Comment by manishrjain** [comment]
You could also use tmpfs to store data. That would give you fast storage.

**Comment by rebootcode** [comment]
@janardhan1993 and @manishrjain - I would like to verify below settings as recommended above :-

```
opts := badger.DefaultOptions
opts.Dir = "/tmp/badger"   // tmp directory as recommended
opts.ValueDir = "/tmp/badger"
opts.SyncWrites = false   // sync write to false as recommended
db, err := badger.Open(opts)
```

Thanks

**Comment by janardhan1993** [comment]
Looks good.

**Comment by shazow** [comment]
One handy reason to support in-memory storage (or something like a memory-backed os.FS) is that it makes writing tests with throw-away data much more convenient without thrashing the disk unnecessarily. :)

**Comment by manishrjain** [comment]
You can set `TableLoadingMode = options.LoadToRAM`, which would still give you the durability, without compromising on read performance. I'd also recommend using LSMOnlyOption (instead of Default), and setting `ValueLogLoadingMode` to at least options.MemoryMap (or even options.LoadToRAM if you have the memory available for it).

**Comment by shazow** [comment]
@manishrjain thanks for the tip!

**Comment by auror** [comment]
I'm using the latest version of badger this way

```
db, err := bv3.Open(bv3.DefaultOptions("/tmp/badger"))
if err != nil {
panic(err)
}
```

and loading 10M keys. Key is 0-10M integer and value is 25bytes long. I believe badger persists on disk async but the RAM usage of the idle golang application is dancing b/w 250 MB - 500 MB. Why's the memory so high ? is it not persisting the data to disk & instead storing data in DRAM ? Or am I missing any other setting in Badger?
