### ISSUE TITLE
ErrKeyNotFound when running multiple async write->read jobs

### ISSUE THREAD

**Issue by GlenDC** [dgraph-io/badger#380]
Badger seems to have a bug, where when writing and reading from many goroutines at the same time, the data is not immediately available.

This bug is still valid on latest master: commit 0225b784d8dfc250b3be597fa806f0fd677a6628

The procedure to reproduce this issue all one have to do is:

+ create a badger db with default options;
+ spawn x amount of goroutines (how high x needs to be depends on the CPU of the host);
+ on each goroutine do:
   + first set some random data on a unique key using `db.Update`;
   + then get that random data using that same key using `db.View`;

You'll notice that for some goroutines, the key won't be available in the second step (getting the data back). This is unexpected as by then the `db.Update` operation already finished successfully, and thus it should be available.

I noticed this bug for the first time two weeks ago, and I've since then talked about it with the badger team on Slack. I was then told that this does indeed sound like a bug, and that I should try to create an example to easily reproduce this. It took me a while, as I had many other things to do, but here is an example that you can easily run locally to reproduce the bug 100%* of the time:

```go
package main

import (
	"bytes"
	"crypto/rand"
	"fmt"
	"io/ioutil"
	"os"
	"path"
	"sync"

	"github.com/dgraph-io/badger"
)

func main() {
	db, cleanup := openBadger()
	defer cleanup()

	const (
		jobs     = 1024 * 16
		dataSize = 32
	)

	var wg sync.WaitGroup
	wg.Add(jobs)
	for i := 0; i < jobs; i++ {
		i := i
		go func() {
			defer wg.Done()

			key := []byte(fmt.Sprintf("key#%d", i))
			input := make([]byte, dataSize)
			rand.Read(input)

			// write value
			panicOnError(db.Update(func(txn *badger.Txn) error {
				err := txn.Set(key, input)
				if err != nil {
					return fmt.Errorf("write error for job #%d: %v", i, err)
				}
				return nil
			}))

			// read value
			panicOnError(db.View(func(txn *badger.Txn) error {
				item, err := txn.Get(key)
				if err != nil {
					return fmt.Errorf("read error for job #%d: %v", i, err)
				}
				if outKey := item.Key(); bytes.Compare(key, outKey) != 0 {
					return fmt.Errorf("key not equal: %q != %q",
						key, outKey)
				}
				output, err := item.Value()
				if err != nil {
					return err
				}
				if bytes.Compare(input, output) != 0 {
					return fmt.Errorf("data not equal: %q != %q",
						input, output)
				}
				return nil
			}))
		}()
	}
	wg.Wait()
}

func openBadger() (*badger.DB, func()) {
	tmpDir, err := ioutil.TempDir("", "badger")
	panicOnError(err)

	opts := badger.DefaultOptions
	opts.Dir = path.Join(tmpDir, "data")
	opts.ValueDir = path.Join(tmpDir, "meta")

	db, err := badger.Open(opts)
	if err != nil {
		os.RemoveAll(tmpDir)
		panic(err)
	}

	cleanup := func() {
		db.Close()
		panicOnError(os.RemoveAll(tmpDir))
	}
	return db, cleanup
}

func panicOnError(err error) {
	if err != nil {
		panic(err)
	}
}
```

When running it you should receive a panic similar to the following example panic:

```
panic: read error for job #474: Key not found

goroutine 527 [running]:
main.panicOnError(0x15b3cc0, 0xc420011d10)
	badger_async_issue.go:92 +0x4a
main.main.func1(0xc42001a1f0, 0x1da, 0xc420128000)
	badger_async_issue.go:45 +0x2f5
created by main.main
	badger_async_issue.go:28 +0xa9
exit status 2
```

---

(*) You might need to increase the "`jobs = 1024 * 16`" constant, in case you have a much faster machine then my old MBP laptop of 2015.

I put the constant very high so it triggers the bug 100% of the time, but even when you only have like 64 jobs it seems to trigger, at least it does so in a similar scenario, as triggered from a unit test in the travis CI environment, for one of our project (http://github.com/zero-os/0-stor).

**Comment by Asarew** [comment]
I encountered the exact same issue a couple of weeks ago, but instead of calling `tnx.Get()` I iterated over the keys and saw a very consisted drop in keys. after some quick testing i found out that on average was loosing `99.730%` of the ~35000 key that i wrote into badger.

**Comment by janardhan1993** [comment]
Fixed in master. @GlenDC I verified using your program, i was able to reproduce the issue before the fix, now it works fine.

**Comment by GlenDC** [comment]
Thank you very much @janardhan1993, I can confirm that our unit tests do indeed pass now. My example program runs locally fine as well now.

**Comment by Asarew** [comment]
Same here! thnx for the quick fix @janardhan1993 <3
