### ISSUE TITLE
Implement sql layer

### ISSUE THREAD

**Issue by alvarolm** [dgraph-io/badger#381]
Would be very useful to port an existing sql layer to interpret sql querys, like cockroachdb, https://www.cockroachlabs.com/docs/stable/architecture/sql-layer.html

this could potentially help badger gain ever more traction and open new opportunities for porting into existing projects that already use sql.

**Comment by deepakjois** [comment]
Our goal is to keep Badger as simple as possible. So it is unlikely we will take this on. I suppose an SQL layer can be implemented on top of Badger if required, as a separate package.

**Comment by ivanjaros** [comment]
Yeah, I totally need some library I could put on top of Badger to work with structured data.
I didn' find anything so I started to write my own but I haven't even finished SELECT query and I want to hand myself :D

Has the situation evolved, are there any libraries that do this that I am not aware of?

https://github.com/ivanjaros/mrvkio/blob/master/components/database/badger.go

**Comment by alvarolm** [comment]
@ivanjaros https://github.com/araddon/qlbridge
Could be very usefull
