### ISSUE TITLE
Badger deadlocks for me

### ISSUE THREAD

**Issue by fingon** [dgraph-io/badger#384]
When doing heavy I/O (e.g. ~100+MB/s writes in relatively large transactions, consisting of small keys + values in 100b-64kb range) Badger seems to die at few gigabyte mark for me consistently. 

The app in question uses Badger only from two goroutines at a time, and I am taking care to have mutex enforce only one client at a time uses it. The 'commit' stage (in which it does bulk set/deletes) blows up pretty rapidly.

If I turn on enough debugging elsewhere in the app, this does not happen, which indicates that large transaction size (and-or plenty of transactions per second) seems to be the culprit. I have rather ugly err = ErrTxnTooBig => commit + retry mechanism, but that does not seem to be even involved here.

Relevant goroutines (I believe) from SIGABRT - the first one is only my goroutine, and it seems to be stalled for good in Badger txn.Commit:

goroutine 114 [semacquire]:
sync.runtime_Semacquire(0xc428f6e85c)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc428f6e850)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/waitgroup.go:131 +0x72
github.com/dgraph-io/badger.(*request).Wait(0xc428f6e820, 0x14cde80, 0xc42007e3c0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc42583a090, 0x0, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/transaction.go:474 +0x6b0
github.com/fingon/go-tfhfs/storage.(*BadgerBlockBackend).commit(0xc420106ba0)
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/storage/badger.go:144 +0x3c
github.com/fingon/go-tfhfs/storage.(*BadgerBlockBackend).SetInFlush(0xc420106ba0, 0x0)
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/storage/badger.go:138 +0x1c2
github.com/fingon/go-tfhfs/storage.(*Storage).Flush(0xc4254e2070, 0x4221)
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/storage/storage.go:171 +0xa4a
github.com/fingon/go-tfhfs/fs.(*Fs).Flush(0xc4200c00a0, 0x0)
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/fs/fs.go:76 +0xa5
github.com/fingon/go-tfhfs/fs.(*fsOps).Flush(0xc4200c00d0, 0x0, 0xc4257a4480)
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/fs/ops.go:614 +0x4a
github.com/hanwen/go-fuse/fuse.(*lockingRawFileSystem).Flush(0xc4254de160, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/hanwen/go-fuse/fuse/lockingfs.go:174 +0x63
github.com/fingon/go-tfhfs/fs.(*fsOps).Init.func1()
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/fs/ops.go:38 +0x5d
created by github.com/fingon/go-tfhfs/fs.(*fsOps).Init
	/Users/mstenber/go/src/github.com/fingon/go-tfhfs/fs/ops.go:42 +0x8b

goroutine 5 [select]:
github.com/dgraph-io/badger.(*DB).updateSize(0xc420152000, 0xc420106ca0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:882 +0x16a
created by github.com/dgraph-io/badger.Open
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:251 +0xa36

goroutine 103 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4254e2000, 0xc42000c220)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:187 +0x1e2
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:172 +0x82
``
goroutine 104 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4254e2000, 0xc42000c220)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:187 +0x1e2
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:172 +0x82

goroutine 105 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc4254e2000, 0xc42000c220)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:187 +0x1e2
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/Users/mstenber/go/src/github.com/dgraph-io/badger/levels.go:172 +0x82

goroutine 106 [chan receive, 1 minutes]:
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc420152000, 0xc42000c240, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:764 +0xfa
created by github.com/dgraph-io/badger.Open
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:263 +0xbd4

goroutine 108 [select]:
github.com/dgraph-io/badger.(*DB).doWrites(0xc420152000, 0xc4254de120)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:630 +0x47a
created by github.com/dgraph-io/badger.Open
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:307 +0x1073

goroutine 109 [chan receive, 1 minutes]:
github.com/dgraph-io/badger.(*valueLog).waitOnGC(0xc420152130, 0xc4254de140)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:1030 +0x61
created by github.com/dgraph-io/badger.Open
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:310 +0x10d9

goroutine 16283 [semacquire]:
sync.runtime_Semacquire(0xc42550a0d8)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).Lock(0xc42550a0d0)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/rwmutex.go:98 +0x6e
github.com/dgraph-io/badger.(*logFile).doneWriting(0xc42550a0c0, 0x400001e4, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:155 +0x89
github.com/dgraph-io/badger.(*valueLog).write.func1(0xc429cccb90, 0xc420152130)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:731 +0x2bb
github.com/dgraph-io/badger.(*valueLog).write(0xc420152130, 0xc4336e5360, 0x1, 0xa, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:769 +0x27a
github.com/dgraph-io/badger.(*DB).writeRequests(0xc420152000, 0xc4336e5360, 0x1, 0xa, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:555 +0x118
github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc4336e5360, 0x1, 0xa)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:617 +0x55
created by github.com/dgraph-io/badger.(*DB).doWrites
	/Users/mstenber/go/src/github.com/dgraph-io/badger/db.go:666 +0x342

**Comment by fingon** [comment]
This might be actually OS X oddity too, it seems as if OS X misbehaves somehow some of the time (I managed to do same without Badger once already). I'll reopen if I manage to get some small sample that reproduces this.

**Comment by fingon** [comment]
Unable to come up with small sample, but the issue I thought was the same was not in the end. So this is something that occurs only with Badger. It seems to wind up in that particular backtrace and never get out:

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0xc42c3c0d0c)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc42c3c0d00)
	/usr/local/Cellar/go/1.9.2/libexec/src/sync/waitgroup.go:131 +0x72
github.com/dgraph-io/badger.(*request).Wait(0xc42c3c0cd0, 0x14d17d8, 0xc42007e3c0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc43abc1e60, 0x0, 0x0, 0x0)
	/Users/mstenber/go/src/github.com/dgraph-io/badger/transaction.go:474 +0x6b0
^ your code starts here.

Any suggestions on how to create smaller example / debug what is going on?

**Comment by manishrjain** [comment]
Sometimes things like these can be tracked down to a variable which was used out of scope. So, if you can show your code which causes this behavior, we could have a look.

**Comment by fingon** [comment]
https://github.com/fingon/go-tfhfs/blob/master/storage/badger.go is the code that blows up. Similar bbolt backend ( https://github.com/fingon/go-tfhfs/blob/master/storage/bolt.go ) and raw filesystem backend ( https://github.com/fingon/go-tfhfs/blob/master/storage/file.go ) work fine so the surrounding code is most likely ok, and the code that actually writes to db is single-threaded.

**Comment by fingon** [comment]
It locks up invariably in the commit() method when SetInFlush(false) is called (= view switches to read-only use). All that one does is just call badger.Txn.Commit().

**Comment by janardhan1993** [comment]
@fingon I took a quick look through your code, when you get errTxnToobig you are commiting the txn and creating a new txn but you forgot to call discard() on old transaction.

**Comment by fingon** [comment]
The clients that use that API do their own copying (and much sooner than long-lived transaction is gone) so it is probably ok. I added missing discard, but it did not fix the issue. ~gigabyte or two in and it stalls, it does not stall if I e.g. start it under race detector (no races detected but I guess it alters the goroutine scheduling or something).

**Comment by fingon** [comment]
similarly adding log.Print's or something causes it to last longer or possibly even indefinitely; the ~100MB, ~10-20k sets/second kills it very fast. I am batching the sets so basically slamming those 10-20k sets in at once per second, with retried transactions when toobig error shows up.

**Comment by fingon** [comment]
Closing this, as switching to smaller transactions it went away. No idea if it is Badger bug or not, but now it works 100% fine for me.
