### ISSUE TITLE
any plan to support snapshot?

### ISSUE THREAD

**Issue by siddontang** [dgraph-io/badger#39]
Hi

I am very glad to see this project and want to try it on my own project. I need the snapshot feature to dump the database concurrently but now Badger misses it, do you have any plan to support this? 

Thanks 😄

**Comment by manishrjain** [comment]
We can add a way to dump the database really fast concurrently. But, it won't be a snapshot in the true sense. The store won't be frozen in time; so as the iterator moves, it would pick up the latest value for the key.

We don't have plans to add any versioning which would be required to do snapshots.

**Comment by siddontang** [comment]
Got it, thanks.

**Comment by boolean5** [comment]
Hello, 
Is there an estimation regarding how soon the feature to dump the db concurrently might be added?

**Comment by manishrjain** [comment]
No one asked for it, so we didn't build it. We could. Feel free to create a separate issue.

**Comment by manishrjain** [comment]
With transactions, Badger can now do snapshots. @siddontang @boolean5

**Comment by siddontang** [comment]
Great news, I will try it later in LedisDB.

**Comment by Xeoncross** [comment]
@siddontang still have any plans to add badger to LedisDB?
