### ISSUE TITLE
Badger UI

### ISSUE THREAD

**Issue by ivanjaros** [dgraph-io/badger#394]
Hi,
is there a UI library(cli/web/...) for browsing the contents like there is for BoltDB?

**Comment by pawanrawal** [comment]
Hey @ivanjaros. We don't have any UI library to browse the contents.

**Comment by sneko** [comment]
@pawanrawal did you do internal progress to debug Badger with any type of UI? Thanks

**Comment by JohannesHoppe** [comment]
Are there plans to change this or is there a community project for this? A graphical interface is a basic tool that you would expect with any database!!

**Comment by mangalaman93** [comment]
badger is an implementation of the LSM tree data structure and an embedded database. Dgraph on the other hand, has a graphical interface to use if you want to check it out.
