### ISSUE TITLE
Sequence keys

### ISSUE THREAD

**Issue by ivanjaros** [dgraph-io/badger#395]
I have a need for sequenced keys, ie. auto-increment(I want to only append records). Is there such option? In the readme the "sequence block" is mentioned but I don't think that is what I'm looking for. Is there such option?

**Comment by pawanrawal** [comment]
Hey @ivanjaros 

You could get a sequence number using https://github.com/dgraph-io/badger#monotonically-increasing-integers, add your own prefix to it and store that as the key.

**Comment by ivanjaros** [comment]
Hm I guess I'd rather use timestamps. This seems complicated.

**Comment by ivanjaros** [comment]
If anybody's interested, I have used https://github.com/segmentio/ksuid and Badger uses natsort for keys so you can achieve a correct order(ie. sorted by the time the record was created).
