### ISSUE TITLE
Invalid value pointer offset

### ISSUE THREAD

**Issue by jackmcgary** [dgraph-io/badger#397]
I'm writing a bunch of values with:
```
db.Update(func(txn *badger.Txn) error {
  err = txn.Set([]byte("key1234"), data)
  return err
})
```
Then a moment later I'm trying to pull them back out:
```
db.View(func(txn *badger.Txn) error {
  opts := badger.DefaultIteratorOptions
  it := txn.NewIterator(opts)
  prefix := []byte("key")
  for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
    item := it.Item()
    v, err := item.Value()
  }
})
```
When I try to read the value it errors out:
`Invalid value pointer offset: 1550993 greater than current offset: 1531447`

Am I missing something here? Thx.

**Comment by manishrjain** [comment]
Shouldn't be happening. Can you please create a working example which can show this problem?
