### ISSUE TITLE
Q: Iterator ordering guarantee

### ISSUE THREAD

**Issue by ivanjaros** [dgraph-io/badger#398]
Hi,
if I only append new records(ie. key is never duplicated), does Badger guarantee proper(time-based) ordering of records in the same order they were written?

_I am using https://github.com/segmentio/ksuid for keys_

**Comment by deepakjois** [comment]
The iterator has a guaranteed order, but it isnt ‘time-based’. It is based on the lexicographically sorted order of the byte value of the keys.

A cursory reading of the ksuid docs suggest that they are lexicographically sorted: https://github.com/segmentio/ksuid#3-lexographically-sortable-portable-representations

Does that answer your question?
