### ISSUE TITLE
Feature Request: Setting Total DB Size Limit

### ISSUE THREAD

**Issue by notbdu** [dgraph-io/badger#399]
Any plans on allowing clients to set a total db size limit?

Currently, in order to maintain an upper limit on DB size, I would have to track the size of badger and expire out the oldest data explicitly in a loop. This is best effort and makes it impossible to guarantee a size limit. 

Additionally, after reviewing `doRunGC`, it looks like a value log rewrite is triggered based on a threshold level of expired keys. Ideally (for performance reasons) I would like to be able to just dump the oldest value log files w/o rewriting.

**Comment by manishrjain** [comment]
> I would like to be able to just dump the oldest value log files w/o rewriting.

Value log contains values. So, we can't just delete them, without losing data.

We have a new technique for GC, where we don't move the values, but we punch holes into value log files to reclaim disk space.

> Any plans on allowing clients to set a total db size limit?

That won't work well with the design of the DB. It's better to do what you're doing, i.e. if the size increases, call value log GC. You could also run it in a timed loop.
