### ISSUE TITLE
some namings in source code are confusing

### ISSUE THREAD

**Issue by baiwfg2** [dgraph-io/badger#402]
Hi. Lately I happen to read some source code of badger in order to know how it implements WiscKey structure. But some naming really puzzles me. For example, What's exactly folder ***y*** means ?  Another word, oracle, is there a  practical meaning in this context ?

**Comment by h7kanna** [comment]
I too have the same question!

**Comment by h7kanna** [comment]
Hi @janardhan1993, I observe package 'y' being used by in dgraph also. 
https://godoc.org/github.com/dgraph-io/badger/y?importers

'internal' package might be more appropriate if it is internal package only to badger.
Only a suggestion.

Thanks.
