### ISSUE TITLE
What if key is not stored in LSM-tree ?

### ISSUE THREAD

**Issue by baiwfg2** [dgraph-io/badger#403]
According to Wisckey paper, key is stored in LSM-tree, value is stored in separate vlog file. In such way we can understand it can indeed reduce read and write amplification compared to original LSM-tree way. So in this case is it necessary for key to be stored in LSM-tree ? Is it possible for key to be stored in the same way as value to get higher performance ?

**Comment by MoZhonghua** [comment]
I have read this paper recently, and found following sentence:
=============================================
3.4.2 Optimizing the LSM-tree Log

In WiscKey, the LSM-tree is only used for keys and value addresses. Moreover, the vLog also records inserted keys to support garbage collection as described in the previous section. Hence, writes to the LSM-tree log file can be avoided without affecting correctness.

**Comment by janardhan1993** [comment]
@baiwfg2  Searching for key would be slow if key is not stored in LSM.

@MoZhonghua We don't have LSM-tree log, we use vlog as our write ahead log for crash resilence.

**Comment by manishrjain** [comment]
Not sure if there's anything more that needs to be done here.
