### ISSUE TITLE
Why single value compression is removed?

### ISSUE THREAD

**Issue by MoZhonghua** [dgraph-io/badger#411]
I wonder why single value compression is removed from badger. I try to re-implement this feature with snappy compression, and found a big performance boost when data is highly compressable.

##  Test computer
- OS: Arch Linux 
   * Linux arch 4.14.15-1-ARCH SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
- Storage: Netac SSD 240GB
- CPU: AMD Ryzen 1600x
- RAM: 16GB
- Filesystem: ZFS with compression=off

##  Dataset

- dowload from [wikimedia page](https://meta.wikimedia.org/wiki/Data_dump_torrents#English_Wikipedia), use the dataset [simplewiki-20170820-pages-meta-current.xml.bz2](http://itorrents.org/torrent/B23A2BDC351E58E041D79F335A3CF872DEBAE919.torrent)
- size: uncompressed to about 1.0GB, about 428763 pages in this tarbar

I extract the "title" and "text" of every page, and insert badger with "title" as key and "text" as value.
- key distribution (in bytes): min: 1, mean: 20, max: 221
- value distribution (in bytes): min: 1, mean: 1753, max: 1965877

The raw data size is ~700M in total.

##  Benchmark result

|  	| Uncompressed 	| Compressed with snappy 	|
|---------------------	|--------------	|------------------------	|
| vlog size 	| 738M 	| 442M 	|
| LSM tree size 	| 20M 	| 20M 	|
| insert (items/sec) 	| 62750 	| 68528 	|
| iterate (items/sec) 	| 88780 	| 232248 	|

* Value is always compressed no matter how big it is
* Iteration is done after drop all cache using following command
```bash
 echo 3 | sudo tee /proc/sys/vm/drop_caches
```

With snappy compression, insertion speed is almost the same, but with 2.6x iteration speed.

If you guys want to try more benchmarks, I can create a pull request of my "single value compression" implementation.

**Comment by genexp** [comment]
Why would the database force this when you can do it in your own marshal method?  Snappy isn't *always* a good tradeoff.

**Comment by MoZhonghua** [comment]
You're right, it's better to let user do compression. Please close this issue.

**Comment by shirmanov** [comment]
@MoZhonghua Why the iterating becomes faster when you compress values while values are moved out of LSM tree in Badger?
