### ISSUE TITLE
Check if items is deleted when using AllVersions

### ISSUE THREAD

**Issue by Asarew** [dgraph-io/badger#417]
So i have been checking the code and noticed this comment: [Return deleted or expired values also, otherwise user can't figure whether the key was deleted.](https://github.com/dgraph-io/badger/blob/master/iterator.go#L383). but i don't see a way to identify if the item has been deleted while iterating.

**Comment by janardhan1993** [comment]
Implemented in master, item exposes IsDeletedOrExpired Method now
