### ISSUE TITLE
go test -race fails

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/badger#43]
Running `go test -race ./...` causes some tests to fail.

**Comment by szymonm** [comment]
We get SIGBUS error when running kv_test.TestGetMore with `-race`.

```
unexpected fault address 0x47f6b88
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x47f6b88 pc=0x108a467]

goroutine 5 [running]:
runtime.throw(0x15ccd43, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4200497f8 sp=0xc4200497d8
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0x1c8 fp=0xc420049848 sp=0xc4200497f8
runtime.memmove(0xc44302ca80, 0x47f6b88, 0x9)
	/usr/local/go/src/runtime/memmove_amd64.s:172 +0x697 fp=0xc420049850 sp=0xc420049848
runtime.slicebytetostring(0x0, 0x47f6b88, 0x9, 0x4f51, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:90 +0x84 fp=0xc4200498b0 sp=0xc420049850
github.com/dgraph-io/badger/badger.(*KV).decodeValue(0xc4200d9400, 0x47f6b88, 0x9, 0x4f51, 0x47f6b00, 0xc420049af0, 0x4f51, 0xc49a379b00, 0x1074b93)
	/Users/szymonmatejczyk/dgraph/go/src/github.com/dgraph-io/badger/badger/kv.go:308 +0xd9 fp=0xc420049a88 sp=0xc4200498b0
github.com/dgraph-io/badger/badger.(*KV).Get(0xc4200d9400, 0xc420049cc8, 0x9, 0x20, 0x9, 0x20, 0x9, 0x0)
	/Users/szymonmatejczyk/dgraph/go/src/github.com/dgraph-io/badger/badger/kv.go:349 +0xdf fp=0xc420049b18 sp=0xc420049a88
github.com/dgraph-io/badger/badger.TestGetMore(0xc420067380)
```

**Root case**
When retrieving a value that is stored in LSM tree using a mmap file, we have call stack as follows:

```
github.com/dgraph-io/badger/badger.(*levelHandler).get
	/Users/szymonmatejczyk/dgraph/go/src/github.com/dgraph-io/badger/badger/level_handler.go:238
github.com/dgraph-io/badger/badger.(*levelsController).get
	/Users/szymonmatejczyk/dgraph/go/src/github.com/dgraph-io/badger/badger/levels.go:456
github.com/dgraph-io/badger/badger.(*KV).get
	/Users/szymonmatejczyk/dgraph/go/src/github.com/dgraph-io/badger/badger/kv.go:341
github.com/dgraph-io/badger/badger.(*KV).Get
```

`levelHandler.get()` scans the tables on the given level using an iterator that is closed at the end of `levelHandler.get` call. Closing the iterator decreases ref count on the `table`. `table.Iterator.Value()` points to the data in mmaped file (is not copied). If there are no more references to the table (after compaction usually), the file is truncated. Then, the `Value()` from the iterator tries read truncated mmaped file resulting in SIGBUS.

I see 2 possible fixes for that
1. table Iterator should copy the value of each entry (it already copies the key).
2. The user needs to close the iterator manually using closing function returned by `KV.Get`.

Which one do you opt for @manishrjain ? Do you see any other ways of dealing with it?

**Comment by manishrjain** [comment]
We'll copy over the value in block iterator, as discussed.
