### ISSUE TITLE
How to deal with LOCK file after program crash?

### ISSUE THREAD

**Issue by Niondir** [dgraph-io/badger#433]
I'm a little confused with the LOCK file. When my process crashes and `Close()` is not called, I can not reopen the database since the lock file still exists.

Also it is not clear to me what data I loose when not calling `Close()` e.g. due to a `panic`. And how to force badger to sync to disk regularly to reduce possible data loss to e.g. the last minute.

One option would be to keep a exclusive file handle on the LOCK file while the process is running, so I can safely delete the file and the LOCK is only valid if the delete fails.

**Comment by janardhan1993** [comment]
Lock file is used to ensure that two different processed doesn't use the same badger instance. You can safely delete the LOCK file if you know that the program accessing badger has crashed.

You won't loose any data if you use default options, the write is acknowledged only after it's synced to disk(value log - it's WAL for us).

**Comment by Niondir** [comment]
Thanks, I will just delete the LOCK file. But that only moves the problem of detecting if multiple processes running to my application.

I will try to experiment with exclusive file locks on the `LOCK` file to let the delete fail when the program is still running.

**Comment by janardhan1993** [comment]
Badger takes file lock on the `LOCK` file but i am not sure whether that prevents the file from getting deleted.

**Comment by Niondir** [comment]
Keeping the LOCK file exclusively would solve the problem. If badger just does

`os.OpenFile(lockfile, os.O_EXCL, 0)`

I can only delete the LOCK file if the process that opened the DB is closed. This way the OS takes care.


My code now looks like:

```
os.Remove(lockfile) // Ignore the error, badger will let me know that the LOCK still exists
db, err := badger.Open(opts)
os.OpenFile(lockfile, os.O_EXCL, 0) // Keep exclusive handle on LOCK to prevent the delete of another instance

```

**Comment by campoy** [comment]
Hey @manishrjain, can you have a look at this issue?

The conversation has been stale for a while so I'd consider closing the issue.

**Comment by campoy** [comment]
Issue closed after long period of inactivity.

Please reopen if issue is still relevant, thanks!
