### ISSUE TITLE
Invalid value pointer offset: 1659 greater than current offset: 0

### ISSUE THREAD

**Issue by Niondir** [dgraph-io/badger#434]
I'm getting an error while iterating my data: `Invalid value pointer offset: 1659 greater than current offset: 0`

Further Tests:
* `db.Backup()` leads to `Invalid value pointer offset: 1659 greater than current offset: 746`
* `db.PurgeOlderVersions()` runs but does not help

Feels like the value log is corrupted or something. Is there any preferred way to recover from this?

Here is my Database (only 16MB): https://files.lobaro.com/index.php/s/xWXphXDnNYRF0BN

My Code:
```
func iterateData(db *badger.DB, cb func(*model.Data) error) error {
	err := db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()
		prefix := []byte(PREFIX_DATA)
		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			item := it.Item()
			k := item.Key()
			v, err := item.Value()
			if err != nil {
				return err // Error appears here
			}

			entity := &model.Data{}
			err = json.Unmarshal(v, entity)
			if err != nil {
				logrus.WithError(err).WithField("key", string(k)).Warn("Failed to unmarshal channel")
			} else {
				err := cb(entity)
				if err != nil {
					return err
				}
			}
		}
		return nil
	})

	return err
}
```

**Comment by manishrjain** [comment]
Can you either describe steps to reproduce this, or upload your Badger directory for me to look at?

**Comment by Niondir** [comment]
I linked the download of my Badger directory as zip archive. I will continue to work with badger and try to find out how this was caused. I guess it's somehow related to program crashes / terminations during development.

In my case any recovery, even with some data loss would be acceptable. Sure, finding the root cause would be better ;)

**Comment by manishrjain** [comment]
If there were crashes, a replay might have truncated the log file, if some entries were corrupted. In that case, the corresponding entries in LSM tree won't find the values on the value log, causing this error.

**Comment by janardhan1993** [comment]
@niondir Do you use syncwrites=false in options

**Comment by Niondir** [comment]
@janardhan1993 I'm using default options.

**Comment by Niondir** [comment]
Has anyone with deeper insight taken a look into the provided datafiles? Any clue what it could be or how it could been caused? It happend a second time to me already.

Since the data is not critical yet I will keep using Badger, hoping to get closer to this issue.

**Comment by manishrjain** [comment]
What is the environment here? Is it possible for the file to be corrupted?

**Comment by Niondir** [comment]
I'm working on a Windows machine. I don't write much to the database and never notices the problem without a restart, I assume the error happens somewhere during Start or Shutdown of my application.

**Comment by schomatis** [comment]
@Niondir As mentioned by @manishrjain the database seems to be corrupted, the [CRC](https://github.com/dgraph-io/badger/blob/master/value.go#L256-L258) is failing (in the first iteration) and the value log is truncated to zero. Also, the database you provided seems to include the `LOCK` file that is only present (I think) when the database is opened and Badger is running, was that the case? If not that could be an indication of an abrupt termination of the Badger process.

**Comment by manishrjain** [comment]
Yup. As @schomatis pointed, DB is indeed corrupt. You can see this by using the badger tool.

```
badger backup --dir ~/Downloads/bdb
```

This would truncate value log to zero, and then complain about file offset.

**Comment by schomatis** [comment]
@manishrjain Maybe the user could be notified of the corrupted database, and left up to him (e.g., through a flag in `Open`) whether or not to truncate what could be 1GB of (some) recoverable data.

**Comment by Niondir** [comment]
@schomatis I'm pretty sure the database is corrupted by unpleasant shutdown of my application, but shouldn't the DB always be in a state where it can be recovered? Imagine a power failure that leaves your whole DB corrupted.

I thought that is exactly what should be avoided by the "Crash resilience" mentioned  e.g. here: https://blog.dgraph.io/post/badger/

What is the best strategy to deal with this kind of critical failures? I could do regular backups and in case of a broken DB recover the latest backup. But this will get pretty expensive with bigger databases.

**Comment by manishrjain** [comment]
@schomatis : When a file system level corruption occurs, it can add garbage data to the end of file. For each key-value pair in the DB, we store a checksum, which validates the data written against the checksum stored. A mismatch means that entry and all entries after it are corrupt, and can't be trusted. Badger truncates the value log from that entry onwards. It does not truncate the entire value log by default.

https://blog.dgraph.io/post/alice/

In this case, it seems like first entry itself might have been corrupt, which is what's causing the entire log to be truncated.

If you wish Badger to not truncate the value log, you can open Badger with `ReadOnly` setting. It would skip the value log replay and the truncate, and just shut down the instance with an error.

@Niondir : A power failure shouldn't leave the entire DB corrupted. File systems can corrupt data towards the end of file, not typically in the middle or the beginning. For the entire DB to be lost, a disk level failure has to happen, where some bits were swapped at the beginning of the file. Even then, Badger stores data in many files. So, each of those files would have to have their bits swapped for it to corrupt the entire DB.

The thing is, Badger is designed to handle many crash scenarios. You can read about them in the blog post above. But, it obviously can't recover your data in case of file corruption or disk corruption.

**Comment by schomatis** [comment]
@manishrjain 

> If you wish Badger to not truncate the value log, you can open Badger with ReadOnly setting. It would skip the value log replay and the truncate, and just shut down the instance with an error.

I understand but I'm assuming the user won't necessarily know the database has been corrupted until *after* Badger truncates the log file (in the next `Open`) so it won't have the opportunity to re-open with `ReadOnly` setting. Also an automated system in production (e.g., managed with Docker) will restart the service (e.g., after a crash) with the same settings as usual (without `ReadOnly`) and that will also result in a truncated log file.

**Comment by schomatis** [comment]
> We could add an option which would avoid truncation of value log -- which you can turn and keep on.

+1

> This won't affect anything else but just avoid a value log truncation. Note that you would not be able to use the DB though.

I'm fine with that. The truncation mechanism is assuming the (most common) error scenario where there was a problem (e.g., crash) during the last append to the value log file and it is trying to correct that (by eliminating the inconsistency) to keep going with the rest of the operations. But in the (much less likely) scenario where there is disk corruption (in any of the Badger files or at any position) we're are already at crisis mode (not due to Badger's fault of course) and just want to salvage as much data as possible. Granted, I don't see an easy way to distinguish between both.

By the way, from what I've been reading in the blog post (and Badger's code) the crash scenario would seem to assume the error happens while writing to the value log file, but is there an scenario where the write error would happen in the SST files (or in the manifest)?

**Comment by schomatis** [comment]
@manishrjain Great, I'll try to take a closer look at the ALICE framework used for the tests, my main concern is if what was reported here, a state of inconsistency between the SST and the log (which would render the database unusable) could happen after a crash or if it was only related to (a much more severe and improbable error of) disk corruption?

**Comment by manishrjain** [comment]
FYI. Added a Truncate flag to avoid automatically truncating the value log. Instead, Badger by default would return an error if truncation is required.

dgraph-io/badger#452
