### ISSUE TITLE
Seek iterator with Reverse doesn't work

### ISSUE THREAD

**Issue by brk0v** [dgraph-io/badger#436]
Code:

```go

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"github.com/dgraph-io/badger"
)

func main() {
	dir, err := ioutil.TempDir("", "badger")
	if err != nil {
		log.Fatal(err)
	}
	defer os.RemoveAll(dir)

	opts := badger.DefaultOptions
	opts.Dir = dir
	opts.ValueDir = dir

	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	bkey := func(i int) []byte {
		return []byte(fmt.Sprintf("%09d", i))
	}
	bval := func(i int) []byte {
		return []byte(fmt.Sprintf("%025d", i))
	}

	txn := db.NewTransaction(true)

	// Fill in 1000 items
	n := 1000
	for i := 0; i < n; i++ {
		err := txn.Set(bkey(i), bval(i))
		if err != nil {
			log.Fatal(err)
		}
	}

	err = txn.Commit(nil)
	if err != nil {
		log.Fatal(err)
	}

	opt := badger.DefaultIteratorOptions
	opt.PrefetchSize = 10
	opt.Reverse = true

	// Iterate over 1000 items
	var count int
	err = db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(opt)
		for it.Seek([]byte("0")); it.ValidForPrefix([]byte("0")); it.Next() {
			count++
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Counted %d elements", count)
}
```
This code returns 0 elements in reverse mode and 1000 elements with reverse = false

**Comment by janardhan1993** [comment]
@brk0v  That's the expected behaviour. Seek searches for a key greater than or equal to the specifed key. Say you have the following keys "00" ,"01", "02". When you seek for "01" in reverse mode the iteration would start at "00". 
Similarly in your case since you are seeking for "0" it will go past all the values and you won't find anything.

**Comment by brk0v** [comment]
Ok. Got it. 
My case is to emulate some kind of buckets inside badger db. I was adding a prefix to keys. This prefix is a bucket. But with current iterator logic I can't find the last item in my "bucket".

**Comment by manishrjain** [comment]
You still can. You just need to choose the seek key wisely. Following from @janardhan1993's example, if you have [00, 01, 02], and you want to start from 01, then you can use `01~` (with tilde character). That way, the seek would stop just before 01, and it the first item would be 01.

**Comment by gaillard** [comment]
@janardhan1993 you said 

> Say you have the following keys "00" ,"01", "02". When you seek for "01" in reverse mode the iteration would start at "00".

So forward the seek starts with >= and reverse it starts with < ? Based on the wording in the doc I was thinking it would be seeking with "01" forwards would give "01", "02", ... and seeking with "01" reverse would give "01", "00", ... no?

**Comment by rebootcode** [comment]
He wanted to get the last item in bucket not the first, @manishrjain - I think, you mis understood his statement.

**Comment by manishrjain** [comment]
It's all about the choice of seek key. If you want the first data from reverse, you can just call Rewind after setting Reverse option.

**Comment by rebootcode** [comment]
There is no way to `seek`  reverse and rewind based on prefix.

**Comment by manishrjain** [comment]
You can set reverse and then Seek to prefix + 0xFF byte. That'd bring you to prefix.

**Comment by msackman** [comment]
@AlexMackowiak I don't think what you have will work correctly for case 1c. I've tried ... it doesn't play ball. If your prefix is `0xFF` and you want to iterate in reverse, without prior knowledge of the key length, I think it's impossible. It's almost like there's no choice but to reserve part of your key space for "impossible" values so that you can seek to them.
Therefore, IMO, the API / semantics for reverse iteration is quite bad, and needs overhauling.

**Comment by AlexMackowiak** [comment]
@msackman Yeah you're actually right, I stumbled across this myself in some tests about a week later and I guess I forgot to follow up here. `it.Rewind()` does not work with `reverse=true` how I expected it should, and I even filed an issue on the forum: https://discuss.dgraph.io/t/iterator-rewind-invalid-with-reverse-true-and-prefix-option-set/15518 but as far as I can tell this is the expected behavior?

I believe the actual case 1c that I ended up writing in my code was just to append as many `0xFF` values as the key length, and just hope that case doesn't come up much if ever in practice (which is a reasonable assumption for my application).

**Comment by msackman** [comment]
@AlexMackowiak Yep. I think in conclusion it's actually impossible to seek to the last item in a database without prior knowledge of the key length. Personally, I'm switching back to BoltDB as that seems to have a much better designed API IMO.

**Comment by PeterMcKinnis** [comment]
Just wanted to post example code for [AlexMackowiak](https://github.com/AlexMackowiak) solution.  

```

func incrementPrefix(prefix []byte) []byte {
	result := make([]byte, len(prefix));
	copy(result, prefix);
	var len = len(prefix);
	for len > 0 {
		if (result[len - 1] == 0xFF) {
			len -= 1;
		} else {
			result[len - 1] += 1;
			break;
		}
	}
	return result[0: len];
}

// Seeks to the last key that is valid for the given prefix. For correct 
// behavior, the iterator must be setup to iterate in the reverse direction
func  SeekLast(it *badger.Iterator, prefix []byte) {
	it.Seek(incrementPrefix(prefix));
}
```

Example Usage
```
func example(db *badger.DB, prefix []byte) error {

	return db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Reverse = true
		var it = txn.NewIterator(opts);
		defer it.Close();

		for SeekLast(it, prefix); it.ValidForPrefix(prefix); it.Next() {
			// Do stuff with item...
		}
		return nil;
	});
}
```

Test
```
func Test_seekForReverseIterate(t *testing.T) {
	type args struct {
		prefix []byte
	}
	tests := []struct {
		name string
		args args
		want []byte
	}{
		{"Standard Case", args{[]byte{0x05, 0x45, 0x77}},  []byte{0x05, 0x45, 0x78}},
		{"Some 0xFF", args{[]byte{0x05, 0xFF, 0xFF}},  []byte{0x06}},
		{"All 0XFF", args{[]byte{0xFF, 0xFF, 0xFF}},  []byte{}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := incrementPrefix(tt.args.prefix); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("seekForReverseIterate() = %v, want %v", got, tt.want)
			}
		})
	}
}

```

As others have mentioned, I believe this should be in the standard library.  `SeekLast` could be added as a method on `Iterator` for a non-breaking change to that would allow the desired behavior.  

Alternatively .  `Iterator.Rewind` and `Iterator.Seek` could be updated, but this would be a breaking change.  I suspect that almost no-one is relying on the current behavior.  I can't think of real work use case it, but certainly doesn't mean that there isn't one out there.

**Comment by AlexMackowiak** [comment]
@PeterMcKinnis I believe this solution is currently missing one case and loses some efficiency over optimal reverse prefix scanning:
1. When the result of `incrementPrefix()` is itself a key in your database, the resulting iterator will not be valid for the prefix.
    a. This is the "DB with exact match on incremented key" case from my original post, and requires an `it.Next()` call to fix.
    
2. You did legitimately find a workaround to the correctness issue when the prefix is entirely 0xFF!
    a. This workaround is to ditch the badger Prefix IteratorOption entirely and check the prefix match at each key yourself
         i. (Adding `opts.Prefix = prefix` to `Test_SeekLast` causes two test failures)
    b. There is one downside to this though, [finding the first prefix match in BadgerDB is already decently slow
](https://github.com/dgraph-io/badger/pull/1719) and not specifying the Prefix IteratorOption will [slow it down even further](https://github.com/dgraph-io/badger/blob/c5d36c806aa80954a24606a982a475a717d44de2/iterator.go#L332-L335)

The code I ended up writing to account for everything in the reverse prefix case is the following:
```
options := badger.DefaultIteratorOptions
options.Reverse = true
options.Prefix = rangePrefixKey
it := tx.NewIterator(options)
...
incRangePrefix := common.Strinc(rangePrefixKey) // incrementPrefix() analog
if len(incRangePrefix) > 0 {
    it.Seek(incRangePrefix) // Point to the first key <= the range prefix
    if it.Item() != nil && bytes.Equal(it.Item().Key(), incRangePrefix) {
        // Exact match on incremented range prefix, need to move back one key for the last key matching the prefix
        it.Next()
    }
} else {
    // Entire range prefix was just [0xFF, 0xFF, 0xFF, ..., 0xFF], use the last key in the database
    // There's currently a bug with it.Rewind() when in reverse and with a prefix, it does not correctly find the largest key
    // https://discuss.dgraph.io/t/iterator-rewind-invalid-with-reverse-true-and-prefix-option-set/15518
    it.Seek(bytes.Repeat([]byte{0xFF}, len(rangePrefixKey)+1))
}
```

**Comment by PeterMcKinnis** [comment]
@AlexMackowiak 

I implemented your solution but, it also fails the case where `incrementPrefix` is a valid key.  I haven't done perf testing but this solution does work.  No idea if its faster or not.

```go

// This implementation uses a prefix on the iterator
func getKeys2(db *badger.DB, prefix []byte) ([][]byte)  {
	result := [][]byte{};
	err := db.View(func(txn *badger.Txn) error {

		// First find the max key in 
		opts1 := badger.DefaultIteratorOptions
		opts1.Reverse = true
		it1 := txn.NewIterator(opts1)
		defer it1.Close()
		SeekLast(it1, prefix);
		if (!it1.ValidForPrefix(prefix)){
			// empty result set
			return nil;
		}
		maxKey := it1.Item().KeyCopy(nil);
	
		// Now iterate with prefix correctly
		opts2 := badger.DefaultIteratorOptions
		opts2.Reverse = true
		opts2.Prefix = prefix;		
		it2 := txn.NewIterator(opts2)
		defer it2.Close()
		for it2.Seek(maxKey); it2.Valid(); it2.Next() {
			result = append(result, it2.Item().KeyCopy(nil));
		}
		return nil
	})
	if (err != nil) {
		log.Fatal(err);
	}
	return result;
}
```

**Comment by AlexMackowiak** [comment]
@PeterMcKinnis 

I replaced your `SeekLast` with my implementation as follows and I don't see any test failures pertaining to that increment case

```
func SeekLast(it *badger.Iterator, prefix []byte) {
	incRangePrefix := incrementPrefix(prefix)
	if len(incRangePrefix) > 0 {
		it.Seek(incRangePrefix) // Point to the first key <= the range prefix
		if it.Item() != nil && bytes.Equal(it.Item().Key(), incRangePrefix) {
			// Exact match on incremented range prefix, need to move back one key for the last key matching the prefix
			it.Next()
		}
	} else {
		// Entire range prefix was just [0xFF, 0xFF, 0xFF, ..., 0xFF], use the last key in the database
		// There's currently a bug with it.Rewind() when in reverse and with a prefix, it does not correctly find the largest key
		// https://discuss.dgraph.io/t/iterator-rewind-invalid-with-reverse-true-and-prefix-option-set/15518
                it.Seek(bytes.Repeat([]byte{0xFF}, len(rangePrefixKey)+1))
	}
}
```
I also have extensive test cases on this particular case, although they were written as part of a much larger, proprietary system that I wouldn't be able to share here.

I did not however have test coverage of the following case!
1. When the prefix is all 0xFF
2. but another key exists which matches the 0xFF ... 0xFF prefix but is longer than the prefix

My code was incorrect in this case, and to be _truly_ correct you would need to know the length of the longest key in the database, as a workaround to `it.Rewind()` being unusable when `reverse=true` and `prefix` is set. Or alternatively make a new iterator without `prefix` set, so it's going to get pretty gross either way. I'll update my code posted with a note about this.
