### ISSUE TITLE
Txn is too big to fit into one request

### ISSUE THREAD

**Issue by rof20004** [dgraph-io/badger#441]
I am trying to insert one million register but I got this error: Txn is too big to fit into one request

How can I solve this?

This is my code.

```
package main

import (
	"log"
	"strconv"

	"github.com/dgraph-io/badger"
)

var database = &badger.DB{}

func initDB() {
	// Open the Badger database located in the /tmp/badger directory.
	// It will be created if it doesn't exist.
	opts := badger.DefaultOptions
	opts.Dir = "./badger"
	opts.ValueDir = "./badger"
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	database = db
}

func main() {
	initDB()

	log.Println("Writing to database...")

	database.Update(func(txn *badger.Txn) error {
		for i := 0; i < 1000000; i++ {
			key := "Character" + strconv.Itoa(i)
			value := strconv.Itoa(i)
			err := txn.Set([]byte(key), []byte(value))
			if err != nil {
				log.Fatalln(err)
			}
		}
		return nil
	})
}

```

**Comment by manishrjain** [comment]
You can stop adding more keys and just commit the transaction. A single txn can't be too big, which is what the error is indicating.

**Comment by rof20004** [comment]
@manishrjain Thanks and sorry.

**Comment by manishrjain** [comment]
No worries, mate!

**Comment by AaronVasquez** [comment]
I'm running into this issue too. What is the recommended txn size?

**Comment by manishrjain** [comment]
Badger would tell you when the txn size is too big by returning that error. In general, a txn should not exceed the size of a single memtable.

**Comment by leighmcculloch** [comment]
What's the right way to determine that error has occurred? From what I can see the error returned is `errors.fundamental` which isn't exported, so there's no way of doing `if err == badger.ErrTxnTooBig` to make a programatic decision to try again.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger/blob/a6f0866f06a0ef6ac612e427ffe5d081db4e6fab/errors.go#L38

This is the error that gets returned. It is exported. Here's the documentation around retrying:

https://github.com/dgraph-io/badger#read-write-transactions

**Comment by leighmcculloch** [comment]
Ah, thank you!!!
