### ISSUE TITLE
Support encryption at rest

### ISSUE THREAD

**Issue by asimpatnaik** [dgraph-io/badger#443]
Hi,
Currently there is no authentication support. It will be a great feature to have.
We are using badger for developing a banking solution and data privacy is a requirement.
Kindly let me know if you can incorporate the security feature.

Regards,
Asim.

**Comment by manishrjain** [comment]
I'd like to understand this use case in a bit more detail. Can you please shoot me a mail? My email id is manish, with company domain.

**Comment by manishrjain** [comment]
If other people need this feature, please feel free to upvote. We'll consider making this feature available as an enterprise extension.

**Comment by cretz** [comment]
@manishrjain - Github doesn't have a voting feature. I assume you are asking people to add a thumbs up reaction? Also, people have a harder time finding closed issues to even vote on. Granted, for those on GitHub, they might not consider it if it's an "enterprise extension".

**Comment by gedw99** [comment]
+1 security at rest is exactly what I need.
The keys should be stored in the local key store. There are a few golang libs that do this for desktops and mobiles.
I use badget on mobile now and it's amazing

**Comment by gedw99** [comment]
Is Encryption at Rest going through a Use case / Scoping stage ?

I am using badger in a prototype and Security at rest is critical for privacy reasons.

If a design RFP document is floating around let me know and i can comment

**Comment by manishrjain** [comment]
There's no spec yet.

**Comment by gedw99** [comment]
Ok. Thanks for the feedback. I am working on government projects where
security at rest is mandatory and so can give requirements in general and
architecture approaches if you want.

Anyway .. let me know. Don't want to be pushy pushy :)

**Comment by tsingson** [comment]
same req. 
but i add  a crypto / de-crypto layer over badger, so it work fine.

**Comment by gedw99** [comment]
@tsingson
i was thinking of taking the same approach. Just do the encryption above Badger.
However, that means search will not work because the index is now encrypted ???

What i think has to happen is that the unencrypted data is indexed, and the encrypted data is stored.
SO when querying your hitting the clear data, and that index points to encrypted data.
Then higher app at your application layer all the records you get back you can decrypt. 

If anyone has other ideas i would be happy to discuss...

**Comment by tsingson** [comment]
@gedw99  I do not  crypto the key.  value be crypto only when key-value save to badger.
and a LRU / LFU cache layer over the crypto layer, so it's fast search ( index and shading for Concurrency access ) .

so, it's work stable in business field.

**Comment by TandyCorp** [comment]
This seems like a valuable addition, a Transparent Data Encryption scheme would probably be the easiest to implement. Encrypting and decrypting data at the file read & write stages, this would solve the problem of someone having access to the file system and copying the database files from disk. The standard go encryption library could be used to implement it, it just a question of how to store the key.

**Comment by gedw99** [comment]
Keep the key in the key store the OS provides ? Just like what VPN clients
do..

**Comment by cretz** [comment]
> it just a question of how to store the key.

> Keep the key in the key store the OS provides?

No, key management and generation should be caller concerns. If people want to make helpers for management, derivation, etc so be it. Sqlite encryption impls just take a key and rekey (see a Go wrapper I wrote [here](https://github.com/cretz/go-sqleet).

Also since this is pure Go, the crypto algo should be a sensible default but allow callers to provide their own `crypto.Block` builder.

**Comment by manishrjain** [comment]
Looks like RocksDB added that recently. So, we should be able to pick a few pointers from them, if possible: https://github.com/facebook/rocksdb/pull/2424

**Comment by james-lawrence** [comment]
is this currently in progress/is there an ETA? would love to see this would make badger a perfect fit for a project of mine.

willing to put in work testing/helping develop the feature.

**Comment by james-lawrence** [comment]
gotcha, well i'll check in once i get to at rest encryption being the main blocker for my project.

**Comment by campoy** [comment]
Adding this to the possible improvements to be added *after* v2 has been released.

**Comment by manishrjain** [comment]
This feature is planned for Q3 2019.

**Comment by omercnet** [comment]
Hi @manishrjain any update on ETA? we'd love to get this sooner than later :)

**Comment by campoy** [comment]
@balajijinnah is currently working on this in #1020 which has been LGTMed today.

The change should go into master soon and into the next release

**Comment by sleto-it** [comment]
Hi all,

This has been implemented and released in BadgerDB v2.0.0, which is available for download ([Release](https://github.com/dgraph-io/badger/releases/tag/v2.0.0) | [Blog post](https://blog.dgraph.io/post/releasing-badger-v2/)) . Dgraph users will get encryption in v1.1.1 which is currently in RC ([v1.1.1-rc2 announcement](https://discuss.dgraph.io/t/dgraph-v1-1-1-rc2-release-candidate/5622) | [Documentation](https://docs.dgraph.io/master/enterprise-features/#encryption-at-rest))

Closing. Please reopen if needed

Thanks,
