### ISSUE TITLE
Revise `require.Error` usage

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/badger#450]
Some tests are calling [`require.Error`](https://github.com/stretchr/testify/blob/c679ae2cc0cb27ec3293fea7e254e47386f05d69/require/require.go#L225-L238) with an extra argument, e.g.,

https://github.com/dgraph-io/badger/blob/e630a49709e529560871db2e356ea33fe2171e01/value_test.go#L396-L400

expecting (in what I'm assuming) for the function to check equality of errors but `Error` is actually interpreting the second argument (the "expected error") as the error value to check against `nil` and the third argument (the actual returned error) as the informational message (`msgAndArgs`) if the check fails (and hence is not checking the error itself).

**Comment by manishrjain** [comment]
Can you please send a PR to fix this?

**Comment by schomatis** [comment]
Sure.

**Comment by manishrjain** [comment]
Done. c3ac2ff

**Comment by schomatis** [comment]
Sorry, I completely forgot about this. I'll submit a PR to fix a couple more of these cases not addressed in the other commit.
