### ISSUE TITLE
Replication support via Raft

### ISSUE THREAD

**Issue by hobbs** [dgraph-io/badger#451]
It would be interesting to support replication via [Raft](https://github.com/hashicorp/raft), similar to the [BoltDB adapter](https://github.com/hashicorp/raft-boltdb) or [dqlite](https://github.com/CanonicalLtd/dqlite).

Obviously, this is a large feature request, just wanted to start the conversation.

**Comment by hobbs** [comment]
Actually, I did find this: https://github.com/s4ayub/huffleraft

**Comment by manishrjain** [comment]
Nice work! Raft is beyond the design goals of Badger, we do it at Dgraph level.
