### ISSUE TITLE
How to Check if key exists after set ttl expired

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/badger#456]
I am setting key-value with TTL for 1 day. I just want to check if the key exists than print or do some write.

I searched "Exist" and "Exists" in the code base and I could not find any? Is there any function to check, if the key exists?

**Comment by rebootcode** [comment]
@manishrjain & @deepakjois  & @janardhan1993 

any documentation info, please?

**Comment by manishrjain** [comment]
@ghartz : SSTables are immutable. Once written, they are not modified. Only compaction can discard versions of keys. Working on a change to discard expired versions, as per this issue: #464 . 

Thanks for pointing out the bug. I've made it part of my pending PR.

@rebootcode : As mentioned by @ghartz , you can use the `ErrKeyNotFound` error during Get to determine if the key exists or not. The error returned is the same irrespective of whether the key exists or has expired.
