### ISSUE TITLE
Blog for 2.0 

### ISSUE THREAD

**Issue by Graphpinto** [dgraph-io/badger#457]
Review feature launch blog

**Comment by janardhan1993** [comment]
https://github.com/dgraph-io/open/blob/master/content/post/badger-v2.0.md

**Comment by Graphpinto** [comment]
Thanks @janardhan1993.

**Comment by cloudaice** [comment]
@janardhan1993 https://github.com/dgraph-io/open/blob/master/content/post/badger-v2.0.md  This link page is 404 ?

**Comment by manishrjain** [comment]
Open is a private repository for our blog. We haven't published the blog post yet. Some changes need to go in before we can release v2.0.
