### ISSUE TITLE
How to deal with performance issues?

### ISSUE THREAD

**Issue by Niondir** [dgraph-io/badger#459]
I'm loading data which I filter based on a timestamped saved inside the json encoded value.

With 35k entries, loading data takes ~750ms which is not acceptable.

While I'm new to key value stores I have some questions and ideas about optimizing the performance.

1) I could index my data based on the timestamp to avoid loading and unmarshaling of all values.
2) I could add the timestamp to my object keys to avoid loading and unmarshalling of all values.

Is there any recommendation about 1) and 2) or did I missed some better option?

Is there a way to tell badger to cache some data in memory? Since 35k values probably fit in RAM

**Comment by Niondir** [comment]
Iterating only the keys still takes ~280ms what do I miss?

**Comment by Niondir** [comment]
I also missed:

```
opts := badger.DefaultIteratorOptions
opts.PrefetchValues = false
```

But I still wonder how I get rid of old value log files. I have no data left, but iterating the deleted keys seems to take a lot of time.

**Comment by icholy** [comment]
Encode the timestamp into your keys. See how it's implement in redis streams http://antirez.com/news/114

**Comment by Niondir** [comment]
My keys now look like `<prefix>_<uuid>_<timestamp>`, adding the `opts.PrefetchValues = false` gave another performance boost. Iterating 362880 keys now takes 550ms where a simple in memory iteration with the same logic takes 232ms (see code below). Is there so much overhead in iterating keys with badger? - Still it seems acceptable.

```
func TestIterateInMemory(t *testing.T) {
	list := make([][]byte, 3*12*60*24*7)
	for i := range list {
		list[i] = []byte("prefix_" + string(i) + "_" + string(time.Now().Add(time.Duration(-i) * time.Second).Unix()))
	}

	until := time.Now()
	since := time.Unix(100, 0)
	cnt := 0
	start := time.Now()
	for i := range list {
		tokens := bytes.Split(list[i], []byte{'_'})

		var timestamp int64
		var t time.Time
		var err error
		if len(tokens) > 2 {
			timestamp, err = strconv.ParseInt(string(tokens[2]), 0, 64)
			t = time.Unix(timestamp, 0)
			if err != nil {
				cnt++
			}
		}

		if !until.IsZero() && (t.After(until) || t.Equal(until)) {
			cnt++
		}

		if !since.IsZero() && t.Before(since) {
			cnt++
		}
	}

	t.Logf("Iterating took %s", time.Since(start))
}
```

But the biggest issue still is, that even if I delete entries from the DB, the iteration does not speed up again. It feels like entries getting flagged as deleted but are still iterated internally. `PurgeOlderVersions` + `RunValueLogGC` does not seem to solve this.

**Comment by manishrjain** [comment]
Working on a change to discard invalid versions of keys. See #464 .

Closing this issue for now. Let me know if there's anything else that needs to happen here.
