### ISSUE TITLE
Api for mass purging specific keys

### ISSUE THREAD

**Issue by Asarew** [dgraph-io/badger#460]
I've run into a use case where i have to delete a lot of specifc keys before a version. It's possible to grab the specific keys + version while iterating, but it's not possible to mark a specific version of the key to be deleted/garbage collected. The only api that does something like this is [PurgeVersionsBelow](https://godoc.org/github.com/dgraph-io/badger#DB.PurgeVersionsBelow) but that creates a new transaction for every time that it's called.

**Comment by manishrjain** [comment]
v2.0, which is in works, makes purging keys a lot nicer and more efficient. So, I'd suggest waiting a bit until v2.0 is released.

**Comment by Asarew** [comment]
Is there an estimation on when 2.0 is released?

**Comment by manishrjain** [comment]
I released v1.5.0 a couple of days ago, which removes the PurgeVersions API calls. It gets rid of keys during compactions. So, there's no need for that call anymore.
