### ISSUE TITLE
How to autoincrement a key?

### ISSUE THREAD

**Issue by arriqaaq** [dgraph-io/badger#462]
Hi Team,
I'm basically using Badger for certain real time analytics metrics, and would like to know how to auto increment a key instead of reading it every single time, like a redis INCR operation. Help will be appreciated as

**Comment by manishrjain** [comment]
You can use this:

https://github.com/dgraph-io/badger#monotonically-increasing-integers

**Comment by arriqaaq** [comment]
Thank you @manishrjain , appreciate it. Would a INCR method help?

**Comment by manishrjain** [comment]
Actually, you can use merge operations to incrementing a key, without reading it.

https://github.com/dgraph-io/badger/#merge-operations

That's what INCR method is.
