### ISSUE TITLE
Is there any plan to implement pessimistic transaction?

### ISSUE THREAD

**Issue by kingluo** [dgraph-io/badger#463]
The badget implements read-write transaction in optimistic way, correct?
I am wondering is there chances `Commit()` would always fail under high contention on some hot keys, and retries after `ErrConflict` has a problem: it seems hard to determine how many times to retry.

**Comment by manishrjain** [comment]
Badger provides lock-free transactions, which works similar in nature to optimistic locking.

Transactions can keep on resulting in a conflict if the same key write is present in many simultaneous transactions.

**Comment by kingluo** [comment]
I mean how many times I should retry in case of conflict? It seems impossible to predict.
But if I could lock the key in advance, it is supposed to be successful.

**Comment by kingluo** [comment]
Why badger do not provide pessimistic locking just like rocksdb?

**Comment by manishrjain** [comment]
Doing explicit locks in advance means lower write throughput, less concurrency and more contention. Badger is built with the goal of high concurrency.
