### ISSUE TITLE
Any way to update TTL of existing key?

### ISSUE THREAD

**Issue by JeanMertz** [dgraph-io/badger#467]
I've got a use-case where I want to check for a key to exist, and if it exist, I want to extend the (already existing) TTL of that key.

I can do this now by - when a key exists - retrieving that key, deleting it, and inserting it again with a fresh TTL, but I suspect there will be a lot of overhead there, which will become problematic for the volume of keys I want to store/check in the cache.

Any thoughts on this?

**Comment by manishrjain** [comment]
Keys once written are immutable. They can only be *superceded* by a new version of the key.

Just as a suggestion on top of my head, you could split your key into two: one with value, and one with the TTL. Then, the TTL key would be a lightweight key which you can keep updating without affecting the value.

**Comment by JeanMertz** [comment]
> They can only be superceded by a new version of the key

> you could split your key into two: one with value, and one with the TTL

In this case, I don't actually store any values, I'm only interested in the keys, and the attached TTL. Does that mean that I can simply insert the key for a seconds time, with a new TTL, and the result will be as excepted: the key will remain until the TTL of the second insert is expired, not when the TTL of the first insert expires?

**Comment by manishrjain** [comment]
Yes, that's right. Each update is a new version of that key, and the latest version determines the behavior. So, your TTL would be based on the new version.
