### ISSUE TITLE
Feature Request: Ability to rm TTL'd vlog/sst files efficiently. 

### ISSUE THREAD

**Issue by jiminoc** [dgraph-io/badger#468]
For heavy TTL workloads it would be much more efficient in regards to disk usage if you were able to store metadata about the keys in a header section that indicated if all the keys were expired. That way you could just "rm" the file instead of having to scan through it. e.g. all keys have a TTL and the highest TTL timestamp is X

**Comment by manishrjain** [comment]
The keys are sorted globally. Value log stores them in the order of writes, while LSM tree stores them in levels, with each level storing the keys in sorted order. So, it's not possible to pinpoint one file without affecting other keys.

Also, key-only scan is really fast, so there's no need to do a file-based division of keys.
