### ISSUE TITLE
Support for column families

### ISSUE THREAD

**Issue by noorainp** [dgraph-io/badger#469]
It would be great if there was a column family support like there is for RocksDB

**Comment by manishrjain** [comment]
Column families would require separate storage for key-value pairs in different column families. That's beyond the design goals of Badger.

**Comment by manishrjain** [comment]
I should add, you can easily segregate the keys by adding prefixes. Then when you need to get rid of the keys, you can iterate over that prefix, and mark all those keys as deleted. Compaction would then get rid of the keys (as of v1.5.0), and so would value log GC.

**Comment by noorainp** [comment]
Prefix seems like a viable option. My only concern was that for larger
datasets, I would have to go through all the keys adding unnecessary
overheads. Having column families would definitely speed up the process.

**Comment by manishrjain** [comment]
Dgraph key only iteration is blazing fast. So, the overhead is minimal. Anyways, deletion of throw-away column families doesn't sound like it would be in the path of main logic.
