### ISSUE TITLE
Assert Failed when re-init the badger without insertion

### ISSUE THREAD

**Issue by Hendra-Huang** [dgraph-io/badger#47]
I build an app using Go and I try to use badger as the key-value store. I have successfully set and get to the store, but I found some weird error when I stop the binary and start the binary again. This is my error message
```sh
2017/05/29 13:12:41 Assert failed
github.com/dgraph-io/badger/y.Errorf
	/go/src/github.com/dgraph-io/badger/y/error.go:98
github.com/dgraph-io/badger/y.AssertTrue
	/go/src/github.com/dgraph-io/badger/y/error.go:63
github.com/dgraph-io/badger/badger.(*levelHandler).replaceTables
	/go/src/github.com/dgraph-io/badger/badger/levels.go:131
github.com/dgraph-io/badger/badger.(*levelsController).doCompact.func2
	/go/src/github.com/dgraph-io/badger/badger/levels.go:506
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
```

How to reproduce this error:
1. Start my apps and it will initialize the badger via `badger.NewKV(badger.DefaultOptions)` method in the main function
2. Don't do any SET operation
2. Stop my apps and it will call `defer kv.Close()` in the main function too
3. Start my apps again and it will show the error message above

I have tried some cases but it seems like if I call `badger.NewKV` and then close it without any insertion to the store and then calling `badger.NewKV` again will trigger the error.

If I delete the store directory, my apps can start again but the data is gone bcause it is deleted.

Did I do anything wrong ? I can't really debug it because the error message does not contains much information about what is happening. Thanks for the help

**Comment by manishrjain** [comment]
Investigating.

**Comment by stephane-martin** [comment]
I just stumped into that too. Looks like it happens when creating a KV, closing the KV, reopening the KV, without having inserted anything. Same panic error that previously reported;

**Comment by manishrjain** [comment]
This change https://github.com/dgraph-io/badger/commit/b0ce0e136df40b708d834d210fd607bf41461ca1 fixes this bug. Try it out. If you still see the error, feel free to reopen the issue.

**Comment by Hendra-Huang** [comment]
Okay thanks. It is solved
