### ISSUE TITLE
Replaying value log file issue "after a crash"

### ISSUE THREAD

**Issue by alash3al** [dgraph-io/badger#478]
Dears, 

I'm using badger in a long-running-service "that never stops", at some point in time we detected that badger cannot write data "resulting in server timeout" after some investigation "using badger info" from cli, we found that there is an error "Database was not properly closed, cannot open read-only", I think that our service maybe restarted from a crash that terminated badger.

So, how can we fix that issue or how we can replay the vlog data?

**Comment by manishrjain** [comment]
Looks like you're trying to open the DB with `ReadOnly` option set to true. You can set that to false. If there was a crash, it's also possible that the value log might need truncation, which Badger wouldn't do by default. You can set `Truncate` option to true to allow for that.

Closing the issue, as this is a general question.

**Comment by manishrjain** [comment]
I think you might not be closing your iterators, and trying to write data. Those iterators might be blocking the value log files from being closed, due to their read locks, which would block the write. Something on those lines.
