### ISSUE TITLE
Mutability of []byte in transaction methods

### ISSUE THREAD

**Issue by stephane-martin** [dgraph-io/badger#482]
Hi,

no really an issue with Badger, but rather a point of attention.

The Txn methods take *[]byte* arguments for keys and values. Byte slices are *mutable*.

For example, when performing a Delete(key), the Delete operation will not be completed right at the method call, but later on, when the transaction ends. In the meantime, the key is stored in an Entry object and lives inside the txn. 

So what happens I modify the 'key' byte slice after the Delete() call, but before the transaction ends ? Chaos :-)

Got bitten by that when introducing sync.Pool to reuse keys and values. The byte slices were reused, and the writes  started to be non sense. Pretty hard to debug too. Maybe that should be documented?

Thank you

**Comment by manishrjain** [comment]
Yeah, we should mention them. Maybe you can send a documentation PR?

**Comment by stephane-martin** [comment]
Here you are

**Comment by manishrjain** [comment]
Reviewed. One comment, and it should be good to go.
