### ISSUE TITLE
Should deleted or expired entries be backed up?

### ISSUE THREAD

**Issue by Kelindar** [dgraph-io/badger#483]
During the backup, deleted or expired items are written in, would it make sense to provide an option or default to skipping writing such entries ? Perhaps by simply adding a check  `item.IsDeletedOrExpired()` in the `Backup` method. 

https://github.com/dgraph-io/badger/blob/c6f5a0e8190915f35cb2b98ca64c8013f1156c88/backup.go#L50

It makes sense for my personal use-case as I've noticed when using this and doing regular snapshots the snapshot keeps growing, even though most of my keys expire very quickly. I'm not yet very familiar with badger's codebase, but I assumed if I run `RunValueLogGC(0.50)` prior to `Backup`, but it doesn't seem to evict expired keys.

**Comment by Kelindar** [comment]
I ended up doing something like this: 

```
// Backup creates a snaphshot of the store.
func (s *Storage) Backup(writer io.WriteCloser) error {

	// Run GC before backing up
	s.db.RunValueLogGC(0.50)

	// This is a copy of badger backup except it doesn't write any
	// deleted or expired items in the snapshot.
	logging.LogAction("badger", "writing a snapshot")
	return s.db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.AllVersions = true
		it := txn.NewIterator(opts)
		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			if item.IsDeletedOrExpired() {
				continue // Skip deleted or expired items
			}

			val, err := item.Value()
			if err != nil {
				continue
			}

			entry := &protos.KVPair{
				Key:       y.Copy(item.Key()),
				Value:     y.Copy(val),
				UserMeta:  []byte{item.UserMeta()},
				Version:   item.Version(),
				ExpiresAt: item.ExpiresAt(),
			}

			// Write entries to disk
			if err := writeTo(entry, writer); err != nil {
				return err
			}
		}
		return nil
	})
}
```

**Comment by manishrjain** [comment]
You could simplify your logic by not setting `AllVersions=true`, and leave it to false. Then, you won't need to specifically handle the `IsDeletedOrExpired`.
