### ISSUE TITLE
Adding a BeforeCommit Option

### ISSUE THREAD

**Issue by dc0d** [dgraph-io/badger#487]
By adding a `BeforeCommit func(txn *Txn, key, val []byte) error` function to database options, implementing secondary indexes (and more interesting scenarios) will become easier and more straight forward.

I needed this for implementing an embedded document database (relatively small one) based on `badger` and have already sent a [pull request](https://github.com/dgraph-io/badger/pull/486).

**Comment by manishrjain** [comment]
I think secondary indices can be built from within your update functions. We do that in Dgraph as well. I doubt putting this in Badger adds anything of value that can't be done in the application layer.

**Comment by dc0d** [comment]
A key-value store is rarely used without some sort of secondary indexes. And calling this manually is an error prone task and adds lots of clutter to the consumer code-base. 

This event has no overhead over the current performance of badger (if it's `nil`) and passes all the tests.

It seems a convenient utility (IMHO) since one has to create some sort of secondary index in majority of cases.

**Comment by gedw99** [comment]
@manishrjain 
You can only do orchestration, but not choreography. @dc0d's BeforeCommit function allows choreography patterns and hence allows many more use cases and inside out architectures. 

@dc0d You can always write a generic wrapper over badger and implement the needed Events ?

**Comment by dc0d** [comment]
@gedw99 I wanted to implement a document database (based on badger) and so far most of it is done. Any feedback is most welcome! https://github.com/dc0d/dockage

**Comment by gedw99** [comment]
@dc0d see my comments on https://github.com/dc0d/dockage
