### ISSUE TITLE
Limit manifest's change set size

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/badger#490]
(In a similar way as it was done for the [value log replay](https://github.com/dgraph-io/badger/pull/158/files#diff-1c18e563343128db9eb1948c03ced241R151).)

https://github.com/dgraph-io/badger/blob/dc0df253d239ff6abe3ffbbcdf3cb1e49e646369/manifest.go#L356-L357

**Comment by manishrjain** [comment]
Reasoning?

**Comment by schomatis** [comment]
The same as the one described in vulnerability number 1 of the ALICE [post](https://blog.dgraph.io/post/alice/) which the cited PR fixes.

> The vulnerability occurs when the key and value lengths in a value log entry header contain garbage data. These lengths are used to figure out how to read the key and value. A 4-byte integer’s largest value is ~4 billion, causing a worst case memory allocation of 8GB (4GB for each of the key and value). This can cause the process to go out of memory, resulting in Badger refusing to start.

**Comment by manishrjain** [comment]
I see. Good catch.

**Comment by manishrjain** [comment]
ALICE would have to see a lot of writes going into MANIFEST, which doesn't happen as often as writes which go into the value log. If run long enough, on a powerful machine, this might trigger, I reckon. There's a time gap between write and sync, a crash should happen at that time and must leave some garbage data appended to the file.

https://github.com/dgraph-io/badger/blob/dc0df253d239ff6abe3ffbbcdf3cb1e49e646369/manifest.go#L208-L215

**Comment by campoy** [comment]
This seems like a serious issue, so I'd like to have you @manishrjain check whether it's indeed something we should fix or it's not relevant to the current codebase anymore.
