### ISSUE TITLE
confusing about comment

### ISSUE THREAD

**Issue by zerolocusta** [dgraph-io/badger#492]
I am reading badger source code.
The comment of `db.go/writeLevel0Table` says that it will drop deleteValues,but`s.NewIterator()`will return a `skl.Iterator`,and this iterator will not drops deleteValues while traversing memtable,but `badger.Iterator` will drops deleteValues.
```go
// WriteLevel0Table flushes memtable. It drops deleteValues.
func writeLevel0Table(s *skl.Skiplist, f *os.File) error {
	iter := s.NewIterator()
	defer iter.Close()
	b := table.NewTableBuilder()
	defer b.Close()
	for iter.SeekToFirst(); iter.Valid(); iter.Next() {
		if err := b.Add(iter.Key(), iter.Value()); err != nil {
			return err
		}
	}
	_, err := f.Write(b.Finish())
	return err
}
```
Wanna know where was wrong.
Thanks.

**Comment by manishrjain** [comment]
writeLevel0Table doesn't drop any value. That comment seems to be wrong. I'll push a fix.

`badger.Iterator` would skip over the deleted values, it doesn't modify the DB (add/drop key-values) in any way. However, a recent change to the DB that I committed, would now drop versions of keys which are deleted and/or older.
