### ISSUE TITLE
PurgeOlderVersions still mentioned in docs

### ISSUE THREAD

**Issue by dolzenko** [dgraph-io/badger#493]
https://github.com/dgraph-io/badger/blob/65cbaa2e25f7f04fbef4c37aa27554e85def4b6f/db.go#L930 mentions PurgeOlderVersions , while https://github.com/dgraph-io/badger/pull/475 says it was replaced with SetWithDiscard, can somebody clarify when do we need SetWithDiscard and if its safe to remove the calls to PurgeOlderVersions?

**Comment by manishrjain** [comment]
Just pushed a change to master to remove that portion of the comment. PurgeOlderVersions is no longer available, you do not need it anymore.
