### ISSUE TITLE
Deleted keys during iteration with PrefetchValues=false are visible to the next read

### ISSUE THREAD

**Issue by luma** [dgraph-io/badger#494]
## What I see

I was walking and deleting a subset of keys. I was doing this with `PrefetchValues=false`, as the deletion criteria is just based on a min and max key. I found that when using `PrefetchValues=false` some of the keys would not be deleted, but they are all deleted when values are prefetched.

## What I expect

All keys to be deleted, regardless of the value of `PrefetchValues`. I actually set `PrefetchValue` to false based on the following recommendation in the Badger README, so I was pretty surprised :-)

> When Prefetch is false, don't call Item::Value and do a pure key-only iteration. This might be useful if you just want to delete a lot of keys.

## Badger Version

The latest on the master branch.

## Reproduction

The following small Go program should demonstrate the problem. It should write 4 keys, delete all the keys, and then prints out every key that is still there. The last step should always print nothing out.

Instead I see:

``` shell
$ go run main.go 
WRITING one value1
WRITING two value2
WRITING three value3
WRITING four value4
DELETING four
DELETING one
DELETING three
DELETING two
READING four value4
READING one value1
```

``` go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/badger"
)

func main() {
	opts := badger.DefaultOptions
	opts.Dir = "/tmp/badger"
	opts.ValueDir = "/tmp/badger"
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	defer os.Remove("/tmp/badger")

	writeKey(db, "one", "value1")
	writeKey(db, "two", "value2")
	writeKey(db, "three", "value3")
	writeKey(db, "four", "value4")

	// Delete all the keys
	err = db.Update(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions

		// PrefetchValues is false, not all of the keys will be
		// deleted, with true they will be
		opts.PrefetchValues = false

		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Rewind(); it.Valid(); it.Next() {
			k := it.Item().Key()

			fmt.Printf("DELETING %s\n", string(k))
			if err := txn.Delete(k); err != nil {
				return err
			}
		}

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	// Print all the keys
	err = db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		it := txn.NewIterator(opts)
		opts.PrefetchSize = 10
		defer it.Close()

		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.Key()
			v, err := item.Value()
			if err != nil {
				log.Fatal(err)
			}

			fmt.Printf("READING %s %s\n", string(k), string(v))
		}

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

}

func writeKey(db *badger.DB, key, value string) {
	err := db.Update(func(txn *badger.Txn) error {
		fmt.Printf("WRITING %s %s\n", key, value)
		return txn.Set([]byte(key), []byte(value))
	})

	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by manishrjain** [comment]
It doesn't matter what the value of `PrefetchValues` is. You need to do `k := it.Item().KeyCopy(nil)`, because you must pass a slice of key, which doesn't change to `txn.Delete`. I've tested your code successfully with this change.

**Comment by luma** [comment]
thanks @manishrjain

**Comment by enenum** [comment]
I see this problem right now and the proposed fix does not help it. I even upgraded from v1.6.1 to v2.0.3 - still no good...

**Comment by jarifibrahim** [comment]
@enenum can you please create a new issue with steps to reproduce it?
