### ISSUE TITLE
Iterating performance degrades when the database has a lot of deleted key values

### ISSUE THREAD

**Issue by stephane-martin** [dgraph-io/badger#496]
Hi,

1 - when iterating over a fresh empty database, the iteration is instantaneous
2 - after inserting quite a lot of key-values (say 1M), the iteration is slower (on my server it can be a few seconds). That's ok and understood.
3 - then delete the all the key values. Perform a GC. Iterate over the (empty again) database. The iteration is not instantaneous. A bit faster than in step 2, but still takes over 1sec.
4 - close the database, reopen it: iteration is a bit faster than in step 3, but still takes almost 1sec.

I understand it has to do with garbage collecting the deleted stuff. Is it possible to get better results ?

Thanks!

**Comment by stephane-martin** [comment]
There is some memory leakage too, probably linked to the recursive calls in yieldItemValue (see also issue 495).

**Comment by stephane-martin** [comment]
The memory leak problem is solved by removing the recursive call in yieldItemValue, but iterating seems to continue to be in linear complexity of *deleted* keys.

**Comment by manishrjain** [comment]
So, garbage collection only works on the value log files. It would consolidate the valid keys, and then delete the old log file. However, what GC doesn't do is to run LSM tree compactions. These compactions are what you need to get rid of keys from the LSM tree. LSM tree compactions happen as new data pours in, and the level sizes increase beyond their limits. There's no other way to "force" a compaction.

If you want to bring your DB to it's cleanest state, you'd need to take a backup and reimport it into a new DB. Or, I had this idea to allow offline LSM tree compactions (https://github.com/dgraph-io/badger/issues/299), which could help with discarding deleted or expired key versions from LSM tree by rewriting it. If you think that tool is useful, you can add a comment there to explain why you need it, and I can prioritize it.
