### ISSUE TITLE
Debug unreasonable "heavy" storage

### ISSUE THREAD

**Issue by Phil192** [dgraph-io/badger#498]
Hi everyone!

Surprisingly I've encountered that my dapp (that use ipfs, but have own badger storage) take all space on my ssd and succesfully crashed. I've found that heaviest file is a .vlog files - 26 Gb. My dapp really do not produce so much data.
Storage files:
```
du -h -all
12K  ./000001.sst
1.1G  ./000018.vlog
1.1G  ./000008.vlog
1.1G  ./000019.vlog
1.1G  ./000024.vlog
1.1G  ./000002.vlog
1.1G  ./000004.vlog
1.1G  ./000017.vlog
1.1G  ./000011.vlog
1.1G  ./000007.vlog
1.1G  ./000023.vlog
1.1G  ./000021.vlog
1.1G  ./000022.vlog
1.1G  ./000020.vlog
36K  ./000003.sst
1.1G  ./000013.vlog
1.1G  ./000005.vlog
1.1G  ./000009.vlog
1.1G  ./000014.vlog
1.1G  ./000015.vlog
1.1G  ./000000.vlog
4.0K  ./MANIFEST
532K  ./000004.sst
1.1G  ./000001.vlog
1.1G  ./000010.vlog
1.1G  ./000016.vlog
319M  ./000025.vlog
1.1G  ./000012.vlog
4.0K  ./LOCK
1.1G  ./000003.vlog
12K  ./000002.sst
1.1G  ./000006.vlog
```
How i can debug db transactions? Is there any tool to see all or trace recent records/versions? Thank you!

**Comment by manishrjain** [comment]
Did you run garbage collection? https://github.com/dgraph-io/badger#garbage-collection

**Comment by Phil192** [comment]
@manishrjain Nope. Should I do it manually?

**Comment by manishrjain** [comment]
You should call it periodically so that Badger would clean up these value log files.

**Comment by Phil192** [comment]
@manishrjain Could your give me advice, please, how often should I call GC? Thank you.

**Comment by manishrjain** [comment]
That depends upon how quickly your data is coming in. You could use for e.g., `DB.Size` method to see the size of the DB, and every time it grows by some size, you could run the value log GC. You could also re-run it whenever value log GC is successful, i.e. returns nil error.

Or, you could just run it periodically based on a timer. There are many ways you can run this, all depends upon your application requirements. Some people choose to run it when there's little activity going on, etc.

**Comment by kkshetty** [comment]
> You could also re-run it whenever value log GC is successful, i.e. returns nil error.

@manishrjain - This is an excellent tip, that should be part of the README.md. Turned out to be really useful for me.

**Comment by manishrjain** [comment]
Done. Added a code sample as well.
