### ISSUE TITLE
Make sure all entries that are part of a transaction are written to the same value log file.

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/badger#500]
This [commit](https://github.com/dgraph-io/badger/commit/b5727f1b8485a1812e3e904216cc01de7346dce5) seems to break the `ValueLogFileSize` API. I'm failing to understand why was this modification introduced, I'm not seeing any comments in the commit, nor is it part of any encompassing PR that would explain its purpose. This should be documented.

**Comment by manishrjain** [comment]
This is to ensure that all the changes for one transaction are part of the same value log file. That we don't split one transaction across two value log files. This is for correctness and simplicity.

**Comment by schomatis** [comment]
> This is to ensure that all the changes for one transaction are part of the same value log file. That we don't split one transaction across two value log files.

I understand *what* the commit is doing, I don't understand *why*. But anyway, this stills breaks API and should at least be documented (if not avoided).

(@manishrjain If it's not too much problem could you allow for some grace period for the author of the issue to respond before closing the issue? I understand that closing doesn't prevent the conversation from continuing, but if feels more natural to have an issue open if we're still actively discussing it.)

**Comment by manishrjain** [comment]
What API does it break? ValueLogFileSize isn't an API, it's just an indication for when we should wrap up the file and start a new one. Badger makes no guarantees that all the value log files must be lower than this number.

Regarding keeping the issue open, this seems more like a question or a discussion than an issue (judging from your opening comment). As you noticed, the discussion can continue, there's no need to keep the issue open.

**Comment by schomatis** [comment]
> ValueLogFileSize isn't an API, it's just an indication

> Badger makes no guarantees that all the value log files must be lower than this number.

Again, this should be clearly documented then. For me, everything the user has interaction with (like one of Badger's options) is part of the Badger API because if its behavior changes that will have a direct impact on the user's code which is expecting a specific behavior from it (like having a value log file within the size indicated with the `ValueLogFileSize` option), there is an implicit contract (IMO).

I guess I can't categorically classify this as a bug (and the issue has already been closed) so I just leave here my comment as feedback from a Badger's user perspective.

**Comment by manishrjain** [comment]
> Again, this should be clearly documented then.

If so, please send a PR to add that documentation. If this is important to you, then you must make that effort.
