### ISSUE TITLE
Storm-like toolkit for Badger?

### ISSUE THREAD

**Issue by ammmir** [dgraph-io/badger#504]
[Storm](https://github.com/asdine/storm) is a toolkit for BoltDB that provides indexes and additional query capabilities. Is anyone working on or knows of a project like that for Badger?

**Comment by manishrjain** [comment]
None that I know of.

**Comment by mkhennoussi** [comment]
A Storm-like toolkit for badger could be very interesting :) Is it on the roadmap ?

**Comment by jpincas** [comment]
I started working on one this weekend: https://github.com/jpincas/tormenta

Its very early days and I have a specific use case in mind (ERP/Ecommerce database), so it might not be exactly what you are looking for.

**Comment by jpincas** [comment]
https://github.com/jpincas/tormenta is a bit more advanced now.  Still more testing and benchmarking needed, but I think it can mostly do what @ammmir was asking for.

**Comment by manishrjain** [comment]
Also see: https://github.com/zippoxer/bow

Closing the issue, because we don't have any plans to build a Storm like toolkit for Badger.
