### ISSUE TITLE
Is DB.Close() necessary if SyncWrites=true?

### ISSUE THREAD

**Issue by brianbwong** [dgraph-io/badger#507]
From the docs:

> Close closes a DB. It's crucial to call it to ensure all the pending updates make their way to disk. 

Is there any potential for data loss if Close() does not get called (eg because of runtime panic) if SyncWrites=true?

**Comment by manishrjain** [comment]
No. There's no potential data loss with SyncWrites=true. Clean `Close()` is highly recommended though.
