### ISSUE TITLE
Dump / View data in the database ?

### ISSUE THREAD

**Issue by ghost** [dgraph-io/badger#508]
What tooling exists to see current data in badger ?

**Comment by manishrjain** [comment]
None right now. I have a branch with some changes, which I wanted to push to a new module under `badger` binary. But, haven't done that yet. It's in `mrjn/debug` branch if you want to contribute.

**Comment by Phil192** [comment]
Hi there! I'm struggling with fetching and reading all data from storage:
`
func viewAll(db *badger.DB) {
txn := db.NewTransaction(false)
defer txn.Discard()
iterOpts := badger.IteratorOptions{false, 0, false, true}
itr := txn.NewIterator(iterOpts)
defer itr.Close()
b := state.NewBucket(state.BucketRecords)
multiBuffer := capn.NewSingleSegmentMultiBuffer()
for itr.Seek(b.NewKey(nil).Bytes()); itr.Valid(); itr.Next() {
    value, err := itr.Item().Value()
    if err != nil {
        log.Fatalln(err)
    }
    read, err := capn.ReadFromMemoryZeroCopyNoAlloc(value, multiBuffer)
    if err != nil {
        log.Fatalln(err) // EOF error
    } else if read != int64(len(value)) {
        panic(fmt.Sprintf("wrong read: %d != %d", read, len(value)))
    }
    vv := proto.ReadRootRecord(multiBuffer.Segments[0])
    out, err := vv.MarshalCapLit()
    if err != nil {
        log.Fatalln(err)
    }
    err = ioutil.WriteFile("cmd/db/content.out", out, 0777|os.ModeAppend)
    if err != nil {
        log.Fatalln("toFile", err)
    }
}
}`
result: **EOF**
As result content.out contains only first (probably first) chunk of data. What am i doing wrong? Thank you!

**Comment by jarifibrahim** [comment]
@manishrjain What kind of information do we want to show to the user? Do we want a complete dump of database, like a list of `key => value`?

**Comment by manishrjain** [comment]
Have a look at Dgraph debug. We need something similar.
