### ISSUE TITLE
db.Close() is very slow (~1 second)

### ISSUE THREAD

**Issue by brianbwong** [dgraph-io/badger#509]
Why does db.Close() take about 1 second even on empty db's? I don't know the details of the implementation, but this seems quite long given that opening and closing a file takes ~100 mics (and surely you're doing less work in Close() than opening 10,000 files). I have about 30 tests, each of which opens up a fresh badger db, so the test suite takes quite a while to run.

```
package main

import (
    "log"
    "github.com/dgraph-io/badger"
    "fmt"
    "time"
)

func main() {
    opts := badger.DefaultOptions
    opts.Dir = "./badger"
    opts.ValueDir = "./badger"

    db, err := badger.Open(opts)
    if err != nil {
        log.Fatal(err)
    }

    start := time.Now()
    db.Close()
    fmt.Printf("Time to close: %s\n", time.Since(start))
}
```

Output:
`Time to close: 879.784689ms`

**Comment by manishrjain** [comment]
DB.Close is a call done once when your program is exiting. We're using it to force an L0 compaction, among other clean up tasks. Optimizing that isn't a priority. Test suite taking over 30 seconds to run, is a pretty fast test suite, I'd say.

**Comment by brianbwong** [comment]
Fair enough, thanks for the explanation.

As a follow-up: I realized that the tests run fine without db.Close() at the end of each test. I was expecting this to cause a "lock in use" error, but presumably what's happening is that when the db goes out of scope it relinquishes its lock. Could you shed more light on this (why it happens and whether it's behavior I can count on)?

**Comment by manishrjain** [comment]
Can't say. Going out of scope is something Go lang hides away from the application. So, we don't explicitly have a trigger to release file locks or anything.
