### ISSUE TITLE
Slice bounds out of range error

### ISSUE THREAD

**Issue by jokerbo1** [dgraph-io/badger#510]
Hello sir:
  now  I use bager error:

> [HTTP Server] http: panic serving 10.70.6.29:29856: runtime error: slice bounds out of range
> goroutine 2288530 [running]:
> net/http.(*conn).serve.func1(0xc4200a10e0)
> 	/usr/local/go/src/net/http/server.go:1697 +0xd0
> panic(0xa87900, 0xf1bdd0)
> 	/usr/local/go/src/runtime/panic.go:491 +0x283
> ep2p/vendor/github.com/dgraph-io/badger.(*valueLog).Read(0xc420184130, 0x43200000000, 0x1e8dd3, 0xc4200f6d00, 0x6f1, 0x0, 0x0, 0x6f1, 0x2c, 0x2c)
> 	/Users/user/Documents/goWorkCode/src/ep2p/vendor/github.com/dgraph-io/badger/value.go:804 +0x332
> ep2p/vendor/github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc4200bcc60, 0xc4257786f8, 0x445a81, 0xc4202a40e4, 0xc, 0x0, 0x42)
> 	/Users/user/Documents/goWorkCode/src/ep2p/vendor/github.com/dgraph-io/badger/iterator.go:137 +0x224
> ep2p/vendor/github.com/dgraph-io/badger.(*Item).Value(0xc4200bcc60, 0xc4202a40c0, 0x24, 0x30, 0xc4200bcc60, 0x0)
> 	/Users/user/Documents/goWorkCode/src/ep2p/vendor/github.com/dgraph-io/badger/iterator.go:89 +0x63
> ep2p/utils.(*Fdb2).Get.func1(0xc420154990, 0xb79fa0, 0xc420154990)
> 	/Users/user/Documents/goWorkCode/src/ep2p/utils/fdb.go:174 +0x96
> ep2p/vendor/github.com/dgraph-io/badger.(*DB).View(0xc420184000, 0xc425778800, 0x0, 0x0)
> 	/Users/user/Documents/goWorkCode/src/ep2p/vendor/github.com/dgraph-io/badger/transaction.go:549 +0xfb
> ep2p/utils.(*Fdb2).Get(0xc42576c058, 0xc42001a2e5, 0x24, 0x0, 0x0, 0xc42001a2e5, 0x24)
> 	/Users/user/Documents/goWorkCode/src/ep2p/utils/fdb.go:169 +0x81
> main.gettaskResult(0xefaa20, 0xc420154120)
> 	/Users/user/Documents/goWorkCode/src/ep2p/ep2p_server/server.go:360 +0xb4

Description:
   i use badger memory task info  ,before two month run well , today  i want get value by key ,prompt this message ,the key is a uuid ,value is a jsontext ,i dont know how to repeat this problem,wish help you solution this problem.

**Comment by jokerbo1** [comment]
@deepakjois @fjl @hnakamur @KevBurnsJr @maxpert

**Comment by manishrjain** [comment]
The code lines mentioned here don't seem to match up. What version of Badger are you on? Also, how do we reproduce this.

**Comment by jokerbo1** [comment]
Sorry ,I dont know how to reproduce this.
```
func (f *Fdb2) Get(k string) (val string, e error) {
	log.Println("key: ",k)
	err := f.Stor.View(func(txn *badger.Txn) error {
		item, err := txn.Get([]byte(k))
		if err != nil {
			return err
		}
		v, err := item.Value()
		if err != nil {
			return err
		}
		val = string(v) //fmt.Printf("The answer is: %s\n", val)
		return nil
	})

	if err != nil {
		return "", err
	}
	return
}
```
the error prompt  this line get value slice range out.
> item.Value

**Comment by manishrjain** [comment]
Can you update your Badger version to the latest v1.5.1?

**Comment by jokerbo1** [comment]
Ok ,after repeat this issue submit it,i will close.
