### ISSUE TITLE
Key Not Showing Up in Prefix Scan 

### ISSUE THREAD

**Issue by dc0d** [dgraph-io/badger#512]
Doing a prefix scan for a prefix like `^d91c3bef076f8580<^g` includes a key such as `^d91c3bef076f8580<^golang`.

But a prefix like `^d91c3bef076f8580<^n` does not include a key like `^d91c3bef076f8580<^nosql`.

Why is that so?

Code: I was playing around implement a generic way for secondary indexes and [here](https://github.com/dc0d/kvv/blob/024943ffb4082661092e11369cd3ad45a32102c0/kvv_usage_test.go#L204) is the code that shows this behavior.

**Comment by dc0d** [comment]
@manishrjain Thanks for the follow up!

Here is the [code](https://gist.github.com/dc0d/85f9a556a7527b2620c8060f5332c5ed) and the badger commit is `cdf9ffb40fde980875360cf2b1f7d66946fdc769`.

**Comment by manishrjain** [comment]
Badger is doing the right thing. You have two keys, you seek to the first one, which fails `ValidForPrefix`; so the iteration stops. The same happens twice. And then you seek to the keys specifically, with the same prefix as the key has, so it works.

I think you might be confusing `ValidForPrefix` functionality. It would stop on the first encounter with a key which doesn't have that prefix. It won't just skip over those records.
