### ISSUE TITLE
Doubt about Prefix Scan performance

### ISSUE THREAD

**Issue by Inkeliz** [dgraph-io/badger#513]
I'm a little confusing how the Prefix Scan works, or maybe the Badger at all works. I'll try to explain my case of use,, but it can be completly wrong.

I would like to have "two values" as the key, suppositly like `[user_id][random_id]`, both have the same size (32 bytes), for simplicity consider: `AAABBB`. So, possible to access the value givin the `user_id` and `random_id`, which leads us to somenting like `txn.Get([]byte{"AAABBB"})`, that is ok.

However, if I need to get all values from a specific user, I can use the `Prefix Scan` to get all contents that begin with "AAA", which is the user.

Most of calls will get the value directly, givin the full key ("AAABBB"). But, some calls need to list all data, that is the point.

How expensive is the `Prefix Scan`, compared to a single access using the "full key"? It'll iliterate all the keys/values one-by-one?

**Comment by manishrjain** [comment]
Iteration would always be more expensive than a single key lookup. You could try it out and see if you can find the balance between functionality and performance.
