### ISSUE TITLE
Potential deadlock in value log

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#515]
Saw this happening. This could be due to some other bug (move keys), or due to improper logfile locking in value log.

```goroutine 6217500 [semacquire, 17 minutes]:
sync.runtime_Semacquire(0xc4672ce6d8)
	/usr/lib/go-1.10/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).Lock(0xc4672ce6d0)
	/usr/lib/go-1.10/src/sync/rwmutex.go:98 +0x6e
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*logFile).doneWriting(0xc4672ce6c0, 0x5bb227e, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:156 +0x7c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).write.func1(0x11b7c40, 0xc48529ff50)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:854 +0x289
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).write(0xc4201b39c8, 0xc48eecb000, 0x753, 0x900, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:898 +0x36e
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).writeRequests(0xc4201b3880, 0xc48eecb000, 0x753, 0x900, 0xc47d1ce600, 0xc4822c3180)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:585 +0xfe
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc48eecb000, 0x753, 0x900)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:651 +0x55
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).doWrites
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:700 +0x327

---
goroutine 6030265 [semacquire, 17 minutes]:
sync.runtime_Semacquire(0xc4672ce6dc)
	/usr/lib/go-1.10/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc4672ce6d0)
	/usr/lib/go-1.10/src/sync/rwmutex.go:50 +0x49
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).getFileRLocked(0xc4201b39c8, 0x12, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:919 +0xc6
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).readValueBytes(0xc4201b39c8, 0x5b00000012, 0xc400adc6e1, 0xc4a35c9ac0, 0xdad86c, 0x81e, 0x2, 0x0, 0x9, 0x4)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:944 +0x40
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).Read(0xc4201b39c8, 0x5b00000012, 0xadc6e1, 0xc4a35c9ac0, 0xc466316d50, 0x7f051aaa0109, 0xf, 0xc4716f8e00, 0xc47d13ea58, 0xad9250)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:933 +0x8b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc4c5a1a840, 0x0, 0xc4915da000, 0xb, 0x7f06f5bc16c8, 0x0, 0xc47d13eb70)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:162 +0x16b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).Value(0xc4c5a1a840, 0x17, 0x20, 0xc478f37740, 0x17, 0x20)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:103 +0x63
github.com/dgraph-io/dgraph/posting.ReadPostingList(0xc478f37740, 0x17, 0x20, 0xc4bd598f50, 0x7f06f5bc16c8, 0x0, 0x8b3f12)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:411 +0x22d
github.com/dgraph-io/dgraph/worker.(*grpcWorker).PredicateAndSchemaData.func2(0xc478f37740, 0x17, 0x20, 0xc4bd598f50, 0x17, 0xc478f37740, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/predicate.go:253 +0x28f
github.com/dgraph-io/dgraph/worker.(*streamLists).produceKVs.func1(0xc4406e1d70, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/stream_lists.go:150 +0x306
github.com/dgraph-io/dgraph/worker.(*streamLists).produceKVs(0xc46aa1b320, 0x13103a0, 0xc46aa1af90, 0xc4386378c0, 0xc43b007c20, 0xc43b3a2060, 0x0, 0xc4865a7fb0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/stream_lists.go:169 +0x233
github.com/dgraph-io/dgraph/worker.(*streamLists).orchestrate.func1(0xc4406e1ae0, 0xc46aa1b320, 0x13103a0, 0xc46aa1af90, 0xc4386378c0, 0xc43b007c20, 0xc43b3a2060, 0xc43b3a20c0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/stream_lists.go:54 +0x94
created by github.com/dgraph-io/dgraph/worker.(*streamLists).orchestrate
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/worker/stream_lists.go:52 +0x19a
```

**Comment by prune998** [comment]
I never had an error log for that but I can confim that after 1.4.0 release I started having some deadlocks. 
After adding some more debug I found it was during the closing of a vlog file/ re-opening it read only. 
Specificaly the `doneWriting` func in `value.go`, line 155. Sometimes the `lf.lock.Lock()` never return.

I can't see what's preventing it though...

**Comment by manishrjain** [comment]
Can you try from master? I just pushed a change y'day, which would panic on multiple / unclosed iterators in a txn, which is what could be causing this deadlock. It would help find issues in your code (it did in Dgraph).

**Comment by manishrjain** [comment]
Update: I think this commit solves this issue: https://github.com/dgraph-io/badger/commit/b1ad1e93e483bbfef123793ceedc9a7e34b09f79

**Comment by manishrjain** [comment]
Made a release v1.5.2 with these fixes. Closing the issue for now.

@prune998 : If you see this with v1.5.2, feel free to reopen the issue.

**Comment by prune998** [comment]
seems to be working as expected ! thanks !

**Comment by prune998** [comment]
Sorry @manishrjain I responded too early. The issue on my side is still there. At some point Badger tries to close a vlog file and stays waiting for the mutex lock.
I reach no error or pannic... 

As this operation is supposed to be running in a single goroutine, I don't see where it could be. Obviously a `-race` gave nothing too. 
Changing GOMAXPROCS to 1 sometimes solve the issue but it really depends... adding some delays or heavy logs in the code also resole the issue, sometimes. it looks like a race but I have no clue.... and it's working with 1.4.0

**Comment by manishrjain** [comment]
Any way to reproduce it?

**Comment by prune998** [comment]
Sadly not really... We parse some OpenstreetMap Protobuf files and index them in transactions. The deadlock happen with any file, whatever size it is.

Badger is opened (created as I remove the DB files between each run) like : 
```
	opt := badger.DefaultOptions
	opt.Dir = *dbdir
	opt.ValueDir = *dbdir
	kv, err := badger.Open(opt)
	if err != nil {
		log.Fatal(err)
	}

	defer kv.Close()
```
Then we have 3 indexing passes. Each pass read the Protobuf file and index some points using `Txn.Set(key,val)`. Then every 2000 point we `Txn.Commit(nil)` and `KV.NewTransaction(true)`
The 3rd pass we use another transaction to do some Gets like : 
```
                         txn := h.KV.NewTransaction(false)
			defer txn.Discard()

			for _, nID := range w.NodeIDs {
				i, err := txn.Get(nID)
				if err != nil {
					log.Fatal(err)
				}
```

Each step ends with : 
```
	h.Lock()
	defer h.Unlock()

	// finishing batch
	if h.count > 0 {
		err := h.Txn.Commit(nil)
		if err != nil {
			log.Fatal(err)
		}
	}
	h.Txn.Discard()
}
```

The lock seem to have nothing to do with our code. I've added lots of debug in Badger, and it really happen at the moment where the `vlog` file is too big (size or number of entries) and another one is created.
I really can't explain this issue.
It sometimes work, depending on the server, the number of CPU, and does not depend on the Protobuf file we are parsing...

**Comment by manishrjain** [comment]
Are you using the latest version 1.5.2? If it's locking when a value log is being rewritten, that indicates that some read has failed to release the read lock on the file, which might be due to an unclosed iterator, or another open long-running transaction.

**Comment by prune998** [comment]
What I understand is that Badger have a goroutine that is responsible to trigger the vlog change when the size is reached, independently of the current transactions, right ? 

I do use 1.5.2 for testing since yesterday.

We're not using `txn.NewIterator()` at all, so I think I can eliminate this issue.
I do have opened transactions (I think), but Badger should be able to write everything that was commited right ?

**Comment by manishrjain** [comment]
If you can provide a way to reproduce this, I can have a look. I haven't seen this happen otherwise.

Maybe I can run your code if you'd like to share it with me privately.

**Comment by prune998** [comment]
@manishrjain that's something I did some weeks ago, and it worked. But as my issue seems to disappear when the code is changed, I wasn't sure it was due to the mmap.
My guess is still that it is...
In all the tests I made, one was to unlock before lock (which lead to a panic, obviously) just to prove the file wasn't locked before...
```
        lf.lock.Unlock()
	lf.lock.Lock()
	defer lf.lock.Unlock()
```

Here is how I changed the code in `vendor/github.com/dgraph-io/badger/value.go` : 
```
func (lf *logFile) doneWriting(offset uint32) error {
        // Sync before acquiring lock.  (We call this from write() and thus know we have shared access
        // to the fd.)
        if err := lf.fd.Sync(); err != nil {
                return errors.Wrapf(err, "Unable to sync value log: %q", lf.path)
        }
        // Close and reopen the file read-only.  Acquire lock because fd will become invalid for a bit.
        // Acquiring the lock is bad because, while we don't hold the lock for a long time, it forces
        // one batch of readers wait for the preceding batch of readers to finish.
        //
        // If there's a benefit to reopening the file read-only, it might be on Windows.  I don't know
        // what the benefit is.  Consider keeping the file read-write, or use fcntl to change
        // permissions.
        fmt.Println("locking")
        lf.lock.Lock()
        fmt.Println("done locking")
        defer lf.lock.Unlock()
        if err := lf.munmap(); err != nil {
                return err
        }
...
```
And here is the log of the application : 
```
rm db/* ; time docker run -ti --rm --entrypoint=/root/osmparsernodedb  -v /opt/data/osrm/frbeca:/data osmindexer/osmdbd:ec510076 -filename /data/belgium-latest.osm.pbf -dbdir /data/db -debug

locking
done locking
locking
done locking
locking
done locking
2018/06/21 11:53:58 pass 1 finished
locking
done locking
locking
done locking
locking
done locking
2018/06/21 11:54:15 pass 2 finished
locking   <--------------------------------- application deadlock here


^C
real    4m2.113s
```

Here is the log when it's working, exact same code, same docker image, same files... It's just that once and a while it's working...
```
rm db/* ; time docker run -ti --rm --entrypoint=/root/osmparsernodedb  -v /opt/data/osrm/frbeca:/data osmindexer/osmdbd:ec510076 -filename /data/belgium-latest.osm.pbf -dbdir /data/db -debug
locking
done locking
locking
done locking
locking
done locking
2018/06/21 11:45:27 pass 1 finished
locking
done locking
locking
done locking
locking
done locking
2018/06/21 11:45:44 pass 2 finished
locking
done locking
2018/06/21 11:45:56 pass 3 finished

real    0m56.318s
```

**Comment by manishrjain** [comment]
I'd say that you should try to isolate this from your application, by creating a standalone program which can reproduce this. Most likely, this might be because of how you're using transactions, as opposed to a bug in Badger itself.
