### ISSUE TITLE
out of memory error when opening specific database

### ISSUE THREAD

**Issue by JAicewizard** [dgraph-io/badger#517]
I updated my server stuff that uses badger today, when running badger on a specific database it crashed.
Since this system is relatively new, and the database is still empty I removed the database from that folder and tried again, even that failed.
This is the third database opened by our program, this used to work fine before.
This is the output of the program, up until it crashes.
https://pastebin.com/vwhzsPAf

All it does is registering some GOB objects, and opening the database.
I did a memory pprof just before the line of the crash, but that just gives a total a 90MB, so that cant be it.

**Comment by manishrjain** [comment]
You're running out of memory. To decrease memory, you can tweak the Badger options. Look at https://github.com/dgraph-io/badger#memory-usage

**Comment by JAicewizard** [comment]
this exact same solution worked before, it uses 80-90MiB for the first 2 (populated) databases, only the completely empty, and the freshly generated database uses over 1GiB of RAM.
I dont see how that is something you want.

**Comment by manishrjain** [comment]
Each Badger instance would have some overhead in memory usage. Again, you can use the options to try to decrease that.
