### ISSUE TITLE
Is MergeOperator safe with limited options.NumVersionsToKeep?

### ISSUE THREAD

**Issue by pcjdean** [dgraph-io/badger#520]
Is that possible the data not compacted by MergeOperator are compacted by compactBuildTables? Therefore, there is data loss.

**Comment by jarifibrahim** [comment]
@pcjdean Yes, that is possible. The main compaction might delete older values during compaction.

**Comment by jarifibrahim** [comment]
This should be fixed by https://github.com/dgraph-io/badger/pull/794

**Comment by jarifibrahim** [comment]
@pcjdean We've fixed this and it's in master. Please do give it a try.
