### ISSUE TITLE
bug: backup / restore creates zombies

### ISSUE THREAD

**Issue by Scapal** [dgraph-io/badger#521]
When restoring a backup, previously deleted keys are back, just without a value.
They should stay deleted.

**Comment by mame82** [comment]
Same here, hackish workaround:
- load backup in temporaray DB
- iterate over key-value-pairs of temp DB
- update Set(k,v) in target db only if valu from temp DB has len(val) > 0

Having deleted keys around is a big issue

**Comment by manishrjain** [comment]
Hmm... Will look into this.

**Comment by manishrjain** [comment]
Looks like the code doesn't take into account deleted keys or discard earlier versions. Need to add a test case and fix the code.

**Comment by Scapal** [comment]
Could we just filter out expired and deleted items?

```
if item.Version() < since {
				// Ignore versions less than given timestamp
				continue
			}
if item.IsDeletedOrExpired() {
   // Ignore deleted or expired items
   continue
}
```
