### ISSUE TITLE
Enable truncation in non Windows environments

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/badger#523]
During a corrupted database `Replay()`, where a truncation operation is needed, there is an extra check (besides the `--truncate` flag) for Windows environments, that the value log is not loaded with `mmap`: [`len(lf.fmap) == 0`](https://github.com/dgraph-io/badger/blob/master/value.go#L327). In a Linux environment this check still holds (it's not discriminated) and it would appear to prevent a DB truncation even if the truncate flag is set, see https://github.com/ipfs/go-ipfs/issues/5213. An indication of this is the fact that setting the `ValueLogLoadingMode` to `FileIO` seems to fix it, permitting the truncation to take place.

Furthermore, if the truncation is not allowed, the [error message](https://github.com/dgraph-io/badger/blob/master/errors.go#L98) does not reflect *why* is the truncation not allowed and it gives the impression to the user that the (already set) `-t` flag is needed.

**Comment by schomatis** [comment]
Sorry for the delay, the code I was referring to and its link is available in the initial post, just after the text you quoted.

**Comment by manishrjain** [comment]
Yes, I saw that yesterday. Will fix this one.

**Comment by manishrjain** [comment]
This should now be fixed with the refactoring that happened recently. Badger would replay and truncate files before memory mapping them, this should work in Windows as well.
