### ISSUE TITLE
Truncation error: invalid argument

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/badger#524]
During a truncation call in a corrupted DB the following error was encountered,

```
Unable to replay value log: "badgerds//000017.vlog": truncate badgerds//000017.vlog: invalid argument
```

leaving the DB in an unrecoverable state. See https://github.com/ipfs/go-ipfs/issues/5213#issuecomment-403937390.

**Comment by manishrjain** [comment]
Need more details.

**Comment by schomatis** [comment]
Yes, on it.

**Comment by manishrjain** [comment]
Any more details here? I'm not sure how to even start to debug this. Most likely, this is an issue with the file system, which might not be supporting truncate.

**Comment by schomatis** [comment]
I'm waiting on @lgierth to provide more information but he may be too busy at the moment so I'm going to close this and we'll reopen when we can provide you more details to work on.

**Comment by schomatis** [comment]
Reopening as we were able to provide access to the DB.

**Comment by schomatis** [comment]
This seems to be a problem on the IPFS side, closing here.
