### ISSUE TITLE
Why does the first write take 20 times as long as the second one?

### ISSUE THREAD

**Issue by brianbwong** [dgraph-io/badger#528]
When doing a series of synchronous write, I find that the first one is quite slow at ~10ms and the subsequent ones are faster. Why is this? Is there some warm-up operation that can be moved into db initialization?

Not a huge deal, but I got a little worried when I just benchmarked one write and thought that every write might be taking 10ms. 

```
package main

import (
    "log"
    "github.com/dgraph-io/badger"
    "fmt"
    "time"
)

func main() {
    opts := badger.DefaultOptions
    opts.Dir = "./badger"
    opts.ValueDir = "./badger"
    opts.SyncWrites = true

    db, err := badger.Open(opts)
    if err != nil {
        log.Fatal(err)
    }

    start := time.Now().UnixNano()

    for i := 0; i < 10; i++ {
        txn := db.NewTransaction(true)
        err = txn.Set([]byte(fmt.Sprintf("obj %d", i)), []byte("hello"))
        if err != nil {
            log.Fatal(err)
        }
        err = txn.Commit(nil)
        if err != nil {
            log.Fatal(err)
        }
        txn.Discard()

        end := time.Now().UnixNano()
        fmt.Printf("%d ", end-start)
        start = end
    }
}
```

Output: `8673625 390764 349725 439390 368219 348387 367550 349595 403517 322622`

**Comment by manishrjain** [comment]
Hard to say why you're seeing the first write having more latency than others. But, in general, if you intend to do benchmarking of writes, I'd highly recommend using callbacks for dur commits.

`txn.Commit(cb)`, instead of nil. I'll add an example for how to use callbacks, they produce the highest write throughput achievable via Badger.

**Comment by manishrjain** [comment]
Updated the question about writes being slow:
https://github.com/dgraph-io/badger#frequently-asked-questions

**Comment by eastrd** [comment]
I'm experiencing similar problem, except for me it's the first query after a long time of inactivity takes significantly longer time than subsequent queries. 

To elaborate, I have a large pool of badger db connections and first query would always take minutes whereas subsequent queries would only take a few seconds. 
All options are default, this even happens with one connection as well, which lead me to think there is highly likely some kind of warmup operation going on.
