### ISSUE TITLE
Callback when a key expires

### ISSUE THREAD

**Issue by sathyanarayanant** [dgraph-io/badger#529]
I would like to keep track of the number of keys in the database. When a key is created it may be created with a TTL. Is there a way to specify a callback function that will be called when a key is going to deleted because of expiry ? 

I looked at the documentation, and could not find this feature.

**Comment by manishrjain** [comment]
There's no exact moment in time when a key is deleted. If a key is expired, Badger would just not return it anymore, and later when compaction happens, that key would be discarded. So, there's no way for Badger to make a callback on the exact moment when a key "expires".

You could, however, do a key-only iteration over Badger periodically, asking for `AllVersions` during iteration. That'd return the expired/deleted versions too. Then based on how long ago they expired and how often your iteration happens, you could run the callbacks.
