### ISSUE TITLE
Allow to store the value log in another directory then the rest of the files

### ISSUE THREAD

**Issue by zaibon** [dgraph-io/badger#53]
What would be the consequences of having the value log in another directory then the rest of the files ?
I'm thinking to have two kind of disk, one for the LSM tree and one for the value log. I was thinking to use a slower disk for the value log to lower the cost again. 

I dived into the code a bit and have a PR ready to enable his feature if you are interested.

**Comment by manishrjain** [comment]
Sure, send me the PR.
