### ISSUE TITLE
calculateSize Crashed 

### ISSUE THREAD

**Issue by guijun** [dgraph-io/badger#530]
<img width="687" alt="wechatimg1223" src="https://user-images.githubusercontent.com/4198234/42792258-07f61b30-89a7-11e8-8fb8-01ba52ab00f9.png">

**Comment by guijun** [comment]
btw, OS is macosx 10.13.5

**Comment by manishrjain** [comment]
Closing this issue for now. Feel free to reopen, if you think there's something wrong at Badger end.
