### ISSUE TITLE
Deadlock at logFile.doneWriting

### ISSUE THREAD

**Issue by gutweiler** [dgraph-io/badger#531]
If a valuelog reaches its filesize limits, `logFile.doneWriting` will obtain a RWLock for reopening the file in read-only mode.

If there are iterators currently accessing the values, the file will never be closed, and all read/writes to this store are blocked.

only happens with `ValueLogLoadingMode: options.MemoryMap` and iteration option `opts.PrefetchValues = false`. (at least i cannot reproduce it with FileIO or just PrefetchValues)

we observed this issue rarely under load, this is a unit-test who reproduces it on each run:

[write_test.go.txt](https://github.com/dgraph-io/badger/files/2201014/write_test.go.txt)

[traces.txt](https://github.com/dgraph-io/badger/files/2201016/traces.txt)

**Comment by paulftw** [comment]
hi @gutweiler thank you for a well documented bug report. we will take a look

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger#frequently-asked-questions

Have a look at the top question there: My writes are getting stuck. It seems like that's what you're experiencing.

**Comment by gutweiler** [comment]
Yep, that is the case.

How do you define "long running iteration"? Each iteration of the test finishes in less than 10ms.

The use of .Value() inside a non-prefetched iterator and mmap will end up in an Lock, sooner or later.

It would be nice if the documentation of Value() would mention that, or the behaviour of .ValueCopy() would be used in this use-case.

**Comment by manishrjain** [comment]
With the changes to `Value` now taking a function, `doneWriting` should no longer block.
