### ISSUE TITLE
More document on how to integrate with Prometheus

### ISSUE THREAD

**Issue by pzhao5** [dgraph-io/badger#534]
I am a little confused by the expvar in Badger that it expose.

What is the right way to integrate that value into Prometheus? Any sample code will help a lot

**Comment by manishrjain** [comment]
Think those values should be in `/debug/vars` or something. Prometheus should be able to parse them from that page.

**Comment by qrpike** [comment]
This would really be great to see how to implement. A very basic example would be extremely helpful.
