### ISSUE TITLE
Readme wrong...

### ISSUE THREAD

**Issue by gedw99** [dgraph-io/badger#537]
Zerotier no longer uses badgerdb . They moved on to a custom db of their own

**Comment by manishrjain** [comment]
There is no Zerotier in the list of users. There is 0stor. Their Github page mentions that they're using Badger.
https://github.com/zero-os/0-stor

**Comment by gedw99** [comment]
But they are not anymore.

**Comment by manishrjain** [comment]
Emm... link to some PR which removes Badger?

**Comment by gedw99** [comment]
sorry my mistake. Its another one of their clients that stopped using it.
