### ISSUE TITLE
Changing expiry/metadata without changing value

### ISSUE THREAD

**Issue by sathyanarayanant** [dgraph-io/badger#538]
Hi,

Is there a way to just update the expiry/metadata of the key without changing the value ?

I could so something like - 
```
item, _ := txn.Get(key)
value, _ := item.Value()
txn.SetWithTTL(key, value, nowPlus1Day)
```

but this incurs the cost of Getting the value even though I am not changing it. 

Is there a better way ?

**Comment by manishrjain** [comment]
LSM trees are immutable. You can't update anything in place.
