### ISSUE TITLE
Transaction Conflict

### ISSUE THREAD

**Issue by C-ollins** [dgraph-io/badger#539]
Hello, I ‘set’ to a transaction multiple times and ‘get’ once before committing and I got a conflict for doing that. I’m not sure what I did wrong here and I’m confused on how to fix this error. What is causing the conflict here?

**Comment by manishrjain** [comment]
If you get and set the same key, using different transactions concurrently, they might have conflict. Can't help any further without looking at the code.

**Comment by C-ollins** [comment]
It's a large code base that was already using bolt. I'm creating a driver for badger and I can't tell where the writes or reads are coming from. I fixed it by using a ManagedDB and using a commtTs of 1 always.

**Comment by manishrjain** [comment]
ManagedDB is playing with fire, you can get burnt in strange ways. So, be careful. I'd recommend against using it.

Simple thing to do would be to retry the transaction on a conflict.

**Comment by C-ollins** [comment]
How do I retry? Calling commit again?

**Comment by manishrjain** [comment]
I don't know your code, but if you're using `db.Update`, running that in a loop would do.
