### ISSUE TITLE
bug: int overflows on 32-bit arch

### ISSUE THREAD

**Issue by badgerissues** [dgraph-io/badger#54]
$ go get -u -a "github.com/dgraph-io/badger/badger"
    # github.com/dgraph-io/badger/table
    ./builder.go:113: constant 4294967295 overflows int
    ./builder.go:192: constant 4294967295 overflows int
    ./iterator.go:162: constant 4294967295 overflows int

     $ go version
    go1.8.1 linux/386

Symptom of sloppy coding. You might want to `grep -RI "int$" .` and verify that all variables have correct primitives and bounds.

**Comment by szymonm** [comment]
Thanks for reporting.

Resolved by #56
