### ISSUE TITLE
db.Size() returns zero values before first db.Close()

### ISSUE THREAD

**Issue by wvh** [dgraph-io/badger#544]
Hello,

When I create a new database and fill it with thousands of keys, db.Size() still returns `0, 0` for the LSM and value log sizes until I close the database for the first time. `SyncWrites` is true and the values have been written to the disk.

Is there some sort of hard Flush() functionality I'm overlooking? I've checked the db.Close() code, but there is not a whole lot that can be called from outside the badger code.

**Comment by manishrjain** [comment]
If you want to estimate the size of the DB, better to do a key-only iteration over all the versions, and sum up the item.EstimatedSize().
