### ISSUE TITLE
Badger Configurations

### ISSUE THREAD

**Issue by C-ollins** [dgraph-io/badger#545]
I have tried tweaking the options of badger but I basically don't know what is going on there. I'm using badger on mobile and I get memory crashes. What configuration would you suggest for a 400mb(max) database running on a 200mb memory allocations.

**Comment by manishrjain** [comment]
What options are you trying?

**Comment by C-ollins** [comment]
```
opts := badger.DefaultOptions
opts.Dir = dbPath
opts.ValueDir = dbPath
opts.ValueLogLoadingMode = options.FileIO
opts.TableLoadingMode = options.FileIO
opts.ValueLogFileSize = 209715200
opts.MaxTableSize = 209715200
opts.LevelOneSize = 209715200
opts.NumMemtables = 2
```
This is the current one I'm using. I have tried different tweaks. I used lesser values and the database became very slow.

**Comment by manishrjain** [comment]
You should decrease the MaxTableSize to 4MB. Decrease NumCompactors to 1. NumLevelZeroTables to 1. NumLevelZeroTablesStall to 2. NumMemtables to 1. You can still keep TableLoadingMode to mmap.

**Comment by C-ollins** [comment]
Thanks. I looked at the app ram usage while running. Normally it goes straight up till it crashes but after applying this changes it still went up and it dropped several times. Didn't crash tho

**Comment by C-ollins** [comment]
Celebrated too early. I tested it with more data and I couldn't commit because transaction size was too big.  I guess I have to increase MaxTableSize to maybe 40mb could be enough because I'm unaware of the size of data that can come in.
