### ISSUE TITLE
Open db failed

### ISSUE THREAD

**Issue by BeaverCC** [dgraph-io/badger#546]
Hello,

I use badger for image storing. Badger acts great when I keep store image to a single db. But when it hit 6.1T. I close the db, but can never open that db again. The message is 
```
Unable to open value log: Unable to map file: cannot allocate memory
``` 
Can i open that large db in some way?

My server has 64GB memory, and 128GB swap.

**Comment by manishrjain** [comment]
Have a look at this:
https://github.com/dgraph-io/badger#memory-usage
