### ISSUE TITLE
Missing Prev() method on the Iterator?

### ISSUE THREAD

**Issue by ivanjaros** [dgraph-io/badger#547]
I am implementing KV store as underlying storage for structured data and I need to be able to filter the data based on the usual SQL conditions. I have just realized that after I have implemented the `>` and `>=` that I cannot implement `<` or `<=` because the iterator lacks the **Prev()** method.

So for example if my key is `/foo/123` and my condition is `>= 123`, I can simply write for loop with `iterator.Seek(/foo/123), iterator.ValidateForPrefix(/foo/), iterator.Next()` which would give me` /foo/124`, `/foo/125` and so on. But I simply cannot go from `/foo/123` to `/foo/122` due to missing `Prev()` method. I could simply start at the `/foo/` prefix but that means I will be going through a ton of keys that won't match the condition.

I fail to see why the Prev() method hasn't been implemented yet, any info on this?

**Comment by manishrjain** [comment]
You can use reverse iteration, via IteratorOptions.

**Comment by ivanjaros** [comment]
**Thanks**, will have a look. But why so complicated?

**Comment by manishrjain** [comment]
A `Prev` method adds significant complexity to the codebase, which is why it was omitted. We have no plans to add it. You can work around it with a reverse iteration as mentioned above.

**Comment by C-ollins** [comment]
I feel that’d slow down the code when iterating through tons of data

**Comment by manishrjain** [comment]
Badger's key-only iteration is blazing fast, so it might not be that bad.
