### ISSUE TITLE
More than one iterator?

### ISSUE THREAD

**Issue by C-ollins** [dgraph-io/badger#548]
I have an implementation that uses iterators concurrently. Is there a way to achieve this since I can only open on iterator? I also get an error that an iterator wasn’t closed but I assigned a uuid to every transaction and I printed it out when iterators are opened and closed. Every iterator seems closed but I still get the error

**Comment by ivanjaros** [comment]
That doesn't make any sense. Use concurrent transactions, not iterators. If you need write transaction then simply chan the logic.

**Comment by C-ollins** [comment]
OK. I'd use that. How about the "Unclosed Iterator" that I didn't open? How does that happen. I track every opening and closing and I don't see any unclosed iterator from my side.

**Comment by manishrjain** [comment]
See this: https://github.com/dgraph-io/badger/issues/522

It could be that you're discarding the transaction before closing iterator. Try to see if you can find some ordering issue in your code, potentially by checking defers.

**Comment by C-ollins** [comment]
I created a struct which contains my transaction and iterator. Whenever discard is called, I close the iterator and I get error.

**Comment by ivanjaros** [comment]
Collins - just use defer iterator.Close() within transaction and you should be fine. seems you have logic ordering issue, this should take care of it.

**Comment by C-ollins** [comment]
Okay, Thanks.
