### ISSUE TITLE
Function to query a single node by name takes time.

### ISSUE THREAD

**Issue by AJAviJain** [dgraph-io/badger#559]
Dgraph version :- v1.0.8 and using Windows - 16GB RAM

schema :- name: string @index(term, trigram) . 

suppose there are 2 nodes >> "abc" and "abc 123".

Now i want to get a node "abc" by name.

query1 >> {node (func: eq(name, "abc") {uid name}}
query2 >> {node (func: allofterms(name, "abc") {uid name}}

query1 is giving the exact node but takes time and it's case sensitive.
query2 is giving both the nodes.

I want to use "term" type, as i will need it for searching and other things so i can't use "exact" type. and also due to it's case sensitive so that's not recommended.

There must be a way to get a node by name and name can be case insensitive and should give the node exact matching the name.

**Comment by manishrjain** [comment]
This is a Dgraph issue. Please bring this up on https://discuss.dgraph.io.
