### ISSUE TITLE
Poor performance of Dgraph for Sample  case ? Check if implementation is wrong ?

### ISSUE THREAD

**Issue by AJAviJain** [dgraph-io/badger#560]
Looks Like getting and creating 50k nodes, not achievable in 1 sec with latest dgraph java.

Windows >> 16 GB RAM and Dgraph version >> v1.0.8

Server config >>
https://pastebin.com/XSY5FwkV

Sample JAVA code to reproduce >>
https://pastebin.com/WBfzkdJ1

Results >>
Writes :- 50k nodes in batch Took 15.16 mins
              50k nodes one by one Took 72sec
Reads :- Getting 1 lac nodes one by one Took 2.17 mins

Help me with JAVA implementation to crack this in mili seconds, i may be implementing in wrong way.

**Comment by manishrjain** [comment]
This is a Dgraph issue. Please bring this up on discuss.dgraph.io
