### ISSUE TITLE
Remove 2 variables assignment

### ISSUE THREAD

**Issue by ntrrg** [dgraph-io/badger#564]
Hi, the first example from the [Managing Transaction Manually](https://github.com/dgraph-io/badger/tree/b65e2a3f653cc42acc70ae9eba104de990986c84#managing-transactions-manually) section has a 2 variables assignment.

![image](https://user-images.githubusercontent.com/6060009/45526532-8134ad00-b7a5-11e8-9cf0-3e21908a62a1.png)

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger/commit/8a9c3174148b220d3677dcd9bae9a596c21d4129
