### ISSUE TITLE
Read-only mode inquiry

### ISSUE THREAD

**Issue by mfridman** [dgraph-io/badger#567]
There is an `opts.ReadOnly` mode, but it only works if ALL processes are accessing badger in a read-only manner _and_ no other process has a lock on the directory.

Would it be possible for 1 (long-lived) process to acquire a lock on the directory and then allow multiple other processes to open the DB in a read-only manner?

E.g., suppose we have a single producer running in its own process generating data. We then have a number of short-lived clients opening badgerDB in a read-only manner to check said-data. (there would obviously be a penalty loading the data from disk, but that's okay)

The suggestion here is to allow short-lived clients to open badgerDB in a read-only manner as a snapshot. *Not* for clients to acquire a read-only connection that's "updated" or "synced", i.e., replicated.

Thoughts?

**Comment by manishrjain** [comment]
Sorry, that won't be possible. If you want to have multiple readers, it's better to just open one RW Badger, and have it service all the read/write requests originating from many different sources. Different processes should not be using Badger directory as a common point of communication, instead, the process running Badger should be that hub.

**Comment by mfridman** [comment]
@manishrjain Fair enough, thanks for this great package.
