### ISSUE TITLE
Item expiresAt becomes 0 everytime restarting Badger

### ISSUE THREAD

**Issue by WangBeyond** [dgraph-io/badger#569]
Everytime after I restart my service which is using badger. When I do iteration over all the items, I found the expireAt become 0 while other data like keys, meta, version and values are not.
I feel like expireAt of the items are stored in a separate place and not flushed to disk somehow. Any advice?

**Comment by Hamper** [comment]
I also have this problem when application closed without db.Close() after write key with ttl (e.g. application killed).  Are you found any workaround for this issue, or use Close() and hope, that application under no circumstances will not be killed?
