### ISSUE TITLE
Sync Access from Other goroutine

### ISSUE THREAD

**Issue by dc0d** [dgraph-io/badger#57]
When accessing a badger kv store from a goroutine other than the one it got created on, even in a synchronized manner (using a `sync.Mutex`), I get:

panic: send on closed channel
```
goroutine 31 [running]:
github.com/dgraph-io/badger/badger.(*KV).BatchSet(0xc4200be580, 0xc42926e000, 0x1, 0x1, 0x0, 0x0)
	/.../github.com/dgraph-io/badger/badger/kv.go:541 +0x125
github.com/dgraph-io/badger/badger.(*KV).Set(0xc4200be580, 0xc4250ec020, 0x10, 0x40, 0xc42001e090, 0x10, 0x40, 0xc420032e98, 0x43c6c4)
```

The code can be found [here](https://gist.github.com/dc0d/735aea2e25a1a18db1c76351af458579).

**Comment by manishrjain** [comment]
Most likely, you're calling Set on a closed KV store. You should have Close() be the last action on the store, after all the Sets / Gets.

**Comment by dc0d** [comment]
Seems it was a timing problem. Another important question would come to mind here: Is it safe to access a kv store instance from different goroutines?

**Comment by manishrjain** [comment]
Of course, yes. You can have multiple goroutines perform both Sets, Gets, Deletes etc.

For ideas to achieve write performance, you can have a look at our benchmark populate code.
https://github.com/dgraph-io/badger-bench/blob/master/populate/main.go#L155-L175
