### ISSUE TITLE
Entry for Badger data loss challenge

### ISSUE THREAD

**Issue by tigp** [dgraph-io/badger#575]
Seems like it's inconsistent https://github.com/tigp/badger-data-challenge

Ref: https://github.com/dgraph-io/badger/issues/570

**Comment by manishrjain** [comment]
```
			if strings.HasPrefix(key, prefix) {
				result[key] = v
			}
```

You shouldn't access v beyond the iterator loop. You must copy it over, using `ValueCopy(nil)`, if you intend to use it outside the loop.

Just tested it. Works alright after switching to `ValueCopy`.

**Comment by tigp** [comment]
@manishrjain Yay! It works, I actually had a real problem with that and switched to bolt as this was not obvious. Don't recall if I've seen that in the examples. Could be nice for a project to articulate on that. Have a great day!

**Comment by tigp** [comment]
Not really sure if I understand it correctly, I'm assigning new iterator to a variable and using it's functions get for loop moving and the value is called inside this loop. How it should look if it's used inside the iterator?
