### ISSUE TITLE
Hangs on I/O errors, loses an error (still hangs)

### ISSUE THREAD

**Issue by tv42** [dgraph-io/badger#579]
This isn't quite #570 data loss challenge worthy, so I'm not bothering with full repro. The lost error still causes a hang, so nothing gets falsely accepted.

Here's the relevant code:

- when flushMemtable returns, nothing starts it again: https://github.com/dgraph-io/badger/blob/a1528d1744ca8987841c406b1510795563d2bec4/db.go#L280

- this is not exactly news, but the comment doesn't make you realize badger reliably hangs on I/O errors: https://github.com/dgraph-io/badger/blob/a1528d1744ca8987841c406b1510795563d2bec4/db.go#L801-L803 (the function body is littered with returns)

- this still returns `nil` even when `dirSyncErr != nil`; this loses an error, but it doesn't cause a data loss bug (just the hang), because nothing checks the return value: https://github.com/dgraph-io/badger/blob/a1528d1744ca8987841c406b1510795563d2bec4/db.go#L840-L843

**Comment by manishrjain** [comment]
Thanks for reporting, @tv42 . That TODO needs to be fixed by retrying the op if it gets an error, instead of quitting. Will take a look over the week.

**Comment by manishrjain** [comment]
Fixed via https://github.com/dgraph-io/badger/commit/8b6445e8943f0774fbc8d3e7872f084961900ef4

**Comment by manishrjain** [comment]
Added another commit after this to not return from the dir sync issue, because we do that as a best effort thing.
