### ISSUE TITLE
CAS & Consistency

### ISSUE THREAD

**Issue by dc0d** [dgraph-io/badger#58]
Why CAS is `uint16`? Is the kv store consistent for this CAS at that specific time? Any lazy (eventual) behavior there?

BTW, your kv's performance is amazing even on conventional (not SSD) hard disks! Nice job!

**Comment by manishrjain** [comment]
CAS is not time-based, neither is it a counter. We generate a random number for every set on that key, so 16-bit is as good as any other. Not sure what do you mean by lazy behavior, but no.

> BTW, your kv's performance is amazing even on conventional (not SSD) hard disks! Nice job!

On hard disks? Interesting. Thanks!

**Comment by dc0d** [comment]
I'm not that familiar with databases algorithms internals. The WAL gave me that (wrong) impression that there might be a delay between two updates of a certain key, to get actually committed into the store. I just wanted to be sure if a key got updated sequentially (for example in an imaginary tight loop) it should fail for sure, employing CAS.

**Comment by manishrjain** [comment]
Yes, we store the CAS counter in the WAL. So, if a write to LSM had failed in memory due to CAS mismatch, and the machine crashed; when it comes back up, the exact same decision will be made. All the write operations are attempted sequentially.
