### ISSUE TITLE
Delete entries do not contain Ts in deleteMoveKeysFor

### ISSUE THREAD

**Issue by pradeepyella** [dgraph-io/badger#581]
Entry For #570

https://github.com/dgraph-io/badger/blob/af99e5f9ec18aca5d8ff40d2cfd909f7d21f392d/value.go#L492
```
for itr.Seek(badgerMove); itr.ValidForPrefix(badgerMove); itr.Next() {
			......
			if vp.Fid == fid {
				e := &Entry{Key: item.KeyCopy(nil), meta: bitDelete}
				result = append(result, e)
			}
		}
```

It should be  `e := &Entry{Key: y.KeyWithTs(item.Key(), item.Version()), meta: bitDelete}`

If timestamp is not appened, badger would think that `key[:len(key)-8](x)` is deleted at timestamp `key[len(key)-8:](y)`. So if latest value of x was written at timestamp y and it got moved after GC, then move key for x  at timestamp y would get deleted. As a result if someone reads x at ts > y, nothing would be returned for key x.

**Comment by manishrjain** [comment]
Can you produce an example which shows this issue in terms of what the user expected and what was returned?

**Comment by pradeepyella** [comment]
I am showing the case how data could be lost due to deleteMoveKeys. I have used internal function to simulate what delete move keys would do. 

See the code where newKey is defined. Now suppose new key is garbage collected and moved to new file and eventually move key cleanup for newKey happens. Then it would delete the move key of other key which is `key(0)`

Whenever cleanup of move key of newKey happens it would delete move key of `key(0)`. Thus we would lose data of `key(0)`. Let me know if you have any doubts

**Comment by pradeepyella** [comment]
> `DeleteMoveKeys` function is really a cleanup function. Even if it doesn't run, it would only mean unnecessary keys get left behind. There is a bug here though, however, I doubt you'd be able to generate a data loss which is caused by this.

Cleanup is deleting some other key at different timestamp right ? Unnecessary keys get left behind but it's deleting some other data also.
