### ISSUE TITLE
Reject keys prefixed with !badger

### ISSUE THREAD

**Issue by pradeepyella** [dgraph-io/badger#582]
Entry For #570.
This is also a major security risk.
Suppose badger is being run in context where it stores the key value pairs from external source. It could be as simple as using it for storing key value pairs from some third party source.
Malicious input in the third party source can cause data loss or even unrecoverable error where badger would never start.

First script stores a bunch of key value pairs and also "!badger!head". The script exists without doing db.Close() which can happen if program crashes.  Now on restart of db, some of the acked keys are missing. Since they are no longer present in lsm after restart, The data would be eventually lost after GC

Solution: Badger should have a check so that users can't set/change internal keys.

```
package main

import (
	"log"
	"fmt"
	"encoding/binary"
	"github.com/dgraph-io/badger"
)


var db *badger.DB

var ts uint64

func main() {
	var err error
	dir := "p"

	opts := badger.DefaultOptions
	opts.Dir = dir
	opts.ValueDir = dir
    opts.ValueLogMaxEntries = 64
    opts.MaxTableSize = 1 << 13
    ts = 5

	db, err = badger.OpenManaged(opts)
	logError(err, "open badger")

	data := fmt.Sprintf("%100d",1)
    key := func(i int) string {
    	return fmt.Sprintf("%d%100d",i, i)
    }

    for i := 0; i < 32; i++ {
    	err := saveByKey(key(i), []byte(data))
    	logError(err, "saving value")
    }

    for i := 32; i < 64; i++ {
    	err := saveByKey(key(i), []byte(data))
    	logError(err, "saving value")
    }

    for i := 64; i < 96; i++ {
    	err := saveByKey(key(i), []byte(data))
    	logError(err, "saving value")
    }
    ts = 10000
    val := make([]byte, 12)
    binary.BigEndian.PutUint32(val[:4], 6)
	binary.BigEndian.PutUint32(val[4:8], 0)
	binary.BigEndian.PutUint32(val[8:12], 0)
    err = saveByKey("!badger!head", val)
    logError(err, "saving value")
  
    for i := 96; i < 128; i++ {
    	err := saveByKey(key(i), []byte(data))
    	logError(err, "saving value")
    }
     
    for i := 128; i < 150; i++ {
    	err := saveByKey(key(i), []byte(data))
    	logError(err, "saving value")
    }

	for i := 96; i < 150; i++ {
    	err = getByKey(key(i))
    	logError(err, "getting value")
    }
}


func saveByKey(key string, value []byte) error {
	txn := db.NewTransactionAt(ts, true)
	defer txn.Discard()
	ts = ts + 1
	if err := txn.Set([]byte(key), value); err != nil {
		return err
	}
	err := txn.CommitAt(ts, nil)
	ts = ts + 1
	return err
}

func getByKey(key string) error {
	return db.View(func(txn *badger.Txn) error {
		item, err := txn.Get([]byte(key))
		if err != nil {
			return err
		}
		val, err := item.Value()
		if err != nil {
			return err
		}
		if len(val) == 0 {
			log.Fatalf("key not found %q", key)
		}
		return err
	})
}

func logError(err error, context string) {
	if err != nil {
		log.Fatal(context, ":", err)
	}
}
```

```
package main

import (
	"log"
	"fmt"
	"github.com/dgraph-io/badger"
)


var db *badger.DB

var ts uint64

func main() {
	var err error
	dir := "p"

	opts := badger.DefaultOptions
	opts.Dir = dir
	opts.ValueDir = dir
    opts.ValueLogMaxEntries = 64
    opts.MaxTableSize = 1 << 13
    ts = 5

	db, err = badger.OpenManaged(opts)
	logError(err, "open badger")

    key := func(i int) string {
    	return fmt.Sprintf("%d%100d",i, i)
    }

	for i := 96; i < 150; i++ {
    	err = getByKey(key(i))
    	logError(err, "getting value")
    }
}


func saveByKey(key string, value []byte) error {
	txn := db.NewTransactionAt(ts, true)
	defer txn.Discard()
	ts = ts + 1
	if err := txn.Set([]byte(key), value); err != nil {
		return err
	}
	err := txn.CommitAt(ts, nil)
	ts = ts + 1
	return err
}

func getByKey(key string) error {
	return db.View(func(txn *badger.Txn) error {
		item, err := txn.Get([]byte(key))
		if err != nil {
			return err
		}
		val, err := item.Value()
		if err != nil {
			return err
		}
		if len(val) == 0 {
			log.Fatalf("key not found %q", key)
		}
		return err
	})
}

func logError(err error, context string) {
	if err != nil {
		log.Fatal(context, ":", err)
	}
}
```

**Comment by pradeepyella** [comment]
Now where it's mentioned in docs that user shouldn't use keys prefixed with !badger. Badger is basically a key value store so user can store anything. Can you please point me to the docs which shows that these keys shouldn't be stored.

It's a bug since it's not mentioned anywhere in docs. How is user supposed to know unless he reads the source code.

**Comment by pradeepyella** [comment]
@manishrjain Also user can't do this always.
Say my key consists of unit64 and uint32 and I encode them as following using bigendian. The encoding of following numbers would give me !badger!head as key. I just wrote !badger!head in example so that it would be easy for you.

There could be various other encoding schemes where !badger!head would get overwritten and badger would loose data. 

func main() {
	fmt.Printf("Hello, playground %q\n", string(getKey(2405592234828591649, 1751474532)))
}

func getKey(x uint64, y uint32) []byte {
  key := make([]byte, 12)
  binary.BigEndian.PutUint64(key[0:8], x)
binary.BigEndian.PutUint32(key[8:12], y)
return key
}

**Comment by manishrjain** [comment]
You only know about badger head because you read the code. If you're trying to argue that this is a bug because of lack of documentation, you don't have it. We could add a check to make Badger more robust, but that's it really. Deliberately trying to muck up Badger, will muck up Badger.

**Comment by pradeepyella** [comment]
@dominikh I already showed a example where we could end up with !badger!head due to encoding.
But leave it, it's their decision. We can't really do anything if they are not agreeing it's a bug.

**Comment by manishrjain** [comment]
> Would the bug have been valid if he chose random values from a 96-bit key space and ended up with !badger!head by sheer luck?

At the rate of a million tries per second, it would take ~5000 trillion years to reach the key. I might not be alive by then. So, no! :grinning:

**Comment by pradeepyella** [comment]
If badger is exposed to web, then user can choose that integer with malicious intentions to screw up badger.
But I assume you don't want these type of issues as part of this challenge.
