### ISSUE TITLE
Unable to import v1.5.4 (via gopkg)

### ISSUE THREAD

**Issue by chvck** [dgraph-io/badger#599]
I'm currently unable to do a `go get gopkg.in/dgraph-io/badger.v1` as it errors with 

`# gopkg.in/dgraph-io/badger.v1
../../gopkg.in/dgraph-io/badger.v1/transaction.go:101:19: o.readMark.MinReadTs undefined (type y.WaterMark has no field or method MinReadTs)`

transaction.go imports `"github.com/dgraph-io/badger/y"` which is now out of sync with the 1.5.4 tag as it has removed the MinReadTs function.

https://github.com/dgraph-io/badger/issues/596 is causing our code to error against HEAD.

**Comment by danielmai** [comment]
This works: `go get gopkg.in/dgraph-io/badger.v1/badger`

We continue to make changes on `master`.
