### ISSUE TITLE
Use proper sem ver for tagging repo

### ISSUE THREAD

**Issue by mfridman** [dgraph-io/badger#606]
Just a minor nit to play nice with go modules. Can you use `v2.0.0-rc.1` ?

E.g., instead of the current `v2.0-rc1` reading like so (in a go.mod file)
```
github.com/dgraph-io/badger v1.5.5-0.20181004181505-439fd464b155
```

`v2.0.0-rc.1` should read like this:

```
github.com/dgraph-io/badger v2.0.0-rc.1
```

In this case it makes a difference when parsing out change logs, etc.

**Comment by alee792** [comment]
:+1: , for some reason the "canonical" module of Badger has a slightly different API (txn.Commit requires a non-nil arg) than the actual current version, and it's a bit of a headache.

**Comment by leedstyh** [comment]
Thoughts on this? 

Using badger v2 now, but badger is the only one package not compatible with go module in my app.

**Comment by adauhajre** [comment]
this is breaking some of my automation workflow with go modules...can we please fix this?

**Comment by alee792** [comment]
If you guys are blocked by the tag, a quick workaround would be to reference a branch or specific commit.

**Comment by manishrjain** [comment]
I've just pushed a new tag v2.0.0-rc2. Hope that works!

**Comment by mfridman** [comment]
@manishrjain Thanks! Minor nit, `v2.0.0-rc.2` but it'll do as long as you don't exceed `rc10`

```
github.com/dgraph-io/badger v2.0.0-rc2+incompatible
```

**Comment by mfridman** [comment]
Looks good, safe to close issue @manishrjain 

The `+incompatible` is normal. Indicates project has v2 tag but hasn't opted in to Go modules, i.e., no go.mod file.
