### ISSUE TITLE
Invalid skip GC parameters

### ISSUE THREAD

**Issue by sunpuyo** [dgraph-io/badger#615]
Using a default configuration, I tested writing data with small key & big values (~4MB).
It does not gc at all, so I checked trace log. At trace log, badger always skips to gc and remains log
> Head pointer is at zero

In my case, because of big values, a memtable increases very slowly, but valueLog files increases so sharply. However, an only way to update a head, which is used to pickLog, is a flushMemtable or close. 
So I close and re-run test, but badger still skips gc 

> Size window: 107411660.50. Count window: 10000.
> Skip first 284.69 MB of file of size: 1024 MB
> Fid: 0. Skipped: 284.94MB Num iterations: 5792. Data status={total:739.4192714691162 discard:739.4192714691162 count:2739}

I review a code related with gc, and found some bugs at a 'Value.go' file.
> // If we couldn't sample at least a 1000 KV pairs or at least 75% of the window size,
> // and what we can discard is below the threshold, we should skip the rewrite.
> if (r.count < countWindow && r.total < sizeWindow*0.75) || r.discard < discardRatio*r.total {
> 	tr.LazyPrintf("Skipping GC on fid: %d", lf.fid)
> 	return ErrNoRewrite
> }

countWindow is 10,000 not 1,000. - 1% of vlog.opt.ValueLogMaxEntries (default = 1,000,000)
And an unit of r.total is 'MB', but unit of sizeWindow is 'byte'.
So, if average size of value is big (1MB~) than gc will always be skipped.

**Comment by leerspace** [comment]
This is fixed in 68856daada4b64bbb68c1466d70927f42da475b7, right?

**Comment by sunpuyo** [comment]
Yes, that's exactly.
