### ISSUE TITLE
Assertion error when compaction

### ISSUE THREAD

**Issue by WangBeyond** [dgraph-io/badger#620]
Hi, I occasionally  got the following error
> 2018/11/02 09:32:23 Assert failed
gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger/y.AssertTrue
/home/ubuntu/jenkins/workspace/go-diffs/src/gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger/y/error.go:55
gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger.(*levelsController).doCompact
/home/ubuntu/jenkins/workspace/go-diffs/src/gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger/levels.go:675
gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker
/home/ubuntu/jenkins/workspace/go-diffs/src/gitlab.myteksi.net/gophers/go/vendor/github.com/dgraph-io/badger/levels.go:254
runtime.goexit
golang/go/src/runtime/asm_amd64.s:2361

> 

Do you have any advice?

**Comment by manishrjain** [comment]
Increase your MaxLevels. You're hitting the max levels.

**Comment by manishrjain** [comment]
Curious: How much data is your Badger instance holding?

**Comment by WangBeyond** [comment]
Thanks, it seems working after increasing maxLevels. The data size is around 100GB
