### ISSUE TITLE
Add an `AppendValue(dst []byte) ([]byte, error)` method to Item

### ISSUE THREAD

**Issue by alxarch** [dgraph-io/badger#621]
Currently `Item.CopyValue` uses `append(dst[:0], buf...)` which does not work for the simple case of values that can be just concatenated. Using `item.Value(func([]byte) error) error` is an option buf forces an extra allocation for the closure. Generallly speaking while closures are nice and easy to use in `go` they almost always incur the performance penalty of an allocation to be able to capture the context of the closure. IMHO APIs should be avoiding closures or at least provide alternatives that don't require unneeded allocations.

**Comment by manishrjain** [comment]
You can just pass `ValueCopy(dst[len(dst):])`. That'd append the value to dst buffer.

**Comment by alxarch** [comment]
No this is not correct, if dst doesn't have sufficient capacity it will split the buffer

**Comment by manishrjain** [comment]
In that case, please use the `Value(..)` API, which would handle your specific use case. I doubt this is general enough that we need to add it to the Badger APIs.

**Comment by alxarch** [comment]
But it is general. Let's say you store a stream of small messages and you want to create a buffer that contains an arbitrary range of those messages. With the `Value(func())` method I am forced to do an extra allocation for *every* message I want to add to the buffer just to pass the *right* buffer to which to append. That is an O(n) number of allocations depending on number of messages in the range and not on the actual size of messages. I understand your reluctance to add more methods but the way `ValueCopy` works is misleading because the first thought that comes to mind is what you said about `dst[:n]` and when `append` is *needed* it's usually in a performance sensitive part of the code where allocations should be avoided. That said I find it's easier to pass `dst[:0]` to `AppendValue` directly when *you* choose to do so and get the exact behaviour of `ValueCopy`.  I think since the `Value` api is changing in a breaking way for 2.0 it's worth considering.
