### ISSUE TITLE
[enhancement] Using WriteBatch with OpenManaged

### ISSUE THREAD

**Issue by svmhdvn** [dgraph-io/badger#629]
I'm trying to do a lot of bulk writes on a managed DB. Currently, WriteBatch uses the unmanaged transactions API, so the only way I can do bulk writes is by managing my own transactions. It would be convenient to be able to use a similar API for WriteBatches with a managed DB, since I need the `commitAt` functionality for other transactions.

**Comment by gitlw** [comment]
Thanks @svmhdvn for raising this. PR submitted and waiting for review from other devs in the Dgraph team.

**Comment by manishrjain** [comment]
@svmhdvn : You can also use the `TxnWriter` available in Dgraph: x/badger.go, if you're going to use this for a Dgraph binary.

**Comment by campoy** [comment]
Is this something we still want to work on? An old PR #633 was created and eventually abandoned.

Hey @svmhdvn, did the recommendation above fix your issue?

**Comment by campoy** [comment]
Closing as there's a work around using `TxnWriter`.

Please, reopen if the workaround is not sufficient.
