### ISSUE TITLE
use badger has unhappy thing, call tx.Set and call tx.Get, it can't read set data

### ISSUE THREAD

**Issue by hvritual** [dgraph-io/badger#634]
`package main

import (
	"encoding/binary"
	"fmt"
	"github.com/dgraph-io/badger"
)

const (
	PidLen     = 8
	SIndexLen   = 1
	KeyLen           = PidLen + SIndexLen
	PTIdLen = 8
	SILen      = 8
	RelValueLen      = PTIdLen + SILen
)

type Relation struct {
	Pid   uint64
	SIndex byte
	PT uint64
	SI    uint64
}

func main() {
	fileName := "./test"
	opts := badger.DefaultOptions
	opts.Dir = fileName
	opts.ValueDir = fileName
	db, err := badger.Open(opts)
	if err != nil {
		fmt.Println(err)
		return 
	}
	rels := []Relation{
		Relation{
			Pid:   0x00f65483de1fae44,
			SI:    1,
			SIndex: 0,
			PT: 0x037f363f03c0a00,
		},
		Relation{
			Pid:   0x00f65483de1fae44,
			SI:    2,
			SIndex: 1,
			PT: 0x037f363f03c0a00,
		},
		Relation{
			Pid:   0x00f65483de1fae44,
			SI:    3,
			SIndex: 2,
			PT: 0x037f363f03c0a00,
		},
		Relation{
			Pid:   0x00f65483de1fae44,
			SI:    4,
			SIndex: 3,
			PT: 0x037f363f03c0a00,
		},
	}
	err = db.Update(func(tx *badger.Txn) error {
		buf := make([]byte, KeyLen)
		val := make([]byte, RelValueLen)
		for _, rel := range rels {
			binary.BigEndian.PutUint64(buf, rel.Pid)
			buf[SILen] = rel.SIndex
			binary.BigEndian.PutUint64(val, rel.PT)
			binary.BigEndian.PutUint64(val[PTIdLen:], rel.SI)
			fmt.Printf("%x, %x", buf, val)
			if err := tx.Set(buf, val); err != nil {
				fmt.Println(err)
				return err
			}
		}
		return nil
	})
	fmt.Println("err:%v", err)

	err = db.View(func(tx *badger.Txn) error {
		buf := make([]byte, KeyLen)
		for _, rel := range rels {
			binary.BigEndian.PutUint64(buf, rel.Pid)
			buf[SILen] = rel.SIndex

			fmt.Printf("buf %x", buf)

			item, err := tx.Get(buf)
			if err != nil {
				return err
			}
			item.Value(func(val []byte) error {
				fmt.Printf("%x, %x", buf, val)
				return nil
			})
		}
		return nil
	})
	fmt.Println("err:%v", err)

}

`

that is test code, thank for you help

**Comment by manishrjain** [comment]
This works:

```package main

import (
	"encoding/binary"
	"fmt"

	"github.com/dgraph-io/badger"
)

const (
	PidLen      = 8
	SIndexLen   = 1
	KeyLen      = PidLen + SIndexLen
	PTIdLen     = 8
	SILen       = 8
	RelValueLen = PTIdLen + SILen
)

type Relation struct {
	Pid    uint64
	SIndex byte
	PT     uint64
	SI     uint64
}

func main() {
	fileName := "./test"
	opts := badger.DefaultOptions
	opts.Dir = fileName
	opts.ValueDir = fileName
	db, err := badger.Open(opts)
	if err != nil {
		fmt.Println(err)
		return
	}
	rels := []Relation{
		Relation{
			Pid:    0x00f65483de1fae44,
			SI:     1,
			SIndex: 0,
			PT:     0x037f363f03c0a00,
		},
		Relation{
			Pid:    0x00f65483de1fae44,
			SI:     2,
			SIndex: 1,
			PT:     0x037f363f03c0a00,
		},
		Relation{
			Pid:    0x00f65483de1fae44,
			SI:     3,
			SIndex: 2,
			PT:     0x037f363f03c0a00,
		},
		Relation{
			Pid:    0x00f65483de1fae44,
			SI:     4,
			SIndex: 3,
			PT:     0x037f363f03c0a00,
		},
	}
	err = db.Update(func(tx *badger.Txn) error {
		for _, rel := range rels {
			buf := make([]byte, KeyLen)
			val := make([]byte, RelValueLen)
			binary.BigEndian.PutUint64(buf, rel.Pid)
			buf[SILen] = rel.SIndex
			binary.BigEndian.PutUint64(val, rel.PT)
			binary.BigEndian.PutUint64(val[PTIdLen:], rel.SI)
			fmt.Printf("%x, %x\n", buf, val)
			if err := tx.Set(buf, val); err != nil {
				fmt.Println(err)
				return err
			}
		}
		return nil
	})
	fmt.Printf("err:%v\n", err)

	err = db.View(func(tx *badger.Txn) error {
		buf := make([]byte, KeyLen)
		for _, rel := range rels {
			binary.BigEndian.PutUint64(buf, rel.Pid)
			buf[SILen] = rel.SIndex

			fmt.Printf("buf %x\n", buf)

			item, err := tx.Get(buf)
			if err != nil {
				return err
			}
			if err := item.Value(func(val []byte) error {
				fmt.Printf("%x, %x\n", buf, val)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	})
	fmt.Printf("err:%v\n", err)
}
```

You need to ensure that the byte slice to `Set` is not overwritten. The ownership of the byte slices must be transferred to `Set` function.

**Comment by hvritual** [comment]
ok, I konw。Set is not finished, but next loop is overwritten. thank you
