### ISSUE TITLE
Concurrent Writing Causes Continuous Memory Growth

### ISSUE THREAD

**Issue by heidawei** [dgraph-io/badger#636]
in func (o *oracle) decrRef(){} ，the oracle refCount will be not == 0 for a long long time in concurrent，it will cause memory growth

**Comment by manishrjain** [comment]
Oracle stores a map[uint64]uint64, which is pretty cheap. In almost all the cases, there are typically some tiny windows where no txn is going on, and this map can be removed -- so this concern seems theoretical in nature. I doubt we need any more mechanism than the existing one.

**Comment by heidawei** [comment]
I do not think so, when I new txn and set KVs with batch and commit in concurrent writing case, I write 100000W KV to badger, I see the memory grow......, use go tool pprof heap, I see oracle map has a lot of memory, the GC will be problem

**Comment by manishrjain** [comment]
If you think memory growth is a problem, you could add some blockers in your code, which would pause new transactions, until there's no pending txn. And then it can run txns immediately. That would allow Oracle to discard its map.

**Comment by heidawei** [comment]
good idea，thank you
