### ISSUE TITLE
MergeFunc to append/overwrite part of key data

### ISSUE THREAD

**Issue by vtolstov** [dgraph-io/badger#638]
does it MergeFunc suitable for this use-case?
1) i have key name A with value []byte("test") (value = "test")
2) i want to append value of key A with []byte("TEST") (value = "testTEST")
3) partially overwrite value of key A with []byte("data") (value = "dataTEST")

also how can i pass for example offset to write new data?

**Comment by vtolstov** [comment]
what do you think?

**Comment by manishrjain** [comment]
Badger and LSM trees in-general are immutable. When you "set" something, that is an append-only operation, which can shadow a previous version of the key.

You could use MergeFunc, it just consolidates multiple versions and writes a new version of the key.

**Comment by vtolstov** [comment]
thanks
