### ISSUE TITLE
Opening, reading, and then closing the datastore is slow

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#641]
It looks like a lot of time is being spent in `compactBuildTables`.

```
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger.(*levelsController).compactBuildTables(0xc000221e30, 0x0, 0x1961e20, 0xc0000cc1a0, 0xc000135aa0, 0xc000135b00, 0xc0003181a0, 0x3, 0x3, 0xc0003201a8, ...)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/levels.go:479 +0x1103
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger.(*levelsController).runCompactDef(0xc000221e30, 0x0, 0x1961e20, 0xc0000cc1a0, 0xc000135aa0, 0xc000135b00, 0xc0003181a0, 0x3, 0x3, 0xc0003201a8, ...)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/levels.go:645 +0xd3
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger.(*DB).Close(0xc00030b180, 0x0, 0x0)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/db.go:406 +0x313
```

```
goroutine 186 [syscall]:
syscall.Syscall6(0x11, 0xc, 0xc01a02a000, 0x3b44fff, 0x0, 0x0, 0x0, 0x0, 0xc00999fc18, 0xa7a34d)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pread(0xc, 0xc01a02a000, 0x3b44fff, 0x3b44fff, 0x0, 0xc01a02a000, 0x6f2a90281058, 0xc00999fc80)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1311 +0x72
internal/poll.(*FD).Pread(0xc000135200, 0xc01a02a000, 0x3b44fff, 0x3b44fff, 0x0, 0x1010000009bce93, 0x0, 0x3b44fff)
	/usr/lib/go/src/internal/poll/fd_unix.go:196 +0x9f
os.(*File).pread(0xc00000e050, 0xc01a02a000, 0x3b44fff, 0x3b44fff, 0x0, 0xc00999fd30, 0x101, 0xc00999fcd8)
	/usr/lib/go/src/os/file_unix.go:258 +0x58
os.(*File).ReadAt(0xc00000e050, 0xc01a02a000, 0x3b44fff, 0x3b44fff, 0x0, 0x3b44fff, 0x1359a27, 0xc0000b3301)
	/usr/lib/go/src/os/file.go:126 +0xfd
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/table.(*Table).loadToRAM(0xc009bb80f0, 0x3b44fff, 0x415)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/table/table.go:352 +0x9f
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/table.OpenTable(0xc00000e050, 0x1, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/table/table.go:139 +0x374
gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger.(*levelsController).compactBuildTables.func2(0x415, 0xc000221e30, 0xc00970c420, 0xc00007ec00)
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/levels.go:468 +0x22f
created by gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger.(*levelsController).compactBuildTables
	/home/steb/projects/go/src/gx/ipfs/QmdG6rxQFetuV853nsNQn9EbrUEjQcbPB2htDniuLTQBsg/badger/levels.go:454 +0xec3
```

**Comment by Stebalien** [comment]
By "slow", I mean it's hanging for ~.5s.

**Comment by manishrjain** [comment]
Compactions can and will take time. Badger can have millions of keys in a single table, and therefore, to compact it with 10 more tables in the next level, does take time. Compactions, however, run in the background and don't cause much impact on the live path of data loading or querying.

When you close Badger, it causes some extra compactions to prepare the DB for efficient querying, so Close can take some time. When Badger is opened, it loads up the meta information from LSM tree tables for efficient querying. Both of these take some time, despite parallelization.

**Comment by Stebalien** [comment]
> When you close Badger, it causes some extra compactions to prepare the DB for efficient querying, so Close can take some time.

Is there any reason to do this on close? Pausing/hanging on close tends to frustrate users. Is this so that users can get efficient queries when opening the database in read-only mode?

**Comment by manishrjain** [comment]
Yes. Open and close are lot rarer compared to reads and writes.

**Comment by Stebalien** [comment]
> Open and close are lot rarer compared to reads and writes.

That depends on the use-case. For example, a small command-line utility invoked from a shell script will repeatedly open, do one operation, and then close the database.

Unfortunately, IPFS does exactly this when run in "local" mode. That is, we have two modes of operation:

* daemon: we start a daemon that opens the repo and then services requests over an HTTP API.
* local: instead of running a daemon in the background, the `ipfs` command *locally* opens the datastore, does any work it needs to (e.g., read a file), then closes the datastore and exits.

**Comment by Stebalien** [comment]
> The closing part would only take time if there's a lot of data to compact at the top level. Otherwise, if there's not much written, then either there won't be any compaction or a quick one.

There's a lot of *existing* data but little new data. By "a lot" I mean 12GiB and 400K key/value pairs. Unfortunately, I can't replicate this with a *new* (smaller) db.

Should this process scale with the size of the database or the amount written since the last compaction?

**Comment by manishrjain** [comment]
Only the new data needs to be pushed down, i.e. Compacted. Also note that this is happening all the time in background as well. So, how much needs to be done at close varies.

**Comment by shazow** [comment]
Would it be possible to have an option to avoid compaction, unless some trivially-computed metric is reached that forces it?

This way projects that have both a daemon mode and a one-shot mode, they can avoid compaction during one-shot runs unless absolutely necessary.

I was also evaluating using badger for another one-shot cli project but was concerned about the added latency.

**Comment by manishrjain** [comment]
This PR adds an option to skip force compaction of Level 0 on close. It should help.

https://github.com/dgraph-io/badger/pull/645

**Comment by Stebalien** [comment]
Thanks! I'm not sure if that'll work for go-ipfs when run in "offline" as we'll need to make sure the database is compacted eventually.

However, it might be worth adding that to IPFS when run as a daemon (where we expect IPFS to be online long enough to compact in the background). That could speed up shutdown there.

**Comment by manishrjain** [comment]
Irrespective of whether the option is set or not, Badger would do any compactions that are necessary, as levels exceed their max size. This option only would avoid an extra (forced) compaction that we were doing to move everything from L0 -> L1 (even if L0 does NOT exceed its max size).

**Comment by Stebalien** [comment]
Awesome!
