### ISSUE TITLE
3 hdd and 1 ssd disk, how to deal?

### ISSUE THREAD

**Issue by vtolstov** [dgraph-io/badger#644]
I have server with 3 hdd and 1 ssd, i want to store data in hdd, but value log in ssd (to speedup writing).
Very simple case - create 3 instances of badger for each hdd and create dir for each on ssd.
Can it possible to something else to have space from different disks but use only one single ssd for value log?

**Comment by manishrjain** [comment]
Not sure I fully understand the question. Have you looked at options? Allows lsm tree storage to be different from value log.

**Comment by vtolstov** [comment]
Yes, but i want to use one badger db instance and have ability to write data to 3 disks. Does it possible to implement something like selector for path based on key?

**Comment by manishrjain** [comment]
No. That's not possible. You'd need to set up a Raid array, or some file system which can span multiple hard disks.
