### ISSUE TITLE
Possibility to test existence of a key without reaching Value log

### ISSUE THREAD

**Issue by zaibon** [dgraph-io/badger#66]
Currently to test if a key exists or not I use `Get` and then test if the Value is nil or not.
Does that mean we hit the value log every time or we only stay in the memtable and LSM ?

**Comment by manishrjain** [comment]
This is a useful feature. We can add it, so it won't go beyond LSM tree to figure this out.

**Comment by zaibon** [comment]
Great !
How do you see the API for that ? adding an `Exists` method on the `KV` struct ?
Or put it on the `KVItem` ?
I can work on a PR since I'll need it for one of my project.

**Comment by manishrjain** [comment]
You can create a has function. Happy to accept a PR.

**Comment by alexbakker** [comment]
The 'Exists' function no longer exists (hah). Could this be added back or does it no longer make sense to have this feature?

**Comment by janardhan1993** [comment]
You can do a get and if value is not found badger returns errKeynotfound. Earlier you had to fetch the value to determine if key exists or not. With the change in API exists is no longer needed since get doesn't go to value log.
