### ISSUE TITLE
Introduce LRU cache in Badger

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#663]
Could work at 2 levels:

- Cache SSTables in memory, based on frequent access. Though, that might just be the same effect as doing mmap over the tables.
- Cache values which lie in value log. This could be useful in that it can avoid disk seeks. We don't need to cache values which lie in the LSM tree, considering SSTables are already either in RAM or at least MMapped in most cases.

The question is which LRU cache to use. https://github.com/coocood/freecache , or https://github.com/allegro/bigcache seem promising. Or, maybe we write our own, similar to this one: http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html

**Comment by zhiqiangxu** [comment]
I think "Cache values which lie in value log" is the way to go:) 

IMHO the most difficult point is to maintain data consistency when introducing cache.

**Comment by alxarch** [comment]
Check out https://github.com/VictoriaMetrics/fastcache also

**Comment by mangalaman93** [comment]
We have considered Fastcache, it doesn't do well on hit ratios. Here are the raw results for benchmarks https://docs.google.com/spreadsheets/d/1c5AbsHPh-z6KyxkiBJ4ipNR7U7QVuSmR38fym8NeC50/edit?usp=sharing

**Comment by campoy** [comment]
Hi @mangalaman93,

Could you update this is issue? What's the current status?

**Comment by mangalaman93** [comment]
https://github.com/dgraph-io/ristretto work is in progress. Once it is complete, we should be able to add it to badger.

**Comment by anacrolix** [comment]
Any plans for this now that Ristretto is released?

**Comment by danielmai** [comment]
Ristretto has been added to Badger with #1066 and released in Badger v2.0.0.

**Comment by zhiqiangxu** [comment]
@danielmai @jaipradeesh Does the block cache have consistency guarantee like mentioned in this thesis ? 

: https://dspace.mit.edu/bitstream/handle/1721.1/75448/818331182-MIT.pdf?sequence=2

**Comment by anacrolix** [comment]
I think I misunderstood, I thought this would be support for dropping least recently used key values. Does something like that exist for Badger?
