### ISSUE TITLE
Possible race condition/nil pointer dereference in internals

### ISSUE THREAD

**Issue by magik6k** [dgraph-io/badger#67]
While wiring up badger to use it in IPFS I've ran into an issue which looks like some sort of race condition, after which there is a panic from badger internals after nil pointer dereference. It's hard for me to create minimum test case for that, though I'm able to reproduce it with 100% 'success' rate.

Here is all the info I was able to gather about that issue: https://gist.github.com/magik6k/b9634d85e84fe90906744de0127dbc20

Scenario A is the easiest one to reproduce, though go race detector doesn't detect anything related to it.

Info on messages:
* Calls to functions in https://github.com/ipfs/go-ds-badger/blob/master/datastore.go
* `Has` is implemented using Get
* `Query` is implemented using `NewIterator`

I hope this is enough data to solve this issue, if it's not I'm happy to provide more.

**Comment by whyrusleeping** [comment]
@manishrjain Is badger safe to use concurrently?

**Comment by manishrjain** [comment]
Badger is safe to use concurrently. In fact, that's how it's supposed to be used.

You can now replace `Has`, to use `Exists`, which just got added. Iterator should not be used concurrently, that's meant to be single-threaded. I can't tell from your code right away if that's the case or not (traveling). Can you confirm that Iterator is being used serially?

**Comment by magik6k** [comment]
After looking more into it, I managed to fix this on my end. What happened was `iter.Close` being called twice. I think that it should be acceptable to call Close multiple times, and if that's not possible due to implementation details, it would be nice to have it documented. Other than that, badger seems to perform really well.

**Comment by manishrjain** [comment]
Close shouldn't be called twice. I don't think there's any precedence of ensuring that Close() would not complain if called like that. So, I doubt we should bake any extra logic to handle this condition.

**Comment by manishrjain** [comment]
@magik6k If you gather some numbers from IPFS re: your usage of Badger, performance benefits, etc. it would be great to see them.
