### ISSUE TITLE
badger restore - doCompact errors

### ISSUE THREAD

**Issue by zorino** [dgraph-io/badger#677]
When I restore a backup file I get a lot of : 

ERROR: Error while running doCompact: Unable to fill tables for level: 0 (or 1)

Is this a normal behavior ?

Thank you

**Comment by dmibor** [comment]
+1 

See the same thing when opening DB after process using badger crushes, together with very long value log replay.

**Comment by manishrjain** [comment]
Yes, this is normal behavior.
