### ISSUE TITLE
Possible bug in WriteBatch

### ISSUE THREAD

**Issue by dmibor** [dgraph-io/badger#681]
Trying to use single WriteBatch to write multiple times with periodic flushing - from the way code looks and synchronized it is designed for it, but have errors returned that I'm trying to use discarded transaction.

Think there might be a bug here
```
func (wb *WriteBatch) Flush() error {
	wb.Lock()
	_ = wb.commit()
==>	wb.txn.Discard()
	wb.Unlock()
```
Seems to me there is no value in discarding txn here, since when commit is done here:
```
func (wb *WriteBatch) commit() error {
	if wb.err != nil {
		return wb.err
	}
	// Get a new txn before we commit this one. So, the new txn doesn't need
	// to wait for this one to commit.
	wb.wg.Add(1)
==>	wb.txn.CommitWith(wb.callback)
	wb.txn = wb.db.newTransaction(true, true)
	wb.txn.readTs = 0 // We're not reading anything.
	return wb.err
}
```
it will discard commited txn inside CommitWith and create new one after, and then for no apparent reason discard new txn as well. I thought new txn here is created so that WriteBatch can again handle Set() after Unlock() , but this Discard() gets in the way , would it be better to remove it?

**Comment by manishrjain** [comment]
Flush() is not called right after `commit()`. Commits happen all the time, Flush only happens at the end of the program. Not a bug, it's designed to act that way.
