### ISSUE TITLE
Quick way to drop all keys with a certain prefix

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#683]
We now have a `DropAll` API, which can drop all the tables from LSM tree, and log files from value log. It contains mechanisms by which we can pause writes and compactions, and alter the tree. We use this to provide a `Flatten` API as well.

We can use these mechanisms to rewrite the LSM tree to drop all the keys with a certain prefix, without using delete markers. That'd be great to provide an idea of namespaces to users, and also to clear out certain predicates in Dgraph.

**Comment by Asarew** [comment]
I think that this AP would be beter if you're able to specify a range instead of only a prefix. Which would also broaden the use case.
