### ISSUE TITLE
Live stream Badger updates

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#684]
We should have a way by which we can live stream updates to Badger as they happen. There can be an option to restrict it to certain prefixes as well. This would be useful in Dgraph for giving users access to updates as they happen in the Dgraph cluster.

P.S. If we put some ads in between the updates, we can build YouTube TV. The longer the ads, the closer we get to the goal.

**Comment by gedw99** [comment]
this would be really useful !

**Comment by campoy** [comment]
Definitely not a P0 (nor a P1, imho) but let's see what benefits this could bring and figure out whether it makes sense to implement it as part of v2.1 or later.

**Comment by gedw99** [comment]
sure.

For the Record, yes CDC and Subscriptions are very similar and doing it at Badger level first would be great underpinning.
For CDC you want to get a subscription feed of the transaction changes happening to Bager.
See Cockroach CDC for great example of the API etc.

**Comment by ashish-goswami** [comment]
@gedw99 we have implemented subscription support in Badger recently. Please have a look at https://github.com/dgraph-io/badger/pull/771.

**Comment by gedw99** [comment]
@ashish-goswami  thank you !  It will definitely help lots of edge cases i had with Badger.

**Comment by ashish-goswami** [comment]
@gedw99 closing it for now. Feel free to open it if required.
