### ISSUE TITLE
Goroutine leak

### ISSUE THREAD

**Issue by lni** [dgraph-io/badger#685]
Code at github.com/dgraph-io/badger/y/watermark.go:203 is copy and pasted below

It seems to me that there is no way to terminate the loop. this is causing goroutine leaks in my testing.  

```
for mark := range w.markCh {
    if mark.waiter != nil {
      doneUntil := atomic.LoadUint64(&w.doneUntil)
      if doneUntil >= mark.index {
        close(mark.waiter)
      } else {
        ws, ok := waiters[mark.index]
        if !ok {
          waiters[mark.index] = []chan struct{}{mark.waiter}
        } else {
          waiters[mark.index] = append(ws, mark.waiter)
        }
      }
    } else {
      if mark.index > 0 {
        processOne(mark.index, mark.done)
      }
      for _, index := range mark.indices {
        processOne(index, mark.done)
      }
    }
  }
```

I tried to read the code, but the comments are a bit confusing. It talks about raft proposals, could you please help to have a look and confirm whether badger uses raft internally? Thanks.

```
// mark contains raft proposal id and a done boolean. It is used to
// update the WaterMark struct about the status of a proposal.
```

**Comment by manishrjain** [comment]
Watermark is typically used for the entire lifetime of the process. Therefore, we don't have a way to "Close" the watermark and stop the goroutine.

I've modified those comments to make it clear what the mark does.

**Comment by lni** [comment]
If it is for the entire lifetime of the process, can I ask why it is not shut down when db.Close() is called? 

I'd expect that I can repeatedly open and close a DB without leaking any resources.

**Comment by manishrjain** [comment]
Should be an easy fix. But, I'm curious: Why are you repeatedly opening and closing DBs? Typically, a process opens it once and uses it for the entire lifecycle of the process.

**Comment by lni** [comment]
@manishrjain thanks for fixing this. 

I am building a Raft library, it is available [here](github.com/lni/dragonboat). In my monkey testing, I randomly shutdown and restart Raft nodes to see whether Raft clusters can correctly handle such node failures. That is why I repeatedly open/close DBs.

**Comment by manishrjain** [comment]
Saw the library, good work! :+1:
