### ISSUE TITLE
Questions on GC and disk space efficiency

### ISSUE THREAD

**Issue by zorino** [dgraph-io/badger#687]
" DB.RunValueLogGC(): This method is designed to do garbage collection while Badger is online. Along with **randomly picking a file**, it uses statistics generated by the LSM-tree compactions to pick files that are likely to lead to maximum space reclamation. "

Is one run of DB.RunValueLogGC() only process one value file ?

I am a bit concern with the space efficiency of a KV store that will contain hundred of millions of KV.

If I understood correctly badger does not compress the keys or values when compared to rocksdb ?

What are the alignments for keys in .sst files and values in .vlog files ?

Also what is the value pointer size in the LSM tree ?

What would be your recommendation to maximize the disk space reclamation at the end of a massive bulk upload ?

Thanks

**Comment by manishrjain** [comment]
> Is one run of DB.RunValueLogGC() only process one value file ?

https://github.com/dgraph-io/badger#garbage-collection

> If I understood correctly badger does not compress the keys or values when compared to rocksdb ?

Badger doesn't. It does do prefix diffing of the keys though.

> Also what is the value pointer size in the LSM tree ?
https://github.com/dgraph-io/badger/blob/a6ef9cff264898ece232760face372bbfe690c96/structs.go#L32

But, what should be looking at is `Options.ValueThreshold`.

Please bring these questions on discuss.dgraph.io.
