### ISSUE TITLE
Invalid record in the MANIFEST file

### ISSUE THREAD

**Issue by lni** [dgraph-io/badger#690]
When reading the badger code, I saw the following part which loads the MANIFEST file from disk. 

https://github.com/dgraph-io/badger/blob/2017987d447a842cb9fe872ad0cceab9a6a93632/manifest.go#L365-L367

This loop goes through all records in the MANIFEST file, each record has a length and checksum value, badger ensures that only records with the expected length and checksum are unmarshaled and applied. It breaks from the loop and silently return what have been loaded so far on checksum mismatch or unexpected EOF. 

What happens if the on-disk checksum or length value is corrupted, say some bits flipped due to physical disk errors? When not all records are read from the MANIFEST file and only part of the MANIFEST is read, will that cause data loss issue? 

New to the badger codebase, apologize if I missed anything here.

**Comment by manishrjain** [comment]
Yes. If Badger can't read MANIFEST file, then it wouldn't know the LSM tree levels of the tables. All bets are off at that point and it would need manual intervention to either recreate the MANIFEST or recreate the DB from a backup or something.

**Comment by lni** [comment]
My concern is that the current implementation doesn't return an error when this happens. It seems that users are not notified for such possible corruption. 

Maybe just panic and print an error message showing data corruption detected?

**Comment by campoy** [comment]
This seems like a clear mistake in the code. That break should be a return if we really wanna make sure that any missmatch in the checksum makes the server stop.

This should be fixed with first a test proving the problem occurs and then a small PR fixing the code.
