### ISSUE TITLE
Is badger distributed?

### ISSUE THREAD

**Issue by chetandhembre** [dgraph-io/badger#696]
Hi,
I just stumble upon badger after reading article how Dgraph using it.
I like what you guys are doing.
I just wanted to know badger as project gives functionality like sharding or replication ?
If it question already asked please link me to that issue.
Thanks.

**Comment by Xuanwo** [comment]
No, badger is not a distributed system.

**Comment by manishrjain** [comment]
As @Xuanwo said, Badger is not distributed. It is embedded KV DB.

**Comment by jeromeheng** [comment]
Too many data if I want to store , and how to expand it  ?

**Comment by jeromeheng** [comment]
@ashish-goswami  more than 100 billons ，and I need that It's a distributed system  ，just like redis : )
