### ISSUE TITLE
Time sorted compaction..

### ISSUE THREAD

**Issue by burmanm** [dgraph-io/badger#703]
As mentioned in the Jaeger PR 760, I would like to propose a time window compaction system for badger also. This is close to what Cassandra provides (TWCS).

Idea is to flush and compact tables based on when they were created. That is, flushing strategy could be something of a configured interval or automatic timing that flushes to the disk the latest data as is always done with the LSM memtables, but change the compaction targets. Inside the time window compactions should only target the configured interval of tables and keep the old ones as immutable and filtered out from the compaction target. For example, flushing could occur every one (1) minute and then a compaction could trigger once an hour. That compaction would look at the data from the last hour and compact only those. A larger compaction could occur for example once a day that would then compact all those hour old tables to a single table. After that, the data is left untouched and next day the process would start from the beginning. Inside those time split windows the compaction process would be equal to what badger currently implements.

With that example, the smaller compactions would target 60 files while the larger one would at most look at 24 files. Not more, regardless of the amount of data. This allows faster, less resource consuming compactions to occur and reduces the overhead of the compaction process.

Same benefits apply to the queries. When storing time series data, one often wants to look at the data between certain intervals. That data is then quickly found from a small subset of the files without the need to poll all the tables. What it does require for optimal performance is TTL for deletions, which then is a simple process of dropping a whole file without any need for extra compactions after that.

This probably requires some sort of knowledge from badger regarding the timestamp and is somewhat specialized approach. I don't think the general keydesign could always sustain this type of structure and still be effective. So this might be something more difficult to handle for key iteration design - I'm not enough familiar with the badger internals to comment if there's a good approach to this issue.

**Comment by burmanm** [comment]
For the second issue, the actual need comes from the Cassandra use-case, where we saw this type of high-write time series data to cause large amount of compactions and write amplification. I have not ran badger in production. So this is proposal is mostly coming from something learned while running production with other LSM databases (HBase has same compaction strategy copied from Cassandra).

For Cassandra, there isn't global sorting as obviously the tombstones and distributed nature (eventual consistency between nodes) causes some issues why this isn't necessarily possible option. Also, Cassandra does not store SSTables in leveled form when doing time window compaction. So directly copying those strategies for reading are not going to work.

**Comment by manishrjain** [comment]
I don't think this approach is possible in Badger, where we keep all the keys in sorted order. Let us know if you have some ideas specific for LSM trees with these properties.

**Comment by campoy** [comment]
Hi there, @burmanm 

This seems like it would be a really big change in our current codebase.
I'll keep the issue in our list of potential ideas for later improvements, but the priority will stay low until we find more demand for the feature.

Thanks
