### ISSUE TITLE
Allow multiple iterators in a single Read / Write transaction

### ISSUE THREAD

**Issue by timshannon** [dgraph-io/badger#705]
Currently you can only have one iterator on a read / write transaction:
https://github.com/dgraph-io/badger/blob/master/iterator.go#L396

I have a scenario where I would want to read the consistent state of the current transaction before it's committed.  I'm currently getting around this by re-seeking a single iterator, but the ideal situation would allow for using multiple iterators.

According to this comment: https://github.com/dgraph-io/badger/pull/704#issuecomment-459037069 it may be possible.

**Comment by noahdesu** [comment]
This would be useful to have. For example, to do basic merge-join in a transaction.

**Comment by campoy** [comment]
Adding this to the list of API changes we're considering for v2.

**Comment by campoy** [comment]
It seems we could use multiple iterators as long as it's not concurrently, would that be enough or do we need to change anything in our code?

**Comment by timshannon** [comment]
I don't see why that would be an issue.

**Comment by campoy** [comment]
Why would using multiple iterators concurrently would be an issue? Data races, unfortunately.

Why do you need multiple non-read-only iterators concurrently?
Is there a specific algorithm you're trying to implement?

**Comment by timshannon** [comment]
Sorry, I've been busy, and I just revisited this and realized that in my glibness my response may have been interpreted differently than I intended.  I meant I didn't see any reasons why changing to multiple non-concurrent iterators would cause me any problems.  I meant that I'm fine with that change.

Sorry for the confusing.

**Comment by campoy** [comment]
In that case, I think this issue can be closed?
Let me know if there's any other questions you might have and thanks for contributing :)
