### ISSUE TITLE
Byte-ordered floats - help needed

### ISSUE THREAD

**Issue by jpincas** [dgraph-io/badger#709]
I really hope you don't mind me asking this here - this is not an issue with Badger, but I have a feeling you guys will be well placed to help.

I'm working on Tormenta (https://github.com/jpincas/tormenta) which is backed by Badger.  I am creating keys which contain floats which need to be stored in byte-order so I can user Badger's key iteration properly.  I don't have a solid CS background so I'm a little out of my depth.

I encode the floats like this: `binary.Write(buf, binary.BigEndian, value)`.  This works fine for positive floats, but the byte ordering breaks down for negative floats.

As an aside, ints present the same problem, but I was able to fix that relatively easily by flipping the sign bit on the int with `b[0] ^= 1 << 7` (where `b` is the `[]byte` holding the result of encoding the int), and then flipping back when retrieving the key.

Although `b[0] ^= 1 << 7` DOES also flip the sign bit on floats and thus places all the negative floats before the positive ones, the negative ones are incorrectly (backwards) ordered.  It is necessary to flip the sign bit and reverse the order of the negative floats.

A similar question was asked on StackOverflow here: https://stackoverflow.com/questions/43299299/sorting-floating-point-values-using-their-byte-representation, and the solution was agreed to be:

> XOR all positive numbers with 0x8000... and negative numbers with 0xffff.... This should flip the sign bit on both (so negative numbers go first), and then reverse the ordering on negative numbers.

However, that's way above my bit-flipping-skills level, so I was hoping a Go bit-ninja could help me translate that into some Go code.

**Comment by jpincas** [comment]
If anyone is interested - I asked the question on StackOverflow and got a great solution: https://stackoverflow.com/questions/54557158/byte-ordering-of-floats

Here are the functions I use to manipulate the encoded bytes of floats so they are stored in byte order:
```func flipFloat(b []byte) []byte {
	if b[0]>>7 > 0 {
		for i, bb := range b {
			b[i] = ^bb
		}
	} else {
		b[0] ^= 0x80
	}

	return b
}

func flipFloatBack(b []byte) []byte {
	if b[0]>>7 > 0 {
		b[0] ^= 0x80
	} else {
		for i, bb := range b {
			b[i] = ^bb
		}
	}

	return b
}```

**Comment by MeirionHughes** [comment]
FYI see https://github.com/google/orderedcode
