### ISSUE TITLE
Add io.Reader to Item

### ISSUE THREAD

**Issue by thumbsized** [dgraph-io/badger#710]
Hi, I have gobed data stored as values and when I want to read them I have to creaate new buffer, get data from item via Value() function, fill the buffer with the data and then call encoder on the struct.

I think that the Item could match the io.Reader interface so items could be used directly without the need to call the Value() method in cases when such data access is required.

**Comment by campoy** [comment]
Thanks for the report, @thumbsized 

Could you provide a quick sample of the kind of code you ended up writing?

We're considering changes to the API as we approach the release of badger v2 and your input would be very valuable.

Thanks
