### ISSUE TITLE
Example please? Copying one badgerdb to another

### ISSUE THREAD

**Issue by zfLQ2qx2** [dgraph-io/badger#711]
Hello, I was wondering if someone could show me a better way of copying one database to another.

I am iterating through one database and writing a subset of keys to a second database. If I am reading an item and writing it immediately in a single transaction that works - but is incredibly slow (there are 20 million keys/items I am copying, the overhead of doing each one in a separate transaction is too much.

I then made various attempts to write records in batches of a few thousand, but after writing all 20 millions records I would query the new database and find that only nine or ten records were present. I ran into this numerous times.

The way I eventually got everything to work was by making copies of both the key and values returned from the iterator (as in make([]byte, len), copy(dst, src)). Using this method I could copy the records in a reasonable amount of time and all the records were present in the new database. However, it seems like I'm doing a lot of extra work.

Does anyone have a quicker/better way of doing the same thing?

**Comment by manishrjain** [comment]
Use Stream framework and batchwriter.
