### ISSUE TITLE
New release and update changelog

### ISSUE THREAD

**Issue by arctica** [dgraph-io/badger#717]
The last release was 8 months ago and the changelog also has no information as to what changed since then but there have been quite a bit of commits and changes.

Please consider making a new release and updating the changelog.

**Comment by campoy** [comment]
This is definitely not a P0 issue, but we should fix it anyway.

We are going to be releasing a new v2 version which will contain a bunch of new features and a detailed change log.

In the future the release pace will be much more regular, which will avoid this issue from happening.

Thanks for the report, @arctica!

**Comment by campoy** [comment]
A new release has been cut, @arctica!

You can now download the latest version v2.0.0-rc1 for testing, we should release the final version next week after some testing
