### ISSUE TITLE
Info about keys in the tree

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#719]
We need a way to show how many keys are stored per SSTable, and the overall key and value size distribution. We have something similar in `dgraph debug` tool. We can apply that in Badger as well, to show more debug information to the end user.

Could be part of the existing `badger info` tool.

**Comment by sch00lb0y** [comment]
How about storing the number of keys in the table manifest itself, when badger flushes or comapacting.
then we can show the number of keys by reading the manifest.  

I would like to pick this one.

**Comment by jarifibrahim** [comment]
I'm trying to find a good way to count the number of keys per SSTable. The following code snippet shows the number of keys per SSTable per Level (few meta keys also) but it isn't efficient.
```go
TotalKeys := 0
for lid, l := range db.lc.levels {
    for tid, t := range l.tables {
        it := t.NewIterator(false)
        var count int
        for it.Rewind(); it.Valid(); it.Next() {
            count++
        }
        TotalKeys += count
        fmt.Printf("Level:%d Table:%d Count:%d Size:%d\n", lid, tid, count, t.Size())
    }
}
```

@manishrjain do we store the key counts anywhere?

**Comment by manishrjain** [comment]
It is just for debugging. It is good enough.
