### ISSUE TITLE
badger database size much bigger than leveldb 

### ISSUE THREAD

**Issue by Lpc-Win32** [dgraph-io/badger#741]
I have been attempting to migrate an application from LevelDB to Badger. But Badger databases(400G) much better than LevelDB(146G).
Base on commit deee8c7
Most operations is insert, so I think the matter is not GC's.
Witch options should tuning? Thanks for your help！

```golang
func (db *BadgerDB) badgerGc() {
	ticker := time.NewTicker(1 * time.Minute)
	defer ticker.Stop()
	for range ticker.C {
	again:
		err := db.db.RunValueLogGC(0.5)
		if err == nil {
			goto again
		}
	}
}

func NewBadgerDB(name string, dir string) (*BadgerDB, error) {
	dbPath := filepath.Join(dir, name + ".db")
	badgerOpts := badger.DefaultOptions
	badgerOpts.Dir      = dbPath
	badgerOpts.ValueDir = dbPath

	db, err := badger.Open(badgerOpts)
	if err != nil {
		return nil, err
	}

	database := &BadgerDB{
		db: db,
	}
	go database.badgerGc()

	return database, nil
}
```

**Comment by Lpc-Win32** [comment]
I konw the reason! leveldb used snappy to compress data. 
I will try to reduce badger storge size, like leveldb

**Comment by tmm1** [comment]
Are there still plans to compress values inside badger?

**Comment by campoy** [comment]
Hi there, yes @tmm1 - we have plans to add encryption and compression to our datasets.
