### ISSUE TITLE
Badger reading stale data causing transaction conflicts

### ISSUE THREAD

**Issue by sarath-ambati** [dgraph-io/badger#742]
I have a scenario where I would like to increment a value in the badger store. These update can happen concurrently. In the code, I take lock on a mutex, read and increment the value and unlock it. The other go routine, will wait for the unlock and increment the value. But gets a commit error with "Transaction Conflict". Even though the second routine reads after the commit of the first one, the read is stale. 
Note that I am creating the connection before the mutex lock. If i create the connection after the mutex lock in the below example, it works fine. Seems like, when the connection is created, badger reads based on the a snapshot at the time connection is created. 

I would like to handle txns manually as i have a bunch of updates to perform as part of the connection. Each routine can create the connection and perform their work until they hit a common object to update on and the application handles these locks.

Can you point me to the right way for handling such scenarios ? Is there an option that I can use to not read stale data ?

```go
package main

import (
	"fmt"
	"strconv"
	"sync"

	"github.com/dgraph-io/badger"
)

var DB *badger.DB

func Setup(badgerDir string) {
	opts := badger.DefaultOptions
	opts.Dir = badgerDir + "/badgerdb/state"
	opts.ValueDir = badgerDir + "/badgerdb/state"
	db, err := badger.Open(opts)
	DB = db
	if err != nil {
		panic(err)
	}
}

func GetConnection() *badger.Txn {
	return DB.NewTransaction(true)
}

func Read(txn *badger.Txn, key []byte) ([]byte, error) {
	item, err := txn.Get(key)
	if err != nil {
		return nil, err
	}
	resultBytes, err := item.ValueCopy(nil)
	if err != nil {
		return nil, err
	}

	return resultBytes, err
}

func Write(txn *badger.Txn, key []byte, val []byte) error {
	err := txn.Set([]byte(key), val)
	if err != nil {
		return err
	}

	return nil
}

func main() {
	fmt.Println("Hello World")
	Setup("./test")

	var i int64
	wg := &sync.WaitGroup{}
	mutex := &sync.Mutex{}

	for i = 0; i < 3; i++ {
		wg.Add(1)
		go func(i int64) {
			fmt.Println("Trying to read" + strconv.FormatInt(i, 10))
			txn := GetConnection()
			mutex.Lock()
			res, err := Read(txn, []byte("test"))
			val := 0
			if err == nil {
				fmt.Println("Existing value in  DB: " + string(res))
				val, _ = strconv.Atoi(string(res))
				val++
				fmt.Println("Value to be stored:" + strconv.FormatInt(int64(val), 10))
			}
			//store.WriteBytes(ctx, "test", []byte(strconv.FormatInt(int64(val), 10)))
			Write(txn, []byte("test"), []byte(strconv.FormatInt(int64(val), 10)))
			err = txn.Commit()
			if err != nil {
				fmt.Println("Error in commit." + err.Error())
			}
			wg.Done()
			mutex.Unlock()
		}(i)
	}
	wg.Wait()
	txn := GetConnection()
	res, _ := Read(txn, []byte("test"))
	fmt.Println(string(res))
	txn.Discard()
}
```

**Comment by jarifibrahim** [comment]
>Seems like, when the connection is created, badger reads based on the a snapshot at the time connection is created.

@sarath-ambati A transaction relies on last read timestamp. Transactions in badger can run concurrently (provided they do not modify the same key)

If you create the transaction after acquiring the mutex, it would work fine. This ensures that the transaction sees up-to-date data
```go
func main() {
    ....
    for i = 0; i < 3; i++ {
        wg.Add(1)
        go func(i int64) {
            fmt.Println("Trying to read" + strconv.FormatInt(i, 10))
            mutex.Lock()
            txn := GetConnection()
            ....
            wg.Done()
            mutex.Unlock()
        }(i)
    }
```
You could also try creating one transaction and then performing all the operations inside it.
```go
func main() {
    ....
   txn := GetConnection()
   for i = 0; i < 3; i++ {
        wg.Add(1)
        go func(i int64) {
            fmt.Println("Trying to read" + strconv.FormatInt(i, 10))
            mutex.Lock()
            ....
            wg.Done()
            mutex.Unlock()
        }(i)
    }
    wg.Wait()
    err := txn.Commit()  // IMPORTANT: Commit only after all go routines are completed
    if err != nil {
        fmt.Println("Error in commit." + err.Error())
    }
```

>I would like to handle txns manually as i have a bunch of updates to perform as part of the connection. Each routine can create the connection and perform their work until they hit a common object to update on and the application handles these locks.

You can use the `managed mode`. Open the database using the following method
https://github.com/dgraph-io/badger/blob/851e462df52e830df8415f92676c0c9586a21df6/managed_db.go#L19-L27

and commit using 
https://github.com/dgraph-io/badger/blob/851e462df52e830df8415f92676c0c9586a21df6/managed_db.go#L48

**Comment by jarifibrahim** [comment]
@sarath-ambati I think the comment above answers all your questions. Can we close this issue?

**Comment by jarifibrahim** [comment]
Closing this issue. Please feel free to reopen.
