### ISSUE TITLE
BatchWrites

### ISSUE THREAD

**Issue by icholy** [dgraph-io/badger#75]
Are there any plans to add support for batched writes?

**Comment by stephane-martin** [comment]
I think it is already supported?

- add the writes to an *Entry slice with EntriesSet (https://godoc.org/github.com/dgraph-io/badger/badger#EntriesSet)
- batch them with BatchSet (https://godoc.org/github.com/dgraph-io/badger/badger#KV.BatchSet)

**Comment by icholy** [comment]
@stephane-martin ah, missed that.
