### ISSUE TITLE
Txn.DeleteWithMeta

### ISSUE THREAD

**Issue by yangzh** [dgraph-io/badger#751]
first of all, great system: simple design and enable endless possibilities!

I would like to propose the addition of DeleteWithMeta for Txn.

We already have SetWithMeta, and in my own hacking I would like to specify specific user meta to remove, hence a Txn.DeleteWithMeta will be helpful.

For the same reason, a WriteBatch.DeleteWithMeta is also helpful, but to a lesser extent.

I guess that would be very straightforward to implement. Thanks again!

**Comment by campoy** [comment]
Hi @yangzh and thanks for your message!

Could you give us a quick example of what is the use case behind deleting something with metadata?

The current API doesn't provide `SetWithMeta` anymore as it has been replaced by the `WithMeta` method of the `Entry` type.
But even if that had not changed, how would adding metadata to an entry right before deleting would help you in your use case?

**Comment by yangzh-deepmap** [comment]
thanks, @campoy, I didn't check messages earlier.

DeleteWithMeta might be a misnomer, what I wanted is to delete entry that has the key, and with certain Meta data only, so Txn.DeleteByMeta would be more appropriate name.

I'm not sure if the updated API supports this feature: it would be great if you already provide that (or consider adding it). 

The use case is that I might have Entries with the same key, but with different Meta, and I want to selectively remove one of them, and keep others intact.

Hope that clarifies. thanks.

**Comment by campoy** [comment]
I see, so you'd be using the Meta as a way to select all the keys you want to delete?

If I understand that correctly, this should be doable iterating over the keys yourself and deleting the ones that have the given meta value. Is that accurate?

**Comment by yangzh** [comment]
@campoy, thanks for the response, your response is right.

Previous I thought about reusing "Meta" as another independent dimension for data modeling. However, that doesn't seem to be the case for badger as you cannot have data entries with the same key (and version, for that matter), but different "Meta". "Meta" is more like half dimension in this sense.

If I were to have a full dimension support for "Meta", probably I need to use an application-level composite key (key, Meta).

Anyway, I don't think this is relevant to this request, closing it.
