### ISSUE TITLE
Concurrent writes via update

### ISSUE THREAD

**Issue by fpessolano** [dgraph-io/badger#756]
Is golang safe for concurrent writes?
I have an application with several threads (can be a very large number) which access the same badger DBS to write. Concurrent writes (only to different keys) can happen. 
If I test for races (with -race) I get continuos reports of concurrent write data races.
Is this normal?

**Comment by ashish-goswami** [comment]
@fpessolano Badger is safe for concurrent writes. You can call **db.Update** method from different threads to write data to badger. Documentation link https://github.com/dgraph-io/badger#read-write-transactions

**Comment by fpessolano** [comment]
This is what I thought, however go -race reports races for mist badger accesses, should I simply ignore them?

**Comment by ashish-goswami** [comment]
Can you share example with us?

**Comment by fpessolano** [comment]
I try even if I cannot disclose much of the code.
Every thread can write on the database but on different locations, it is by construction impossible that they write on badger with the same key. When they need to write they call a function (as function not goroutine) that looks like this:

```
func StoreSample(d SampleData, sDB bool, updatehead ...bool) (err error) {
	ts := d.Ts()
	tag := d.Tag()
	val := d.Marshal()
        if st, ok := tagStart[tag]; ok {
		i := (ts - st[0]) / (st[1] * 1000)
		lab := tag + strconv.Itoa(int(i))
		if sDB {
			err = update(val, []byte(lab), *statsDB, false)
		} else {
			err = update(val, []byte(lab), *currentDB, false)
		}
	} else {
		err = errors.New("Serie " + tag + " not found")
	}
	if len(updatehead) == 1 {
		// do something
	}
	return err
}
```

The update function is pretty simple:

```
func update(a []byte, id []byte, db badger.DB, ttl bool) (err error) {
	err = db.Update(func(txn *badger.Txn) error {
		var err error
		if ttl {
			err = txn.SetWithTTL(id, a, currentTTL)
		} else {
			err = txn.Set(id, a)
		}
		return err
	})
	return err
}
```

Badger works fine, but when I run in debug with -race I get a race warning every time err = db.Update(func(txn *badger.Txn) error {…} is executed. If I comment it … race warnings are gone. All racing warnings refer to badger/db.go lines 533, 623 and 660 (updateHead, writeRequests, doWrites.funcl)

**Comment by fpessolano** [comment]
This is how the DB are declared
```

                  once.Do(func() {
			optsCurr := badger.DefaultOptions
			optsCurr.Truncate = true
			optsCurr.Dir = "dbs/current"
			optsCurr.ValueDir = "dbs/current"
			optsStats := badger.DefaultOptions
			optsStats.Truncate = true
			optsStats.Dir = "dbs/statsDB"
			optsStats.ValueDir = "dbs/statsDB"
			currentDB, err = badger.Open(optsCurr)
			if err == nil {
				statsDB, err = badger.Open(optsStats)
				if err != nil {
					_ = currentDB.Close()
				}
			}
		})
```

**Comment by campoy** [comment]
Hi there, @fpessolano.

Could you provide a complete repo reproducing this issue? A very simplified version of the code that is causing this crash would allow us to figure out what the issue is and how we can fix it.

Thanks!
