### ISSUE TITLE
Support Go modules for v2

### ISSUE THREAD

**Issue by treeder** [dgraph-io/badger#758]
Could you add a `go.mod` and update imports for v2 so we can use the v2 releases release candidates with modules?

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by gedw99** [comment]
+1

**Comment by campoy** [comment]
Hey @treeder,

Sorry for the delay. We're actually working on a couple of extra changes that we'd like to include with our v2.
We will update this issue with a plan for our v2 release next week.

In the meanwhile, is this an urgent change?
Could you give more details on how this is currently breaking your workflow?

Thanks!

**Comment by treeder** [comment]
Francesc!  Been a while.. :) Didn't know you were involved with this, great project. 

It's not urgent, seems to be working fine with `github.com/dgraph-io/badger v2.0.0-rc.2+incompatible`. I can't remember exactly what issue I was having though as I created this over a month ago (and my memory doesn't last that long).

**Comment by campoy** [comment]
Once #646 has been merged giving support for modules for badger v1.5.4 we can create a branch to support v2.

**Comment by thedevsaddam** [comment]
@campoy I just pushed the dependency updates on #646

**Comment by campoy** [comment]
Go modules is now supported for v1.5.5 and will soon be supported for v2.0.0 as soon as we tag it.

The release will be tagged once all the issues in the milestone are closed https://github.com/dgraph-io/badger/milestone/5
