### ISSUE TITLE
'compaction on level 0' warning explanation?

### ISSUE THREAD

**Issue by drew-512** [dgraph-io/badger#759]
First, allow me say how awesome it is to be using Badger and what a privilege to have such a badass db engine be FOSS.  Many thanks!

Sorry if this is a repeat question, but can anyone explain what is likely happening and why I see the below message?

`WARNING: While forcing compaction on level 0: Unable to fill tables`

I comes consistently after I make a new db and only add a couple k-v pairs.  

Thanks!

**Comment by manishrjain** [comment]
Thanks!

That's a normal thing, no need to be worried about this "error." It just means that when trying to compact level 0, we couldn't find enough tables to cause a compaction.

**Comment by drew-512** [comment]
Ok cool, thanks. ;) 

When I see "warning" it means "notable cause of concern" to me.  This looks more like an "info" level of concern and I guess we'll have to get used to that shift.

**Comment by jarifibrahim** [comment]
@drew-512 The error message was fixed in https://github.com/dgraph-io/badger/commit/291295e18f0eca0ea8ca6df9e2725cfe73b4c915#diff-7a117cbfd5485ed35efcbb2995c37aa0R378 commit. On newer versions of badger, you won't see this warning.

Closing this issue. Feel free to reopen.
