### ISSUE TITLE
Throttle the number of pending txns in WriteBatch

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#760]
Currently, WriteBatch can create too many pending txns, which can cause memory issues. Instead, we should add a method `SetMaxPending(max int)` (default to 100 maybe), which can be enforced via `Commit` and `callback` using `Throttle`. In fact, Throttle can be used to simplify the internals of WriteBatch.

**Comment by manishrjain** [comment]
We also need Throttle in `db.Load` method for similar reasons.

**Comment by tsellers-r7** [comment]
As a note, this looks related to the other P0 Issue
https://github.com/dgraph-io/badger/issues/714

**Comment by ashish-goswami** [comment]
Fixed in https://github.com/dgraph-io/badger/pull/762
