### ISSUE TITLE
Txn.SetEntryWithDiscard

### ISSUE THREAD

**Issue by chernomyrdin** [dgraph-io/badger#774]
First of all,
great system: simple design and enable endless possibilities!

I would like to propose the addition of SetEntryWithDiscard for Txn. Or somethig else fo set meta bit `bitDiscardEarlierVersions` in Entry.
For the same reason, a WriteBatch.SetEntryWithDiscard is also helpful, but to a lesser extent. I guess that would be very straightforward to implement.

Thanks again!

**Comment by ashish-goswami** [comment]
@chernomyrdin Thanks for raising the issue. We already have **SetWithDiscard** for Txn, which is similar to what you are proposing. However we don't have this in **WriteBatch**.
Feel free to raise a PR if possible.

**Comment by chernomyrdin** [comment]
I need save to database Entry with TTL and DiscadEarlierVersions at one time.
first variant code:
```
// SetEntryWithDiscard acts like SetEntry, but adds a marker to discard earlier
// versions of the key.
//
// The current transaction keeps a reference to the entry passed in argument.
// Users must not modify the entry until the end of the transaction.
func (txn *Txn) SetEntryWithDiscard(e *Entry) error {
	return txn.modify(&Entry{
		Key:       e.Key,
		Value:     e.Value,
		UserMeta:  e.UserMeta,
		ExpiresAt: e.ExpiresAt,
		meta:      bitDiscardEarlierVersions,
	})
}
```
or second variant:
```
// SetEntryWithDiscard acts like SetEntry, but adds a marker to discard earlier
// versions of the key.
//
// The current transaction keeps a reference to the entry passed in argument.
// Users must not modify the entry until the end of the transaction.
func (txn *Txn) SetEntryWithDiscard(e *Entry) error {
	e.meta = bitDiscardEarlierVersions
	return txn.modify(e)
}
```
What code style preferred?

**Comment by ashish-goswami** [comment]
@chernomyrdin ExpiredAt is exported field and hence can be set directly using dot operator like **e.ExpiredAt = time.Now().Unix()**

**Comment by ashish-goswami** [comment]
We have introduced new APIs for Entry. These APIs allows you to set more than one property on Entry. Finally calling SetEntry on Transaction/WriteBatch adds entry to Transaction/WriteBatch. https://github.com/dgraph-io/badger/pull/822
