### ISSUE TITLE
txn.Commit() in README example is missing an argument

### ISSUE THREAD

**Issue by bep** [dgraph-io/badger#779]
I copied and pasted an example, and it did not compile.

**Comment by ashish-goswami** [comment]
@bep are you talking about below example?
```go
updates := make(map[string]string)
txn := db.NewTransaction(true)
for k,v := range updates {
  if err := txn.Set([]byte(k),[]byte(v)); err == ErrTxnTooBig {
    _ = txn.Commit()
    txn = db.NewTransaction(..)
    _ = txn.Set([]byte(k),[]byte(v))
  }
}
_ = txn.Commit()
```
I have raise a PR for this https://github.com/dgraph-io/badger/pull/780

**Comment by bep** [comment]
There are several.

**Comment by ashish-goswami** [comment]
@bep can you tell us where else you are facing this issue?

**Comment by bep** [comment]
Use a search in the README for  `txn.Commit()`

**Comment by campoy** [comment]
Closing this issue due to lack of detail on what doesn't compile and which error message it causes.

Please feel free to open if you are able to provide the code snippet, platform, version for the repo and tooling, etc.
