### ISSUE TITLE
Allow more than one byte in UserMeta

### ISSUE THREAD

**Issue by bep** [dgraph-io/badger#784]
This was discussed by @janardhan1993  and @srh back when this was added in #123 -- but was left as is, for now: "We could always make it more generic later."

I'm doing some prototyping using Badger as a storage for some planned new features in Hugo. And one problem I'm tinkering with is to find a reasonably fast way of detecting changes.

So, I thought if I could store an MD5 checksum (16 bytes) in `UserMeta` I would be home free.

Oh, and feel free to chime in with "why don't you do _this_ instead?".

I could create a PR for this myself. My main concern is how to handle the API change, since `UserMeta` is now currently a single `byte`.

**Comment by manishrjain** [comment]
The moment we allow UserMeta to be a byte slice, users are going to start using it for storing values. That's the job of the value. UserMeta is only meant to allow one to identify the type of a value without fetching it.

I think you could instead create some index keys, which can contain the MD5 checksums. Keeping them in a different prefix would allow you to use the prefix iterator to quickly identify what data changed.

**Comment by campoy** [comment]
Hi @bep,

Did @manishrjain answer help? Changing `UserMeta` to be a slice is clearly a backwards incompatible change, but I'd like to understand better what you're trying to implement.

In a different issue we have a proposal to subscribe to changes on the database. Would that help your use case?

**Comment by bep** [comment]
@campoy yes, his answer help. I started this thread after some very early test with this library. I will close this.
