### ISSUE TITLE
Ristretto caching for bloomfilters in memory

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#791]
While debugging https://github.com/dgraph-io/badger/issues/772#issuecomment-486614654 we realized that bloomfilter size increases as the number of table increases (we store all the bloom filters in memory)

So, we should maintain a clock based cache for the tables in memory and allow them to be evicted.

**Comment by jarifibrahim** [comment]
Related to https://github.com/dgraph-io/badger/issues/663

**Comment by campoy** [comment]
Downgraded to p1 since no action has been taken since this was filed.

Should this still be worked on? If so, let's chat about how and when to implement this.

**Comment by manishrjain** [comment]
We should do something to avoid bloom filter size growing linearly as the number of tables grow.
