### ISSUE TITLE
Support compression of SS-tables

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#792]
For Badger, it would be nice to support compression of SST tables.
Here's how compression works in RocksDB for reference:
https://github.com/facebook/rocksdb/wiki/Compression

**Comment by jarifibrahim** [comment]
Badger used to support compression of value log but it was removed in https://github.com/dgraph-io/badger/issues/144

**Comment by campoy** [comment]
What's the logic behind this change?

It seems it was previously removed due to the complexity it brought being too high for the commodity it provided.

How has that changed since #144?

**Comment by jarifibrahim** [comment]
@campoy This issue is about compressing data stored in SST. #144 was about compressing value log file.

**Comment by campoy** [comment]
What are the plans on this, then? Is it something already being implemented? What's the urgency on it? Feel free to add the corresponding priority label.

**Comment by jarifibrahim** [comment]
@campoy We don't have any concrete plans for the compression right now. This is something we would need in the future.

**Comment by manishrjain** [comment]
We need compression in Badger. It's a common theme which keeps coming up.
