### ISSUE TITLE
Add benchmark tool to badger

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#801]
We need a way to benchmark the read speed of the disk on which Badger is running.

The tool should first read all the keys in the system, then do lookups on those keys randomly (via multiple goroutines) and report back the read latency observed by Badger. This can help us figure if a certain disk/FS is slower than expected.

**Comment by manishrjain** [comment]
This tool should not try to modify the data set and work with any existing data set.

**Comment by campoy** [comment]
We should have this done for v2 to be able to run benchmarks easily and compare different versions.

@ashish-goswami you had already this issue assigned to you and on P0 for a bit, what are your plans on this?
