### ISSUE TITLE
Benchmark Skiplist Implementation

### ISSUE THREAD

**Issue by ashish-goswami** [dgraph-io/badger#810]
Idea is to see the changes in read and insert time into current Skiplist implementation as more and more keys are inserted into it. Based on the result do optimisations if required.

**Comment by campoy** [comment]
Hey @ashish-goswami, what is the goal of this change?

Could you describe a bit more in detail why and how you're going to benchmark this?

**Comment by campoy** [comment]
Ping @ashish-goswami

**Comment by ashish-goswami** [comment]
Currently writes to DB using transaction APIs are slow. This exercise is to find bottleneck in skiplist implementation, so that writes using transaction API can be improved. Because of slow writes, we implemented StreamWriter, which directly writes data to LSM levels
