### ISSUE TITLE
Allow ValueThreshold to be greater than uint16

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#812]
If we can allow values greater than 64KB to be colocated with the key, Badger can operate like a typical LSM tree. This setting is useful in certain workloads, so we should modify our record header to allow uint32 sized values (4GB-ish). This would be a breaking change.

**Comment by campoy** [comment]
I'd like to better understand what's the goal of this change and how it'd affect the current and potential users of badger.

**Comment by ashish-goswami** [comment]
Badger stores values with size greater than a threshold(**ValueThreshold**), to value log files and its pointer in the LSM tree with the key. If value size is less than the threshold, key and value both are stored in LSM tree only(This way it behaves as pure LSM tree). While storing key and value in LSM tree, their metadata like key size, value size are stored first. Type of value size is currently uint16, This restricts us, from having values with size greater than 64KB(in pure LSM tree mode). If we change the type to uint32, we can have values of size ~4GB.
This will be a breaking change as the underlying format of SST is getting changed. I am addressing this in PR https://github.com/dgraph-io/badger/pull/819

**Comment by campoy** [comment]
Ok please keep this issue updated as we get closer to resolution.

**Comment by jarifibrahim** [comment]
This has been fixed via https://github.com/dgraph-io/badger/pull/893
