### ISSUE TITLE
question: size on disk estimation & configuration

### ISSUE THREAD

**Issue by marcosrmendezthd** [dgraph-io/badger#813]
hi, great work on badger!

 i'm new to badger and would appreciate some help in figuring out how to use badger effectively for our use case. i'd like to use it for store and forward. if things are not working as they should, store it in badger and then read it later when things are working.

i won't know the exact distribution size of the payloads/values i'll be saving. though i'd like keys to be pretty simple, maybe a timestamp (nanos or micros) or a monotonic sequence in order to read them back in order.

i'd like to be able to create the correct badger configuration given a directory and a maximum size so that the directory size does not go over that maximum. i'm not sure i understand all the configuration parameters enough to ensure that this happens.

**Comment by ashish-goswami** [comment]
@marcosrmendezthd Thanks!

We don't have any option as of now, which deletes old data after size of Badger directory exceeds a threshold.

**Comment by marcosrmendezthd** [comment]
@ashish-goswami can i use key expiration for that as well? if i can guesstimate how much overhead i'll need, then i can probably make it work.

**Comment by ashish-goswami** [comment]
Yes. You can use key expiration. In every compaction iteration, Badger will try delete keys which are expired. But this will be the best effort to keep size minimum. There is no guarantee of size not exceeding a threshold.

**Comment by marcosrmendezthd** [comment]
thanks @ashish-goswami !
