### ISSUE TITLE
Create issue template with all needed info

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#831]
Most issues start with someone from the dgraph team requesting for follow-up information on an issue report.

Let's write down the kind of information we'd like to have and how to obtain it and create an issue template to speed up the whole process.

See example #830, maybe @ashish-goswami can take care of this one?
Follow the example of how the Go repo does it https://github.com/golang/go/issues/new

**Comment by jarifibrahim** [comment]
Fixed via https://github.com/dgraph-io/badger/pull/834
