### ISSUE TITLE
Improve disk usage for key-only datasets

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#832]
Created from #738 

Sometimes we want to use badger as a key set rather than a key-value store.

We should consider whether adding some kind of special case behavior for when the value is an "empty" value (e.g. `struct{}`).

Is the complexity added worth the performance gain for this use case? Is the use case common enough?

**Comment by markmssd** [comment]
Not sure where to drop this, so I'll put the link here. Just wanted to share it. I was wondering how well `badger` would run on that new `Key-Value SSD` https://www.anandtech.com/show/14839/samsung-announces-standardscompliant-keyvalue-ssd-prototype... a Key-Value DB running alongside a Key-Value SSD... you know...

**Comment by campoy** [comment]
This doesn't belong here, but it is really interesting!

I created #1040 to track this.

**Comment by manishrjain** [comment]
@campoy : Can you clarify what the issue is? I'm not sure what disk usage issues are you seeing with key-only datasets. Setting value to nil should already be allowed by Badger.

**Comment by jarifibrahim** [comment]
As @manishrjain mentioned, I don't think there's anything to be done here. If the value is set to `nil`, that's as good as setting only the key. The overhead of having a nil value should be very minimal.
