### ISSUE TITLE
Compile as a shared c lib

### ISSUE THREAD

**Issue by ghost** [dgraph-io/badger#836]
Not sure if this is something anyone is interested in, but here goes...

It useful to be able to use badger embedded in other systems. 

For GUI (Mobile and Desktop) I embed it in Flutter using FFI. Others might be using QT or who knows what.
https://gist.github.com/mraleph/2582b57737711da40262fad71215d62e

For IOT is very useful to have a badger at the edge and you need to compile it as a c shared lib in order to get it into the BSP and Yocto aspects.
https://www.zephyrproject.org/
https://github.com/zephyrproject-rtos/zephyr

Either way holding data at the edge using Badger and then streaming changes out of it into DGraph at the center would be an amazingly useful way to build systems.

For making this easy this little gem of golang scaffolding could be a huge help, so you can keep the interfaces in sync with the golang code using just codegen.
https://c.for-go.com

**Comment by campoy** [comment]
Hi @gedw99,

Could you explain a little more in detail whether this is something you're offering to build or whether you're a potential user?

If you're a user, could you tell me also about your experience using badger from a C system? Is this something you've tried at all?

Using `-buildmode=c-shared` should be enough.

**Comment by sleto-it** [comment]
Hi, 

The account of the original author has been deleted. As a result this issue has been associated with the GitHub ghost user (https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account)

As we have not received other comments, I am now closing this issue. Please comment if needed and we will reopen

Many thanks,
