### ISSUE TITLE
iterator issue

### ISSUE THREAD

**Issue by artvel** [dgraph-io/badger#84]
Hi there

I just started trying out badger and it seems very nice so far!
I'm not sure about the behavior of the iterator at one point.

```go
package badger

import (
	"testing"
	"fmt"
	"github.com/dgraph-io/badger/badger"
	"strconv"
)

func TestWrite(t *testing.T) {
	opts := badger.DefaultOptions
	opts.Dir = "data"
	opts.ValueDir = "data"
	kv, err := badger.NewKV(&opts)
	if err != nil{
		panic(err)
	}
	defer kv.Close()
	for i := 0; i < 15000; i++{
		err = kv.Set([]byte("test_"+strconv.Itoa(i)), []byte("value_"+strconv.Itoa(i)))
		if err != nil{
			panic(err)
		}
	}
}

func TestIterator(t *testing.T) {
	opts := badger.DefaultOptions
	opts.Dir = "data"
	opts.ValueDir = "data"
	kv, err := badger.NewKV(&opts)
	if err != nil{
		panic(err)
	}
	defer kv.Close()
	optsi := badger.DefaultIteratorOptions
	it := kv.NewIterator(optsi)
	var kvItem *badger.KVItem
	it.Rewind() // it.Next() produces error without it.Rewind()
	for it.Next();it.Valid();it.Next(){
		kvItem = it.Item()
		fmt.Println("k", string(kvItem.Key()), "v", string(kvItem.Value()), "c", kvItem.Counter())
	}
}

```

I called TestWrite and then TestIterator. Without it.Rewind() before the loop you should encounter an error.
My question is pretty simple. Do I need to call rewind at this point or is it a bug?

**Comment by fraenky8** [comment]
Hi!

i think you used the for-loop in a "wrong" way. You put a Next()-call at the initializing position. Looking at the godoc for the `NewIterator`-function, it says

```go
for it.Rewind(); it.Valid(); it.Next() {
...
}
```

So you can just put the Rewind()-call inside the head of the for-loop.

Still wondering, why a new created iterator must be rewinded, following does not work too, if the Rewind()-call is missing:

```go
it.Rewind()
for it.Valid() {
	kvItem = it.Item()
	fmt.Println("k", string(kvItem.Key()), "v", string(kvItem.Value()), "c", kvItem.Counter())
	it.Next()
}
```

I would expect a new iterator is just usable after creating it.

**Comment by manishrjain** [comment]
The reason `Rewind` must be called, is because we need to know where to start prefetching from. One could not use `Rewind` and use `Seek`. In that case, if we automatically start prefetching from the beginning, all that work would need to be abandoned and would cause delays in doing the `Seek` call.

In short, the reason to specify the initial point is that we do extra work in the background; and we need to know where to begin.

Hope that answers your query.

**Comment by artvel** [comment]
Well, the idea was to implement a custom Seek but as far as I understood it's not possible without calling Rewind.

**Comment by manishrjain** [comment]
You can call `Seek` directly, then you don't need to call `Rewind`.

**Comment by artvel** [comment]
Yes, but you can't build a Seek like Seek([]byte("*contains*")). You can only seek the whole key and that's my issue. I thought it would be possible to build a custom seek without Rewind.
