### ISSUE TITLE
Examples for new stream writer

### ISSUE THREAD

**Issue by tegk** [dgraph-io/badger#842]
Is there a full code example somewhere how to use the new stream writer?

Thanks

**Comment by campoy** [comment]
I wonder if @danielmai or @manishrjain know about this.

**Comment by ashish-goswami** [comment]
Hey @tegk, we have recently started using stream writer in **fill** command to write sorted data https://github.com/dgraph-io/badger/blob/b5fb93ccbae3847592bef7d2eb94863496f2f91c/badger/cmd/fill.go#L75 Please have a look, if it can of any help.

**Comment by campoy** [comment]
After looking into this, the question has been answered and new documentation will be written.
