### ISSUE TITLE
DB Open in readonly mode crashes if directory doesn't exists

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#843]
### What version of Go are you using (`go version`)?
go version go1.12.4 linux/amd64

### What version of Badger are you using?
Master

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
N/A

### What did you do?

```go
package main

import (
	"fmt"

	"github.com/dgraph-io/badger"
)

func main() {
	opt := badger.DefaultOptions
	opt.ReadOnly = true
	opt.Dir = "foobar"

	db, err := badger.Open(opt)
	if err != nil {
		fmt.Println("error", err)
	}
	db.Close()
}
```
### What did you expect to see?
The above program should return an error when the directory doesn't exist

### What did you see instead?
`db.Clost()` call crashed with nil pointer exception
```
➜  go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x798d13]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).Close(0x0, 0x6, 0x0)
	/home/ibrahim/Projects/go/src/github.com/dgraph-io/badger/db.go:349 +0x53
main.main()
	/home/ibrahim/Projects/go/src/github.com/jarifibrahim/foo/main.go:18 +0x157
exit status 2
```

**Comment by campoy** [comment]
This is not a bug.

The program you wrote should not use `db` when `err` is not nil.
The correct code should be:

```go
package main

import (
	"fmt"

	"github.com/dgraph-io/badger"
)

func main() {
	opt := badger.DefaultOptions
	opt.ReadOnly = true
	opt.Dir = "foobar"

	db, err := badger.Open(opt)
	if err != nil {
		fmt.Println("error", err)
		return // or os.Exit(1) or something similar
	}
	defer db.Close()

	// doing stuff with the db
}
```

**Comment by jarifibrahim** [comment]
@campoy The issue is reproducible even with your script. The issue here is that `db` and `err` both are `nil`.
