### ISSUE TITLE
Does badger support range scan directly or indirectly?

### ISSUE THREAD

**Issue by ToWorld** [dgraph-io/badger#847]
I try to use badger as an embeddable kv store to test write performance, and we also need to test the performance of range scan, but I couldn't find out the API of range scan. Could anyone please point me in the right direction?

**Comment by jarifibrahim** [comment]
@ToWorld How about doing something like this?
```Go
startKey := []byte("fooKey")
endKey := []byte("barKey")

iopt := DefaultIteratorOptions
itr := txn.NewIterator(iopt)
defer itr.Close()

for itr.Seek(startKey); itr.Valid(); itr.Next() {
	item := itr.Item()
	if bytes.Equal(item.Key(), endKey) {
		break
	}
    // Process the item
}
```

**Comment by ToWorld** [comment]
> @ToWorld How about doing something like this?
> 
> ```go
> startKey := []byte("fooKey")
> endKey := []byte("barKey")
> 
> iopt := DefaultIteratorOptions
> itr := txn.NewIterator(iopt)
> defer itr.Close()
> 
> for itr.Seek(startKey); itr.Valid(); itr.Next() {
> 	item := itr.Item()
> 	if bytes.Equal(item.Key(), endKey) {
> 		break
> 	}
>     // Process the item
> }
> ```

Thank you for your response. And there is an obvious mistake to be corrected that you should use the function of Compare instead of Equal when the endKey is absent.

**Comment by jarifibrahim** [comment]
>Thank you for your response. And there is an obvious mistake to be corrected that you should use the function of Compare instead of Equal when the endKey is absent.

Yes, that's correct.

Closing this.
