### ISSUE TITLE
deadlock of badger

### ISSUE THREAD

**Issue by nnsgmsone** [dgraph-io/badger#848]
### What version of Go are you using (`go version`)?

<pre>
$ go version
</pre>

go 1.12 and go 1.11

### What version of Badger are you using?

latest master 

### Does this issue reproduce with the latest master?

yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?

ubuntu18.04 

### What did you do?

I run the following code:
```
package main

import "fmt"
import "time"
import bd "github.com/dgraph-io/badger"

func main() {
	opts := bd.DefaultOptions
	opts.Dir = "/tmp/test"
	opts.ValueDir = "/tmp/test"
	bd.Open(opts)
	go func() {
		for {
		}
	}()
	go func() {
		cnt := 1
		for {
			time.Sleep(100 * time.Millisecond)
			cnt = cnt + 1
			fmt.Println(cnt)
		}
	}()
	time.Sleep(time.Hour)
}
```
### What did you expect to see?

I hope to see the number of non-stop output increases.

### What did you see instead?
output is stop，program deadlock

**Comment by nnsgmsone** [comment]
gc forced caused the dead end，the specific reasons are confusing.

**Comment by gitlw** [comment]
Hi @nnsgmsone 

I tried this program, and the numbers are always increasing in the output. Hence I'm not sure how to reproduce the problem.
If you still believe you are getting a deadlock, can you please try to locate the process id, use the command
`kill -3 <process id>`
to trigger a goroutine dump, and post the dump here? That should help shed some light on the real problem.

**Comment by nnsgmsone** [comment]
I found this to be a problem with golang. Thank you.

**Comment by nnsgmsone** [comment]
Ok, this is a problem with golang. This is the link: https://github.com/golang/go/issues/10958

**Comment by nnsgmsone** [comment]
@gitlw That will take a few minutes to trigger, and it will take the gc force to divide the deadlock.
