### ISSUE TITLE
retry indefinitely when disk errors occurred

### ISSUE THREAD

**Issue by huangnauh** [dgraph-io/badger#864]
[retry indefinitely when disk errors occurred](https://github.com/dgraph-io/badger/blob/master/db.go#L923)

* Let the user control retry flush times.
* Receive error events from badger.

This gives the user a chance to stop badger or do something else when disk errors occurred.

This is useful for databases built on top of Badger.

**Comment by campoy** [comment]
This issue should be part of our next release, just waiting for #861 to be merged.
