### ISSUE TITLE
Difference Between Options.Dir and Options.ValueDir

### ISSUE THREAD

**Issue by postables** [dgraph-io/badger#866]
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 linux/amd64
</pre>

The documentation isn't very clear on what the difference is between these two options. When `Dir` and `ValueDir` are the same value, I see the following types of files:

```
1.1G    000000.vlog
580K    000001.sst
26M     000001.vlog
4.0K    000002.sst
4.0K    LOCK
4.0K    MANIFEST
```

Based off a guess, I would say the `.vlog` are the location of the "value files", where `ValueDir` stores things, and everything else is where `Dir` stores stuff? What's the point of the `.sst` files? I'm guessing those are the LSM trees?

**Comment by jarifibrahim** [comment]
@postables Badger has two main types of files
1. `SST` file which stores the keys in sorted order (it might optionally store the values also)
2. `Value Log (vlog)` file which stores all the values. The vlog file serves as a Write Ahead Log (WAL) for badger. All the entries inserted into Badger are first written to the WAL and then inserted into the LSM Tree.

The `Options.Dir` stores `SST` files while `Options.ValueDir` stores the `value log` files.
The `value log` files can be used to recover badger in case of a crash.

**Comment by postables** [comment]
Excellent that clears up my confusion. Thank you.
