### ISSUE TITLE
Optimize serial writes

### ISSUE THREAD

**Issue by nnsgmsone** [dgraph-io/badger#869]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

go version go1.11.4 linux/amd64

### What version of Badger are you using?

newest

### Does this issue reproduce with the latest master?

yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?

16GB, ntel® Xeon(R) CPU E3-1225 v6 @ 3.30GHz × 4, 256G SSD

### What did you do?

I run the following code:
```go
  opts := badger.DefaultOptions
    opts.Dir = "test.db"
    opts.ValueDir = "test.db"
    db, err := badger.Open(opts)
    if err != nil {
        log.Fatal(err)
    }
    t := time.Now()
    for i := 0; i < 100000; i++ {
        tx := db.NewTransaction(true)
        if err := tx.Set([]byte(fmt.Sprintf("%v", i)), []byte(fmt.Sprintf("%v", i))); err != nil {
            tx.Discard()
            log.Fatal(err)
        }
        if err := tx.Commit(); err != nil {
            log.Fatal(err)
        }
    }
    fmt.Printf("process: %v\n", time.Now().Sub(t))
```
### What did you expect to see?

I hope it will be completed in a few seconds

### What did you see instead?
It took three minutes

**Comment by jarifibrahim** [comment]
@nnsgmsone The code works slowly because you're committing each entry individually. You can use `write batch` API if you want to perform bulk insert. Also, take a look at the second question in the FAQ https://github.com/dgraph-io/badger#frequently-asked-questions

Take a look at this example
```go
opts := badger.DefaultOptions
opts.Dir = "/tmp/test"
opts.ValueDir = "/tmp/test"

db, err := badger.Open(opts)
if err != nil {
	log.Fatal(err)
}
t := time.Now()
for i := 0; i < 100000; i++ {
	tx := db.NewTransaction(true)
	if err := tx.Set([]byte(fmt.Sprintf("%v", i)), []byte(fmt.Sprintf("%v", i))); err != nil {
		tx.Discard()
		log.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}
}
fmt.Printf("Time taken via Transaction: %v\n", time.Since(t))
t = time.Now()
wb := db.NewWriteBatch()
for i := 0; i < 100000; i++ {
	if err := wb.Set([]byte(fmt.Sprintf("%v", i)), []byte(fmt.Sprintf("%v", i)), 0); err != nil {
		log.Fatal(err)
	}
}
if err := wb.Flush(); err != nil {
	log.Fatal(err)
}
fmt.Printf("Time taken via write batch: %v\n", time.Since(t))

```
``` 
go run main.go  
badger 2019/06/17 16:05:32 INFO: All 0 tables opened in 0s
Time taken via Transaction: 1m31.054582494s
Time taken via write batch: 328.984388ms
```

**Comment by nnsgmsone** [comment]
Thanks, I have packaged the redis protocol on the badger. If i use batch, then different commands will affect each other?

**Comment by manishrjain** [comment]
Hey @jarifibrahim , for fun, can we actually determine why serial writes are slow. Maybe we can identify some optimizations to be had. We use channels internally, maybe they cause some slowdown here; or maybe it's something else.

One thing to immediately try out would be to set `SyncWrites` to false and see how fast that makes the serial writes.

Optimizing serial writes isn't a priority, but this issue gives us a chance to really get this path tested. So, I'm going to reopen this issue and we can get to it once we're past v2.1 and some of the other urgent things.

**Comment by nnsgmsone** [comment]
@manishrjain i think so

**Comment by hudbrog** [comment]
Is there any reason batch is not included in 1.5.x releases?

**Comment by jarifibrahim** [comment]
@hudbrog We recently released badger v1.5.5 which includes the Write batch API https://github.com/dgraph-io/badger/compare/v1.5.5...master

**Comment by jarifibrahim** [comment]
The serial writes are slower because we don't batch entries. We write individual entries to the value log and the file write system call takes most of the time. We should batch entries while writing them to the vlog.
![profile002](https://user-images.githubusercontent.com/12949454/60975510-bff5ae00-a349-11e9-82d6-6195eb6cd0c0.png)

**Comment by jarifibrahim** [comment]
@nnsgmsone You can set `options.SyncWrites=false` if you want to achieve better performance. Setting sync writes to false means we won't sync every write to the file. This would improve badger performance but it might cause data loss in case of a crash.
With sync writes => about 6 minutes
Without sync writes => about 4.2 seconds

**Comment by nnsgmsone** [comment]
@jarifibrahim ok, Is it possible to use a dedicated goroutine to periodically refresh data to disk when sync is off?

**Comment by jarifibrahim** [comment]
@nnsgmsone You run `db.Sync()` method periodically https://github.com/dgraph-io/badger/blob/afa8faea28202a295f48846f6f61fd1931eed9ab/db.go#L482-L486

**Comment by nnsgmsone** [comment]
@jarifibrahim ok

**Comment by manishrjain** [comment]
I think this issue has been sufficiently diagnosed. Long story short, turn off SyncWrites and serial writes are much faster.
