### ISSUE TITLE
Dependency not installed

### ISSUE THREAD

**Issue by carlca** [dgraph-io/badger#87]
Hello, I've just installed using `go get github.com/dgraph-io/badger`. I then went to the `badger` folder and ran `go test`. I got the error message:
```
# github.com/dgraph-io/badger
kv_test.go:29:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/usr/local/go/src/github.com/stretchr/testify/assert (from $GOROOT)
	/Users/carlca/Code/go/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	github.com/dgraph-io/badger [setup failed]
```
It would be handly if, at least, there were some installation instructions detailing such requirements.

Cheers,
Carl

**Comment by manishrjain** [comment]
Thanks for reporting, didn't realize that. Added instructions in README.

**Comment by carlca** [comment]
It all works fine now. Thanks, Manish!

Cheers,
Carl
