### ISSUE TITLE
Cannot acquire directory lock on 

### ISSUE THREAD

**Issue by lengrongfu** [dgraph-io/badger#876]
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go version go1.12.4 darwin/amd64
</pre>

### What version of Badger are you using?
v1.5.5

### Does this issue reproduce with the latest master?
no

### What are the hardware specifications of the machine (RAM, OS, Disk)?
disk

### What did you do?

func main(){
       opts := badger.DefaultOptions
	opts.Dir = "./db1"
	opts.ValueDir = "./db1"
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
		panic(err)
	}
	defer db.Close()
        .......
         CURD 
}

exec: `go run main.go`, and at the same time I execute kill -9 $pid, then open it again and report an error.

And there is a lock file in the `./db1` directory。

![image](https://user-images.githubusercontent.com/15009201/59670461-91733000-91ee-11e9-85c7-74c43db7fc04.png)

### What did you expect to see?

I hope to start normally or give a solution to how to solve this scenario.

### What did you see instead?

2019/06/18 17:21:16 Cannot acquire directory lock on "./db1".  Another process is using this Badger database.: resource temporarily unavailable
exit status 1

**Comment by jarifibrahim** [comment]
@lengrongfu The `LOCK` file ensures two that two difference processes cannot access badger at the same time. You can delete the `LOCK` file if you're sure the process accessing it is no longer running.
