### ISSUE TITLE
Document badger.Loader

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#883]
badger.Loader has absolutely no documentation

We need to fix that and explain what it is for and how to use it.

Exported identifiers missing documentation:

- [ ] https://godoc.org/github.com/dgraph-io/badger#DB.NewLoader
- [ ] https://godoc.org/github.com/dgraph-io/badger#Loader
- [ ] https://godoc.org/github.com/dgraph-io/badger#Loader.Finish
- [ ] https://godoc.org/github.com/dgraph-io/badger#Loader.Set

**Comment by martinmr** [comment]
Loader should not be a public API. It's used to load a backup file and it's only used internally by the backup file. I'll open a PR to refactor it into an unexported type.
