### ISSUE TITLE
Go build broken, missing tag v2.0.0-rc.2

### ISSUE THREAD

**Issue by jin-tron** [dgraph-io/badger#886]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### What version of Badger are you using?
v2.0.0-rc.2

### Does this issue reproduce with the latest master?
yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
AWS EC2, x86_64 GNU/Linux

### What did you do?
Install ipfs cluster,

git clone https://github.com/ipfs/ipfs-cluster.git
export GO111MODULE=on # optional, if checking out the repository in $GOPATH.
go install ./cmd/ipfs-cluster-service

### What did you expect to see?
go install command complete. I did same installation 3 hours ago with no this dependency error.

### What did you see instead?
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: unknown revision v2.0.0-rc.2

Would it be a tag issue in recent a few hours?
Thank you!

**Comment by jin-tron** [comment]
In ipfs-cluster master branch, go.mod has,
github.com/dgraph-io/badger v2.0.0-rc.2+incompatible

**Comment by jarifibrahim** [comment]
@jin-tron Looks like we've tagged the release incorrectly. I see tag `v2.0-rc1` but I think it should be `v2.0.0-rc1`.

https://github.com/ipfs/ipfs-cluster.git will have to be updated anyway.

**Comment by jin-tron** [comment]
Thank you for your quick response!

**Comment by sanderpick** [comment]
Possibly an old tag was deleted?

**Comment by MichaelMure** [comment]
Huu, I don't want to be annoying beyond measure, but it seems that the last stable version of `go-ipfs` can't be built because of this, and that's kinda very annoying.

**Comment by Kubuxu** [comment]
The branch that had the tag got deleted. This means that our builds are broken. Master of go-ipfs should be fixed soon (see https://github.com/ipfs/go-ipfs/pull/6461).

**Comment by campoy** [comment]
Hi there and sorry for the inconvenience!

I was the person that deleted that tag since didn't make any sense (we had not release v2.0.0-rc1 so it was kind of weird that we had a tag for rc2!).

I already pushed the tag back on pointing to v2.0.0-rc1 and I will keep it there for now.

Out of curiosity, how did you end up using that tag, @jin-tron?

Thanks for the report, and again sorry for breaking the build!
Can we compensate somehow? We got a bunch of new stickers :)

**Comment by campoy** [comment]
Also, please let me know if pushing that tag again fixed your build, @jin-tron!

**Comment by jin-tron** [comment]
Looks tag has been added back and the ipfs-cluster build fixed.
No worry, I would say maybe we need better dependency management tools than Go mod.

**Comment by campoy** [comment]
I think Go mods is not bad, but that tag should have never existed in the first place.

**Comment by Kubuxu** [comment]
I agree that the tag shouldn't have existed. I think what has happened is go modules picked it up as the newest version when we were updating `go-ds-badger` at some point.

I think it will still cause failed builds on our side but we already resolved these by releasing `go-ds-badger@0.0.4`.

**Comment by MichaelMure** [comment]
As of now, the stable (that is, frozen) version of `go-ipfs` still fail to compile with:

```
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: error loading module requirements
```

Any chance you would restore the tag to the exact commit ? You might be able to retrieve the hash with `git reflog`.

**Comment by Kubuxu** [comment]
I was able to find the tag in my own repo: https://github.com/Kubuxu/badger/releases/tag/v2.0-rc1

As you can see it is signed.

**Comment by ansermino** [comment]
I'm still experiencing this issue. 
```
$ go get -u github.com/dgraph-io/badger/v2
go: finding github.com/AndreasBriese/bbloom latest
go: finding github.com/dgryski/go-farm latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/golang/groupcache latest
go: finding golang.org/x/net latest
go: finding github.com/xiang90/probing latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding github.com/armon/consul-api latest
go: finding github.com/golang/glog latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/time latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/crypto latest
go: finding github.com/coreos/pkg latest
go: finding golang.org/x/tools latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/alecthomas/template latest
go: finding github.com/kr/logfmt latest
go: finding github.com/alecthomas/units latest
go: finding golang.org/x/exp latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/dgryski/go-sip13 latest
go: finding github.com/BurntSushi/xgb latest
go: finding golang.org/x/image latest
go: finding golang.org/x/mobile latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/google/pprof latest
go: downloading github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: extracting github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: extracting github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
```
```
$ go mod tidy
go: finding github.com/ChainSafe/log15 latest
go: finding github.com/perlin-network/life/exec latest
go: finding github.com/ipfs/go-datastore/sync latest
go: finding github.com/perlin-network/life latest
go: finding github.com/inconshreveable/log15 latest
go: finding github.com/ipfs/go-ipfs/core latest
go: finding github.com/ipfs/go-ipfs/repo latest
go: finding github.com/libp2p/go-libp2p/p2p/host/routed latest
go: finding github.com/libp2p/go-libp2p/p2p/host latest
go: finding github.com/libp2p/go-libp2p/p2p latest
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: error loading module requirements
```

Running `go1.12.6`,  not using vendoring, repo is outside `$GOPATH`. I've tried clearing my `$GOPATH` and emptying `go.mod` without any luck. Does anyone know of a solution/workaround?

**Comment by Kubuxu** [comment]
Try running `go clean -modcache` and then for applications that depend on the tag that was messed up set `export GOPROXY='https://proxy.golang.org'`.

proxy.golang.org which will be default in 1.13, contains correct source code for the tag that was removed and then re-added. Unfortunately, when the tag was readded it was updated to latest/master which is not compatible with the code that was there before.

**Comment by ansermino** [comment]
@Kubuxu The proxy seems to have resolved the issue for me. Many thanks!
