### ISSUE TITLE
Add Windows and MacOS agents to TeamCity then drop TravisCI

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#888]
Currently TeamCity only tests Go 1.12.4 on Linux ([source](https://github.com/dgraph-io/badger/pull/879#issuecomment-503773501)), we should add agents to test on other platforms (Windows and MacOS) and other Go version (Go 1.11 and tip).

This should be done before we release v2.0.0, as we need to make sure this version works well on all platforms.

**Comment by campoy** [comment]
Hey @danielmai, could you update on this issue?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8666). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
