### ISSUE TITLE
Errror Downloading in Go 1.12.6

### ISSUE THREAD

**Issue by cbalano** [dgraph-io/badger#889]
<pre>
> go version
go version go1.12.6 linux/amd64

</pre>

> go get github.com/dgraph-io/badger
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: error loading module requirements

**Comment by cbalano** [comment]
After further investigation, it turns out that this fails on any go version I tried, not just 1.12.6
OS'es tried: Alpine Linux 3.9, 3.10

> go version
go version go1.12.4 linux/amd64
>
> go get github.com/dgraph-io/badger/v2
go: finding github.com/gorilla/context v1.1.1
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/prometheus/client_model v0.0.0-20190115171406-56726106282f
go: finding github.com/Shopify/toxiproxy v2.1.4+incompatible
go: finding golang.org/x/sys v0.0.0-20181122145206-62eef0e2fa9b
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
go: finding google.golang.org/grpc v1.17.0
go: finding github.com/gogo/protobuf v1.2.0
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding github.com/gorilla/mux v1.6.2
go: finding github.com/onsi/ginkgo v1.7.0
go: finding github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: finding github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: finding github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: finding github.com/eapache/queue v1.1.0
go: finding github.com/eapache/go-resiliency v1.1.0
go: finding github.com/onsi/gomega v1.4.3
go: finding github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: finding github.com/pierrec/lz4 v2.0.5+incompatible
go: finding github.com/Shopify/sarama v1.19.0
go: error loading module requirements
>
>
>
> go get github.com/dgraph-io/badger
go: finding github.com/onsi/ginkgo v1.6.0
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/hpcloud/tail v1.0.0
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding github.com/sirupsen/logrus v1.2.0
go: finding golang.org/x/tools v0.0.0-20180828015842-6cd1fcedba52
go: finding github.com/go-stack/stack v1.8.0
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding github.com/go-kit/kit v0.8.0
go: finding golang.org/x/sys v0.0.0-20181116152217-5ac8a444bdc5
go: finding github.com/gogo/protobuf v1.1.1
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: finding honnef.co/go/tools v0.0.0-20180728063816-88497007e858
go: error loading module requirements

**Comment by jarifibrahim** [comment]
@cbalano Can you confirm if the issue is still reproducible? We fixed this issue two days ago and I don't get an error when I run `go get -v github.com/dgraph-io/badger`.

**Comment by cbalano** [comment]
The issue went away after I rm-rf the vendor directory. So I guess it can be closed.
