### ISSUE TITLE
Failed to compile badger for 32-bit systems (ARM, x86)

### ISSUE THREAD

**Issue by maxpert** [dgraph-io/badger#89]
I am trying to compile a system with 

# vendor/github.com/dgraph-io/badger
src/vendor/github.com/dgraph-io/badger/kv.go:139: constant 2147483648 overflows int

You can repro it for any 32-bit system.

**Comment by manishrjain** [comment]
Thanks for the PR. Reviewed it.

**Comment by maxpert** [comment]
Fix is in :+1:
