### ISSUE TITLE
Nvme SSD ？

### ISSUE THREAD

**Issue by lengrongfu** [dgraph-io/badger#902]
![image](https://user-images.githubusercontent.com/15009201/60254243-21585e80-9900-11e9-95bd-7cfebb868b90.png)

badger是否支持Nvme SSD 设备？

**Comment by manishrjain** [comment]
Badger works really well with NVMe drives.

**Comment by jarifibrahim** [comment]
Manish has answered the question. Closing this issue.

**Comment by lengrongfu** [comment]
@manishrjain Hello, Does the badger implement the `NVMe` driver protocol itself, or tell me how badger supports `NVMe`, thank you。
