### ISSUE TITLE
Value log gc doesn't work due to too large txn

### ISSUE THREAD

**Issue by simonxw** [dgraph-io/badger#907]
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.12.1
</pre>

### What version of Badger are you using?
1.5.4

### Does this issue reproduce with the latest master?
yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Linux, 32GB, SDD

### What did you do?
With default db options,  vlog file size 1GB, memtablesize = 64MB, keep writing keys with a certain ratio of overwrites to badger db. There are about 32 vlog files and 1GB per file.

### What did you expect to see?
vlog gc works.

### What did you see instead?

vlog gc keeps failed with error:

 vlog gc not executed    {"error": ": Txn is
 too big to fit into one request", "errorVerbose": "Txn is too big to fit into one request\ngithub.com/dgraph-io/badger.ini
t\n\t/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/errors.go:38\natlas/internal/pkg/badgerdb.init\n\t<autogenerated>:
1\natlas/cmd/atlas/config.init\n\t<autogenerated>:1\natlas/cmd/atlas/bootstrap.init\n\t<autogenerated>:1\natlas/cmd/atlas/c
lustersvc.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/lib64/go/1.11/src/runtime/proc.go
:189\nruntime.goexit\n\t/usr/lib64/go/1.11/src/runtime/asm_amd64.s:1333\n\ngithub.com/dgraph-io/badger/y.Wrap\n\t/root/go/p
kg/mod/github.com/dgraph-io/badger@v1.5.4/y/error.go:71\ngithub.com/dgraph-io/badger.(*valueLog).iterate\n\t/root/go/pkg/mo
d/github.com/dgraph-io/badger@v1.5.4/value.go:323\ngithub.com/dgraph-io/badger.(*valueLog).rewrite\n\t/root/go/pkg/mod/gith
ub.com/dgraph-io/badger@v1.5.4/value.go:411\ngithub.com/dgraph-io/badger.(*valueLog).doRunGC\n\t/root/go/pkg/mod/github.com
/dgraph-io/badger@v1.5.4/value.go:1176\ngithub.com/dgraph-io/badger.(*valueLog).runGC\n\t/root/go/pkg/mod/github.com/dgraph
-io/badger@v1.5.4/value.go:1216\ngithub.com/dgraph-io/badger.(*DB).RunValueLogGC\n\t/root/go/pkg/mod/github.com/dgraph-io/b
adger@v1.5.4/db.go:983\natlas/internal/pkg/badgerdb.(*BadgerKVDB).valueLogGC\n\t/root/workspace/goraftstore/internal/pkg/ba
dgerdb/badgerdb.go:490\nruntime.goexit\n\t/usr/lib64/go/1.11/src/runtime/asm_amd64.s:1333"}

**Comment by simonxw** [comment]
After reading the code, the issue happens during rewrite, it buffers valid key values until 64MB (hardcoded) and batch writes to new log file.  There is a fomula about maxBatchSize: opt.maxBatchSize = (15 * opt.MaxTableSize) / 100.  Here maxtablesize is 64MB. That's why issue happened. After change the buffer size to 5MB vlog gc worked well.

One option is to enlarge maxtablesize but we don't want to as we have some memory limit. Can we make that buffer size or maxBatchSize confirable? 

The buffer size I'm talking about is referring to 64*mi in value.go:rewrite():

			size += int64(e.estimateSize(vlog.opt.ValueThreshold))
			if size >= 64*mi {
				tr.LazyPrintf("request has %d entries, size %d", len(wb), size)
				if err := vlog.db.batchSet(wb); err != nil {
					return err
				}
				size = 0
				wb = wb[:0]
			}

**Comment by simonxw** [comment]
wrongly close the issue. reopening

**Comment by campoy** [comment]
Thanks for the issue report, @simonxw 

If I understand correctly, the garbage collection process does not succeed and an error is logged or actually returned?

**Comment by simonxw** [comment]
Yes, an error returned and the message was "Txn is too big to fit into one request"
