### ISSUE TITLE
Some good strategies to implement

### ISSUE THREAD

**Issue by n-ozerov** [dgraph-io/badger#909]
Recenty, i've found report about MongoDB engine based on RocksDB: https://pgday.ru/presentation/178/5964963da443b.pdf

Google Translated version is here: https://drive.google.com/file/d/1JL2XbYTQFm7favk77TuX9We36ZFAHU2p/view?usp=sharing

There were mentioned two good things -- how to reclaim space and column families:

Deletion:

1. Collecting stats about tombstones during iteration on range.
2. If the amount exceeded threshold, start compaction for this range.

This could be helpful for scenarios with many (or batch range) deletion (queues, etc). 

Also it has function DeleteFilesInRange which allows to delete files if all keys in specified range.

Column families allows to use many LSM trees which share same WAL to allow making transactions. Which could be good for some operation like deleting whole column by deleting whole tree, it also should take less space than using prefixes.

Sorry for my bad English. I'll try to explain again if you didn't understand me.

**Comment by campoy** [comment]
Hi there @n-ozerov,

The second link is broken, and unfortunately, I do not speak Russian.
Could you provide more info about the features?

Thanks

**Comment by n-ozerov** [comment]
Updated link. I've just found that many of text\images rely on https://github.com/facebook/rocksdb/wiki/Compaction

The most interesting pages are 44-64, 75-87.

I've found a few feature requests where people asked about column families and got rejected, so it would be better to focus on LSM compaction.

As far as i understood, if iterator notices huge range of tombstones it forces compactions in this range.

**Comment by n-ozerov** [comment]
Well, i tried to think by myself and i realized how we can make offline compaction:

1. We have Flatten function which brings all tables\keys\versions to same level. We apply that function.
2. Then change level number to highest possible which fits into max level space. 

Example:
Level: 0.      0 B Size.      0 B Max.
Level: 1.      0 B Size.   268 MB Max.
Level: 2.   233 MB Size.   2.7 GB Max.

Turns into:

Level: 0.      0 B Size.      0 B Max.
Level: 1.      233 MB Size.   268 MB Max.
Level: 2.      0 B Size.      2.7 GB Max.

3. We iterate through whole db and decide which sst tables we can delete immediately (all keys are tombstoned) and where ranges of tombstones exceeded threshold (for ex. 700) so we merge tables in same level (of course if it possible to do in LSM tree).

4. In the end we should have most compacted tree at the highest possible level.

**Comment by manishrjain** [comment]
Let's accept this issue. We should have a mechanism to compact tables based on some heuristics.

**Comment by campoy** [comment]
I'd like to have an idea of how much work this entails.

Could you @manishrjain, or maybe @jarifibrahim, give an estimate?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8722). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
