### ISSUE TITLE
Why is the value of p in the skip list 1/3?

### ISSUE THREAD

**Issue by lengrongfu** [dgraph-io/badger#910]
![image](https://user-images.githubusercontent.com/15009201/60398933-68f51980-9b90-11e9-9f3a-1f61fe9377bd.png)

I think that when `p` in the skip list as `1/2` is better to do a binary search, why do `1/3`?

**Comment by campoy** [comment]
That's a great question, indeed.

The value of p in a skip list doesn't need to be two, and the trade-offs of choosing its value are very well documented on the original paper: http://homepage.cs.uiowa.edu/~ghosh/skip.pdf

I recommend the section actually titled "choosing p"
