### ISSUE TITLE
about creating bloom filters, and memory usage

### ISSUE THREAD

**Issue by kidjersey** [dgraph-io/badger#927]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11

</pre>

### What version of Badger are you using?
1.5.4

### Does this issue reproduce with the latest master?
it's not a bug so honestly i haven't tried but looked at the code and seems the same there

### What are the hardware specifications of the machine (RAM, OS, Disk)?
suse linux, 64gb, ssd

### What did you do?
writing new keys+values.  we have cases where keys are similar in nature in that they may be the same except for the last few bytes.  specifically we are using keys between 768-1024 bytes in length.  we basically are using default options (except for setting numcompactors=1).  
 

### What did you expect to see?
smoother memory usage

### What did you see instead?
large buffer sizes which very quickly uses up a lot of heap.  below is 536mb alloc which caused us to OOM

runtime stack:
runtime.throw(0xbff5e2, 0x16)
	/usr/lib64/go/1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc0e4000000, 0x24000000, 0x11e6cf8)
	/usr/lib64/go/1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x11cd640, 0x24000000, 0x7fa5f352cbc0, 0x7fa681e9ad20)
	/usr/lib64/go/1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x11cd640, 0x1000d, 0x0)
	/usr/lib64/go/1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x11cd640, 0x1000d, 0x11e6d08, 0x20300400000000)
	/usr/lib64/go/1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x11cd640, 0x1000d, 0x410101, 0x7fa68126ad00)
	/usr/lib64/go/1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/lib64/go/1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x11cd640, 0x1000d, 0x7fa681010101, 0x417a65)
	/usr/lib64/go/1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x20019137, 0x450101, 0x7fa696e0bf40)
	/usr/lib64/go/1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/lib64/go/1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/lib64/go/1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/lib64/go/1.11/src/runtime/proc.go:1229

goroutine 2236 [running]:
runtime.systemstack_switch()
	/usr/lib64/go/1.11/src/runtime/asm_amd64.s:311 fp=0xc055439358 sp=0xc055439350 pc=0x457e70
runtime.mallocgc(0x20019137, 0xad3ee0, 0xc055439401, 0xc055439430)
	/usr/lib64/go/1.11/src/runtime/malloc.go:913 +0x896 fp=0xc0554393f8 sp=0xc055439358 pc=0x40d956
runtime.makeslice(0xad3ee0, 0x20019137, 0x20019137, 0xc055439470, 0x40b159, 0x20)
	/usr/lib64/go/1.11/src/runtime/slice.go:70 +0x77 fp=0xc055439428 sp=0xc0554393f8 pc=0x442b87
bytes.makeSlice(0x20019137, 0x0, 0x0, 0x0)
	/usr/lib64/go/1.11/src/bytes/buffer.go:231 +0x6d fp=0xc055439468 sp=0xc055439428 pc=0x4ee3cd
bytes.(*Buffer).grow(0xc056174000, 0xc9, 0x2)
	/usr/lib64/go/1.11/src/bytes/buffer.go:144 +0x16c fp=0xc0554394b8 sp=0xc055439468 pc=0x4edd2c
bytes.(*Buffer).Write(0xc056174000, 0xc030ef0e00, 0xc9, 0x1a2, 0x2, 0x0, 0x0)
	/usr/lib64/go/1.11/src/bytes/buffer.go:174 +0xe5 fp=0xc0554394e8 sp=0xc0554394b8 pc=0x4ee015
github.com/dgraph-io/badger/table.(*Builder).addHelper(0xc0250a8000, 0xc030ef0e00, 0xd1, 0x1a2, 0x42, 0x0, 0xc0530fd5e3, 0xc, 0xd, 0x0)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/table/builder.go:118 +0x3c1 fp=0xc0554395e0 sp=0xc0554394e8 pc=0x959b81
github.com/dgraph-io/badger/table.(*Builder).Add(0xc0250a8000, 0xc030ef0e00, 0xd1, 0x1a2, 0x42, 0x0, 0xc0530fd5e3, 0xc, 0xd, 0x0, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/table/builder.go:169 +0x83 fp=0xc055439648 sp=0xc0554395e0 pc=0x959cb3
github.com/dgraph-io/badger.(*levelsController).compactBuildTables(0xc0000302a0, 0x0, 0xcc68a0, 0xc0120a6000, 0xc00c6e4a20, 0xc00c6e4a80, 0xc00566e7b0, 0x5, 0x5, 0xc05bb58f80, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/levels.go:438 +0x7cb fp=0xc055439aa8 sp=0xc055439648 pc=0x97325b
github.com/dgraph-io/badger.(*levelsController).runCompactDef(0xc0000302a0, 0x0, 0xcc68a0, 0xc0120a6000, 0xc00c6e4a20, 0xc00c6e4a80, 0xc00566e7b0, 0x5, 0x5, 0xc05bb58f80, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/levels.go:638 +0xd3 fp=0xc055439c18 sp=0xc055439aa8 pc=0x975653
github.com/dgraph-io/badger.(*levelsController).doCompact(0xc0000302a0, 0x0, 0x3ff0000000000000, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/levels.go:705 +0x498 fp=0xc055439f18 sp=0xc055439c18 pc=0x975fc8
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc0000302a0, 0xc02b2663a0)
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/levels.go:254 +0x1c9 fp=0xc055439fd0 sp=0xc055439f18 pc=0x972529
runtime.goexit()
	/usr/lib64/go/1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc055439fd8 sp=0xc055439fd0 pc=0x459f51
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/root/go/pkg/mod/github.com/dgraph-io/badger@v1.5.4/levels.go:233 +0x82

**Comment by kidjersey** [comment]
hi all, not submitting a bug but rather an enhancement request of sorts.

i am trying to really limit the memory my application is using and would like to try and keep it as stable as possible, avoiding any sudden spikes.
during sst compaction i see dramatic increase in memory usage.  as far as i understand what is happening is in table builder buf will mostly only contain the byte difference from base key of each block whereas keyBuf will contain each full key.  so if there is not much difference in keys in the table(s) then keyBuf will grow much larger than buf.

during this specific instance here my application was consuming about ~1GB or so and memory usage increases by ~3GB within seconds of compaction starting, leading to the OOM.

i _think_ keyBuf is used solely for bloom filter.  bloom filters i don't think are too terribly important for me.

as a test quickly hacked the code to just effectively remove creating the bloom filter and memory usage from then on is perfectly smooth+stable during compaction.

so i think my question would be, is keyBuf only just used for creating the bloom filter later?  i think that's the only use but wanted to make sure.
and i guess an enhancement would be, could there be an option to just disable building the bloom filter?  would that at all be a useful thing for folks in general?

thanks very much!

**Comment by jarifibrahim** [comment]
This should be fixed by https://github.com/dgraph-io/badger/pull/940.

**Comment by kidjersey** [comment]
thanks @jarifibrahim !
