### ISSUE TITLE
The database has crashed. . .

### ISSUE THREAD

**Issue by nnsgmsone** [dgraph-io/badger#930]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go 1.11.4
</pre>

### What version of Badger are you using?

master

### Does this issue reproduce with the latest master?

yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?

8GB, ubuntu18.04, 18 SSD
### What did you do?
I complete the redis protocol and implemented some functions. The project address is as follows: https://github.com/infinivision/store，

### What did you expect to see?

I hope the program can run smoothly.

### What did you see instead?
```
badger 2019/07/15 14:48:14 WARNING: While running doCompact: While running compaction for: {elog:0xc0000b64e0 thisLevel:0xc00006e2a0 nextLevel:0xc00006e300 top:[0xc00012a0f0 0xc00012a1e0 0xc00012a2d0 0xc00012a3c0 0xc00012a4b0] bot:[] thisRange:{left:[] right:[] inf:true} nextRange:{left:[33 98 97 100 103 101 114 33 104 101 97 100 0 0 0 0 0 0 0 0] right:[107 101 121 58 95 95 114 97 110 100 95 105 110 116 95 95 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[]}: While opening new table: 8: open test.db/000008.sst: too many open files
badger 2019/07/15 14:48:14 INFO: Got compaction priority: {level:0 score:1 dropPrefix:[]}
badger 2019/07/15 14:48:14 INFO: Running for level: 0
badger 2019/07/15 14:48:14 ERROR: writeRequests: Create value log file. Path=test.db/000012.vlog. Error=open test.db/000012.vlog: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x783456]
```

**Comment by jarifibrahim** [comment]
@nnsgmsone Badger keeps the file descriptors open for SST and vlog files. There is a limit on the maximum number of file descriptors. 
On Linux and Mac, you can check the file descriptor limit with `ulimit -n -H` for the hard limit and `ulimit -n -S` for the soft limit. A soft limit of `65535` should be enough. Set it using `ulimit -n -S`. This should fix your issue.

**Comment by nnsgmsone** [comment]
Can add some judgment when the file descriptor is not enough? Or add a lru algorithm to the file descriptors, so that the file descriptors that are not commonly used can be recycled. . @jarifibrahim

**Comment by nnsgmsone** [comment]
![2019-07-15 15-42-59 的屏幕截图](https://user-images.githubusercontent.com/31609524/61201483-3d893780-a717-11e9-8454-83cb43ca144f.png)
I think my setup is big enough, but it will still crashed @jarifibrahim

**Comment by jarifibrahim** [comment]
@nnsgmsone Can you check the soft limit? `ulimit -n -S`?

**Comment by nnsgmsone** [comment]
@jarifibrahim  soft limit is 1024，I will try again after modifying it.

**Comment by nnsgmsone** [comment]
@jarifibrahim 
![2019-07-15 15-49-29 的屏幕截图](https://user-images.githubusercontent.com/31609524/61201801-30207d00-a718-11e9-9184-43b257a141d7.png)
![2019-07-15 15-49-34 的屏幕截图](https://user-images.githubusercontent.com/31609524/61201804-31ea4080-a718-11e9-9e21-c65c665c46a0.png)
This phenomenon will still occur. Does it need to release the fd that is not commonly used?

**Comment by jarifibrahim** [comment]
@nnsgmsone How many SST file and value log files do you have? The `ulimit` you've set should be more than enough.

>Does it need to release the fd that is not commonly used?

Right now, badger doesn't release the file descriptors until the db (or the file) is closed. Reusing the file descriptors is something we might add to badger in future.

**Comment by nnsgmsone** [comment]
@jarifibrahim  Well, in fact, in addition to badger, tcp also takes up some fd. Then the badger crashed when the file descriptor is not enough. . .

**Comment by jarifibrahim** [comment]
@nnsgmsone This doesn't look like a badger issue to me. Double check your ulimit. Maybe it's an issue with your TCP connection.
I'm going to close this issue since I don't think there's anything we can fix in badger. Feel free to reopen.
