### ISSUE TITLE
make event logging configurable

### ISSUE THREAD

**Issue by elagergren-spideroak** [dgraph-io/badger#938]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.7
</pre>

### What version of Badger are you using?
v1.6.0

### What did you do?

Ran benchmarks using badgerdb.

### What did you expect to see?

I *didn't* expect to see logging appear on the CPU profile.

### What did you see instead?

It did, and there's no way to turn it off.

In some of my benchmarks ~10% of the time spent inside (*DB).doWrites (and more elsewhere!) is spent printing to the event log. ISTM there's no way to disable this.

**Comment by ashish-goswami** [comment]
Hey @elagergren-spideroak, how were you running benchmarks? 
You can try to avoid logging by calling **options.WithLogger(false)**.

**Comment by martinmr** [comment]
This is how you configure the logger: https://github.com/dgraph-io/badger/blob/1496af939d8533779f7b6b3f3a6cd251abf5c598/options.go#L231

In your case you'd create a logger that takes the input but returns immediately without doing anything with it.

**Comment by elagergren-spideroak** [comment]
The issue isn't that logger, it's the  *event* logger. See: 

<img width="298" alt="Screen Shot 2019-07-22 at 2 36 36 PM" src="https://user-images.githubusercontent.com/36516532/61667179-2b1a7b00-ac8e-11e9-9855-4db57c214a17.png">

**Comment by elagergren-spideroak** [comment]
I've set the `WithLogger(nil)` option already.

**Comment by divyakoshy** [comment]
> I've set the `WithLogger(nil)` option already, as well as tried a nop logger.

This seems to work:
```
        opts := badger.DefaultOptions("./.badgerdb")
	db, err := badger.Open(opts.WithLogger(nil))
```

**Comment by ericlagergren** [comment]
Note that I’m not talking about general logging, I’m talking about event logging. 

https://github.com/dgraph-io/badger/blob/e627d49fa7e9ddf9c31a833e83c4b3937bb81c66/db.go#L280

See also my screenshot.

**Comment by campoy** [comment]
Are you running pprof while running your benchmarks?
In that case this is expected and a side effect of pprof itself, rather than a bug in badger.

Could you share the whole pprof trace you obtained? Both web and top -cum output would be great

**Comment by mjgarton** [comment]
I seem to have the same issue.

@campoy can you explain what you mean by "running pprof while running your benchmarks"?

In my case, the application calls `pprof.StartCPUProfile` at the start and `pprof.StopCPUProfile` at the end.  Is that what you mean?

**Comment by mjgarton** [comment]
Also

**Comment by mjgarton** [comment]
FWIW these same Printf calls are also responsible for a good chunk of allocations in some of my applications.

Also, if someone can suggest what the API for this configuration should look, I may take a stab at implementing it.

**Comment by campoy** [comment]
Yes, that's what I meant.
Thanks for the extra info, @mjgarton.

@jarifibrahim, please have a look and see whether there's any improvements we can make and how you can guide Martin with his implementation
