### ISSUE TITLE
unexpected Valid() == true for Single Key iteration

### ISSUE THREAD

**Issue by Asarew** [dgraph-io/badger#943]
```golang
// Commit 2 items with the same 'prefix'
txn := db.NewTransaction(true)
txn.Set([]byte("foo"), nil)
txn.Set([]byte("foobar"), nil)
txn.Commit()

// Grab a key iterator for the first key
txn = db.NewTransaction(false)
opt := badger.DefaultIteratorOptions
opt.AllVersions = true
itr := txn.NewKeyIterator([]byte("foo"), opt)

for itr.Rewind(); itr.Valid(); itr.Next() {
	fmt.Println(string(itr.Item().Key()))
}
```
will print:
```
foo
foobar
```

While iterating over all the versions of key `foo`, on the last version the iterator steps to the key `foobar` when calling next.
I expected that the next `itr.Valid()` call would return `false` as this is a different key. But instead it returns `true` because of the shared prefix for this next key.

So to sum it all up, shouldn't this be:
https://github.com/dgraph-io/badger/blob/d8e1fcf01522ac0178bbad13409a680b6854013b/iterator.go#L458-L463

```golang
func (it *Iterator) Valid() bool {
	if it.item == nil {
		return false
	}
	if it.opt.prefixIsKey {
		return bytes.Equal(it.item.key, it.opt.Prefix)
	}
	return bytes.HasPrefix(it.item.key, it.opt.Prefix)
}
```

**Comment by jarifibrahim** [comment]
@Asarew Thanks for reporting the issue and finding the fix. https://github.com/dgraph-io/badger/pull/950 should fix this issue.

**Comment by Asarew** [comment]
Thnx for the support on this
