### ISSUE TITLE
badger.WriteBatch doesn't work well with managed table.

### ISSUE THREAD

**Issue by yangzh** [dgraph-io/badger#944]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### What version of Badger are you using?
badger@v2.0.0-rc.2+incompatible

### Does this issue reproduce with the latest master?
Not tested

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Mac, Version 10.14.3, 16GB

### What did you do?

I'm using a managed table, and want to instantiate a WriteBatch to write some stuff.

### What did you expect to see?
Be able to write a batch of stuff into a managed table.
I guess it's probably fine for a (unmanaged table), but for managed table, there is not sufficient test case.

### What did you see instead?

badger 2019/07/26 10:59:31 INFO: All 0 tables opened in 0s
badger 2019/07/26 10:59:31 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
--- FAIL: TestTable (0.05s)
panic: Commit cannot be called with managedDB=true. Use CommitAt. [recovered]
	panic: Commit cannot be called with managedDB=true. Use CommitAt.

goroutine 5 [running]:
testing.tRunner.func1(0xc000155500)
	/usr/local/go/src/testing/testing.go:830 +0x388
panic(0x1704fc0, 0x195c4c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/dgraph-io/badger.(*Txn).commitPrecheck(...)
	/Users/.../go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible/txn.go:577
github.com/dgraph-io/badger.(*Txn).CommitWith(0xc00012e180, 0xc0001ea0a0)
	/Users/.../go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible/txn.go:648 +0x2d4
github.com/dgraph-io/badger.(*WriteBatch).commit(0xc0002b6040, 0x182e188, 0xc000365e20)
	/Users/.../go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible/batch.go:148 +0x94
github.com/dgraph-io/badger.(*WriteBatch).Flush(0xc0002b6040, 0xc0003d6000, 0xc000365e20)
	/Users/.../go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible/batch.go:172 +0x3b
WriteBatch.Flush(0xc0002b6040, 0xc000365e98, 0x144403f)
.../table.go:267 +0x2b
TestTable.func1(0xc00014c480, 0xd24ec4f1a98c6e5b)
.../table_test.go:38 +0x25f
TestTable(0xc000155500)
.../table_test.go:38 +0x18a
testing.tRunner(0xc000155500, 0x182e180)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x357
exit status 2

**Comment by yangzh** [comment]
Hey, @jarifibrahim Thanks for taking on this report so promptly. 

I know you guys are celebrating, etc, (and congratulations on Dgraph getting new round of funding, by the way). but may I ask when I can see this bug get fixed? I was blocked by this, and was hoping this can get resolved as soon as possible.

**Comment by jarifibrahim** [comment]
Hey @yangzh, the PR https://github.com/dgraph-io/badger/pull/948 is almost ready. We should be able to merge it today.

**Comment by yangzh** [comment]
@jarifibrahim Thanks for the fix, I'm wondering if you can patch this into v2.0.0 branch as well. 
We are using v2.0.0 and would like to stick to that.
