### ISSUE TITLE
question: recommended usage of sequences in an http server

### ISSUE THREAD

**Issue by alinnert** [dgraph-io/badger#969]
I hope it's okay to remove the issue template because it doesn't fit questions.

I know how to use sequences in general. I just wonder how and where do I store and/or get sequences in the context of an http server. Let's take for example following keys:

```
user:0:item:0 = This is the first item of user one
user:0:item:1 = This is the second item of user one
user:1:item:0 = This is the first item of user two
user:1:item:1 = This is the second item of user two
```

This involves one sequence, plus another one for every user.

**user ID sequence**

This is pretty much a global sequence. Now, do I store a reference to the sequence in a global place and access it when I need it? Or is it okay to create a squence (= `db.GetSequence()`) for every added user with a bandwith of `1` (because every http request will only add one user)?

**item ID sequence**

This one is a bit more interesting. I would need to store a sequence for every registered user, which might be quite a lot. Unless I implement a pool of x recently used sequences. The alternative would be again: create a sequence with the bandwith of `1` for every http request (or higher if one request can add more than one item).

Which approach would be recommended for this use case?

**Comment by CanRau** [comment]
Interesting question, how did you solve/handle your situation @alinnert?
