### ISSUE TITLE
Question: Multiple iterators on a read-write transaction.

### ISSUE THREAD

**Issue by elliotcourant** [dgraph-io/badger#981]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### What version of Badger are you using?
master @ 74ed6da2c776a6b4941596df9da3ff84a0703c70

What is the limiting factor of the transaction or iterator object being thread-safe? Is it the pending writes map/iterator that isn't safe if there are multiple iterators at the same time as data being written? 

I'm trying to run two iterators on a transaction after some entries have been written, but while the two iterators are active no writes will occur. If the limiting factor is writes cannot happen while multiple iterators are active would it be reasonable to simply restrict writes until iterators are deallocated?

Sorry if I'm misunderstanding the issue; trying to understand the workings with that object to better approach my problem.

Also sorry if this is not the correct venue for this question. I'm happy to move it if it is.

**Comment by ashish-goswami** [comment]
@elliotcourant Currently limiting factor is pending write map in transaction. It is not thread safe.
That's the reason, you cannot have multiple iterators in RW transaction.
I am not following the second part you asked. Are you trying to run two iterators in RW transaction? Also are entries are written in same transaction?

**Comment by elliotcourant** [comment]
I am trying to run two iterators but I don't think I will get the performance benefit that I thought that I would. I was mostly just curious about what the limiting factor was. Thank you very much!

**Comment by manishrjain** [comment]
We could easily make the txn run iterators concurrently. Thread unsafe was just seemed simple enough for the utility when originally written.
