### ISSUE TITLE
Feature Request: Add python interface/binding

### ISSUE THREAD

**Issue by dreamflasher** [dgraph-io/badger#984]
Please make this great project available to python users by adding a python interface.

**Comment by campoy** [comment]
We're definitely open to contributions here!
Anyone with the skills and interest to implement this?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8667). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
