### ISSUE TITLE
Export "options"

### ISSUE THREAD

**Issue by KBassford** [dgraph-io/badger#985]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.7 linux/amd64

</pre>

### What version of Badger are you using?
latest master, 2019-08-14

### Does this issue reproduce with the latest master?
Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
N/A

### What did you do?
Attempt to import your "option" enum tables.

Problem:
badger.options.FileLoadingMode is not exported (nor is the other table under options).  While I can get around this with some creative imports, it would be smarter to allow folks to use the constants in options.go rather than requiring a separate import.  

### What did you expect to see?
(see above)

### What did you see instead?
(see above)

**Comment by campoy** [comment]
Hey @jarifibrahim , can you have a look at this?

Does it makes sense to you? I"m not sure I follow what it's being requested.

**Comment by KBassford** [comment]
It's pretty basic, if you want to change "WithTableLoadingMode" or "WithValueLogLoadingMode", then you have to cast your value as a "val.(bdoptions.FileLoadingMode)".  Pretty senseless to force a user to cast their value with an unexported enum.

BTW, your latest updates broke "WithBlockSize", "WithBloomFalsePositive" and "ChecksumVerificationMode", though I can't see where they broke from the master.

**Comment by jarifibrahim** [comment]
>BTW, your latest updates broke "WithBlockSize", "WithBloomFalsePositive" and "ChecksumVerificationMode", though I can't see where they broke from the master.

@KBassford What do you mean by `latest update broke them`?

**Comment by KBassford** [comment]
Exactly as stated.  Would not compile, had to comment them out in my code.

**Comment by jarifibrahim** [comment]
Interesting. Could you give me some more information about this @KBassford ? The CI build seems to be working fine so I guess the failure could be because of something in your code.

**Comment by KBassford** [comment]
Maybe this will make it a bit clearer ...
""""
func ConfigureDatabase(path string, options map[string]interface{}) bool {
	if len(path) == 0 {
		loglib.Notify(severity.Err, "ConfigureDatabase called without path!")
		return false
	}
	badgerCfg = badger.DefaultOptions(path)
	if len(options) == 0 {
		return true
	}
	for key, val := range options {
		// For those unexported types
		switch key {
		case "ValueDir":
			badgerCfg.WithValueDir(val.(string))
		case "SyncWrites":
			badgerCfg.WithSyncWrites(val.(bool))
		case "TableLoadingMode":
			badgerCfg.WithTableLoadingMode(val.(bdoptions.FileLoadingMode))
		case "ValueLogLoadingMode":
			badgerCfg.WithValueLogLoadingMode(val.(bdoptions.FileLoadingMode))
		case "NumVersionsToKeep":
			badgerCfg.WithNumVersionsToKeep(val.(int))
		case "ReadOnly":
			badgerCfg.WithReadOnly(val.(bool))
		case "Truncate":
			badgerCfg.WithTruncate(val.(bool))
		case "Logger":
			badgerCfg.WithLogger(val.(badger.Logger))
		case "MaxTableSize":
			badgerCfg.WithMaxTableSize(val.(int64))
		case "LevelSizeMultiplier":
			badgerCfg.WithLevelSizeMultiplier(val.(int))
		case "MaxLevels":
			badgerCfg.WithMaxLevels(val.(int))
		case "ValueThreshold":
			badgerCfg.WithValueThreshold(val.(int))
		case "NumMemtables":
			badgerCfg.WithNumMemtables(val.(int))
		// case "BlockSize":
		// 	badgerCfg.WithBlockSize(val.(int))
		// case "BloomFalsePositive":
		// 	badgerCfg.WithBloomFalsePositive(val.(float64))
		case "NumLevelZeroTables":
			badgerCfg.WithNumLevelZeroTables(val.(int))
		case "NumLevelZeroTablesStall":
			badgerCfg.WithNumLevelZeroTablesStall(val.(int))
		case "LevelOneSize":
			badgerCfg.WithLevelOneSize(val.(int64))
		case "ValueLogFileSize":
			badgerCfg.WithValueLogFileSize(val.(int64))
		case "ValueLogMaxEntries":
			badgerCfg.WithValueLogMaxEntries(val.(uint32))
		case "NumCompactors":
			badgerCfg.WithNumCompactors(val.(int))
		case "CompactL0OnClose":
			badgerCfg.WithCompactL0OnClose(val.(bool))
		case "LogRotatesToFlush":
			badgerCfg.WithLogRotatesToFlush(val.(int32))
		// case "ChecksumVerificationMode":
		// 	badgerCfg.ChecksumVerificationMode = val.(bdoptions.ChecksumVerificationMode)
		// Custom additions.
		case "KillLogging":
			badgerCfg.WithLogger(nil)
		default:
			if len(key) == 0 {
				// Pass
			} else {
				loglib.Notify(severity.Warn, "ConfigureDatabase:", key, "unknown or invalid option!")
			}
		}
	}
	return true
}

""""

**Comment by KBassford** [comment]
Dang I hate when it drops the tabs.

**Comment by KBassford** [comment]
From my Gopkg.toml ...
 name = "github.com/dgraph-io/badger"
 version = "1.6.0"

**Comment by jarifibrahim** [comment]
I don't think I understand the issue.
```go
func main() {
	opt := badger.DefaultOptions("./")
	opt.TableLoadingMode = options.FileIO
	opt.ValueLogLoadingMode = options.LoadToRAM

	db, err := badger.Open(opt)
}
```
can't you do this?

**Comment by KBassford** [comment]
Not unless you do this under imports...
```
	bdoptions "github.com/dgraph-io/badger/options"
```
and change "options" to "bdoptions" because you didn't make "options" enums exportable, only the functions are exported (using: 	badger "github.com/dgraph-io/badger", also under imports).

**Comment by KBassford** [comment]
Trying a more readable version of the code, with includes ...
```
import (
	"bytes"
	"encoding/binary"
	"encoding/gob"
	"fmt"
	"io"
	"os"
	"reflect"
	"regexp"

	badger "github.com/dgraph-io/badger"
	bdoptions "github.com/dgraph-io/badger/options"
)

// ConfigureDatabase : Change default options for startup here
func ConfigureDatabase(path string, options map[string]interface{}) bool {
	if len(path) == 0 {
		loglib.Notify(severity.Err, "ConfigureDatabase called without path!")
		return false
	}
	badgerCfg = badger.DefaultOptions(path)
	if len(options) == 0 {
		return true
	}
	for key, val := range options {
		// For those unexported types
		switch key {
		case "ValueDir":
			badgerCfg.WithValueDir(val.(string))
		case "SyncWrites":
			badgerCfg.WithSyncWrites(val.(bool))
		case "TableLoadingMode":
			badgerCfg.WithTableLoadingMode(val.(bdoptions.FileLoadingMode))
		case "ValueLogLoadingMode":
			badgerCfg.WithValueLogLoadingMode(val.(bdoptions.FileLoadingMode))
		case "NumVersionsToKeep":
			badgerCfg.WithNumVersionsToKeep(val.(int))
		case "ReadOnly":
			badgerCfg.WithReadOnly(val.(bool))
		case "Truncate":
			badgerCfg.WithTruncate(val.(bool))
		case "Logger":
			badgerCfg.WithLogger(val.(badger.Logger))
		case "MaxTableSize":
			badgerCfg.WithMaxTableSize(val.(int64))
		case "LevelSizeMultiplier":
			badgerCfg.WithLevelSizeMultiplier(val.(int))
		case "MaxLevels":
			badgerCfg.WithMaxLevels(val.(int))
		case "ValueThreshold":
			badgerCfg.WithValueThreshold(val.(int))
		case "NumMemtables":
			badgerCfg.WithNumMemtables(val.(int))
		// case "BlockSize":
		// 	badgerCfg.WithBlockSize(val.(int))
		// case "BloomFalsePositive":
		// 	badgerCfg.WithBloomFalsePositive(val.(float64))
		case "NumLevelZeroTables":
			badgerCfg.WithNumLevelZeroTables(val.(int))
		case "NumLevelZeroTablesStall":
			badgerCfg.WithNumLevelZeroTablesStall(val.(int))
		case "LevelOneSize":
			badgerCfg.WithLevelOneSize(val.(int64))
		case "ValueLogFileSize":
			badgerCfg.WithValueLogFileSize(val.(int64))
		case "ValueLogMaxEntries":
			badgerCfg.WithValueLogMaxEntries(val.(uint32))
		case "NumCompactors":
			badgerCfg.WithNumCompactors(val.(int))
		case "CompactL0OnClose":
			badgerCfg.WithCompactL0OnClose(val.(bool))
		case "LogRotatesToFlush":
			badgerCfg.WithLogRotatesToFlush(val.(int32))
		// case "ChecksumVerificationMode":
		// 	badgerCfg.ChecksumVerificationMode = val.(bdoptions.ChecksumVerificationMode)
		// Custom additions.
		case "KillLogging":
			badgerCfg.WithLogger(nil)
		default:
			if len(key) == 0 {
				// Pass
			} else {
				loglib.Notify(severity.Warn, "ConfigureDatabase:", key, "unknown or invalid option!")
			}
		}
	}
	return true
}

```
