### ISSUE TITLE
Remove FLOCK or make it optional

### ISSUE THREAD

**Issue by ehsannm** [dgraph-io/badger#988]
Hi,

We are using badger as our data storage in our project. We run badger on Android and iOS devices. We have problem on some androids, which it seems they have problem with the FLOCK. When we ignore the err in Open method [db.go - line: 232] then we have no problem.

dirLockGuard, err = acquireDirectoryLock(opt.Dir, lockFile, opt.ReadOnly)
	if err != nil {
		return nil, err
	}

for the moment we forked, and changed the code to fix our problem. However I was wondering any better solution do you offer ?

**Comment by jarifibrahim** [comment]
Hey @ehsannm, what's the error you see on android? The directory lock prevents multiple badger instances from accessing the same data directory (unless badger is in read-only mode). Making it optional would be easy but I'd like to understand the problem first.

I do not have much experience with android. Any links or references would be appreciated. :)

**Comment by ehsannm** [comment]
Hi @jarifibrahim, Thanks for your response. 
Basically this error does not happen on all the androids but a good few of them crash when calling Flock. 

avc: denied { lock } for path="/data/data/com.ronaksoftware.river.beta/files/databases/river/badger" dev="vdc" ino=15589 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

It seems that flock in some cases needs root access.

**Comment by jarifibrahim** [comment]
@ehsannm Could it be possible that the android device has some other app (maybe an anti-virus) which acquire the lock on the same file?
Can you try running on the app on a clean android device and see if the error persist?
Alternatively, could you check which process is acquiring the lock (https://unix.stackexchange.com/questions/85994/how-to-list-processes-locking-file should help) ?

**Comment by ehsannm** [comment]
@jarifibrahim It is not happen on all androids, some of them. But our app needs to be compatible with all androids. It may be because of SELinux on some androids. We temporary fixed by changing the code in the badger, but we think if you provide it as an option then we don't need to fork the project for such a little change, or may be another lock mechanism ?!!

**Comment by jarifibrahim** [comment]
@ehsannm I still feel the issue is with android. The `flock` system call should've worked for you.

@manishrjain what do you think? Can we make the file locking optional?

**Comment by ehsannm** [comment]
@jarifibrahim I think so too, but what could we do? we cannot force users to update their phones, Internally we are making sure that we do not access the badger concurrently because it is in our code but forcing users to update their phone is not practical

**Comment by jarifibrahim** [comment]
@ehsannm Feel free to send a PR for this.

**Comment by ehsannm** [comment]
@jarifibrahim I created a pull request #1046

**Comment by ehsannm** [comment]
@jarifibrahim is anything else i need to do ?

**Comment by jonknight73** [comment]
Are there any updates on this please?

**Comment by jarifibrahim** [comment]
Hey @jonknight73 @ehsannm the issue got closed because of

**Comment by jonknight73** [comment]
Thank you very much. I'll be delighted to be able to move off my fork back into the main repo.
