### ISSUE TITLE
Cannot Iterate Through Prefixed Keys in Reverse Order - Can I?

### ISSUE THREAD

**Issue by cbalano** [dgraph-io/badger#999]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.7
</pre>

### What version of Badger are you using?
1.6

### Does this issue reproduce with the latest master?
yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Alpine Linux Docker container 32GB RAM, 6 CPU cores

### What did you do?
Tried to read a set of prefixed keys in reverse order. When browsing the value log file using an editor, I can clearly see that the entries exist in the database.

  ero1 := db.View(func(txn *badger.Txn) error {
    prefix := []byte(<my-prefix>)
    opts := badger.DefaultIteratorOptions; opts.Prefix=prefix; opts.PrefetchValues = false; opts.Reverse = true
    it:=txn.NewIterator(opts); defer it.Close()
    for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
      item := it.Item()
      key := string(item.Key())
      . . . . . . . 

### What did you expect to see?
I expected to iterate through the records starting with the given prefix in reverse order.

### What did you see instead?
The iterator loop did not execute at all. It seems that it.Seek(prefix) positioned itself on the first key starting with the prefix, even though opts.Reverse = true. Then, on it.Next(), it.ValidForPrefix(prefix) becomes false right away. I expected that it.Seek(prefix) would position on the last record starting with prefix in this case, so I can iterate.

**Comment by ashish-goswami** [comment]
@cbalano can you share sample code? I think it should work fine.

**Comment by cbalano** [comment]
<pre>
package main

import (
  "fmt"
  "github.com/dgraph-io/badger"
  "time"
  "encoding/json"
  "os"
)

type Data struct {
  TS string `json:"ts"`
}


func TimeNow() string {
  t := time.Now()
  return  fmt.Sprintf("%d-%02d-%02d %02d:%02d:%02d.%03d", t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond()/1000000)
}



func main() {

  fmt.Println("START")
  opts := badger.DefaultOptions("./db")
  opts.ValueDir = opts.Dir + "/data"
  if _, er := os.Stat(opts.Dir); os.IsNotExist(er) { os.MkdirAll(opts.Dir, 0700) }
  db, ero0 := badger.Open(opts)
  if ero0 != nil { fmt.Println(ero0); os.Exit(1) }

  wb := db.NewWriteBatch()
  defer wb.Cancel()

  for i := 0; i < 3; i++ {
    now := TimeNow()
    val, _ := json.Marshal(Data{now})
    wb.Set([]byte("001/"+now), val)
    time.Sleep(time.Millisecond) }

  for i := 0; i < 4; i++ {
    now := TimeNow()
    val, _ := json.Marshal(Data{now})
    wb.Set([]byte("002/"+now), val)
    time.Sleep(time.Millisecond) }

  for i := 0; i < 2; i++ {
    now := TimeNow()
    val, _ := json.Marshal(Data{now})
    wb.Set([]byte("003/"+now), val)
    time.Sleep(time.Millisecond) }

  wb.Flush(); db.Sync()

//-------------------------------------------------------------

  db.View(func(txn *badger.Txn) error {
    opts := badger.DefaultIteratorOptions; it:=txn.NewIterator(opts); defer it.Close()
    for it.Rewind(); it.Valid(); it.Next() {
      item := it.Item()
      item.Value(func(v []byte) error {
        fmt.Println(string(item.Key()), string(v))
        return nil})}
    return nil })
  fmt.Println("------------")



//-------------------------------------------------------------
  ero1 := db.View(func(txn *badger.Txn) error {
    prefix := []byte("002/")
    opts := badger.DefaultIteratorOptions; opts.Prefix=prefix; opts.PrefetchValues = false; opts.Reverse = true
    it:=txn.NewIterator(opts); defer it.Close()
    for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
      item := it.Item()
      key := string(item.Key())
      item.Value(func(v []byte) error {
        fmt.Println(key, string(v))
        return nil})}
    return nil })
  if ero1 != nil {fmt.Println(ero1)}

  fmt.Println("END")
}
</pre>

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger#frequently-asked-questions

See reverse iteration question there.

**Comment by cbalano** [comment]
I see what you are saying there, Manish; all respect, by the way.

I tried the '~' trick because all my key bytes are standard ASCII, and it worked.

May I suggest adding the '0xff' trick into the Badger code base, so the customer does not have to do the it.seek() yoga on reverse iterators.
